### ISSUE TITLE
Overlapping overview tiles with some content

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1003]
I'm not certain what's causing this problem. Maybe the long image name?

<img width="653" alt="screen shot 2016-12-07 at 3 57 26 pm" src="https://cloud.githubusercontent.com/assets/1167259/20986291/fdba2f10-bc95-11e6-85ab-385d39861bbe.png">

At mobile:

<img width="387" alt="screen shot 2016-12-07 at 3 52 51 pm" src="https://cloud.githubusercontent.com/assets/1167259/20986289/f5e52f6a-bc95-11e6-8636-a286344cbc16.png">

**Comment by spadgett** [comment]
@ajacobs21e @jwforres fyi

**Comment by ajacobs21e** [comment]
@spadgett hmm yeah it looks like there's extra space to the right of 464c90b?

**Comment by RHodzelmans** [comment]
I got the same issue if I create an example service:
oc new-app openshift/deployment-example --name=ab-example-a --labels=ab-example=true SUBTITLE="variant A”
oc new-app openshift/deployment-example --name=ab-example-b --labels=ab-example=true SUBTITLE="variant B” COLOR=“red"
oc new-app openshift/deployment-example --name=ab-example-c --labels=ab-example=true SUBTITLE="variant C” COLOR=“green"

oc expose dc/ab-example-a --name=ab-example --selector=ab-example=true
oc expose svc/ab-example

It completely messes up the layout, both in Chrome and Firefox (latest - running oc cluster up on both 1.3.2 as OCP 3.3.1.7 on Mac (also latest))

**Comment by spadgett** [comment]
@RHodzelmans The two problems I see with your example are:

* Deployments under service `ab-example` stack vertically instead of tiling.
* Some deployment cards show up twice because they are used by multiple services.

If this is what you're seeing, we know about them. We have a card to address the design for those problems in progress now:

https://trello.com/c/QxbqJsoK
