### ISSUE TITLE
Pods that share the same service, but have no `deploymentconfig` set show up in separate cards

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin-web-console#1011]
Pods that are selected by the same service, but have no `deploymentconfig` set, show up in separate cards which overflow into the second column of the overview page.

![screenshot from 2016-12-08 16-23-01](https://cloud.githubusercontent.com/assets/3902875/21028354/aa8d07ea-bd62-11e6-91ce-fa887d4f6204.png)

##### Version
oc v1.3.0-rc1+db098d5-1612-dirty
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://10.13.137.149:8443
openshift v1.3.0-rc1+a38151f-1683-dirty
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. `oc process -f examples/zookeeper/template.json | oc apply -f - `
2. Take a look at the overview page in the web console

##### Current Result
Three separate pod cards for one service

**Comment by spadgett** [comment]
cc @jwforres this only happens when the service doesn't have an app label

**Comment by spadgett** [comment]
The problem is the `display: block;` style for `service-multiple-targets` is being overridden by a later `standalone-service` style.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/21050334/17d8cc14-bde8-11e6-9982-9ad7ddbe0406.png)
