### ISSUE TITLE
Impossible to link application with 3 deployments.

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#103]
version: 1.0.3.alpha.2

I have an app with 3 deployments and 1 service. When I link main deployment/service with a second, I can not add a 3rd one. I can do it editing the service by hand via cli, but not through UI.

**Comment by jwforres** [comment]
We need to come up with a design for where the link action goes once you already have one service linked  @ajacobs21e

**Comment by ajacobs21e** [comment]
@jwforres is service linking possible now?

**Comment by jwforres** [comment]
Not real linking like we will have later, it just adds an annotation to the
service so that they are visually grouped on the overview.   I feel like we
should give the action a different name but not sure what to call it.

**Comment by ajacobs21e** [comment]
How does 1 service & 3 dependents differ from an A/B/C deployment @jwforres ?

**Comment by jwforres** [comment]
A/B/C are slightly different versions of the same part of the application
stack (like just the frontend).   Whereas dependent services are actually
different components in the application stack, example might be the
frontent service as the primary and an API and database services as
dependents.

**Comment by spadgett** [comment]
@ajacobs21e Any ideas on how we can enable this on the overview? I can add it to the actions on the service page, but I worry about discoverability.
