### ISSUE TITLE
Empty events table missing right table header border at some widths

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1037]
![screen_shot_2016-12-14_at_12_13_58_pm](https://cloud.githubusercontent.com/assets/1167259/21192533/eb504f74-c1f6-11e6-833f-d14f57782ae9.png)

**Comment by spadgett** [comment]
@rhamilto fyi

**Comment by rhamilto** [comment]
I'm pretty sure this is a known Chrome bug.  https://bugs.chromium.org/p/chromium/issues/detail?id=2902  :(
