### ISSUE TITLE
Not enough padding below "Projects" header when I can't create a project

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1051]
This was on an iPhone.

![screen_shot_2016-12-19_at_11_35_43_am](https://cloud.githubusercontent.com/assets/1167259/21320517/5390af34-c5df-11e6-8fff-ce0cf999e724.png)

**Comment by rhamilto** [comment]
That's happening because the add button is missing, and that's what has margin on it.  Should be an easy fix.
