### ISSUE TITLE
There's no way to link directly to builds from overview page

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#106]
It would be interesting to have a way (direct link) from the overview page and to see information about current build.

**Comment by spadgett** [comment]
If there is a running build, there should be a link. If it's a pipeline, you should makes sure it has the `pipeline.alpha.openshift.io/uses` annotation:

https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/pipelinetemplate.json#L24

**Comment by spadgett** [comment]
We've discussed leaving the last complete pipeline always visible on the page (with a link to dismiss).

**Comment by jwforres** [comment]
Think we need to go ahead and fix the last pipeline not always being visible

**Comment by jwforres** [comment]
@benjaminapetersen this is the issue tracking making the builds visible instead of disappearing after 5 mins

**Comment by jwforres** [comment]
this has been fixed
