### ISSUE TITLE
Can't see full env var values on mobile

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1063]
I have no easy way to see the name or value beyond the first dozen or so characters on mobile.

![img_0886](https://cloud.githubusercontent.com/assets/1167259/21400708/766a570c-c77f-11e6-820b-eac40dc11402.png)

**Comment by benjaminapetersen** [comment]
Hmm. yeah thats a problem.

**Comment by rhamilto** [comment]
This appears to be specific to iOS/mobile Safari as readonly inputs are scrollable in Android/Chrome.

**Comment by benjaminapetersen** [comment]
Though scrollable inputs is annoying anyway... I don't know that there is a good solution for that.

**Comment by rhamilto** [comment]
> Though scrollable inputs is annoying anyway... I don't know that there is a good solution for that.

By "scrollable" I mean you can long press to put the cursor inside the input and slide left or right to move the cursor and text within the input.

**Comment by spadgett** [comment]
We should consider stacking the inputs inside of showing them side-by-side. You can barely see any of the values. For instance, this is how it looks on an iPhone 6. Even if scrollable, it's not a good experience.

<img width="364" alt="glass" src="https://cloud.githubusercontent.com/assets/1167259/22508406/c28c7efa-e857-11e6-8b07-5d6fff85efde.png">

**Comment by benjaminapetersen** [comment]
Adding @rhamilto to this one with me.  Do we want to try to revise?

**Comment by benjaminapetersen** [comment]
If we do anything, we should be mindful of issue #150 as well (possibly move drag handle to right).

**Comment by rhamilto** [comment]
Further complicating this is the layout for valueFrom entries.  :/

**Comment by benjaminapetersen** [comment]
Yup. 3x inputs stacked w/icons next to them....
