### ISSUE TITLE
Service page Traffic table missing margin-bottom

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1064]
![screen shot 2016-12-21 at 1 47 46 pm](https://cloud.githubusercontent.com/assets/895728/21401998/8238ab06-c784-11e6-91ce-41c2d08a7ad6.PNG)

**Comment by spadgett** [comment]
@sg00dwin minor thing, but can you add a period at the end of that sentence as well

**Comment by spadgett** [comment]
Fixed by #1080
