### ISSUE TITLE
Quota page header looks strange

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1069]
"Quota" and "Limit Range" headers should have equal weight. They are different resources. The help text spacing is odd, too, and it's not obvious it's describing quota.

<img width="638" alt="screen shot 2016-12-22 at 10 34 04 am" src="https://cloud.githubusercontent.com/assets/1167259/21430725/56886ab0-c832-11e6-9198-d297e9e41514.png">

**Comment by jwforres** [comment]
this needs to be fixed for 1.5

**Comment by sg00dwin** [comment]
@spadgett, @rhamilto  What should be the `<h1> ` for this page? 
In it's [previous structure](https://github.com/openshift/origin-web-console/blob/c7a8a6937fbf2d2258a5afb464ae8f314605870b/app/views/quota.html), there were 3 `<h1>` Cluster Quota, Project Quota, Limit Range. Do we go back to that?

**Comment by rhamilto** [comment]
I'm ok with multiple &lt;h1&gt;s.

**Comment by spadgett** [comment]
I'm fine with multiple `<h1>`s as well.
