### ISSUE TITLE
Overview page information about current deployment is to scarce

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#107]
Overview page has lost all information about the image being run, or the build. 

![image](https://cloud.githubusercontent.com/assets/78350/16316045/ea3618ee-3984-11e6-9c68-b0ac9cae9d09.png)

Looking at this overview page I get no valuable information. Maybe that's intended, but I think that even with hover  (like in the graphs) could be better than nothing. I need to navigate away to get some information. 

Think of overview as the dashboard that I do not want to leave, unless I have an specific action to do, and there should be links to most of them (like deployments and current deployment) or pod or service, but nothing else.

**Comment by jwforres** [comment]
Specifics of what information you are missing would help.

**Comment by jwforres** [comment]
@jorgemoralespou please provide more detail on what information you think is missing
