### ISSUE TITLE
Template successfully created message at bottom of page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1084]
When both saving and processing a template from YAML, the created message it at the bottom of the page:

![screen shot 2017-01-06 at 7 55 41 am](https://cloud.githubusercontent.com/assets/1167259/21718448/9bee4c28-d3e5-11e6-862a-930ccdba5489.png)

@jwforres

**Comment by jwforres** [comment]
This is because we moved the alerts to the bottom for the quota warnings

**Comment by spadgett** [comment]
Should we think about affixing alerts to the top of the page?

**Comment by jwforres** [comment]
That would definitely help

**Comment by jwforres** [comment]
Same issue happens when you add a new secret, we probably need to split the quota alerts into a separate alerts object from these two
