### ISSUE TITLE
Cut and copy menu items disabled selecting text in YAML editor

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1085]
![screen_shot_2017-01-06_at_8_21_15_am](https://cloud.githubusercontent.com/assets/1167259/21719010/52091eae-d3e9-11e6-9279-373bc3924154.png)

@jwforres fyi

**Comment by jwforres** [comment]
Yeah I have noticed that as well, has it always been doing that or did it
work at some point?

**Comment by spadgett** [comment]
>  has it always been doing that or did it work at some point?

Not sure because I almost always use the keyboard shortcuts, which work.

**Comment by spadgett** [comment]
Seems to be the same as https://github.com/ajaxorg/ace/issues/3127 and only a problem in Chrome. Lowering severity.

**Comment by spadgett** [comment]
The upstream ace issue has been fixed. We'll need to update the ace dependency when available in a release.

**Comment by jwforres** [comment]
There is a bugzilla open tracking this now so will track it in the BZ

https://bugzilla.redhat.com/show_bug.cgi?id=1463617

It looks like there have been ACE releases, going to test the latest release and see if this is still an issue.

**Comment by jwforres** [comment]
This still does not seem to be fixed in 1.2.6 of ace-builds
