### ISSUE TITLE
Overview app section collapse still shows many starting pipelines

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin-web-console#1097]
There is a separate issue fixing the fact that pipeline builds aren't starting but it surfaces pretty badly in the Overview since it shows all/most of them even when collapsed.

Expanded:
![screen shot 2017-01-10 at 4 52 25 pm](https://cloud.githubusercontent.com/assets/727196/21850454/a737354e-d7d8-11e6-99d5-27015de6987a.png)

Collapsed:
![screen shot 2017-01-10 at 4 52 33 pm](https://cloud.githubusercontent.com/assets/727196/21850462/afe41d6a-d7d8-11e6-9faf-08dd252c59d2.png)

**Comment by spadgett** [comment]
We could collapse pending pipelines like we do for complete. Then if there are more than N pending, summarize "6 pipeline runs pending"?

**Comment by sspeiche** [comment]
I think if there is even more than 1 pending, you'd collapse. Since it should be rare to have that many pending at once, unless there are some issues or performance problems.

**Comment by spadgett** [comment]
@sspeiche Would you be ok with this fix for 1.5?

![screen shot 2017-01-16 at 3 01 50 pm](https://cloud.githubusercontent.com/assets/1167259/22022686/fc4943f8-dc90-11e6-9faa-16699ce4c224.png)

@ajacobs21e has overview designs that show a count for pending pipelines. I was thinking we'd have a count for pending and show details for only running pipeline when we update the overview.

**Comment by spadgett** [comment]
So here you'd see `1 Running | 4 Pending`, and when you expand the twisty, you'd see the full pipeline only for the one that's running.

![screen_shot_2017-01-17_at_8_50_28_am](https://cloud.githubusercontent.com/assets/1167259/22022936/0d7491ea-dc92-11e6-815e-c0343368a952.png)

**Comment by sspeiche** [comment]
@spadgett fine with me. We just need to fix this sync plugin bug and then no one will have so many pending!
