### ISSUE TITLE
Blank overview when I only have build configs and builds

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#110]
In projects where someone is only running builds and has no DCs, no Services, and no non-infrastructure pods.  You got a blank overview.  I suspect this is because our check on the hashSize of pods doesnt take into account that we dont show you build and deploy pods today.

![nothing-here](https://cloud.githubusercontent.com/assets/1467629/16343442/2d989dc0-3a05-11e6-899c-9c120693356e.png)

**Comment by jwforres** [comment]
cc @spadgett

**Comment by spadgett** [comment]
Can we make that the real empty state message?

**Comment by jwforres** [comment]
Similar issue with failed pods https://bugzilla.redhat.com/show_bug.cgi?id=1355950

**Comment by spadgett** [comment]
We have the same problem with circular service dependencies.

**Comment by jorgemoralespou** [comment]
As this page is called "Overview" I would display a banner with a total count of relevant things in my project, that either represent an application or allow me to create an application:
- DC
- BC
- ImageStreams
- Templates
