### ISSUE TITLE
Edit build config spacing inconsistencies

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1100]
On the edit/builds page, there are some inconsistencies with spacing among differing form sections.  Namely, the vertical space between rows of env vars is different from the vertical spacing between rows of build secrets (I think build secrets needs to be adjusted to match env vars).  Additionally, the padding and alignment for delete (X) icons for push secrets, env vars, and build secrets differ.  Presumably, these should all be the same or similar.

![screen shot 2017-01-11 at 3 09 14 pm](https://cloud.githubusercontent.com/assets/895728/21864700/fbf16a4a-d810-11e6-93f6-608de12780dc.PNG)

**Comment by sg00dwin** [comment]
@rhamilto 
I put background color on them so you can see the minor 1px space gap between the edge of the Env Var button and the container edge. Are you good with me opening a pr [for these changes](https://github.com/openshift/origin-web-console/compare/master...sg00dwin:input-close-button-consistency), and then update the env var to match?

<img width="155" alt="envar-gap" src="https://cloud.githubusercontent.com/assets/1874151/22031607/1fee94de-dcaf-11e6-9190-3e2c29a93030.png">

**Comment by rhamilto** [comment]
@sg00dwin, that 1px on the right doesn't concern me. 

It would be great if the space between the right edge of the ui-select and the left edge of the remove button was consistent with the text inputs though.
