### ISSUE TITLE
Page should redirect after removing admin role from self

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin-web-console#1103]
If you remove the admin role from yourself in the membership page the page should redirect/refresh otherwise you continue to click around on other membership management functions and wonder why nothing is happening

**Comment by spadgett** [comment]
@benjaminapetersen Can you see if we can refresh the `canI` rules when adding or removing a role from yourself?

**Comment by benjaminapetersen** [comment]
@spadgett will do
