### ISSUE TITLE
Ignore quota warning when the max=0?

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin-web-console#1110]
If we our quotas include things like `services.loadbalancers=0` or `services.nodeports=0` it'd be helpful to have a way to ignore these from the quota warning in the overview page

**Comment by andrewklau** [comment]
@spadgett will this make it into 1.4 or is that too late?

**Comment by spadgett** [comment]
@andrewklau Unfortunately, it's too late for 1.4. The fix will be in 1.5.
