### ISSUE TITLE
New source secret notification not in view

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin-web-console#1114]
Adding the source secret notification in the new app section ends up at the bottom of the screen and isn't seen by the user until they scroll all the way down

![image](https://cloud.githubusercontent.com/assets/2239920/21960854/e471589c-db4b-11e6-9269-698195cca8d8.png)

**Comment by jwforres** [comment]
This is the same underlying issue as https://github.com/openshift/origin-web-console/issues/1084
