### ISSUE TITLE
Quota alerts displayed twice

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1115]
Seen deploying the `nodejs-mongodb-example` template.

![screen shot 2017-01-16 at 9 03 26 am](https://cloud.githubusercontent.com/assets/1167259/21985879/d228a9ea-dbca-11e6-876a-019c2fa25aaa.png)

cc @jwforres

**Comment by jwforres** [comment]
They are not actually duplicated, one set is referring to DC and service for nodejs-mongodb-example and one set is for mongodb

**Comment by spadgett** [comment]
Ah, I see. I wonder if it's worth combining them.

> **You are at your quota of 2 services in this project.** You will not be able to create service 'nodejs-mongo-db-example' or service 'mongodb'.

**Comment by spadgett** [comment]
And

> **You are at your quota for memory (request) and memory (limit) on pods..** You can still create deployment config 'nodejs-mongo-db-example' and deployment config 'mongodb', but no pods will be created until resources are freed

**Comment by jwforres** [comment]
The ones that are exact duplicates it would be nice if they could be combined, there are some warnings that depend on what a particular DC is asking for w.r.t requests/limits.

We did make the decision at the time to just duplicate because it significantly simplified the logic.

**Comment by spadgett** [comment]
OK closing since it is working correctly
