### ISSUE TITLE
Editing standalone replication controller env vars via KVE results in error

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1118]
![screen shot 2017-01-16 at 10 25 48 am](https://cloud.githubusercontent.com/assets/895728/21988748/5e544e00-dbd6-11e6-8cc1-85b49f41dac6.PNG)

To reproduce: 

1.  Use https://github.com/openshift/origin-web-console/blob/master/test/testdata/overview-edge-cases.yaml to create a standalone replication controller "frontend".  
1.  Reorder the env vars using KVE.

@benjaminapetersen, looks like another KVE bug with secrets and configmaps.

**Comment by benjaminapetersen** [comment]
Looking at this now.

**Comment by jwforres** [comment]
fixed by #1120
