### ISSUE TITLE
Many console warnings about invalid API requests

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1119]
![screen shot 2017-01-16 at 11 43 53 am](https://cloud.githubusercontent.com/assets/1167259/21991568/1e457810-dbe1-11e6-8ace-a8cfc67d3940.png)

cc @jwforres 

Making it a P3 since it doesn't seem to cause problems.

**Comment by jwforres** [comment]
this was a bug in the API between the 1.5 rebase and 1.5.2 rebase
