### ISSUE TITLE
Style guide: Add conventions for formatting angular module/function declarations

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin-web-console#1121]
Please add something to the style guide about formatting for `angular.module` declarations. For example:

[directives/buildPipeline.js](https://github.com/openshift/origin-web-console/blob/master/app/scripts/directives/buildPipeline.js#L3
):

```js
angular.module('openshiftConsole')
  .directive('buildPipeline', function($filter, Logger) {
```

`angular.module` on same line?

[directives/actionChip.js](https://github.com/openshift/origin-web-console/blob/master/app/scripts/directives/actionChip.js#L21):

```js
angular
  .module('openshiftConsole')
  .directive('actionChip', function() {
```

`.module` (or other method calls) on their own line, indented, below `angular`

[directives/deploymentMetrics.js](https://github.com/openshift/origin-web-console/blob/master/app/scripts/directives/deploymentMetrics.js#L3
):

```js
angular.module('openshiftConsole')
  .directive('deploymentMetrics', function($interval,
                                           $parse,
                                           $timeout,
                                           $q,
                                           $rootScope,
                                           ChartsService,
                                           ConversionService,
                                           MetricsCharts,
                                           MetricsService,
                                           ModalsService) {
```

imports aligned to function call, to the right of directive declaration.

[directives/labels.js](https://github.com/openshift/origin-web-console/blob/master/app/scripts/directives/labels.js#L3
):

```js
angular.module('openshiftConsole')
  .directive('labels', function($location, $timeout, LabelFilter) {
```

imports directly inline, not wrapped.

[controllers/attachPVC.js](https://github.com/openshift/origin-web-console/blob/master/app/scripts/controllers/attachPVC.js#L12):

```js
angular.module('openshiftConsole')
  .controller('AttachPVCController',
              function($filter,
                       $routeParams,
                       $scope,
                       $window,
                       APIService,
                       AuthorizationService,
                       BreadcrumbsService,
                       DataService,
                       Navigate,
                       ProjectsService,
                       StorageService) {
```

imports below the controller name, function declaration aligned to controller name

**Comment by spadgett** [comment]
Related to this, I think we should leave off ngdoc comments above these declarations when they have no meaningful descriptions. We have a lot of these copied throughout the code, and some don't even have the right controller names (see #1204).

**Comment by benjaminapetersen** [comment]
agree!

**Comment by spadgett** [comment]
Closing as 3.x is in maintenance only mode. In 4.x, we use prettier.
