### ISSUE TITLE
Documented storage class description annotation not displayed by web console

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1140]
The docs say to use `kubernetes.io/description` for storage class descriptions:

https://docs.openshift.org/latest/install_config/persistent_storage/dynamically_provisioning_pvs.html

The code is looking for `openshift.io/description`, however, so `kubernetes.io/description` doesn't show up in the UI. I'm not sure if this is a code or docs problem.

cc @jwforres @erinboyd @zherman0

**Comment by zherman0** [comment]
@spadgett - where is the code calling openshift.io?

**Comment by spadgett** [comment]
@zherman0 `annotation` filter, which calls the `annotationName` filter

https://github.com/openshift/origin-web-console/blob/master/app/scripts/filters/resources.js#L33

**Comment by spadgett** [comment]
@smarterclayton What should the right annotation for storage class descriptions be? Projects use `openshift.io/description`, but docs say use `kubernetes.io/description` for storage classes.
