### ISSUE TITLE
Long, unbroken names in route table pushes rest of content off-screen

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1161]
![screen shot 2017-01-20 at 11 44 41 am](https://cloud.githubusercontent.com/assets/1167259/22157490/edecac10-df05-11e6-9d96-947d39b5b92c.png)

@jwforres FYI

**Comment by spadgett** [comment]
@sg00dwin @rhamilto You might need #1155 or use the CLI to reproduce. The web console restricts the route name to 63 characters, but they can actually be 253 when created outside the web console.

**Comment by spadgett** [comment]
Similar issue for other resources:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/22157757/021d04e0-df07-11e6-8ae7-22e87a93a03d.png)

**Comment by rhamilto** [comment]
@spadgett, based on #1155, the resources that have this issue are:

* Secrets
* Config Maps
* Autoscalers
* PVCs
* Routes

Are there others?

**Comment by spadgett** [comment]
I think it's potentially any resource table, those are just the ones I fixed name validation for.
