### ISSUE TITLE
Long, unbroken strings on overview overflow containers

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1175]
![screen shot 2017-01-24 at 10 10 41 am](https://cloud.githubusercontent.com/assets/895728/22253001/0d91c60c-e21e-11e6-87f7-a079ee69970b.PNG)

This example shows DC and SS.  There may be others.

**Comment by spadgett** [comment]
We should make sure that metrics tooltips aren't clipped when we fix this since they can extend outside the tile.
