### ISSUE TITLE
Code logic about /app/scripts/controllers/create/createFromImage.js

### ISSUE THREAD

**Issue by woshidagouxiong** [openshift/origin-web-console#1178]
TaskList.add(titles, helpLinks, $routeParams.project, function(){
            var d = $q.defer();
            DataService.batch(generatedResources, context)
              //refactor these helpers to be common for 'newfromtemplate'
              .then(function(result) {
                    var alerts = [];
                    var hasErrors = false;
                    if (result.failure.length > 0) {
                      hasErrors = true;
                      result.failure.forEach(
                        function(failure) {
                          alerts.push({
                            type: "error",
                            message: "Cannot create " + humanize(failure.object.kind).toLowerCase() + " \"" + failure.object.metadata.name + "\". ",
                            details: failure.data.message
                          });
                        }
                      );
                      result.success.forEach(
                        function(success) {
                          alerts.push({
                            type: "success",
                            message: "Created " + humanize(success.kind).toLowerCase() + " \"" + success.metadata.name + "\" successfully. "
                          });
                        }
                      );
                    } else {
                      alerts.push({ type: "success", message: "All resources for application " + $scope.name +
                        " were created successfully."});
                    }
                    d.resolve({alerts: alerts, hasErrors: hasErrors});
                  }
                );
                return d.promise;
              },
              function(result) { // failure
                $scope.alerts["create"] =
                  {
                    type: "error",
                    message: "An error occurred creating the application.",
                    details: "Status: " + result.status + ". " + result.data
                  };
              }
            );

The failure logic seems useless in the code snippet

**Comment by spadgett** [comment]
It looks like there's at one case where the deferred is resolved as a failure, which would trigger this code.

https://github.com/spadgett/origin-web-console/blob/f517fe8456628870ad7dfdac6e247abf385b43a2/app/scripts/services/data.js#L346-L354

Although if we pass a correct action name, it won't happen.

**Comment by jwforres** [comment]
closing since this has been answered
