### ISSUE TITLE
category system isn't properly showing custom java, has usability issues

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin-web-console#1189]
Referencing the source:
https://github.com/openshift/origin-web-console/blob/c9474fc80ed7b5174e97ff168531384dccb049ba/app/scripts/constants.js#L283-L319

And the docs:
https://docs.openshift.org/latest/install_config/web_console_customization.html#configuring-catalog-categories

And the following `ImageStream` gist:
https://gist.github.com/thoraxe/23449ba2aa50fd32c4b21ff4a0017a24

* This Java IS does not appear natively in the Java category
* The docs describe how to add featured and additional language categories, but not how to add subcategories
* Java subcategories are hard-coded as opposed to being introspected by some kind of labeling or tagging system

Ultimately this adds up to a bit of a usability issue. As an example, customers may be using alternative Java middleware stacks (MuleSoft, Spring, etc) and there does not appear to be a way for them to add a category for their own solutions and then have those show underneath.

I can find my Java IS by searching, but it will not appear any way in the current OCP 3.4.0.40 console in the Add to Project dialog.

**Comment by spadgett** [comment]
@thoraxe Your builder with the `java` tag should appear in the Java category. It's a bug that it's not showing up.

The subcategories are customizable as well. We can improve the doc here.
