### ISSUE TITLE
Can not add a role to "default" serviceaccount through the console

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#1191]
When you have a project and you want to add a role to the default serviceaccount, this one does not show in the console, so it's not possible to add an additional role, like "view".
![image](https://cloud.githubusercontent.com/assets/78350/22396543/6f53ae96-e55c-11e6-8a95-42b19429c0ab.png)

But the service account is there in the system, as "default" service account is always there even if you delete it, it will get recreated by openshift.
![image](https://cloud.githubusercontent.com/assets/78350/22396553/a46bedd2-e55c-11e6-8b98-675ac27ba938.png)

**Comment by benjaminapetersen** [comment]
So the API does not return `default` in the list.  I'm going to guess its similar to how it does not return any user who currently has no role.  Its not comprehensive.  

You can add a role to `default` if you type it in the input box manually.  To make this work, we could make a separate request for `serviceaccounts` and build the response into the table, listing SAs w/o roles anyway.  

Checking with @enj to verify, `service accounts` would be the only special case (belonging to the namespace), where users, groups, system users & system groups do not. 

@jwforres

**Comment by enj** [comment]
Yeah a special case to list all service accounts in the namespace seems reasonable.  All the other tabs are for cluster resources so it does not make sense to list all of those.
