### ISSUE TITLE
Overview tile too wide for mobile screen

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1205]
![screen shot 2017-02-01 at 8 19 31 am](https://cloud.githubusercontent.com/assets/1167259/22508264/3366e4b8-e857-11e6-8b2d-4d90224a0848.png)

**Comment by spadgett** [comment]
Seems to only happen with metrics enabled

**Comment by rhamilto** [comment]
This also reproduces happening in Safari (not just mobile Safari).

**Comment by spadgett** [comment]
Closing as the new overview has merged.
