### ISSUE TITLE
Label filter has small click target

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1212]
The label filter has a nice wide input, but only part of it is clickable. You should be able to click anywhere in the input to focus it rather than just the small area with the placeholder text.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/22519229/a0fe6bb0-e87d-11e6-8ed2-9e1ff2f0788c.png)

**Comment by jwforres** [comment]
yeah it will be tricky because while it looks like "one big input" in reality it is several inputs styled to flow together like it is one input :-\

**Comment by sg00dwin** [comment]
@spadgett @jwforres 

We can set the default `.not-full` input when to a larger widths based on viewport widths
https://github.com/openshift/origin-web-console/pull/1216

**Comment by spadgett** [comment]
Fixed by #1216
