### ISSUE TITLE
Changing deploy config type from "Rolling" to "Custom" results in inability to save DC

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1224]
![screen shot 2017-02-06 at 4 39 54 pm](https://cloud.githubusercontent.com/assets/895728/22667474/e5ea35cc-ec8a-11e6-90a8-0785f048c9fb.PNG)

I'm not sure if I should be able to change an existing DC type from "rolling" to "custom", but the fact that the UI allows me to do it suggests that I can.

**Comment by rhamilto** [comment]
@jwforres @spadgett

**Comment by spadgett** [comment]
@rhamilto Can you save if you type in an image name?

**Comment by rhamilto** [comment]
D'oh!  Yup.  Completely overlooked that.  Thanks, @spadgett.
