### ISSUE TITLE
Add to project failed with cluster scoped resource

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin-web-console#1225]
A template containing a ClusterRoleBinding failed to create in the web-ui with:

```
Cannot create cluster role binding "heapster-cluster-reader". the server could not find the requested resource.
```

probably because cluster role binding is cluster scoped.

**Comment by jwforres** [comment]
This is already tracked in this trello story and its associated RFE in bugzilla

https://trello.com/c/RCU304BD
