### ISSUE TITLE
Other Resources Page - 'Choose a Resource' Dropdown 100% Width after Page Resize

### ISSUE THREAD

**Issue by MarkDeMaria** [openshift/origin-web-console#123]
On the 'Other Resources' Page, if after page load the window is resized in any way (horizontal or vertical) the 'Choose a Resource' dropdown will expand to 100% of the page width when clicked. See screenshot.

![image](https://cloud.githubusercontent.com/assets/19572090/16499331/e9804d68-3ecd-11e6-9167-e5a73fa48c05.png)

Occurred on Fedora 23 in Chrome & Firefox

**Comment by MarkDeMaria** [comment]
@benjaminapetersen

**Comment by benjaminapetersen** [comment]
@MarkDeMaria  Got it tagged.  Is probably a similar issue as you resolved with the terminal picker.  Feel free to pick it off if you have some down time in the future.
