### ISSUE TITLE
Long Labels within the Other Resources table are not truncating and extending beyond the table

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#1230]
![screen shot 2017-02-08 at 1 15 05 pm](https://cloud.githubusercontent.com/assets/1874151/22750970/bd97020e-ee00-11e6-9ccf-01650af89b36.png)

**Comment by spadgett** [comment]
Likely a problem for the config maps page as well.

**Comment by sg00dwin** [comment]
thanks @spadgett I'll inspect it as well!

**Comment by sg00dwin** [comment]
Issue exists on config maps.

![screen shot 2017-02-08 at 2 32 16 pm](https://cloud.githubusercontent.com/assets/1874151/22753870/9e76e794-ee0b-11e6-9b0e-b01ead9f1425.png)

**Comment by sg00dwin** [comment]
@spadgett anything needed for this to merge

**Comment by spadgett** [comment]
@sg00dwin We're waiting for the stream to open for 1.6 for lower priority bugs.
