### ISSUE TITLE
Traffic table at mobile wastes vertical space showing the arrows

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#1232]
The Service page's Traffic table is wasting a lot of vertical space at mobile showing the TD's with the arrows in them.

1) Do we still need the arrows at mobile?
2) If we do could we do something like move the arrow up to the left of the content in the previous TD so we dont waste whole rows on it

![traffic-table-mobile](https://cloud.githubusercontent.com/assets/1467629/22797134/3fc2a5ba-eecb-11e6-999e-9bcad03e5928.png)

**Comment by jwforres** [comment]
@ncameronbritt @spadgett

**Comment by rhamilto** [comment]
Maybe arrows overlaying the border between cells?

![3fc2a5ba-eecb-11e6-999e-9bcad03e5928](https://cloud.githubusercontent.com/assets/895728/25186878/72d2d3b2-24ef-11e7-8a69-0969ceedc096.png)

**Comment by ncameronbritt** [comment]
To me, having the arrows at all seems a little strange since what I'm looking at appears to be a table (or definition list). 

If it's important to understand those connections, could the labels for those three lines be in a row with the values underneath, reducing three lines to two?

**Comment by beanh66** [comment]
Agreed, using the arrows vertically seems strange. I'd say drop the arrows for mobile if possible, and if we think they can't go then try the suggestion from @ncameronbritt with still horizontal arrows but stacking the label over the value.
