### ISSUE TITLE
Config map table at mobile may not be obvious that the full values isn't visible

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#1237]
If you have a config map with a lot of key/value pairs in it, or even just on with a lot of content in a value, then at mobile the horizontal scrollbar that appears may end up off the bottom of the screen.  Could we do something like a fade effect on the right side of the content area to indicate that there is more content that is pushing to the right and that its a scrollable content area?

![config-map-scrolling](https://cloud.githubusercontent.com/assets/1467629/22797731/6ecc9e18-eecd-11e6-8aad-3ea88a1ea7ac.png)

**Comment by jwforres** [comment]
@ncameronbritt @rhamilto do we have anything in patternfly today where there is stylistic indicator that content is scrolling behind an edge?

**Comment by rhamilto** [comment]
Not that I'm aware of.
