### ISSUE TITLE
404 pages for config maps and secrets differ

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1244]
I noticed this in testing the [KVE changes](#1090) as they currently make it possible to navigate to one of these 404 pages if a config map or secret in use a pod gets deleted.

![screen shot 2017-02-10 at 9 35 17 am](https://cloud.githubusercontent.com/assets/895728/22830428/82788a10-ef74-11e6-9688-af016f743c1d.PNG)

* uses an alert (which appears to be the "standard" on most other pages)
* has orphaned content on the page (dropdown, "created")

![screen shot 2017-02-10 at 9 35 49 am](https://cloud.githubusercontent.com/assets/895728/22830427/82747ed4-ef74-11e6-8f4e-ed9d21ad7562.PNG)

* uses blank slate 

Presumably we want these pages to be the same.  We probably need to look at all 404 pages across the app and make sure we're consistent.

**Comment by spadgett** [comment]
FWIW, I prefer the blank state message.

Also a problem now that we added links to the events table. Events frequently link to pods that have no longer exist, so it's easy to get a 404.

**Comment by rhamilto** [comment]
Resolved by #1298

**Comment by spadgett** [comment]
@rhamilto I feel like we should fix this for all our pages so we're consistent everywhere

**Comment by rhamilto** [comment]
@spadgett, I don't disagree.  New issue?

**Comment by spadgett** [comment]
Either way, I just didn't want to lose track.
