### ISSUE TITLE
Ability to customize precanned templates

### ISSUE THREAD

**Issue by kargakis** [openshift/origin-web-console#1258]
Ever since volume provision was added in `oc cluster up` I have been playing around with the Jenkins persistent template and it has been really cool that I can have my Jenkins instance persisted between tearing down and spinning up development clusters. What I miss is the ability to specify a PVC directly in the template so I can reuse my already existing data. Maybe not an issue for the console only but also for expanding our templates to support this use case.

**Comment by kargakis** [comment]
I think I want the ability to edit the template and change more values for my project (the actual template shouldn't be edited).

**Comment by jwforres** [comment]
This goes against what Templates are intended to be, which is a black box with parameters. As we move toward using the service catalog and template broker I see this being even less likely for us to do.

cc @bparees
