### ISSUE TITLE
Inconsistency with progress bar on build page

### ISSUE THREAD

**Issue by tracyrankin** [openshift/origin-web-console#126]
On the overview page, the progress bar shows animation when things are running.  When you go to the build page though and look at the list of the builds, the progress bar doesn't show animation.  It is an inconsistency first, but it also makes you wonder if things are actually running still.

**Comment by benjaminapetersen** [comment]
@sg00dwin ping! bet you know the most about this one.

**Comment by spadgett** [comment]
CC @ajacobs

**Comment by spadgett** [comment]
CC @ajacobs21e

**Comment by sg00dwin** [comment]
I spoke with Tracy and want to capture a couple of items we went over.

On the builds page, when a pipeline stage is 'in progress' it's represented as a blue bar/circle and fa-refresh icon that is not spinning, but on the left in the build status block the icon is spinning. 

![in-progress-build-stage](https://cloud.githubusercontent.com/assets/1874151/16530081/33c408c6-3f94-11e6-9d3b-195bb6ddd4f9.png)

An also, on the overview page the 'in progress' build stage animation (bar/circle with time) is different from what's on the 'in progress' pipeline stage above. Should those have a more closely aligned representation or are they similar enough visually?

<img width="507" alt="screen shot 2016-07-01 at 2 10 30 pm" src="https://cloud.githubusercontent.com/assets/1874151/16530333/a21c41ac-3f95-11e6-9359-8f218e780e49.png">

**Comment by spadgett** [comment]
We might look at this as part of https://trello.com/c/Fpx4DBwy

**Comment by ajacobs21e** [comment]
@sg00dwin the visualizations should be the same on both pages

**Comment by ajacobs21e** [comment]
see https://github.com/openshift/origin-web-console/issues/113#issuecomment-230606479
