### ISSUE TITLE
Dupes error on overview when using the edge cases.yml file

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1267]
Just got this error setting up a fresh project:

![screen shot 2017-02-20 at 11 34 40 am](https://cloud.githubusercontent.com/assets/280512/23133876/af75784a-f760-11e6-963f-28643de40331.png)

- Repeater: `service in childServices`, Duplicate key: `undefined:undefined`.  

Digging around to see whats up.

**Comment by benjaminapetersen** [comment]
@spadgett @jwforres

**Comment by spadgett** [comment]
I see the problem.
