### ISSUE TITLE
Consider what we can do to reduce complexity in template logic

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#127]
Original comment is here: https://github.com/openshift/origin-web-console/pull/82/files#r69194937

Some of our template logic may be getting out of hand.  Here is one example from `browse/_deployment-details.html`:

``` html
<button 
  ng-if="'deploymentconfigrollbacks' | canI : 'create'" 
  ng-show="!rollBackCollapsed && (deployment | deploymentStatus) == 'Complete' && !(deployment | deploymentIsLatest : deploymentConfig) && !deployment.metadata.deletionTimestamp" 
  ng-disabled="(deploymentConfigDeploymentsInProgress[deploymentConfigName] | hashSize) > 0" 
  type="button" 
  class="btn btn-default btn-xs" ng-click="rollBackCollapsed = !rollBackCollapsed">
```

The `ng-show` in particular has a lot of details.  I think we could probably reduce this down to `<button ng-show="showRollBack">Roll back</button>` and use a clearly named function to set the boolean in the controller.  

Thoughts @jwforres @spadgett

**Comment by jwforres** [comment]
I'd say in that particular example it makes sense.  It is definitely a balance, we don't want to have a million helper methods either.

**Comment by jwforres** [comment]
moving forward we want to have a rule that 3 boolean clauses in an ng-if is ok if they aren't too complex, but 4 is too many
