### ISSUE TITLE
Replicas inline edit jumps in Safari, when switching between edit and no edit states

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#128]
Ideally the states would toggle seamlessly, but angular is applying an ng-animate before the ng-hide, which has the effect of both states being visible briefly.

**Comment by spadgett** [comment]
This might be better as a dialog anyway

**Comment by jwforres** [comment]
We have the hide-ng-animate class for a shorter term fix.  Switching to a dialog would be a P3 enhancement
