### ISSUE TITLE
Simplify get and watch in controllers

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#129]
We have a lot of this:

``` javascript
DataService
  .get('something', $routeParams.something, context)
  .then(function resolve(theThing) {
     // do lots of things...
    watches.push(DataService
      .watchObject('something', $routeParams.something, context, function(theThing) {
         // do lots of the same things again...
      }));      
  }, function reject(err) {

  });
```

I'm guessing this is to get at any cached data if we have it while waiting for the watch.  I'm wondering if we can eliminate the duplication by one of these:

``` javascript
// option 1: 
// ---------------------------------
// get data out of cache (DataService._data(key)) then watch it
$scope.theThing = DataService.getCached(itsName);
DataService
  .watchObject('something', itsName, context, function(theThing) {
    $scope.theThing = theThing;
  }, reject);




// Option 2: reuse resolve/reject functions
// ---------------------------------
var resolve = function(theThing) {
  // do stuff
};
var reject = function(err) {

}

DataService
  .get('something', itsName, context)
  .then(resolve, reject);
DataService
  .watchObject('something', itsName, context, resolve, reject);




// option 3:
// ---------------------------------
// perhaps we have to ensure the GET happens before the WATCH
// so that we dont get out of sync data. 
// has an extra anonymous function but otherwise seems clean
  var resolve = function(theThing) {
    $scope.theThing = theThing;
    // do other happy stuff...
  };
  var reject = function(err) {
    // do sad stuff...
  }

  DataService
    .get('something', itsName, context)
    .then(function(theThing) {
      resolve(theThing);
      DataService
        .watchObject('something', itsName, context, resolve, reject); // reuse resolve, reject
    }, reject);


```

Prob option 3 would win us the most cleanup.

Thoughts @jwforres @spadgett ?

TODOs to resolve this issue
- [x] update `controllers/build.js` (PR #133)
- [x] update `controllers/buildConfig.js`
- [x] update `controllers/deployment.js`
- [ ] update `controllers/deploymentConfig.js`
- [x] update `controllers/image.js`
- [x] update `controllers/persistentVolumeClaims.js`
- [x] update `controllers/pod.js`
- [x] ~~update `controllers/pods.js`~~
- [x] update `controllers/route.js`
- [x] update `controllers/service.js`

**Comment by benjaminapetersen** [comment]
Btw, my initial thought was to do a `.get()` internally to `.watch()` and use the same callback function, but don't think thats a good idea.

**Comment by jwforres** [comment]
We do a get and then a watch because we don't get a 404 or 403 by watching.
We need to be able to return appropriate error codes and messages when a
user tries to access an object they can't get to.

**Comment by jwforres** [comment]
So adding to my last comment, this all comes back to previous discussions we've had about the fact that our 'watch' methods have no concept of an error callback.  If we wanted to consolidate to a single "watchObject" call here then we'd need both a handler to call when any data is returned, and a handler to call in the even there is an error on initial retrieval of the object.  Under the covers, yes we would have to do a GET and then start watching using a fieldSelector with the name of the object.

**Comment by benjaminapetersen** [comment]
I was initially thinking that but messing with `.watch()` and `.watchObject()` more seems like a bigger risk. I think I'm ok with leaving `.watch()` and `.watchObj()` as is they are and letting the `.get()` handle errors:
```javascript
var someObjResolve = function(resp) {  /* do stuff */  }
var someObjReject = function(err) {  /* do stuff */  }
DataService
  .get('some-obj')
  .then(function resolve(resp) {
    someObjResolve(resp);
    DataService.watch('some-obj', someObjResolve)
  }, someObjReject) // trust the GET will handle the err...

```
Unless 1.) we are worried that the WebSocket is swallowing valuable error info or 2.) we came up with a good name like `.observe()` as a wrapper around both `.get()` and `.watch()`, but I'm not actually sure if that would be an easy win either. 😕

**Comment by jwforres** [comment]
So really all you are asking for is to consolidate the resolvers to be the
same function which is called from both places like you did in your example
PR?

**Comment by benjaminapetersen** [comment]
I follow you, I'd like to not have to do both `.get` and `.watch`, but initially I'm thinking that at least sharing the resolve fns could be enough of a win w/o a major change.
