### ISSUE TITLE
Better way to access variables for extensions?

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin-web-console#131]
For extension purposes, is there a better way to access variables such as user name?

Docs have lead me towards making something like this which feels a little hacky

```
// Fake add to get access to $scope
HawtioExtension.add('nav-help-dropdown', function($scope) {
    openshiftName = ($scope.$parent.user.fullName || $scope.$parent.user.metadata.name);
    return null;
});
```

**Comment by benjaminapetersen** [comment]
The newer extension framework resolves this by passing contextually appropriate data to the callback function.  Checkout the [mobile nav extension](https://github.com/openshift/origin-web-console/blob/master/app/scripts/extensions/nav/dropdownMobile.js) to see how the user object is passed here.  

The particular extension you are working with may not have the objects you are looking for right now, but clarify your need & we can see what is possible.

**Comment by andrewklau** [comment]
Originally I tried that method, but I was not able to return any results with something along the lines of user variable not found. 

Basically I just want to be able to get access to the variables like user name, email, number of projects etc. to be used in a javascript script for external analytical purposes.

**Comment by benjaminapetersen** [comment]
Yup, extension points are not particularly hard to add, nor is passing data.  Leave us some comments with various places you are looking to add the extensions & the data desired & we can review.

**Comment by andrewklau** [comment]
I have a feeling we're on a slightly different page.  

If we want to extract information such as fullname to be used in another extension script we're doing something below which is dependent on assuming nav-help-dropdown is always going to be available:

```
var openshiftName;

angular.module('exampleExtension', ['openshiftConsole'])
    .run(function(HawtioExtension) {
        // Fake add to get access to $scope
        HawtioExtension.add('nav-help-dropdown', function($scope) {
            openshiftName = ($scope.$parent.user.fullName || $scope.$parent.user.metadata.name);
            return null;
        });
    });

// do something else with openshiftName here...
```

My query was whether there a better way to expose $scope without having to hook into the HawtioExtension.add function?

**Comment by benjaminapetersen** [comment]
Are you implying you want global access to data, rather than contextual?  There are many `$scopes` in an angular app, they cannot/should not all be global.

**Comment by andrewklau** [comment]
Sort of yes, if we're only dropping in changes through things like extension.css and extension.js, it would be nice to have a clean way to get these sort of data values to send to things like an external support application, or trigger events, outside of the openshift web console.

The above method works well for our use case, but seems a bit redundant in it's implementation.

**Comment by benjaminapetersen** [comment]
If you are not aiming to extend the console, but instead just want the data, perhaps using the API would be better?

**Comment by andrewklau** [comment]
Take the zendesk widget as an example (https://developer.zendesk.com/embeddables/docs/widget/api#ze.identify) and we add it using the documented method of loading custom scripts (https://docs.openshift.com/enterprise/3.2/install_config/web_console_customization.html#loading-custom-scripts-and-stylesheets)

I was hoping injecting details like Name and Email could be done without what we discussed above.

**Comment by benjaminapetersen** [comment]
The ZenDesk widget seems to be something you embed in another application that you are building.  The OpenShift web console is going the opposite direction, allowing you to build widgets you can inject into the console itself.  These widgets get contextual info (a nav extension gets nav related data, an extension point for builds would get data for builds, etc). 

Are you trying to build something to embed outside the console?

**Comment by liggitt** [comment]
Ben, the extension points are display oriented today. I think he's asking for a data oriented extension point - one which gets specific data available to the console, but doesn't particularly display anything. Do we have an extension point that receives structured user data?

**Comment by benjaminapetersen** [comment]
Ah, we don't yet, but I don't believe there is anything keeping us from adding extensions points like that.

**Comment by andrewklau** [comment]
Yes! That would be helpful, as it'll avoid having to do the above workaround.

**Comment by jwforres** [comment]
Moving to trello https://trello.com/c/0UzanvEF
