### ISSUE TITLE
Pod metrics should display memory cache information

### ISSUE THREAD

**Issue by MarkRx** [openshift/origin-web-console#1315]
By default docker reports memory usage as RSS + cached memory (https://github.com/docker/docker/issues/10824). This propagates up to kubernetes and OpenShift. As a result pod metrics memory usage may be misleading as a large portion of the memory being used may be cached memory.

It would be useful if the UI graph could show both the used memory along with the used memory + cached memory.

Example: Pod is using 771MiB of memory along with an additional 965MiB of cached memory:

OpenShift reports the pod as using 1656MiB of memory. RRS + cache = 1736323072 (KB = 1000) = 1736323072  * (1000/1024) * (1000/1024) = 1656 MiB (KB = 1024)

![osememory_blur](https://cloud.githubusercontent.com/assets/17504314/23470314/11142f3c-fe74-11e6-8b39-6f47e039d35a.png)

> sh-4.2$ more /sys/fs/cgroup/memory/memory.stat                                                                             
> cache 965206016                                                                                                            
> rss 771117056                                                                                                              
> rss_huge 708837376                                                                                                         
> mapped_file 17211392                                                                                                       
> swap 0                                                                                                                     
> pgpgin 32432830                                                                                                            
> pgpgout 32487730                                                                                                           
> pgfault 137177683                                                                                                          
> pgmajfault 389                                                                                                             
> inactive_anon 0                                                                                                            
> active_anon 771096576                                                                                                      
> inactive_file 486178816                                                                                                    
> active_file 479027200                                                                                                      
> unevictable 0                                                                                                              
> hierarchical_memory_limit 2147483648                                                                                       
> hierarchical_memsw_limit 9223372036854771712                                                                               
> total_cache 965206016                                                                                                      
> total_rss 771117056                                                                                                        
> total_rss_huge 708837376                                                                                                   
> total_mapped_file 17211392                                                                                                 
> total_swap 0                                                                                                               
> total_pgpgin 32432830                                                                                                      
> total_pgpgout 32487730                                                                                                     
> total_pgfault 137177683                                                                                                    
> total_pgmajfault 389                                                                                                       
> total_inactive_anon 0                                                                                                      
> total_active_anon 771096576                                                                                                
> total_inactive_file 486178816                                                                                              
> total_active_file 479027200                                                                                                
> total_unevictable 0       

sh-4.2$ ps -aux (ignore all my terminals)

> USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND                                                  
> 1000060+      1  0.0  0.0   4312   360 ?        Ss   Feb22   0:07 /usr/bin/tini -- /usr/bin/docker-entry.sh java -Dcom.sun.
> 1000060+      6  0.0  1.1 20665852 759988 ?     Sl   Feb22   8:45 /usr/lib/jdk/jdk1.8.0_111/bin/java-real -Xloggc:/logs///t
> 1000060+     75  0.0  0.0  11776  1728 ?        Ss   Feb22   0:00 /bin/sh                                                  
> 1000060+     80  0.0  0.0  24884  1648 ?        S+   Feb22   0:00 vi /config/application.properties                        
> 1000060+   4313  0.0  0.0  11780  1852 ?        Ss+  Feb27   0:00 /bin/sh                                                  
> 1000060+   5968  0.0  0.0  11780  1828 ?        Ss+  Feb27   0:00 /bin/sh                                                  
> 1000060+  12423  0.0  0.0  11780  1728 ?        Ss+  Feb27   0:00 /bin/sh                                                  
> 1000060+  12474  0.0  0.0  11776  1784 ?        Ss   Feb27   0:00 /bin/sh                                                  
> 1000060+  14135  0.0  0.0  24868  1632 ?        S+   Feb27   0:00 view application.properties                              
> 1000060+  18460  0.0  0.0  11780  1796 ?        Ss+  Feb27   0:00 /bin/sh                                                  
> 1000060+  43304  0.0  0.0  11776  1780 ?        Ss+  09:38   0:00 /bin/sh                                                  
> 1000060+  43667  0.0  0.0  11776  1728 ?        Ss   09:44   0:00 /bin/sh                                                  
> 1000060+  43690  0.0  0.0  51884  2008 ?        S+   09:45   0:02 top                                                      
> 1000060+  44966  0.0  0.0  11776  1772 ?        Ss+  10:07   0:00 /bin/sh                                                  
> 1000060+  48016  0.0  0.0  11780  1824 ?        Ss+  11:00   0:00 /bin/sh                                                  
> 1000060+  49592  0.0  0.0  11776  1772 ?        Ss+  11:28   0:00 /bin/sh                                                  
> 1000060+  49990  0.0  0.0  11776  1728 ?        Ss   11:35   0:00 /bin/sh                                                  
> 1000060+  50668  0.0  0.0  47428  1688 ?        R+   11:46   0:00 ps -aux   

What I would like to see (perhaps with a tooltip that explains the meaning if I hover over it):
![osememory_blur_cache](https://cloud.githubusercontent.com/assets/17504314/23470941/be248ebe-fe75-11e6-8259-bf70a6feeb7e.png)

**Comment by spadgett** [comment]
cc @mwringe

**Comment by jwforres** [comment]
@mwringe is this something that has been discussed on the hawkular side at all?

**Comment by spadgett** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1431667

**Comment by jwforres** [comment]
De-duping in favor of the bugzilla
