### ISSUE TITLE
Top border of last input hidden when revealing secret

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1320]
The top border of the last copy-to-clipboard input is not visible.

![screen_shot_2017-03-06_at_8_03_05_am](https://cloud.githubusercontent.com/assets/1167259/23611076/7d409664-0243-11e7-994a-634584a843e0.png)

Seems to be related to the `overflow-x` style:

![screen shot 2017-03-06 at 8 06 42 am](https://cloud.githubusercontent.com/assets/1167259/23611165/eed790ca-0243-11e7-9dfe-f520712f8a5e.png)

![screen shot 2017-03-06 at 8 06 48 am](https://cloud.githubusercontent.com/assets/1167259/23611170/f21fbaf0-0243-11e7-8950-982b1d0d6bdb.png)

**Comment by rhamilto** [comment]
Fixed by #1451
