### ISSUE TITLE
Affixed "Follow" link misaligned on Firefox for Mac

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1322]
Extra gap between the edge of the log and the follow link. It should be flush with the black background's edge. We appear to be accounting for the scrollbar width, but on Firefox for Mac, there's no scrollbar.

<img width="288" alt="screen_shot_2017-03-06_at_8_13_20_pm" src="https://cloud.githubusercontent.com/assets/1167259/23637427/9b6eacfa-02a9-11e7-8326-2394bf56d339.png">

**Comment by sg00dwin** [comment]
@spadgett this is another issue that i'm unable to reproduce. Is this something you consistently see? 

Following log before scrollbar needed
<img width="392" alt="screen shot 2017-03-10 at 12 19 00 pm" src="https://cloud.githubusercontent.com/assets/1874151/23805519/2ceffef6-058c-11e7-8660-8fe3a5900916.png">


Following log with scrollbar
<img width="395" alt="screen shot 2017-03-10 at 12 19 04 pm" src="https://cloud.githubusercontent.com/assets/1874151/23805478/08b2942c-058c-11e7-9bd4-eb6d38707db6.png">

**Comment by spadgett** [comment]
My version of Firefox hides the scrollbar when not active. It might depend on your mac system settings.

**Comment by sg00dwin** [comment]
ok, I think i've found the instance of when it happens. looking further...
