### ISSUE TITLE
grunt-autoprefixer is very outdated

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1337]
We're currently 13 releases behind the most recent release of [grunt-autoprefixer](https://github.com/nDmitry/grunt-autoprefixer).  We should probably update.

**Comment by spadgett** [comment]
We should look at other dev dependencies, too. For instance, our ng-annotate version is quite old.

**Comment by benjaminapetersen** [comment]
Yeah, think its been a good year now since we did a sweep & update?  Time flies...
