### ISSUE TITLE
Unknown Provider: SecurityCheckServiceProvider

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1345]
Just ran across this, guessing it might be from pulling some things out of origin-web-console into the commons lib:

<img width="1437" alt="screen shot 2017-03-14 at 5 13 57 pm" src="https://cloud.githubusercontent.com/assets/280512/23922700/c6161a16-08d9-11e7-8b09-de1c6817b8f1.png">

on url:
`https://localhost:9000/dev-console/project/myproject/create/fromtemplate?template=nodejs-mongo-persistent&namespace=openshift`

@jwforres @spadgett

**Comment by jwforres** [comment]
No that is new code, and was already validated by QE.  Are you on master?

**Comment by benjaminapetersen** [comment]
Branched off master, nothing new when i last fetched.

**Comment by jwforres** [comment]
you do need to install-deps since master depends on a more recent version
of origin-web-common

**Comment by benjaminapetersen** [comment]
yeah i reinstalled via bower/npm, but ill do another run & check.

**Comment by benjaminapetersen** [comment]
I'll close this, ran the installs again and I think everything is working.
