### ISSUE TITLE
Spacing above alerts on empty state overview is different

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1346]
![screen shot 2017-03-15 at 9 41 52 am](https://cloud.githubusercontent.com/assets/895728/23951512/a286cc68-0964-11e7-953b-e1659fb4d52c.PNG)

**Comment by spadgett** [comment]
@rhamilto Which overview version? :)

**Comment by rhamilto** [comment]
The new one. @sg00dwin is investigating.
