### ISSUE TITLE
"Stuck" transition on overview

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1347]
I'm not entirely sure how I ended up here, but have a tile stuck in transition:
![screen shot 2017-03-15 at 10 36 53 am](https://cloud.githubusercontent.com/assets/280512/23953610/7d736290-096b-11e7-839b-0634ec40fa67.png)

I'll keep the proj for a bit if we want to debug.

@spadgett @sg00dwin

**Comment by jwforres** [comment]
The new overview just went in, closing this
