### ISSUE TITLE
10 $digest() loop iteration reached if scaling Replica Sets to large enough number

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1350]
Intentionally trying to break it, I scaled up to a point where Angular freaked out:

![screen shot 2017-03-15 at 4 40 11 pm](https://cloud.githubusercontent.com/assets/280512/23969824/2bab5c0a-099e-11e7-939d-a17abce0cd28.png)

I hit the replica editor and entered "50" to case the error.

@spadgett

**Comment by jwforres** [comment]
@benjaminapetersen what page was this from

**Comment by benjaminapetersen** [comment]
ReplicaSets

**Comment by spadgett** [comment]
This seems to be caused  by `orderObjectsByDate` used in pods-table.html
