### ISSUE TITLE
sweep for .length checks, migrate to _.size()

### ISSUE THREAD

**Issue by liggitt** [openshift/origin-web-console#1352]
many API array fields have the potential to be either `null` or `[]`. for safety, we should consistently use _.size() or _.isEmpty() to handle both cases

**Comment by liggitt** [comment]
in 1.6, when we switch to protobuf storage, optional array fields will start tending to be null instead of [] (the `items` field in List objects guarantees `[]`, and objects where `null` vs `[]` is significant will preserve the distinction, but others will prefer null)

**Comment by spadgett** [comment]
@benjaminapetersen Is this complete?

**Comment by benjaminapetersen** [comment]
@spadgett close, I've been through the console & common, I believe the catalog is only partially complete.

**Comment by jwforres** [comment]
@benjaminapetersen think finishing the sweep of catalog is something you could wrap up today? at least identifying whats left and leaving some pointers in here if theres not enough time to get the PRs open

**Comment by benjaminapetersen** [comment]
@jwforres @spadgett I combed through the 3 repos for length checks in JS files, I believe we are good there.  I have not checked over `/views` yet.  It might be a good idea to look through the `html` for `.length` checks that might need an updated to ` | size` filters.

**Comment by spadgett** [comment]
> I have not checked over /views yet. It might be a good idea to look through the html for .length checks that might need an updated to | size filters.

From an API standpoint at least we should be OK. There's no runtime error in the view, and length checks will evaluate to false if the array is undefined.

**Comment by benjaminapetersen** [comment]
Right, the views should handle themselves w/o error.  I think we can close this.
