### ISSUE TITLE
OpenShift Web Console customizing template know-how

### ISSUE THREAD

**Issue by eurodomenii** [openshift/origin-web-console#1353]
The customizations steps decribed at https://docs.openshift.org/latest/install_config/web_console_customization.html#customizing-the-about-page doesn’t work for me. Below are the configuration details, in order to identify the missing part. 

##### Version
oc v1.4.1
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1)  /etc/origin/master/mycustomization/about/about.js
```
angular
  .module('aboutPageExtension', ['openshiftConsole'])
  .config(function($routeProvider) {
    $routeProvider
      .when('/about', {
        templateUrl: 'extensions/about/about.html',
        controller: 'AboutController'
      });
    }
  );

```
2) _/etc/origin/master/mycustomization/about/about.html_  is a modified version of https://github.com/openshift/origin-web-console/blob/master/app/views/about.html

3) _/etc/origin/master/master-config.yaml_
```
...
assetConfig:
  extensionScripts:
    - mycustomization/about/about.js
  extensions:
    - name: about
      sourceDirectory: mycustomization/about
...

```
4) systemctl restart origin-master  or rebooting the master

##### Current Result
console/about unchanged 

##### Expected Result
console/about should provide the new template

##### Additional Information
-The new about.js scripts shows up correctly under _/console/scripts/extensions.js_
-The new custom template shows up correctly under  _/console/extensions/about/about.html_

- Instead of trying to replace with my custom page, I have tried to replace _/create-project_ with content from main page. ( won’t work)
 
cat /etc/origin/master/mycustomization/createfake.js
```
angular
  .module('FakeCreate', ['openshiftConsole'])
  .config(function($routeProvider) {
    $routeProvider
      .when('/create-project', {
        templateUrl: 'views/projects.html',
        controller: 'ProjectsController'
      });
    }
  );

``` 
vim /etc/origin/master/master-config.yaml
```
... 
assetConfig:
  extensionScripts:
    - mycustomization/createfake.js
...

```
Thank you!

**Comment by jwforres** [comment]
Ah I'm fairly certain its because you need to add this to the bottom of your js file

```
hawtioPluginLoader.addModule('aboutPageExtension');
```

This is a documentation bug, opened an issue there https://github.com/openshift/openshift-docs/issues/3964

**Comment by eurodomenii** [comment]
Thanks @jwforres . It works!

**Comment by eurodomenii** [comment]
I should have known  the pattern _hawtioPluginLoader.addModule_ from correct existing example https://docs.openshift.org/latest/install_config/web_console_customization.html#top-navigation-dropdown-menus

**Comment by scheng1** [comment]
@scheng1
