### ISSUE TITLE
Other Resources dropdown has duplicates

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1364]
Likely a side effect of https://github.com/openshift/origin/pull/12986

<img width="248" alt="screen shot 2017-03-19 at 4 17 35 pm" src="https://cloud.githubusercontent.com/assets/1167259/24084374/9d607636-0cbf-11e7-8228-6db08d56cec2.png">

**Comment by jwforres** [comment]
talked with the API folks about this, the suggestion is to just extend our de-duplication list to cover the openshift types.  Our default behavior should stay the same which is to treat kinds from different groups as unique.  As part of fixing this issue we should probably fix this dropdown so it also shows the group when there are duplicates, similar to what we do with duplicate project display names.

I did get confirmation that they are trying to force any new openshift types to go only into API groups, and they will have checks in place in the merge queue that prevent people from adding more types to the old /oapi endpoint.  So hopefully this will be a one time thing, and eventually we'll be able to drop this list once we deprecate /oapi.

**Comment by spadgett** [comment]
@jwforres Does the de-duplication we use in API service allow us to support both groups in templates and import YAML?

**Comment by jwforres** [comment]
Yes, the de-duplication is only in the "availableKinds" method.  It doesn't affect anything else.

**Comment by jwforres** [comment]
To clarify, availableKinds is only used to get a list of unique Kinds, and that is only used in other resources today.

**Comment by jwforres** [comment]
We also need to fix the AVAILABLE_KINDS_BLACKLIST to be handle groups. I'm going to check whether Ingress and Binding should come out of that list now.

**Comment by jwforres** [comment]
Ok so Ingress we can remove since its now covered under the canI list check that we do, and that way it will show up as soon as its allowed.

Binding is allowed under permissions but throws a 405 method not implemented since it doesn't support list.  After the 1.6 rebase lands API discovery will actually include the implemented types, so we will be able to add a second check for "is List implemented" to go with our check for "am i allowed to List"

**Comment by spadgett** [comment]
https://trello.com/c/EjGHumwk

**Comment by jwforres** [comment]
Closing the issue since we are tracking it in trello now

**Comment by jwforres** [comment]
and since its also duplicated in bugzilla

**Comment by spadgett** [comment]
Fixed by https://github.com/openshift/origin-web-common/pull/51
