### ISSUE TITLE
New overview screen always shows 0 pods.

### ISSUE THREAD

**Issue by matskiv** [openshift/origin-web-console#1371]
I was trying new overview screen but I have a problem with number of running pods. It always says "0 scaling to _n_ ..", even when there are pods running.

I am using current master (7f8960af97f07793c657f9f64b1b3d6fc1c5e988) and start it with: 'grunt serve'
Backend is started via 'oc cluster up' (openshift/origin:v1.4.1).

![screenshot from 2017-03-21 14-45-46](https://cloud.githubusercontent.com/assets/1605799/24150284/a55c515c-0e45-11e7-9717-63f195cfaa25.png)

**Comment by spadgett** [comment]
@matskiv Can you try with latest master?

```
$ docker pull openshift/origin:latest
$ oc cluster up --version=latest
```

I think the runtime error is because PetSets were renamed StatefulSets.

**Comment by matskiv** [comment]
Works great with latest openshit :+1: 
Thank you @spadgett
