### ISSUE TITLE
spinner is "trembling"

### ISSUE THREAD

**Issue by andreasn** [openshift/origin-web-console#1373]
This is just a tiny little thing I ran across. For some reason the spinner is shaking a lot.
https://andreasn.portknox.net/s/3lGqmLMa4d8f98f

It's also different from other spinners in Openshift, that uses the [Patternfly spinner](http://www.patternfly.org/pattern-library/widgets/#spinner)
(but that is perhaps a separate issue)

**Comment by spadgett** [comment]
@andreasn What version? We had a similar issue that was fixed relatively recently

cc @rhamilto

**Comment by spadgett** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1365301

**Comment by andreasn** [comment]
This is with console.preview.openshift.com so probably closed in the new version then.

**Comment by spadgett** [comment]
Thanks, I've confirmed that server doesn't yet have the fix. Closing.
