### ISSUE TITLE
Selected very long project names in the project picker result in horizontal scrollbar at mobile resolutions in Safari

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1374]
![screen shot 2017-03-22 at 11 17 37 am](https://cloud.githubusercontent.com/assets/895728/24205281/4fadb8a2-0ef1-11e7-8a84-c61a843f5a95.PNG)

This appears to be a flexbox bug in Safari as it is only reproducible there (mobile Safari does not have the bug). 

@sg00dwin, I'm not sure this is worth the effort given this iteration of the navbar will be EOL-ed soon, but I'm documenting it here for posterity.

**Comment by spadgett** [comment]
Reopening this issue since the fix was reverted.

**Comment by spadgett** [comment]
@sg00dwin @rhamilto Still a problem with the new nav?

**Comment by rhamilto** [comment]
> @sg00dwin @rhamilto Still a problem with the new nav?

Nope.

![screen shot 2017-09-05 at 9 54 27 am](https://user-images.githubusercontent.com/895728/30064616-49baa27c-9220-11e7-81c7-e55db1749cd5.PNG)

Fixed by #1932
