### ISSUE TITLE
Use _.set() for window.OPENSHIFT_CONSTANTS

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-console#1379]
Service catalog will also be creating/extending window.OPENSHIFT_CONSTANTS.  Please use _.set() [here](https://github.com/openshift/origin-web-console/blob/master/app/scripts/constants.js) in order to extend or create window.OPENSHIFT_CONSTANTS.

**Comment by spadgett** [comment]
I think @jeff-phillips-18 has fixed this. @jeff-phillips-18 can you confirm?

**Comment by jeff-phillips-18** [comment]
Yes, this was fixed
