### ISSUE TITLE
Get jenkins log URL from the new annotation instead of modifying it ourselves

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#1384]
See https://github.com/openshift/jenkins-sync-plugin/pull/128

**Comment by jwforres** [comment]
@spadgett @gabemontero FYI opened to track on our side

**Comment by gabemontero** [comment]
Cool - fyi, the openshift jenkins centos image on dockerhub now includes the code that generates the new annotations.

**Comment by gabemontero** [comment]
And https://github.com/openshift/origin/pull/13572 updates the origin side with those new annotations, if that is of consequence to origin-web-console
