### ISSUE TITLE
LogViewer Uncaught TypeError 

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1397]
Prob another related to extracting things out into `origin-web-common`:
![screen shot 2017-04-05 at 10 21 27 am](https://cloud.githubusercontent.com/assets/280512/24712824/f18211ae-19f1-11e7-9699-dad0e7c8291f.png)

@jwforres @spadgett @jeff-phillips-18

**Comment by spadgett** [comment]
This is odd. I don't see how `buffer` can be undefined.

**Comment by spadgett** [comment]
@benjaminapetersen I haven't been able to reproduce. Let me know if you see this again.

**Comment by benjaminapetersen** [comment]
Shall we close? I have not seen again either.

**Comment by spadgett** [comment]
Closing for now. We can reopen if it happens again.
