### ISSUE TITLE
how can i use  *dist* folder

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin-web-console#1406]
Hi i'm trying to host openshift standalone webconsole app.

1) I used **dist**  folder and served it over http
2) added a config.js  file too

Redirect is happening and after login a  404 not fund  page not found on   http://localhost:8080/oauth#long_tokenstring

Can you help me how i can run standalone webconsole and integrate with other openshift api servers

**Comment by spadgett** [comment]
@debianmaster Are you serving the files under a context root? Make sure it you include it in `oauth_redirect_base`.

I'm surprised you didn't need to patch the OAuth client, although it seems like you've gotten past that. Here's the command in case you need it.

```
$ oc login -u system:admin
$ oc patch oauthclient/openshift-web-console -p '{"redirectURIs":["https://localhost:8080/"]}'
```

If you're running the web console on a host other than `localhost`, you'll also need to update the CORS allowed origins in master-config.yaml.

**Comment by debianmaster** [comment]
@spadgett  i did patch it like this
`oc patch oauthclient/openshift-web-console -p '{"redirectURIs":["https://localhost:8080/"]}'`

can you elobrate a bit more on this
`Are you serving the files under a context root? Make sure it you include it in oauth_redirect_base.`

**Comment by spadgett** [comment]
How are you serving the files? Are they at https://localhost:8080/ or under a context root like https://localhost:8080/console ? You'll want to make sure the redirect value in config.js matches.

**Comment by debianmaster** [comment]
i'm serving under   https://localhost:8080/ 
and my config.js is as follows
```javascript
// This is the default configuration for the dev mode of the web console.
// A generated version of this config is created at run-time when running
// the web console from the openshift binary.
//
// To change configuration for local development, copy this file to
// assets/app/config.local.js and edit the copy.
window.OPENSHIFT_CONFIG = {
  apis: {
    hostPort: "master.devday.mycloud.com",
    prefix: "/apis"
  },
  api: {
    openshift: {
      hostPort: "master.devday.mycloud.com",
      prefix: "/oapi"
    },
    k8s: {
      hostPort: "master.devday.mycloud.com",
      prefix: "/api"
    }
  },
  auth: {
    oauth_authorize_uri: "https://master.devday.mycloud.com/oauth/authorize",
    oauth_redirect_base: "http://localhost:8080",
    oauth_client_id: "openshift-web-console",
    logout_uri: ""
  },
  loggingURL: "",
  metricsURL: ""
};

window.OPENSHIFT_VERSION = {
  openshift: "dev-mode",
  kubernetes: "dev-mode"
};
```

**Comment by debianmaster** [comment]
Looks like /oauth endpoint is  NOT found

<img width="776" alt="screen shot 2017-04-10 at 11 49 55 am" src="https://cloud.githubusercontent.com/assets/1439169/24877349/becf715c-1de3-11e7-9cec-1e6b2be8d487.png">

**Comment by spadgett** [comment]
Ah, you'll need to a rewrite rule to serve index.html for URLs that don't match an actual file. Are you using Apache httpd?

**Comment by spadgett** [comment]
See https://github.com/openshift/origin-web-console/blob/master/httpd-cfg/openshift-web-console.conf

**Comment by debianmaster** [comment]
ahh,   makes sense.   i will give a try!!!  thanks @spadgett

**Comment by spadgett** [comment]
Sure thing, good luck

**Comment by jwforres** [comment]
Let us know if you have any other questions on this
