### ISSUE TITLE
Masthead menus are hidden by landing page sidebar.

### ISSUE THREAD

**Issue by jeff-phillips-18** [openshift/origin-web-console#1412]
When on the landing page, the dropdown menus for the help or user menu items are not accessible as they are hidden behind the sidebar.

**Comment by spadgett** [comment]
@jeff-phillips-18 I don't see this in Firefox or Chrome. What browser are you using? Have you run hack/install-deps.sh with latest master?

![screen shot 2017-04-11 at 9 49 04 am](https://cloud.githubusercontent.com/assets/1167259/24912492/41d69f5e-1e9c-11e7-9f56-aadc51c4adf8.png)

**Comment by spadgett** [comment]
Ah I see the open behind the sidebar.
