### ISSUE TITLE
Editing deploy config twice via `Edit YAML` option in immediate succession results in a confusing error

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#142]
<img width="913" alt="screen shot 2016-07-08 at 12 02 01 pm" src="https://cloud.githubusercontent.com/assets/895728/16693693/62b95a1c-4504-11e6-8f3c-f7f3f9175fbc.PNG">

To reproduce:

* Browse to a deployment config and choose `Edit YAML` from the `Actions` menu in the upper right
* Edit an env var
* Click `Save`
* Click `Actions` and `Edit YAML` again
* Make an additional edit to an env var
* Click `Save`
* Notice the resulting error

I notice the error isn't thrown once the `Deploy` button is re-enabled following the deployment resulting from the first edit. 

@benjaminapetersen

**Comment by spadgett** [comment]
We might need to disable the edit yaml menu item until we get an watch update with the previous edits.

**Comment by spadgett** [comment]
Actually that wouldn't fix this... Probably the deployment was updated by the system after you opened the editor since it was in progress. I'm not sure how we can handle this except possibly warning the user the resource has changed.

**Comment by benjaminapetersen** [comment]
Hmm.. this wouldn't fix? 
```javascript

$scope.someSaveAction  = function() {
  $scope.disableEditButtons = true;  // for the ng-disabled in view
  DataService
    .update('someResource')
    .then(function resolve(resp) {
        $scope.disableEditButtons = false;  
    });
};

```

**Comment by spadgett** [comment]
No, the edit triggers a deployment, which I suspect updates the dc status multiple times as it runs.

**Comment by benjaminapetersen** [comment]
Ah, its the same kind of issue as having someone else edit it while you have the editor open... you won't know that your copy is out of date until its too late.

So the next best would be to show a banner on the yaml editor indicating a change has happened, if a watch is triggered while the editor is open?

**Comment by spadgett** [comment]
Yeah, I think that's a good editor change (for any resource).

We could also disable editing while a deployment is in progress if we decide it's a good idea.

**Comment by benjaminapetersen** [comment]
That seems very reasonable to me.  Editing stuff while parts are moving seems risky.
