### ISSUE TITLE
Viewers see empty env var input rather than message when no env vars

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1438]
I thought this was a little odd. I logged in as a user with `view` role in the project. Instead of seeing a message saying there are no env vars, I see two readonly inputs.

![screen shot 2017-04-18 at 12 47 15 pm](https://cloud.githubusercontent.com/assets/1167259/25142536/36ab70a2-2435-11e7-99b0-e03e1919838c.png)

**Comment by benjaminapetersen** [comment]
hmm. yeah that is weird. ill take a look

**Comment by benjaminapetersen** [comment]
I can reproduce this.  So Its probably something we need to either 1. put inside KVE, or 2. update all the templates where KVE appears with an `ng-if` & an alt message.   @rhamilto 

Do we have a preference either way? I lean towards the `ng-if` since we are not limited to just env vars.

**Comment by spadgett** [comment]
For replication controllers we do this:

https://github.com/spadgett/origin-web-console/blob/6c0257867c68da506b49a3e42fd6476e035c2863/app/views/browse/replica-set.html#L79

![screen shot 2017-04-18 at 1 35 43 pm](https://cloud.githubusercontent.com/assets/1167259/25144488/f4241318-243b-11e7-87f1-103bd3c98e07.png)

**Comment by rhamilto** [comment]
> Do we have a preference either way? I lean towards the ng-if since we are not limited to just env vars.

Agreed.  No point in showing the KVE if there is nothing to display (i.e., read only env vars).

**Comment by benjaminapetersen** [comment]
Ok, I can find 10 instances of KVE in readonly mode, I believe each one should have a message like this, but will check them over.
