### ISSUE TITLE
Donut tooltip text sometimes blurry

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1452]
Hard to tell from the screenshot, but sometimes the donut tooltip text is blurry or alternates from sharp to blurry.

![screen shot 2017-04-17 at 11 38 33 am](https://cloud.githubusercontent.com/assets/1167259/25198604/13fb46c2-2516-11e7-91cc-67ca27868708.png)

**Comment by rhamilto** [comment]
Any tips on how to reproduce, @spadgett?

**Comment by spadgett** [comment]
I can't reliably reproduce this, but I've seen it enough times to open the issue. I think it's related to the styles here:

https://github.com/openshift/origin-web-console/pull/918/files#diff-f87f364e52cc029f896e5bb82db91cc1R289

We previously used c3 config to position the tooltip:

http://c3js.org/reference.html#tooltip-position

**Comment by spadgett** [comment]
Closing since I haven't seen this in a long time. Will reopen if I see it again, with more info if I can.
