### ISSUE TITLE
Projects page title and action button need to be updated to match landing page

### ISSUE THREAD

**Issue by beanh66** [openshift/origin-web-console#1460]
The full projects list page should match the landing page as described in the design doc below. The page title should be "My Projects" and the create button should be "+ Create Project" instead of "New Project". 
http://openshift.github.io/openshift-origin-design/web-console/2-projects-page/overview

FYI @spadgett @jwforres @serenamarie125

**Comment by spadgett** [comment]
Is the intent to update all the create buttons so they have a `+`?

![screen shot 2017-04-21 at 11 42 04 am](https://cloud.githubusercontent.com/assets/1167259/25285264/a44ef346-2687-11e7-8ee6-78224a425121.png)

![screen shot 2017-04-21 at 11 42 18 am](https://cloud.githubusercontent.com/assets/1167259/25285272/a8cb3696-2687-11e7-9d9a-0992c1f4547c.png)

**Comment by spadgett** [comment]
![screen shot 2017-04-21 at 11 45 16 am](https://cloud.githubusercontent.com/assets/1167259/25285382/06fdd084-2688-11e7-8f02-8f2da01e9a46.png)

**Comment by beanh66** [comment]
@spadgett You make a great point about consistency. Until we are ready to do something like this across the board, we should hold off. We definitely do still want to change the label to say "Create Project" though, rather than New Project. We can leave the + off for now!

**Comment by spadgett** [comment]
OK thanks! To be clear, I'm not necessarily arguing against the `+`, just for consistency.
