### ISSUE TITLE
Bind message says it successfully bound the service to itself

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1465]
![screen shot 2017-04-24 at 11 31 25 am](https://cloud.githubusercontent.com/assets/1167259/25345225/7e130674-28e2-11e7-93c4-f75904c5ce1b.png)

cc @jwforres

**Comment by jwforres** [comment]
I believe this is fixed in @jeff-phillips-18 's bind component PR that will be going into common, so assigning this to him
