### ISSUE TITLE
Test flake: Unable to create directory "/data/src/github.com/openshift/origin-web-console/.tmp"

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1468]
I've seen this a few times now. Recently in 

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_web_console/1288/console

> Warning: Unable to create directory "/data/src/github.com/openshift/origin-web-console/.tmp" (Error code: EEXIST). Use --force to continue.

**Comment by spadgett** [comment]
This looks like a race when using grunt concurrent

**Comment by jwforres** [comment]
ah well thats an easy fix then
