### ISSUE TITLE
Bind to an application option when no applications exist

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1470]
If I start the bind process in a project that has no applications, I presumably shouldn't see "Bind to an application" option with an empty dropdown since no applications exist.  Instead show a message informing the user she can bind to an application once one or more exists in the project?

![screen shot 2017-04-24 at 3 56 09 pm](https://cloud.githubusercontent.com/assets/895728/25356060/e22cddc8-2906-11e7-8be6-493f982308b2.PNG)
![screen shot 2017-04-24 at 3 56 24 pm](https://cloud.githubusercontent.com/assets/895728/25356061/e22f3fbe-2906-11e7-837f-bb6973670a7e.PNG)

**Comment by ncameronbritt** [comment]
That option should be disabled if there are no applications. Maybe the message should replace the dropdown. 

Would also make sense to default to "Create a secret in my project" in this case.

**Comment by serenamarie125** [comment]
@ncameronbritt can you look at this from a higher level perspective and provide a consistent design for both this case and https://github.com/openshift/origin-web-catalog/issues/233

**Comment by ncameronbritt** [comment]
@openshift/team-ux-review Take a look at these options and let me know what you think (and if you have other ideas I haven't considered.)

![screen shot 2017-05-24 at 2 13 50 pm](https://cloud.githubusercontent.com/assets/8974593/26418761/6eaabba8-408b-11e7-8c08-ab671992f7b9.png)

![screen shot 2017-05-24 at 2 14 03 pm](https://cloud.githubusercontent.com/assets/8974593/26418765/71344772-408b-11e7-930e-ec10990f2352.png)

![screen shot 2017-05-24 at 2 14 12 pm](https://cloud.githubusercontent.com/assets/8974593/26418779/7f14427a-408b-11e7-8f3c-696155392d35.png)

![screen shot 2017-05-24 at 2 14 21 pm](https://cloud.githubusercontent.com/assets/8974593/26418783/8207038c-408b-11e7-9f82-2a648e7156bb.png)

**Comment by ncameronbritt** [comment]
The first sentence "Bind user-provisioned-service to an existing application" doesn't make a whole lot of sense if there are no applications. Perhaps that sentence could be replaced in all cases with something like "Create binding for user-provisioned-service". 

"Create binding" is consistent with the action in the kebab menu and in the bindings section in the overview.

Thoughts? 
@spadgett @jwforres @openshift/team-ux-review

**Comment by jwforres** [comment]
personally I'm leaning to option 2 or 3 because of feature discoverability,
it lets you know its something that you *could* do if you add applications
to your project

**Comment by serenamarie125** [comment]
Thanks for doing this! @ncameronbritt I like Option2 the best

**Comment by beanh66** [comment]
@ncameronbritt +1 to Option 2. I would rather the dropdown still be present but disabled so it will be recognized next time as the same feature.

**Comment by spadgett** [comment]
@jeff-phillips-18 I think this is fixed now?

**Comment by jeff-phillips-18** [comment]
Yes, fixed by #1602
