### ISSUE TITLE
"Projects" button goes to landing page when running the catalog

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#1483]
The text "Projects" should be replaced with whatever we want to call the landing page.

![screenshot from 2017-04-27 16-34-03](https://cloud.githubusercontent.com/assets/8974593/25503303/e5d7b84a-2b67-11e7-9897-dfa9480cee83.png)

**Comment by beanh66** [comment]
@ncameronbritt Should this just be called "Home" since it includes SaaS, Catalog, and Projects Panel?

**Comment by ncameronbritt** [comment]
"Home" seems ok to me, unless we have a better name in mind. @serenamarie125 @beanh66 @cshinn
