### ISSUE TITLE
"View all projects" goes to landing page

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#1484]
When the catalog is turned on, the "View all projects" link in the project sdropdown menu goes to the landing page rather than the projects page. 

![screenshot from 2017-04-27 16-41-51](https://cloud.githubusercontent.com/assets/8974593/25503480/9b8c002e-2b68-11e7-9a3a-8469509de128.png)

This may be a separate issue, but what do you think about styling that item as a link to distinguish it from the projects? @serenamarie125 @cshinn @beanh66 @jwforres @rhamilto

**Comment by jwforres** [comment]
Note to whoever fixes this that it needs to work both when the new experience is enabled and disabled.

**Comment by beanh66** [comment]
@ncameronbritt Agreed, I think the "View All Projects" should be a blue link.

**Comment by spadgett** [comment]
@ncameronbritt @beanh66 Do you mind opening a separate issue for the link color if you think we should change it? #1518 only fixed the link target

**Comment by beanh66** [comment]
@ncameronbritt and @spadgett Will do!
