### ISSUE TITLE
Create project from projects page takes you to the old "add to project" page

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#1485]
When the catalog is turned on, creating a project from the projects list page takes the user to the old (current) add to project page. User should probably be directed back to the projects list page, or into the project with the empty state.

![screenshot from 2017-04-27 16-46-28](https://cloud.githubusercontent.com/assets/8974593/25503882/e23f1adc-2b69-11e7-8c07-5c84d998e4da.png)
![screenshot from 2017-04-27 16-47-26](https://cloud.githubusercontent.com/assets/8974593/25503886/e63265f4-2b69-11e7-997c-8f6161d62ff9.png)

**Comment by ncameronbritt** [comment]
@serenamarie125 @cshinn @beanh66 We should think about the consistency between creating a project from the landing page vs the projects page.

**Comment by beanh66** [comment]
@ncameronbritt The intention was to have that same popover show up for both cases (from the home page and from the projects page) when creating a project. That's what we have in the design docs as well. @jeff-phillips-18 is there already an issue for this one?

**Comment by spadgett** [comment]
@beanh66 No issue yet, although I think we can use this one. I assume we want the same for edit project.

Should we switch to the kebab instead of the 3 icons on this page as well?

**Comment by beanh66** [comment]
@spadgett Yes that is correct

**Comment by serenamarie125** [comment]
Agreed @spadgett kebab makes sense!  Customers I spoke with are happy that those features are available in the UI, but they aren't used that frequently, so hiding them under the kebab shouldn't be an issue from that perspective.

**Comment by ncameronbritt** [comment]
Agreed about the kebab. Another consistency issue that bothers me a little bit is that the landing page projects list and the project page don't use the same list component. The project page uses list-view-pf, so the entire row is clickable, and the landing page uses something different. 

I personally like having the row clickable, as that's consistent with other lists (e.g. overview items) in the console. 

Thoughts @serenamarie125 @beanh66 @cshinn ?

**Comment by beanh66** [comment]
@ncameronbritt In my understanding, neither is using a true list view right now, but in the initial designs the intention was for both to be PF list view. Now that we have more time for this release, I wonder if we will be able to make that change.

**Comment by spadgett** [comment]
We could just switch to using the dialogs always, even with the new experience off. I think they're better.

It would change the behavior so that we don't jump directly to add to project. When we wrote this originally, we didn't have project watch, so we had to go _somewhere_ because the list didn't update. I'm not totally convinced jumping directly to add to project is right. It's kind of annoying if it's not what you want. I'd rather just see the new project added to the list.

cc @jwforres

**Comment by spadgett** [comment]
What should the "New Project" button do in the empty state message? (#1462 renames this to "Create Project")

<img width="930" alt="screen shot 2017-05-03 at 3 52 14 pm" src="https://cloud.githubusercontent.com/assets/1167259/25678672/8cd10c78-3018-11e7-8565-972ef9ad2daa.png">

**Comment by ncameronbritt** [comment]
@spadgett When do users see that?

**Comment by spadgett** [comment]
In the current experience, when they first log in and have no projects.

In the new experience, only if someone sends them a link directly to the projects list. It's not linked from the landing page when there are no projects.

**Comment by ncameronbritt** [comment]
I thought that when I oc cluster up a project called My Project was created
by default. Is that not the case?

**Comment by spadgett** [comment]
@ncameronbritt It is, but only for user `developer` and only when using `cluster up`

**Comment by ncameronbritt** [comment]
@serenamarie125 @cshinn @beanh66 
What @spadgett is asking about here is basically the Day 1 experience if a user has bypassed the landing page.

**Comment by beanh66** [comment]
@ncameronbritt I think this create project button would act the same as it does on the home page, where the overlay panel opens. And there should already be a message that displays when users don't have access to create projects, right @spadgett? The "contact your administrator..." message.

**Comment by spadgett** [comment]
Yes, there can be a custom message in which case there is no button.

**Comment by rhamilto** [comment]
> I personally like having the row clickable, as that's consistent with other lists (e.g. overview items) in the console.

@spadgett and I agree.  I've opened a [separate issue](https://github.com/openshift/origin-web-catalog/issues/239) to address.

**Comment by spadgett** [comment]
> I personally like having the row clickable, as that's consistent with other lists (e.g. overview items) in the console.

It's also consistent with the full project list (since we're working on consistency for these two experiences).

**Comment by spadgett** [comment]
I have a PR that fixes the immediate problem in 3.6 where we redirect to the old catalog. I think we should open a follow on for 3.7 to use the create and edit dialog.
