### ISSUE TITLE
[WIP] Catalog scrollbar variations

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1488]
@serenamarie125 [asked for the inner scrollbar within the catalog landing page to be tweaked](https://github.com/openshift/origin-web-catalog/issues/182#issuecomment-297999532).  Below is the existing as well as an inverse option in addition to a blue option.  Thoughts?

Note:  I tried a middle gray color, but it looked like it belonged to the sidebar rather than the main content area.

Default (as it exists today):

![screen shot 2017-04-28 at 1 44 01 pm](https://cloud.githubusercontent.com/assets/895728/25540414/e63e5698-2c18-11e7-884a-f369ed1b9883.PNG)

Inverse:

![screen shot 2017-04-28 at 1 37 36 pm](https://cloud.githubusercontent.com/assets/895728/25540427/f18eec60-2c18-11e7-944b-0cb7be2eae25.PNG)

Blue:

![screen shot 2017-04-28 at 1 43 36 pm](https://cloud.githubusercontent.com/assets/895728/25540439/06698ba4-2c19-11e7-91c2-8d81391068fd.PNG)

@spadgett, @jwforres, @sg00dwin, @beanh66, @ncameronbritt

**Comment by beanh66** [comment]
@rhamilto I like blue!

**Comment by serenamarie125** [comment]
+1 to the blue.  Looks so much nicer @rhamilto!
