### ISSUE TITLE
Move drag handles away from delete icon?

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#150]
@liggitt suggested moving the drag handles to the left of the field since they're right beside a destructive button.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/16745738/32decb82-4785-11e6-8d6a-5b304bd98435.png)

/cc @jwforres @ajacobs21e @rhamilto @benjaminapetersen

**Comment by liggitt** [comment]
also because I would instinctively look for a drag handle on the left... dragging a row via an icon in the middle of the row feels weird to me. I would expect the drag handle to be either on the far left or the far right, and delete on the far right seems most natural

**Comment by ajacobs21e** [comment]
+1

On Mon, Jul 11, 2016 at 4:37 PM, Jordan Liggitt <notifications@github.com>
wrote:

> also because I would instinctively look for a drag handle on the left...
> dragging a row via an icon in the middle of the row feels weird to me. I
> would expect the drag handle to be either on the far left or the far right,
> and delete on the far right seems most natural
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/origin-web-console/issues/150#issuecomment-231857065>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGHlfv0Fdg3J9v3NMz2ck-K0N1JiAlLXks5qUqmegaJpZM4JJwVF>
> .
>



-- 

Allie Jacobs
UXD

calendar
<https://www.google.com/calendar/b/1/embed?src=ajacobs@redhat.com&ctz=America/New_York>

**Comment by rhamilto** [comment]
A couple of things to consider:

Sort and delete are independently optional functions within the editor.  In keeping both buttons on the right, we have a dedicated space where either button appears, and the appearance of the buttons has no impact on this space.  In doing so, all instances of the editor retain the same "form" regardless of whether or not one or more of the buttons are present.  If we move the sort button to the left, either need to have dedicated space on both the left and the right for buttons regardless of whether or not they appear *or* editor instances that could have different "forms".

Current implementation:

![current-akve](https://cloud.githubusercontent.com/assets/895728/16768235/86c37de2-4811-11e6-84f6-8f6c458c7695.png)

Either side:

![either-akve](https://cloud.githubusercontent.com/assets/895728/16768245/9076c574-4811-11e6-9a2b-afabea0d6861.png)

Either side without dedicated space on the left:

![either-no-reserve-left-akve](https://cloud.githubusercontent.com/assets/895728/16768377/2365722c-4812-11e6-800b-7b54e354ca42.png)

For reference, the design was inspired by Postman, which has the sort and delete buttons both on the right.

![screen shot 2016-07-12 at 8 52 32 am](https://cloud.githubusercontent.com/assets/895728/16768415/510992ee-4812-11e6-9e91-38d09534f9ca.PNG)

**Comment by liggitt** [comment]
my 2¢ is that on the left with dedicated space looks best. I do think the current drag icon is too chunky... a real vertical grip icon (c.f. https://github.com/FortAwesome/Font-Awesome/issues/816) would make that space on the left less conspicuous

**Comment by benjaminapetersen** [comment]
I hear the concern about a destructive & non-destructive icon side by side.  It makes sense to help the user avoid an 'oops'.  Moving the icon all the way to the right though is a lot of real estate to cover to get from one action to the other.  Just throwing that out there.  

To avoid a "wobbly" feeling, if we move the icon right we probably need to have an invisible placeholder for when `sort=false` so the inputs naturally stay in a column.

I'm good with wherever the general consensus lands.

**Comment by jwforres** [comment]
bumping the discussion on this issue, did everyone agree with drag handle on the left with dedicated space?

**Comment by benjaminapetersen** [comment]
@jwforres given what we are researching now, do we want to keep this open, or close it & revisit when we have to port this directive?

**Comment by jwforres** [comment]
the problem still exists.  if we fix it as part of porting the directive great, but we should till be tracking it

**Comment by benjaminapetersen** [comment]
sounds good.

**Comment by spadgett** [comment]
4.x moves the icon to the left.

/remove-lifecycle stale
/close
