### ISSUE TITLE
Move shared items into origin-web-common

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#1500]
Need to move items shared with origin-web-catalog into https://github.com/openshift/origin-web-common

Known items
.word-break & .word-break-all mixins
@screen-lg-max, @screen-xl-min
@screen-xs, @screen-xs-min, @screen-xxs-max
@panel-shaded 
others?

**Comment by jeff-phillips-18** [comment]
What about all the:
pad-left-xl
mar-bottom-md
mar-top-sm
etc....

Should these be added to common?

**Comment by rhamilto** [comment]
> Should these be added to common?

My vote is no.  I'd really like to see us get away from these kind of helper classes in the markup.
