### ISSUE TITLE
Docker container labels

### ISSUE THREAD

**Issue by tpolekhin** [openshift/origin-web-console#1523]
Hello!
I've tried to use container labels to add additional visibility to UI:
```
io.openshift.build.commit.author
io.openshift.build.commit.date
io.openshift.build.commit.id
io.openshift.build.commit.message
io.openshift.build.commit.ref
io.openshift.build.source-location
```
but it seems like this labels only work when build is done via OpenShift internal tools, and buildConfig or Build objects are available in API. Is this true?

Can i somehow add this visibility without using OpenShift build procedure?

Thanks!

**Comment by jwforres** [comment]
Not possible currently.

Assume you mean image labels? Are you using image streams or directly referencing a pull spec in your pod template? If you are using an image stream then it is more likely we would be able to enhance the pod template visualization to show the build details.  If you are directly referencing an image pull spec then we don't have the detailed information about the image loaded currently and requesting that information may have performance concerns.

**Comment by tpolekhin** [comment]
@jwforres thanks for your answer

I used local docker to build image with labels mentioned above.
I pushed that image to docker.io repository and created ImageStream for this image.
I used `oc tag` to import `:latest` tag from docker.io repo to my ImageStream.
In the OpenShift console i can see these labels in `ImageStreams >> image >> :latest`
When i deployed that image from IS using `Add to Project >> Deploy Image` i can see only
Image and Ports under Template section.

As i understood by looking at the source for `_pod_template` labels like Source, Commit, Author etc. are fetched from `build.spec`, if this image was built by OpenShift `buildConfig`

Am i getting this right?
Is there a way to add those labels from ImageStream?

Thanks!

**Comment by jwforres** [comment]
It is possible since you are using an imagestream, it would definitely by an RFE though

**Comment by tpolekhin** [comment]
@jwforres just to make it clear - it should already work? Or it can be done in future releases?
Because right now, with OpenShift 1.4.1 it does not work for me, or maybe I'm just doing it wrong

Thanks!

**Comment by jwforres** [comment]
No it will not work today.  It is an enhancement request.  By saying "it
possible" I meant we have the data readily available already without making
additional requests.  If you had not been using image streams then that
would not have been the case and I probably wouldn't have suggested even
making it an enhancement request because of performance concerns.

**Comment by tpolekhin** [comment]
@jwforres thank you! Would appreciate this feature!
