### ISSUE TITLE
Delete warning wraps to second line on projects list

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1529]
The project usually disappears quickly, but otherwise the warning icon wraps to the next line when visible. We should fix the wrapping, or possibly remove the icon since we update the page so quickly.

![screen shot 2017-05-09 at 1 43 55 pm](https://cloud.githubusercontent.com/assets/1167259/25867866/f6f700d0-34c8-11e7-9131-afd766bb8ddd.png)

@jwforres FYI

**Comment by jwforres** [comment]
don't remove the icon, depending on what is in the project it may take some time to be deleted.
