### ISSUE TITLE
Destination CA cert should not be required

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#1542]
Once https://github.com/openshift/origin/pull/13752 merges the destination CA cert should not be required.  We need to update our client side validation.

**Comment by jwforres** [comment]
cc @spadgett

**Comment by spadgett** [comment]
@jwforres Looks like we had a gap in our validation and didn't require the destination CA cert (although you got a validation error from the server on save).

**Comment by jwforres** [comment]
then nothing to see here :)
