### ISSUE TITLE
Mini log viewer clips text with no eliding or ability to scroll

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#1559]
When a log line is too long for the mini log viewer on the overview it truncates the text, but there is no ellipsis which makes it look like you should be able to copy/scroll to get the full content.  However its really just truncated with no way to view the rest of the line.
![clipped-log-viewer](https://cloud.githubusercontent.com/assets/1467629/26254867/f4b1ba26-3c85-11e7-8dd4-15826717acf2.png)

**Comment by jwforres** [comment]
debatable what the right behavior is, if you allow horizontal scrolling, then as the long lines disappear out the top the window may jump back to the left

**Comment by spadgett** [comment]
I think the best fix is to add an ellipsis. With the current implementation, a horizontal scrollbar can cause the content to jump when the long lines scrolls off, and wrapping lines will cause the mini log viewer to change height.
