### ISSUE TITLE
Log ellipsis is getting clipped on the bottom when a dot is in the larger state

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#156]
![clipped_ellipses](https://cloud.githubusercontent.com/assets/1467629/16775858/b337e510-4830-11e6-90c9-f781e965f93c.png)

**Comment by benjaminapetersen** [comment]
Saw this as well, think it is also slightly clipped on the right side.

**Comment by spadgett** [comment]
@jwforres kicking this out of 1.3.0 at this point

**Comment by sg00dwin** [comment]
Alternate version that doesn't have clipping issue. 

- 3 sizes
- dark and light versions
- with or without text

http://codepen.io/sg00dwin/pen/WxXYEN

**Comment by benjaminapetersen** [comment]
Nice, I like it. would be easy to swap into a directive & handle the sizes with an attribute.

**Comment by jwforres** [comment]
agreed, i like it.  we can swap it out in 1.4
