### ISSUE TITLE
Compression and minifying JS

### ISSUE THREAD

**Issue by alikhajeh1** [openshift/origin-web-console#1562]
https://developers.google.com/speed/pagespeed/insights shows `Minify JavaScript` and `Enable compression` as helping with the performance of the UI - thoughts?

**Comment by spadgett** [comment]
@alikhajeh1 We do both.

Minification:

https://github.com/openshift/origin-web-console/blob/master/Gruntfile.js#L319-L331

HTTP compression:

https://github.com/openshift/origin/blob/3659383d50503e330aee3b42604c85b8fd019ea9/pkg/assets/handlers.go#L39
