### ISSUE TITLE
Persistent error/warning toast notifications should auto dismiss upon a successful resubmission. 

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#1570]
Currently it must be manually dismissed. 

example
<img width="662" alt="screen shot 2017-05-22 at 4 16 29 pm" src="https://cloud.githubusercontent.com/assets/1874151/26326850/1467e3b8-3f0b-11e7-899d-af2529af9fc4.png">

related pr https://github.com/openshift/origin-web-console/pull/1567

**Comment by jwforres** [comment]
this was only an issue in @sg00dwin 's PR where he is switching to toasts and we've resolved the issue in that PR already so I'm closing this
