### ISSUE TITLE
No link back to landing page in our mobile nav

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1579]
Since we hide the home button at mobile, I couldn't find a link back to the landing page anywhere in our current mobile nav. I realize mobile nav changing are coming, but do we need something in the meantime for tech preview?

@serenamarie125 @ncameronbritt @beanh66 @jwforres

**Comment by beanh66** [comment]
@spadgett Do you have a screenshot of the current look? Wondering if the branding is currently shown on mobile.

**Comment by spadgett** [comment]
No branding when inside a project currently.

![openshift web console 2017-05-24 09-04-45](https://cloud.githubusercontent.com/assets/1167259/26404480/287d911c-4060-11e7-945b-6117b8d7eb01.png)

But there is branding here:

![openshift web console 2017-05-24 09-06-02](https://cloud.githubusercontent.com/assets/1167259/26404497/3f203848-4060-11e7-8077-97fbd1debeea.png)

**Comment by serenamarie125** [comment]
good catch @spadgett, we are looking into it

**Comment by serenamarie125** [comment]
@spadgett we would suggest having pficon-home with the Home label as the first item in both of these situations @openshift/team-ux-review please chime in :)

**Comment by cshinn** [comment]
I agree that adding the home link is the way to go. I assume that clicking on the "OpenShift Origin" header would also go there?

**Comment by spadgett** [comment]
> I assume that clicking on the "OpenShift Origin" header would also go there?

+1 This is how it's working for now on pages that have the header, but not all pages do.
