### ISSUE TITLE
Accessibility: Tab order incorrect on projects list page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1580]
The actions kebab is tabbed to before the project link when navigating the project list by keyboard.

![project-tab-order](https://cloud.githubusercontent.com/assets/1167259/26402671/3b1ac1e8-4059-11e7-91fe-350c4610bd24.gif)

**Comment by spadgett** [comment]
@rhamilto fyi

**Comment by jwforres** [comment]
@spadgett fyi i just added an area/accessibility label so it'll be easier to track these
