### ISSUE TITLE
Check project creation flow when a project template is used and modifies project name

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#1588]
We need to make sure when creating a new project on a system that modifies the project name at creation time, that we correctly navigate to the created project's Add to Project page.

For the new experience we should validate the name that appears in the toast is actually the one that was created.

See https://github.com/openshift/origin/pull/14344#issuecomment-303996347

**Comment by jwforres** [comment]
Suspect there are bugs here, but not yet confirmed.

**Comment by mfojtik** [comment]
@jwforres we eventually return the correct project name but I'm not sure how you retrieving the project name (if you just pass it from the user input or readin what the API sent you back).

**Comment by spadgett** [comment]
@mfojtik In most places, we read the project name from the response body of the POST to `projectrequests`. There is one place where we assume it's the same name we sent.

**Comment by jwforres** [comment]
This is just waiting on the next bump of catalog into console.

**Comment by jwforres** [comment]
catalog fix should be in console now
