### ISSUE TITLE
Follow logs not working for me at mobile

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1596]
I believe the log viewer is trying to use the wrong scrollable div.

**Comment by rhamilto** [comment]
The culprit: https://github.com/openshift/origin-web-console/pull/1416/files  Revert this fix and deal with the Safari bug?

**Comment by rhamilto** [comment]
@sg00dwin, what do you think?

**Comment by sg00dwin** [comment]
Well, since the top nav bar is going to be replaced, I'd say revert that change.
