### ISSUE TITLE
Customise authorisation page

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin-web-console#1597]
For oauth requests like in the Jenkins plugin, is there a way to customise the oauth authorisation request page? Ideally if were just wrapped in the same console styling could at least help users understand where the page is coming from.

**Comment by openshift-docker** [comment]
See master_node_configuration.html
<https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-config-oath-authentication-config>
in
the oauth section there is "templates" - the doc in the types.go file
should cover most of it
https://github.com/openshift/origin/blob/master/pkg/cmd/server/api/v1/types.go#L722

**Comment by andrewklau** [comment]
Those are the templates here https://docs.openshift.org/latest/install_config/web_console_customization.html#customizing-the-login-page ?

**Comment by jwforres** [comment]
The oauth authorization request page is actually not owned by the mgmt console, its owned by the oauth server.

I believe today we do not let you customize that particular page.  @liggitt can confirm

**Comment by liggitt** [comment]
correct, it is not customizable today

**Comment by jwforres** [comment]
An enhancement request for that would need to be opened against the origin repo
