### ISSUE TITLE
Process template dialog no longer waits for checks before going to next steps panel

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1603]
We have a number of checks we perform before advancing to next steps processing a template. The wizard no longer waits for the checks. It advances to the next wizard step right away before the checks are complete.

![openshift web console 2017-05-26 16-28-28](https://cloud.githubusercontent.com/assets/1167259/26511511/68ed0620-4230-11e7-899c-b3a62b1ed60f.png)

cc @jeff-phillips-18 @jwforres

**Comment by jwforres** [comment]
can fixed by a combination of the nextCallback returning false and then the listener for successful template process has to set current-step for the wizard.  Fixed this for deploy image already so we can fix this the same way on template process.
