### ISSUE TITLE
Template messages showing up for previous template

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1630]
New experience / template dialog only. The template message and processed parameters are also broken. No message shows up for the first template, and the second template shows the message from the first.

Notice I'm seeing the message from the Cake PHP template when I instantiated the MongoDB template.

![screen shot 2017-06-01 at 11 40 33 am](https://cloud.githubusercontent.com/assets/1167259/26688124/cd0616e0-46bf-11e7-992a-af29a66eb91a.png)

cc @jwforres

**Comment by jwforres** [comment]
I suspect this is a result of it going to the next step before the template has finished processing, so I think fixing the other issue will fix this one.  The directive for next steps is pulling the current data from the processed template cache when it initializes.

**Comment by spadgett** [comment]
@jwforres I tested with my changes in #1621, and it appears to still be a problem. Still investigating.

**Comment by spadgett** [comment]
@jwforres Next steps directive is initialized when the dialog is displayed before the template is processed.

**Comment by jwforres** [comment]
@spadgett i thought template process dialog didn't include the views until the step became the current step

**Comment by spadgett** [comment]
@jwforres It's there:

![openshift web console 2017-06-01 12-03-11](https://cloud.githubusercontent.com/assets/1167259/26689028/54b82306-46c2-11e7-87b9-54cb9035b189.png)

**Comment by jwforres** [comment]
ah right, yeah so i fixed this in import yaml by using an ng-if so that next-steps didnt exist until the template had been procssed

**Comment by spadgett** [comment]
Yeah I had just made the same fix
