### ISSUE TITLE
z-index of toast notifications is not high enough to overlap the overlay component

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#1632]
Toast notifications and the overlay component have the same z-index of 1050, we want toasts to pop up over top of the overlay.

![z-index](https://cloud.githubusercontent.com/assets/1467629/26698403/d4dc34c0-46e3-11e7-9158-94bd9b831f4b.png)

**Comment by jeff-phillips-18** [comment]
Filed Patternfly issue https://github.com/patternfly/patternfly/issues/658
Will work on a workaround until that can be addressed and incorporated
