### ISSUE TITLE
`grunt build` generates incorrect output for Node version >4

### ISSUE THREAD

**Issue by wgordon17** [openshift/origin-web-console#1667]
Specific example being from `dist/scripts/vendor.js`
   
    -}, sf = b("$location"), tf = /^\s*[\\/]{2,}/, uf = {
    +}, sf = b("$location"), tf = /^\s*[\\\/]{2,}/, uf = {

It would be beneficial to at least provide a heads up in the README file or, if possible, determine the root cause for why newer versions generate incorrect output.

**Comment by spadgett** [comment]
We're on a very old version of `grunt-contrib-uglify`, 1.0.1 whereas latest is 3.0.23. It looks like UglifyJS has had a rewrite as well, and the old version is not receiving fixes. I suggest we try with the latest `grunt-contrib-uglify`.

**Comment by jwforres** [comment]
Seems like a good update once we re-open for 3.7

**Comment by spadgett** [comment]
From my testing, this isn't a problem with the latest grunt-contrib-uglify
