### ISSUE TITLE
Show empty state instead of hiding terminal tab

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#167]
Currently we are hiding the terminal tab rather than showing the empty state message (as we do with logs) when unavailable. 

@MarkDeMaria created the issue :)

**Comment by spadgett** [comment]
> Currently we are hiding the terminal tab rather than showing the empty state message

Which is confusing if you were on the tab when the container stops because it disappears while open.

**Comment by MarkDeMaria** [comment]
More specifically: When all containers are terminated, regardless of whether they have been accessed/used via terminal, the terminal tab disappears, causing the terminal and all associated use history to disappear. 

Behavior should be:
-If all containers are terminated and any have been accessed/used via terminal, the tab should remain such that we do not lose terminal use history
-If no containers are available at page load (Meaning no containers have been accessed/used via terminal, the page should show a 'No Containers Running' message until at least one container becomes available.

**Comment by benjaminapetersen** [comment]
Yeah, though not just on load, keep the `watch` in mind.  It could change while the page is loaded.
