### ISSUE TITLE
Inconsistent default icon for templates between old and new experience

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#1673]
In the old experience we used fa-clone, in the new experience its using fa-cubes which we usually used for images not templates.  See https://github.com/openshift/origin-web-console/pull/1382/files#r120115098

**Comment by jwforres** [comment]
@spadgett

**Comment by rhamilto** [comment]
Assuming @spadgett hasn't already done this, I will pick up this bug.  Which icon do we want?  I prefer to still with fa-clone for templates...

**Comment by rhamilto** [comment]
> I prefer fa-clone. Should we use the same default for both templates and service classes?

This is weird because it's weird?  Or because it's different from what I'm used to seeing?

![screen shot 2017-06-23 at 3 06 42 pm](https://user-images.githubusercontent.com/895728/27496828-a7b764e4-5825-11e7-94d8-95c002bbd507.PNG)

**Comment by rhamilto** [comment]
It seems that if we don't change both, you can end up in a situation where you click cubes and see clone in the overlay.
![screen shot 2017-06-23 at 3 09 30 pm](https://user-images.githubusercontent.com/895728/27496919-fccb701a-5825-11e7-9e7d-cb6ce73e8504.PNG)

**Comment by spadgett** [comment]
> This is weird because it's weird? Or because it's different from what I'm used to seeing?

Not great, but not terrible? Hopefully there are few items in the catalog that don't have an icon.
