### ISSUE TITLE
Image secrets table has no empty message

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1686]
<img width="698" alt="screen shot 2017-06-12 at 6 18 37 pm" src="https://user-images.githubusercontent.com/1167259/27057778-9e3f9504-4f9b-11e7-98aa-3d081aa3c4ef.png">

**Comment by sg00dwin** [comment]
@rhamilto we were unassigning each other at the same time!

**Comment by rhamilto** [comment]
@sg00dwin go fer it!  it's yours.  i'm headed to yoga.
