### ISSUE TITLE
Add to project button white for viewer at some resolutions

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#170]
When I don't have create / update authority for a project, the add to project button can show up as white (only at some screen widths).

![openshift_web_console_and_issues_ _openshift_origin-web-console](https://cloud.githubusercontent.com/assets/1167259/16849316/e365cb7e-49c7-11e6-869e-a58b1f82e636.png)

/cc @jhadvig @jwforres

**Comment by spadgett** [comment]
@sg00dwin you can add a read-only user to your project with the command

```
oc policy add-role-to-user view test -n myproject
```

Then log in as user test to see.

**Comment by jhadvig** [comment]
@spadgett so one solution would to put the `ng-if` condition from the div on the nested anchor tag. Then we wont hit the issue.
On the other hand there will be visible `<div>` space in case of small screens:
![screenshot-28](https://cloud.githubusercontent.com/assets/1668218/16910607/deedc12c-4cd9-11e6-9b64-57f12c1e68d2.png)

**Comment by spadgett** [comment]
I think we can fix it in CSS to avoid the problem in the screenshot.
