### ISSUE TITLE
Enter key no longer submits image search in deploy-image component

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1703]
Enter used to trigger a search. Now you need to click the magnifying glass.

**Comment by jwforres** [comment]
looks like form and ng-form behave differently when it comes to enter key submission :-\

I know there was a reason we switched it to ng-form in my PR but I can't remember why now

**Comment by jwforres** [comment]
It's not very clean but I can work around it by adding a `ng-keyup="$event.keyCode === 13 && findImage()` on the text input

**Comment by jwforres** [comment]
apparently ng-form is not supposed to be used in place of form but nested underneath form, see https://github.com/angular/angular.js/issues/2513#issuecomment-39399816

**Comment by spadgett** [comment]
We were using it because there is an outer form in the dialog and you can't nest form elements. Enter seems to work OK in the dialog. Maybe we need an outer form for the non-dialog page.

I believe we have the same problem with `process-template` as well.
