### ISSUE TITLE
Validation for pf-wizard is a bit kludgy

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1707]
Most angular validation can be done fairly cleanly in markup.  This feels a bit hacky to me:

```javascript 
var validityWatcher;
// ...
// in a setup fn:
validityWatcher = $scope.$watch("ctrl.selectionForm.$valid", function(isValid) {
     ctrl.steps[0].valid = isValid;
});
// ... 
// in another fn:
      if (validityWatcher) {
        validityWatcher();
        validityWatcher = undefined;
      }
// 
// in a cleanup fn:
    ctrl.$onDestroy = function() {
      if (validityWatcher) {
        validityWatcher();
        validityWatcher = undefined;
      }
// ...

```

We have more than one form following this pattern now, ideally we can figure out a way to push it back up into markup.  

@jeff-phillips-18 shall I open a patternfly issue as well to track?

**Comment by benjaminapetersen** [comment]
Re PR #1705, comments [here](https://github.com/openshift/origin-web-console/pull/1705#issuecomment-308520894) and a few preceding.

**Comment by benjaminapetersen** [comment]
Another item I'd like to address is:

```javascript
step. nextTitle = 'Foo';
```
Could we rename it to:

```javascript 
ctrl.nextButtonText = 'Foo';
```
or something less verbose but a bit more clear.  "Next Title" seems to imply it will be the title for the next panel, when in fact, it is the text on the button in this panel, but clicking it will progress the user through the steps of the wizard.  

Open for discussion.

**Comment by spadgett** [comment]
Closing this issue since we've opened issues upstream in angular-patternfly.
