### ISSUE TITLE
Auto select a single binding in the delete binding flow

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1709]
Per [this comment](https://github.com/openshift/origin-web-console/pull/1705#issuecomment-308516632) from @ncameronbritt, if there is a single binding, it should be automatically selected & the "delete" button should be enabled.

@spadgett fyi, will fast follow this as a bug.

**Comment by ncameronbritt** [comment]
Tagging @openshift/team-ux-review to get their read on this.
