### ISSUE TITLE
Unable to scale up a Deployment with zero replicas

### ISSUE THREAD

**Issue by kargakis** [openshift/origin-web-console#1714]
Unless I actually edit its YAML.

Running on openshift v3.6.0-alpha.0+8125090-206

Easily reproducible by scaling a Deployment down to zero and wait until the widget that shows the # of pods and lets you scale up/down disappears and instead get back a "No deployments for deployment origin-submit-queue. ".

Also we probably want to change that message as it's wrong+confusing. Wrong because I actually have ReplicaSets for the Deployment around. I guess if the missing widget shows up, the message is going away? Confusing for obvious wording reasons. I would go with "No rollouts for deployment ..." or "No replica sets for deployment ..." in case there is no ReplicaSet for the Deployment.

**Comment by spadgett** [comment]
@kargakis I believe this has since been fixed. Can you check latest master?

![openshift web console 2017-06-15 08-25-51](https://user-images.githubusercontent.com/1167259/27181149-4dbb852e-51a4-11e7-8087-73e1319523fa.png)

**Comment by jwforres** [comment]
@kargakis if you are able to recreate this on master feel free to re-open, but we definitely fixed issues in this area since the version you are on
