### ISSUE TITLE
Add to project dropdown feels misaligned at mobile

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1715]
![screen shot 2017-06-15 at 8 54 51 am](https://user-images.githubusercontent.com/895728/27182210-6f701226-51a8-11e7-8ee2-6902c5645d2c.PNG)

**Comment by benjaminapetersen** [comment]
Is it worth asking, are we sure we want the caret? Our project picker does not use a carat, not sure if there is a consistency issue there (guessing its a bigger patternfly related question though).

**Comment by spadgett** [comment]
Fixed by #1718
