### ISSUE TITLE
Multiple alerts appear if pods are not available

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1716]
![screen shot 2017-06-15 at 10 00 08 am](https://user-images.githubusercontent.com/895728/27184896-90d37a1c-51b1-11e7-9d44-1f000ae586a8.PNG)

![screen shot 2017-06-15 at 10 03 58 am](https://user-images.githubusercontent.com/895728/27185030-02133e2e-51b2-11e7-8577-0dd0018b0a70.PNG)

**Comment by spadgett** [comment]
This doesn't appear to be a new problem, but the location of the toast over the in-page alert makes it worse.
