### ISSUE TITLE
allow filtering of `deploy` pods, visualise them differently & maybe sort them?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin-web-console#1725]
I find it confusing looking at the pods list when there's lots of stuff running with DCs. When I'm wondering if apps are running properly I normally would like to hide deploy pods as they are not apps really but implementation details of how DCs work and end up being confusing noise.

I wonder if we can render/sort them differently; or have a way to easily filter them out?

Sorting pods in name order might be less confusing too? Then related stuff will appear together (pods for the same RC/DC and the deploy pod)

**Comment by jstrachan** [comment]
sorting by name or status could be handy. e.g. sorting by status would let you see all the starting/failed pods together; often the stuff thats ready are not that interesting; its the stuff thats starting/failing thats what you most care about.

**Comment by jwforres** [comment]
There is a similar card that was tracking this for jenkins slave pods https://trello.com/c/vADgewtg and it had a note about handling other infrastructure pods as well. I'm going to update the card to clearly cover all infra pods and track this request there.

Sorting of our tables is a general enhancement we want to make that hasn't been prioritized yet https://trello.com/c/f6tBGkpM
