### ISSUE TITLE
Template configuration is weird if only advanced options are available

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1731]
I landed on this window and immediately felt like things are wrong:

![screen shot 2017-06-16 at 3 37 24 pm](https://user-images.githubusercontent.com/280512/27242147-c91956dc-52a9-11e7-9226-08e8d98f009d.png)

Seems strange to have all this white space & provide only a link. Thoughts?
@jwforres @spadgett

**Comment by spadgett** [comment]
@jwforres I'm starting to think we should show all parameters.

* When using the template broker, all parameters are displayed anyway.
* No way to enter parameters and use create project at the same time.
* Most out of the box templates don't have required parameters anyway, so often the dialog is empty like above.
