### ISSUE TITLE
Warn the user before repeatedly binding to the same service

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1750]
Its possible to achieve this:
![screen shot 2017-06-20 at 3 59 30 pm](https://user-images.githubusercontent.com/280512/27353317-91d932f2-55d1-11e7-851b-734550219758.png)

by binding to the same service multiple times.  The listed bindings do not show enough unique information to make it easy to delete a particular binding (if it matters).

@spadgett @jwforres

**Comment by jwforres** [comment]
@ncameronbritt I'm not sure what the best answer is here, as we have discussed there may be reasons for binding to the same application more than once, particularly when there are bind params.  We've talked about at least warning you when you go to do the binding action if you are duplicating a binding.  But that doesn't help once the binding is created with distinguishing between the two bindings.

**Comment by ncameronbritt** [comment]
@jwforres I see the problem. I think it does make sense to warn users that they are duplicating a binding. Would seeing the name of the secret that's been created help? Another thought is that including a timestamp of when the bind was created, users may be able to make a distinction that way.

Binding notwithstanding, how do users distinguish between secrets today? The names can be pretty ugly, right?

**Comment by jwforres** [comment]
Yeah the timestamp of the binding would help some.  It would definitely help with the, whoops I clicked the wrong thing and now I have two bindings to the same thing and want to delete the one I just created (at least if we have the timestamp in the delete binding dialog as well).

All of our system generated secrets have generally ugly names.  Users can create their own secrets (unrelated to creating bindings) and those would have more reasonable names but are still under the no spaces, no capital letters, etc rules.

**Comment by ncameronbritt** [comment]
I could imagine that indicating who initiated the binding could help too.
"Created 09:20 UTC by jwforres"

**Comment by ncameronbritt** [comment]
Meant to have a date in there too...
"Created 10:04 UTC 30 June 2017 by ncameronbritt"

**Comment by jwforres** [comment]
Yeah I wish... we pretty much never know who created / updated something. It isn't tracked in the api objects.  (projects are the one exception, where we sometimes know the project "owner")

**Comment by jwforres** [comment]
Also as a general rule we don't show things in UTC format, we show it in the person's timezone wherever we show the exact date / time.  But in most places we show relative time like '5 seconds ago' and the exact timestamp is available on hover.

**Comment by ncameronbritt** [comment]
Gotcha. That's easier to parse.

Is there anything else that we could show that might be helpful here?

**Comment by jwforres** [comment]
i think most of the time the only reason to add multiple bindings to the same app would be if you did it with different binding params, otherwise I don't see much point.  If we let you click to reveal the binding parameters when they exist then you'll be able to distinguish between the two.

Otherwise I think the timestamp is sufficient to deal with the "whoops" cases.

There may be some more advanced options later like 

1. letting the user decide how they want to inject the secret info into their app - as environment variables automatically, as environment variables where they map the keys themselves, as files mounted as volumes, etc
2. if they choose the env vars automatically option they will be allowed to choose an env var prefix that will be added in front of every key
3. we *could* let them request a particular secret name instead of having it be auto-generated

I'm not sure any of these are particularly useful to show in this context though.

**Comment by ncameronbritt** [comment]
Here's what I propose based on what we can do now:

- Adding inline warnings when your try to create a binding between services/applications for which there already is a binding. 
![bind warning 1](https://user-images.githubusercontent.com/8974593/27737177-2fb886b2-5d75-11e7-83c2-43b17c4d7c2a.png)
![bind warning 2](https://user-images.githubusercontent.com/8974593/27737178-2fbb68be-5d75-11e7-9bbf-4df7510ba580.png)

- Including a timestamps on the bindings sections for both applications and services.
![application bindings listing](https://user-images.githubusercontent.com/8974593/27737202-4a425364-5d75-11e7-9936-42f9fbf46414.png)
![service binding listing](https://user-images.githubusercontent.com/8974593/27737203-4a445ede-5d75-11e7-93ba-03aa8452fcfa.png)

- Including timestamps on the remove binding dialog to make it easier to know which to remove if you have multiples. 
![new mockup 5](https://user-images.githubusercontent.com/8974593/27737213-50eccc80-5d75-11e7-8878-8c6a3f369f33.png)
![remove binding](https://user-images.githubusercontent.com/8974593/27737212-50ea7fc0-5d75-11e7-8e21-0253504195f7.png)

FYI @openshift/team-ux-review

**Comment by ncameronbritt** [comment]
Note that I put the timestamp where the "DeploymentConfig" and "Secret" labels were in the delete bindings dialogs. Not sure how much value those labels added in that context.

Likewise, I'm not sure how helpful the "Deployment Config" label is in the Application Bindings section for provisioned services. If we indeed want to add timestamps, it's possible we could tighten that section up by removing those labels.

**Comment by spadgett** [comment]
Should we think about blocking users form binding the same instance twice if there are no binding params?

**Comment by ncameronbritt** [comment]
That's not a bad idea. Unless @jwforres can think of a reason why someone would want to do that even without params. ;-)

**Comment by ncameronbritt** [comment]
@spadgett Some of this (showing the timestamps for the bindings) has been addressed by the work Jeff and David have done for bindings. Not sure if that's made it to the Delete Binding wizard though.
