### ISSUE TITLE
Process template in overlay with no params has unnecessary separator

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#1753]
![template-no-params](https://user-images.githubusercontent.com/1467629/27389531-a5395728-566c-11e7-94d0-a8c7fd28ce29.png)

**Comment by jwforres** [comment]
I think this was less of an issue in the full page because the name / description content was at the top instead of to the left

**Comment by rhamilto** [comment]
I've been wracking my brain to figure out a minimalistic way to fix this without significantly altering the templates.  How about simply turning off the top border and top margin for the Labels section?  Maybe that's what you were thinking and I was overthinking it, @jwforres?

Resolves bug:
<img width="1070" alt="screen shot 2017-06-27 at 2 12 36 pm" src="https://user-images.githubusercontent.com/895728/27603080-fde95186-5b42-11e7-9096-177b05d30a31.PNG">

But still looks nice when params are present:
<img width="1070" alt="screen shot 2017-06-27 at 2 12 45 pm" src="https://user-images.githubusercontent.com/895728/27603115-198c28aa-5b43-11e7-92e2-9d98d088a487.PNG">
<img width="1070" alt="screen shot 2017-06-27 at 2 12 55 pm" src="https://user-images.githubusercontent.com/895728/27603114-198bf006-5b43-11e7-9b29-cce9f43050c8.PNG">

**Comment by jwforres** [comment]
I'm fine with that as the solution, especially since it looks like you made that specific to when its in the modal
