### ISSUE TITLE
"View all results" option for search in the catalog does not show consistently

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#1758]
The "View all results" option disappears if there are <5 results.
Now you see it:
![screen shot 2017-06-22 at 2 31 08 pm](https://user-images.githubusercontent.com/8974593/27449778-81af64b4-5757-11e7-8052-547dad659844.png)

Now you don't:
![screen shot 2017-06-22 at 2 31 21 pm](https://user-images.githubusercontent.com/8974593/27449784-8a980072-5757-11e7-8de7-092622d20323.png)

**Comment by jeff-phillips-18** [comment]
@ncameronbritt The "View All..." only shows when there are more than 5 results found.

**Comment by ncameronbritt** [comment]
Thanks @jeff-phillips-18 

I think we should look at showing the "View all" all of the time. @openshift/team-ux-review 

Consider this scenario:
I'm looking for something to do with "node" and I do a search which brings a few (< 5) results. I click on the first one listed, and decide that's not what I wanted. When I cancel out of the order flow, my search term is gone.

**Comment by ncameronbritt** [comment]
I think part of the problem right now is that the first item is highlighted by default. So there isn't a way to have a "results" page with five or fewer items except by using the "Filter by keyword in Category" function. That seems like a bug.

**Comment by jwforres** [comment]
@ncameronbritt assigning you to this until we get agreement from UX folks what they desired behavior is

**Comment by ncameronbritt** [comment]
The [design doc](http://openshift.github.io/openshift-origin-design/web-console/1-homepage/search-filter) indicates the following:

- No results will be highlighted until the up or down arrow key is pressed.
- Pressing the Enter key while no results are selected will trigger the View all results action (see below for details)

The second is currently not possible because there is always an option highlighted. 

I personally see benefit (and no harm) in always having the "View all option" available. Thoughts @openshift/team-ux-review ?

**Comment by beanh66** [comment]
@ncameronbritt I agree with you. Having the view all results always present would provide a consistent way for users to interact with search. Currently it seems like a bug that the first match is automatically selected.

**Comment by serenamarie125** [comment]
+1 on always having View all option @ncameronbritt

**Comment by jeff-phillips-18** [comment]
Looks like we have consensus. I will update.
