### ISSUE TITLE
Broken with Origin 1.2 API since introduction of what-can-i-do

### ISSUE THREAD

**Issue by rassie** [openshift/origin-web-console#176]
Even though this is probably not the main use case, I've been successfully using a git checkout of `origin-web-console` with productive OpenShift Origin 1.2 API for several weeks now. However, since the introduction of what-can-i-do in https://github.com/openshift/origin-web-console/pull/82 the console has been broken in this configuration: every attempt to open a project fails with "User permissions for project $PROJECT could not be loaded."

This is apparently due to the type `SelfSubjectRulesReview` missing in 1.2 (introduced in 1.3.0.alpha1). Like I said, I'm fully aware this is not in any way an intended use case, but I would really appreciate some sort of backward-compatibility with the last stable Origin release, since it allows us to preview upcoming user-facing features with very low overhead.

Would it be possible to make what-can-i-do feature optional in the sense of non-blocking for the main functionality?

**Comment by liggitt** [comment]
I could see creating tags in the web console repo to match origin versions, but conditionally supporting multiple server/web console version pairs adds more complexity than I think we want to carry

**Comment by jwforres** [comment]
we can fallback to be permissive if the selfsubjectrulesreview check fails, if the user cant actually do something they will get an error like they did before
