### ISSUE TITLE
No way to secure a route

### ISSUE THREAD

**Issue by kargakis** [openshift/origin-web-console#1760]
```
openshift v3.6.0-alpha.0+8125090-206
```
I can't find an easy way to promote an unsecure route to a secure one.

**Comment by spadgett** [comment]
@kargakis Did you try editing the route?

Edit Route -> Secure route (checkbox)

**Comment by kargakis** [comment]
Cool

**Comment by spadgett** [comment]
We could put a message a message like `<a>Edit</a> this route to enable security` on the route page to make it more discoverable.

**Comment by kargakis** [comment]
Yeah, making this more discoverable would be nice.

**Comment by kargakis** [comment]
I would also like to expose a Deployment (create a service for it that would then allow me to create a route for the service) but I cannot find a way to do this currently from the console.

**Comment by spadgett** [comment]
Not supported unfortunately (other than using Import YAML). It's a gap.

https://trello.com/c/FZtcmEPK
