### ISSUE TITLE
Ability to show registry URL in About/CLI pages

### ISSUE THREAD

**Issue by wgordon17** [openshift/origin-web-console#1766]
I see where the METRICS_URL and LOGGING_URL are set from `window.OPENSHIFT_CONFIG`, but I can't seem to find anywhere where I can figure out a way to determine what the registry URL endpoint is.

The desired end state would be to provide "convenience" commands on the CLI page, something akin to:

    docker -u `oc whoami` -p `oc whoami -t` REGISTRY_URL
    docker push <image> <tag> REGISTRY_URL/<project>/<name>

**Comment by wgordon17** [comment]
In #1767, I'm using a convention the online team is using, so this isn't so much of an issue. But, it could still be helpful to have available in origin at some point =)

**Comment by jwforres** [comment]
we pushed back awhile ago about adding more things to the dynamic config file, and this was specifically in relation to the registry URL.  The decision at the time was to push this onto the platform mgmt team to provide a way to define cluster configuration that was readable by clients.

@mfojtik might be able to point you to the story where this was being tracked

**Comment by wgordon17** [comment]
@jwforres Perfect, thanks for the clarification!

@mfojtik What can you tell me about this? I think being able to provide the registry URL to customers (and even Logging/Metrics endpoint URLs) to customers through the web console would be great!

**Comment by mfojtik** [comment]
@wgordon17 it is pretty much covered in PM board trello card: https://trello.com/c/2cHkrqIu/954-provide-public-pull-url-for-images  and also pretty high on my list for 3.7. Check the card description if it makes sense to you.

**Comment by wgordon17** [comment]
@mfojtik That's perfect! Thanks =)
