### ISSUE TITLE
Add to project configuration form doesn't pre select the project from which the user initiated the action

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#1774]
Example: I have multiple projects, the most recently created named foo. If I'm on any project within the console and select add to project (browse catalog) and then from the catalog select something, the configuration form 'add to project' select field defaults to project foo, instead of the one I came from. 

As a user, I would expect the form field to have the correct preselected project from which I initiated the action.

**Comment by jwforres** [comment]
This isn't an issue for Import YAML or Deploy Image. This is only if you do Add to Project -> Browse Catalog.

**Comment by spadgett** [comment]
We've removed the default selection when you have more than one project and now have the most recent projects at the top of the list.

Based on discussion in https://github.com/openshift/origin-web-catalog/pull/522, we probably will not implement preselect for the project you came from. The path forward is to have an experience where "Browse Catalog" does not take you out of the current project. See

http://openshift.github.io/openshift-origin-design/web-console/project-details/add-to-project
