### ISSUE TITLE
Warn when using source secrets for incorrect source URLs

### ISSUE THREAD

**Issue by wgordon17** [openshift/origin-web-console#1780]
When selecting a source secret on the create page:

1. It isn't clear whether the source secret is `Basic Authentication` or an `SSH Key`.
2. If the Git Repository URL is mismatched, e.g.
    + `http/https` and the source secret is an `SSH Key`
    + `git@<hostname>` and the source secret is `Basic Authentication`

I think [1] should be possible, as for [2]...I'm not sure if that's a valid problem (maybe git@<hostname> *can* use `Basic Authentication`), or if there's any way to check the URL when the source secret is selected, or if a warning can be displayed after the project is created.

@jwforres Any thoughts?

**Comment by jwforres** [comment]
something like (1) should be possible, but I question whether we should get into trying to client side validation around URL patterns to types of source secrets.

How common is it to have multiple source secrets in the same project?  If the main issue is setting up the wrong one in your project, then we have a longer term goal of letting you test your git connection before you create everything https://trello.com/c/OtTtHhqZ

**Comment by wgordon17** [comment]
Tbh, I'm not sure how common it is to have multiple source secrets. I guess ultimately, it would depend on the organization, if they're using multiple repositories.

I do think that testing the git connection would definitely help this problem. Possibly with some help text around, "HTTPS source secret didn't work, try an SSH source secret?". This came up from an Online user (and then myself and my team in testing)...we couldn't get SSH source secrets to work, but we had been trying an HTTPS source the whole time, not realizing that...DUH...not gonna work! So while it's nice to know that the git connection isn't successful, it's certainly not immediately clear *why* the source secret didn't work.
