### ISSUE TITLE
Show link to full pod template on overview if resource has init containers

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1790]
We should show a message on the overview and link to the configuration tab with the full pod template if resource has init containers.

Follow on to https://trello.com/c/kXzDqvXG

@jwforres FYI

**Comment by cdcabrera** [comment]
@spadgett are we aiming for something like?

![non-expanded](https://user-images.githubusercontent.com/3761375/27804278-04731376-5ffc-11e7-995e-a21cc57b367c.png)

and/or a combination where the expanded view also contains ```init containers```

![expanded](https://user-images.githubusercontent.com/3761375/27804305-32f12ec2-5ffc-11e7-8331-64c875e16a4f.png)

**Comment by spadgett** [comment]
@cdcabrera The idea was an inline message (when expanded only) saying there are two init containers and a link to the page will the full pod template

**Comment by spadgett** [comment]
I was envisioning something like

![openshift web console 2017-07-06 10-58-24](https://user-images.githubusercontent.com/1167259/27917532-41edca6c-623a-11e7-895f-95586e9bc4f6.png)

Where the link takes you to the tab with the pod template details. For different resources, the tab might be different unfortunately since Deployment Configs and Deployments have a history tab.

It might be good to update this filter / service to take an optional tab option:

https://github.com/openshift/origin-web-console/blob/master/app/scripts/filters/util.js#L354
https://github.com/openshift/origin-web-console/blob/master/app/scripts/services/navigate.js#L149

**Comment by spadgett** [comment]
The view for expanded overview rows is here:

https://github.com/openshift/origin-web-console/blob/master/app/views/overview/_list-row-expanded.html#L14
