### ISSUE TITLE
Vertical alignment of toggle arrow and kebab within list-pf-container isn't correct at mobile 

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#1805]
when < 769 icons are not centered vertically.

<img width="834" alt="screen shot 2017-07-07 at 10 24 01 am" src="https://user-images.githubusercontent.com/1874151/27962672-a2fe5058-6300-11e7-8861-69e192eca64e.png">
<img width="639" alt="screen shot 2017-07-07 at 10 24 32 am" src="https://user-images.githubusercontent.com/1874151/27962673-a2ffb114-6300-11e7-84c3-48d585f09572.png">

**Comment by spadgett** [comment]
I believe this was intentional, @rhamilto ?

**Comment by rhamilto** [comment]
> I believe this was intentional, @rhamilto ?

Nope.  That looks like a regression.

**Comment by sg00dwin** [comment]
I might have been introduced back when patternfly updated list-pf. I'll check what's going on.

**Comment by spadgett** [comment]
Whatever change we make, the caret probably shouldn't move when we show and hide warnings.

![openshift web console 2017-07-07 16-27-24](https://user-images.githubusercontent.com/1167259/27975668-31fbf6e0-6331-11e7-81eb-285aaf08fcf4.png)

**Comment by sg00dwin** [comment]
If we don't want the caret and kebab to be centered, when showing alerts, then shouldn't the mini donut not be centered? I seems strange that it is, but the kebab and caret aren't.

<img width="786" alt="screen shot 2017-07-10 at 11 39 37 am" src="https://user-images.githubusercontent.com/1874151/28027409-fad44522-6566-11e7-82f2-f80136ded65f.png">
<img width="784" alt="screen shot 2017-07-10 at 11 38 41 am" src="https://user-images.githubusercontent.com/1874151/28027410-fad9ec16-6566-11e7-8a35-5a010d7a41ff.png">

**Comment by spadgett** [comment]
Good point. @rhamilto opinion?

**Comment by rhamilto** [comment]
I prefer everything centered.

**Comment by beanh66** [comment]
Originally I would have thought everything should be centered as @rhamilto mentioned, but the caret and kebab were purposefully top aligned in PF to account for really tall rows inside of a list, to avoid making a user scroll to find actions. Given that those should probably remain top aligned, IMO  the pod donut and all content should still remain centered. Essentially what @sg00dwin has would be accurate. Curious other thoughts on this @openshift/team-ux-review

**Comment by serenamarie125** [comment]
I consider both the caret and kebab as controls, and think that they should be vertically top aligned (thus making the.  The screenshot above from @sg00dwin looks good!

**Comment by sg00dwin** [comment]
closing issue
icons top aligned are currently functioning as designed
