### ISSUE TITLE
[1.2] Shift key on mobile (Galaxy S5, Google Keyboard) works like backspace in the YAML editor

### ISSUE THREAD

**Issue by rassie** [openshift/origin-web-console#181]
I've tried to do a small fix in a deployment config from my phone while on the road and have found that pressing the Shift key on the virtual keyboard (Google Keyboard) is actually recognized by the editor as backspace, which deletes the character I've just typed. Haven't had the chance to try this on either a different keyboard nor on current development branch, but the bug is definitely there in my tool/version combination,

**Comment by spadgett** [comment]
Appears to be https://github.com/ajaxorg/ace/issues/2038

**Comment by spadgett** [comment]
We've switched to the Monaco editor (VSCode's editor) in 4.2, which addresses this long-open issue. Bonus: the editor now has full completion and hover help based on the OpenAPI schema!

https://github.com/openshift/console/pull/2039

/close
