### ISSUE TITLE
Events are not properly ordered

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#1846]
Doing a build, I go to the events and see:

![image](https://user-images.githubusercontent.com/78350/28208947-98cab9e2-6890-11e7-990e-2d6998677c82.png)

NOTE: Events are sorted by time in the UI.

Which don't make much sense in that order.
I verify that command line the events are ordered.

````
LASTSEEN   FIRSTSEEN   COUNT     NAME           KIND          SUBOBJECT                    TYPE      REASON                         SOURCE                   MESSAGE
4m         4m          1         test-1-build   Pod                                        Normal    Scheduled                      default-scheduler        Successfully assigned test-1-build to localhost
4m         4m          1         test-1-build   Pod           spec.containers{sti-build}   Normal    Pulling                        kubelet, localhost       pulling image "openshift/origin-sti-builder:v3.6.0-rc.0"
4m         4m          1         test-1-build   Pod           spec.containers{sti-build}   Normal    Pulled                         kubelet, localhost       Successfully pulled image "openshift/origin-sti-builder:v3.6.0-rc.0"
4m         4m          1         test-1-build   Pod           spec.containers{sti-build}   Normal    Created                        kubelet, localhost       Created container
4m         4m          1         test-1-build   Pod           spec.containers{sti-build}   Normal    Started                        kubelet, localhost       Started container
````

Version v3.6.0-rc0

**Comment by spadgett** [comment]
We sort by newest first in the UI, but it looks like the events might have the same timestamp.

**Comment by jorgemoralespou** [comment]
@spadgett depends on the time granularity. As you can see in the command line output, they are properly ordered, that means that either they come in order from the API query, or that they have miliseconds granularity. In the web ui, there is no miniseconds granularity, so I guess that ordering of things that happens in the same second can be not in the real order they happened.

**Comment by spadgett** [comment]
As far as I can tell, the API response is coming back with only second granularity and the events are not returned in order.

@fabianofranz How is the CLI sorting events?

**Comment by fabianofranz** [comment]
In `oc get` we don't sort by default, just display them in the order it comes from the API.

**Comment by jorgemoralespou** [comment]
I hope the API does return them sorted as otherwise would be awkward to look at a big list of events.
