### ISSUE TITLE
Image stream tags cropped too short

### ISSUE THREAD

**Issue by csrwng** [openshift/origin-web-console#1848]
In building images for origin inside origin, I need to create image tags that have the name of the origin image. However, when displaying them in the web console, the tags are cropped too small:
![image](https://user-images.githubusercontent.com/5834976/28218313-246e7534-6886-11e7-841f-5cb9b25d053e.png)

**Comment by csrwng** [comment]
@jwforres @spadgett 
/cc @smarterclayton

**Comment by spadgett** [comment]
Looks like it's caused by the `max-width` in `registry-image-widgets`

https://github.com/openshift/registry-image-widgets/blob/cd0ac574aeb21e672a4d4964a99933dcb608c858/images.less#L31

cc @petervo @stefwalter

**Comment by spadgett** [comment]
Making this a blocker since you can't tell which tag is which if they start with the same prefix

**Comment by spadgett** [comment]
We're going to make the tags a little wider for 3.6 in origin-web-console CSS as a stop-gap fix. I opened an upstream issue for the problem https://github.com/openshift/registry-image-widgets/issues/13
