### ISSUE TITLE
Image stream table: aggressive wrapping when not needed

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1849]
There's enough width to display the content without wrapping

![openshift web console 2017-07-14 12-21-22](https://user-images.githubusercontent.com/1167259/28220865-16bfe3ce-688f-11e7-87e8-f0dfbceae750.png)

**Comment by rhamilto** [comment]
@spadgett, shall I assume we should be overriding the default styles from https://github.com/openshift/registry-image-widgets?  I'm assuming the upstream styles are cockpit-specific?  cc: @stefwalter

**Comment by spadgett** [comment]
I'll defer to @petervo. It might be better to fix in the registry-image-widgets repo.

By the way, we have a related problem where all the identifier are truncated to "sha256:" on mobile, so they're not very useful.

**Comment by spadgett** [comment]
Appears to be fixed by #1989
