### ISSUE TITLE
Kubernetes deployment history tab alert jump on browser refresh

### ISSUE THREAD

**Issue by cdcabrera** [openshift/origin-web-console#1857]
Related to issue #1817 , and pr #1845 

The animation related to the alerts directive on Kubernetes has a jump/bump on multiple browser refreshes. 

@spadgett 

![refresh-jul-14-2017 11-16-27](https://user-images.githubusercontent.com/3761375/28218264-005e5f74-6886-11e7-9980-330e93a1b4e5.gif)

**Comment by spadgett** [comment]
Thanks for opening this. If it's only a problem with the new filter in #1845, we might try to tackle it in that PR since we're still locked down for 3.6. I didn't realize it was only the one page.

**Comment by cdcabrera** [comment]
Can do on #1845 haven't been able to track the issue down, probably something silly I'm missing
