### ISSUE TITLE
More roles missing the system-only annotation

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1858]
Looks like another set of roles made it past the `system-only` annotation?

![screen shot 2017-07-17 at 2 16 43 pm](https://user-images.githubusercontent.com/280512/28283107-af760b58-6afa-11e7-83a4-7cdfec920ae1.png)

Any objections to opening an issue in origin to address?

@jwforres @enj

**Comment by jwforres** [comment]
@benjaminapetersen yes please do, we do not want all these controller roles showing up OOTB

**Comment by jwforres** [comment]
this needs to get fixed for 3.6

**Comment by enj** [comment]
@benjaminapetersen this is one line fix to `GetDeadClusterRoles`.

**Comment by jwforres** [comment]
closing since this is tracked in origin, no need for the duplicate
