### ISSUE TITLE
Upgrade to angular-bootstrap v2.2.x is needed

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-console#1861]
Angular-patternfly uses angular-bootstrap v2.2.x.  If console is to achieve parity, it must also upgrade from angular-bootstrap v0.14.3 to v2.2.x.

uib-bootstrap update problems:
- [ ] Fix `?tab` links that don't switch to the tab
- [ ] Fix runtime error on events tab
- [ ] Fix empty membership page
- [ ] Update instances of class="uib-dropdown-menu" to uib-dropdown-menu in catalog

Some dedicated work and time is probably need to fix the visual issues.

**Comment by spadgett** [comment]
Probably using uib-dropdown incorrectly. I've noticed some deprecated warnings from angular-bootstrap in the console

**Comment by spadgett** [comment]
@dtaylor113 Can you try changing `uib-dropdown-menu` from a class to an attribute?

https://github.com/openshift/origin-web-console/blob/master/app/views/directives/header/project-header.html#L33

That might be all that's needed

**Comment by dtaylor113** [comment]
> @dtaylor113 Can you try changing uib-dropdown-menu from a class to an attribute?
Hi @spadgett, that did the trick.  Although I am seeing a small issue when dismissing these dropdowns, they have a blue border until they lose focus:

![image](https://user-images.githubusercontent.com/12733153/28419301-84aef98c-6d2c-11e7-8812-96a048e708a7.png)

![image](https://user-images.githubusercontent.com/12733153/28419308-8a9eaf86-6d2c-11e7-85a2-edc5a39f76e7.png)

**Comment by spadgett** [comment]
We can probably remove the outline if we want, but we might not want to for accessibility. I'm not too worried about it.

cc @sg00dwin @rhamilto

**Comment by rhamilto** [comment]
> we might not want to for accessibility

Agreed

**Comment by spadgett** [comment]
The `active` attribute is now an index set on the tabset rather than a property on the tab itself. This breaks our `persist-tab-state` directive in a way that is tricky to fix.
