### ISSUE TITLE
RC service catalog doesn't render base64 encoded images

### ISSUE THREAD

**Issue by DarrenRatcliffe** [openshift/origin-web-console#1862]
When integrating an external service broker to openshift the resulting services are displayed with broken image links if the broker passes base64 encoded images as opposed to image urls. Is it possible to allow for both eventualities?

![image](https://user-images.githubusercontent.com/1911051/28422920-5f5177ac-6d61-11e7-8343-2d62b7d28f9f.png)

**Comment by spadgett** [comment]
@DarrenRatcliffe Is the broker using data URIs for the image URL?

I was able to add an image URL like this, and it worked.

```
data:image/gif;base64,[base64-encoded-data-here]
```

I was using mock data, though, since I don't have a real broker that does this.

**Comment by DarrenRatcliffe** [comment]
@robertgmoss will be able to provide a deeper level of description (I have asked him to join the thread) but basically yes this is what is being passed in via the broker, yet for some reason the UI code is pre-pending error to it from memory

**Comment by robertgmoss** [comment]
@spadgett yes [see here for the code](https://github.com/cloudfoundry-incubator/apache-brooklyn-service-broker/blob/1c649c0a13438020b0992a1744c908fbb85d5158/src/main/java/org/cloudfoundry/community/servicebroker/brooklyn/service/BrooklynRestAdmin.java#L369)

What we were seeing was Angular adding the `unsafe` tag.

**Comment by spadgett** [comment]
@robertgmoss Thanks. This seems to be happening because the broker uses `data:img/png` instead of `data:image/png`, so it doesn't match Angular's safe pattern:

https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/platform-browser/src/security/url_sanitizer.ts#L45-L47

I believe `image/png` is the correct mime type. Is it possible to fix in the broker?

**Comment by robertgmoss** [comment]
@spadgett you are quite right `image/png` is the correct mime, thanks, I will fix in the broker.

**Comment by spadgett** [comment]
Sounds good @robertgmoss Thanks!

Let us know if you run into any problems. Closing the issue for now.
