### ISSUE TITLE
Show last scale time for things that have an autoscaler

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#187]
the HPA has a Status field for LastScaleTime.  should consider what we could do with this information in the console

**Comment by jwforres** [comment]
cc @spadgett

**Comment by spadgett** [comment]
We should already be showing it when set:

https://github.com/spadgett/origin-web-console/blob/8e405523fe7ca626000bbd6fbb69ad79c1fce453/app/views/directives/hpa.html#L45-L46

**Comment by spadgett** [comment]
Confirmed it's working.

![screen_shot_2016-12-14_at_12_53_49_pm](https://cloud.githubusercontent.com/assets/1167259/21194044/7685a864-c1fc-11e6-9db9-e36fc1584268.png)
