### ISSUE TITLE
UX: add new route screen confusing, use progressive disclosure

### ISSUE THREAD

**Issue by mairin** [openshift/origin-web-console#1886]
This issue concerns the add new route screen in OpenShift Origin. Compare the simplicity of the oc command compared to the UI equivalent:

> oc expose service parksmap

vs

![screenshot from 2017-07-27 13-22-38](https://user-images.githubusercontent.com/799683/28684388-2ec94134-72d2-11e7-97fe-7deb7650870b.png)

I think it might be better to follow a progressive disclosure pattern on this screen, and by default showing only those fields necessary to create the route with the extra options hidden below a toggle. E.g., a great example of progressive disclosure at work in a very similar type of problem is when you do add to project > (choose python / 3.5) > click on advanced. by default you get the bare basics, but you can open up the more specific opts on demand only if needed. That way, newer users / users with simpler needs can get things done more quickly with less distractions / overwhelm. Here's how that looks:

![screenshot from 2017-07-27 13-29-51](https://user-images.githubusercontent.com/799683/28684402-3afd3c58-72d2-11e7-87ce-1707837f32ec.png)

Version
==========

oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://console.gshipley.gce.pixy.io:8443
openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4

**Comment by spadgett** [comment]
@openshift/team-ux-review

**Comment by spadgett** [comment]
I don't disagree, although `oc expose` has its own problems. See https://github.com/openshift/origin/issues/8699

Note that you can just click "Create" if you open this form starting from the service. (Go to service page, Actions -> Create Route OR create a route from the overview.)
