### ISSUE TITLE
Upgrade grunt-ng-annotate

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1889]
We should upgrade grunt-ng-annotate. Our current version is very old and does not work with Angular components.

**Comment by spadgett** [comment]
It looks like ng-annotate is no longer maintained, which is concerning.

https://www.npmjs.com/package/ng-annotate

@jeff-phillips-18 @benjaminapetersen FYI

**Comment by benjaminapetersen** [comment]
Hmm. Yeah, this is problematic. ☹️ 
It doesn't even seem like the babel plugin that replaces it will make feature parity.

**Comment by benjaminapetersen** [comment]
Since we are not using babel, we can't migrate to the babel plugin.  The correct path forward then is likely to drop the dependency & update to use the `['dep', function(dep) {}]` format.

Do we want to consider other options, or should I update this issue?
