### ISSUE TITLE
Landing page projects sidebar should show most recently accessed

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1895]
Currently the landing page projects sidebar shows the 5 most recently created. It'd be better to show the 5 most recently accessed. We could implement this using `localStorage` like we have done for recently-viewed services.

cc @openshift/team-ux-review @jeff-phillips-18 @dtaylor113 @rhamilto

**Comment by dtaylor113** [comment]
We should also make sure we follow: #1481

**Comment by beanh66** [comment]
@spadgett Agreed, the desired behavior would definitely be to show the 5 most recently accessed projects if possible! We have heard this from a number of customers as well :)

**Comment by spadgett** [comment]
@dtaylor113 

* Let's count a project as being accessed when `ProjectsService.get` is called.

https://github.com/openshift/origin-web-common/blob/master/src/services/projects.js#L38

* We can store recently viewed projects as an array of project UIDs in localStorage (like recently viewed services)
* It probably makes sense to have a `RecentlyViewedProjectsService` in common

**Comment by spadgett** [comment]
I think that's a reasonable fallback.

**Comment by dtaylor113** [comment]
Hi,
Is the 'created by' label still relevant if we are going to sort by most recently viewed?

![image](https://user-images.githubusercontent.com/12733153/28935948-1e32c3ae-7854-11e7-8f3b-cbfb19d4bdeb.png)

**Comment by spadgett** [comment]
I think it's still worth showing. We let you sort projects by creator in the full project list page, so we show it there. And if we show it here, we're consistent.
