### ISSUE TITLE
UX / RFE: drap and drop pods into groups

### ISSUE THREAD

**Issue by mairin** [openshift/origin-web-console#1899]
Right now the controls to create and edit groups of pods are a bit complex and the controls small and easy to miss. It might be nice to be able to drag and drop them in / out of groups instead.

**Comment by spadgett** [comment]
The grouping feature has been replaced in 3.6 with a different implemention based on the `app` label. We have a card in our backlog for editing labels, which would be how you can edit apps.

https://trello.com/c/Xx7h1nPq
