### ISSUE TITLE
Bower deprecated, what to do in future

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1902]
Bower is still maintained in the short term, but indications are that its cordially being deprecated:

>    ..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!

https://bower.io/
https://github.com/bower/bower

I don't think we need to do anything soon, but probably good to keep an eye on this.

@spadgett @jwforres

**Comment by spadgett** [comment]
A number of our grunt dependencies are no longer maintained as well.

https://github.com/yeoman/grunt-usemin
https://www.npmjs.com/package/ng-annotate

I think we need to take a step back and look generally at our development toolchain.

cc @jeff-phillips-18

**Comment by benjaminapetersen** [comment]
Yup, prob getting close to time for some revamp.

**Comment by benjaminapetersen** [comment]
Per discussion yesteday, could be beneficial to look @ using `yarn` to replace `bower` & `npm`.  @spadgett mentioned some features of `maven` that were handy for dev w/specifying dependency versions, perhaps `yarn` has brought similar things to front end dev.

**Comment by dtaylor113** [comment]
MiQ is using ```yarn``` so we have some reference there.

**Comment by spadgett** [comment]
https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by benjaminapetersen** [comment]
I'd like to work on this, perhaps after e2e tests stabilize again.  Bring on the pain....

**Comment by benjaminapetersen** [comment]
`usemin` specifically uses `bower.json`, so if we drop `bower` & go all in on `yarn`, we will have to figure out how to redo this.  We would probably have to move to `require` or `import` and add a transpile step... that could be a pain.

**Comment by jeff-phillips-18** [comment]
we could just upgrade to typescript and webpack 😉

**Comment by benjaminapetersen** [comment]
Go big or go home eh?

**Comment by benjaminapetersen** [comment]
A new message from `bower`!

```
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
```

That hint is subtle, eh? :smile:

**Comment by spadgett** [comment]
This is now tracked in Trello: https://trello.com/c/guhAEGVH

/close

**Comment by gitlet** [comment]
Hi! I understand Bower deprecation to an extent (but donno why is it being done so..internally..), so I tried & migrate to "yeoman" instead. .both of which are build tools for frontend. But, please let me know as to why do we need to abondone npm & start using yarn..?

**Comment by benjaminapetersen** [comment]
You shouldn't have to care about this, `bower` still works.  We will be migrating at some point, but will doc any changes once that work is complete.
