### ISSUE TITLE
Use of .table-hover is confusing because we use a blue hover color to indicate clickable

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1904]
On browse page tables, we use [.table-hover](http://getbootstrap.com/css/#tables-hover-rows).  Given the hover color is blue, this is a bit confusing because in places like the project list page and &lt;registry-imagestream-listing&gt; we use a blue hover color to indicate the item is clickable.  I think we should only use .table-hover if the item is clickable OR change the clickable item hover color.  Granted the cursor changes when the item is clickable, but I think the hover color change dominates the cursor change affordance.

Row is not clickable:
![screen shot 2017-08-03 at 9 04 39 am](https://user-images.githubusercontent.com/895728/28923147-022d8410-782b-11e7-9ad8-0b7ae1c7a22e.PNG)

Row is clickable:
![screen shot 2017-08-03 at 9 04 54 am](https://user-images.githubusercontent.com/895728/28923159-0efbc8fa-782b-11e7-8180-f2e226323f6b.PNG)
![screen shot 2017-08-03 at 9 05 05 am](https://user-images.githubusercontent.com/895728/28923158-0eded786-782b-11e7-9cd2-702e5947583b.PNG)

thoughts, @openshift/team-ux-review?

**Comment by ncameronbritt** [comment]
List view items are highlighted in gray whether they're clickable or not: http://www.patternfly.org/pattern-library/content-views/list-view/#/code

The blue highlighting is less subtle than the gray, imho, and it does make it seem like the table row should be clickable. PF uses blue for other actions (links, etc), so the blue highlighting for something that isn't interactive seems to me to be inconsistent. 

Maybe this gray vs blue/interactive vs non-interactive is a question that should be raised upstream?

**Comment by beanh66** [comment]
@rhamilto I agree with the points @ncameronbritt makes regarding gray vs blue. In PF listview links and actions are highlighted in blue on hover as well as the full row is highlighted in blue once selected (when multi-select checkboxes are enabled) but in general rows are not blue on hover. 

I wonder about when a row is actually clickable to jump to a details page if it should be blue on hover though, such as the two examples you show last. @serenamarie125 have you run into this with other products at all?

**Comment by beanh66** [comment]
FYI @rhamilto We have a [PatternFly Design issue in GH](https://github.com/patternfly/patternfly-design/issues/314) to address this inconsistency.
