### ISSUE TITLE
Secret in binding confirmation should be a link

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#1908]
The secret named in the results step of the bind wizard should be a link to that secret, like in the mockup below.

![bind-results](https://user-images.githubusercontent.com/8974593/28937485-fdb07766-7858-11e7-8236-b4c34af77406.png)

**Comment by spadgett** [comment]
https://github.com/openshift/origin-web-common/blob/master/src/components/binding/bindResults.html#L21-L23

**Comment by amarie401** [comment]
@spadgett this looks like it is already a link, I can double check.

**Comment by amarie401** [comment]
@spadgett I have been able to reproduce and notice that it is not a link. I will see if I can fix 👍

**Comment by amarie401** [comment]
@spadgett I am a bit confused on how to see if my changes worked. Do I have the make the change in web-common? If so, how do I make it so that it shows in web-console for my repo?

**Comment by spadgett** [comment]
Yes, the changes need to go in origin-web-common. It's a little tricky to test in origin-web-console.

I usually run `grunt build` in origin-web-common, then symlink the `origin-web-console/bower_components/origin-web-common` folder by to the other git repo.

```
$ cd bower_components
$ rm -rf origin-web-common
$ ln -s ~/git/origin-web-common origin-web-common
```

You'll need to stop and start `grunt build` again in origin-web-console as well. I wish it were easier.

@jeff-phillips-18 might know a better way

**Comment by amarie401** [comment]
Ahh okay I see. Thank you.

**Comment by amarie401** [comment]
@spadgett  It says that the symlink is a broken link. I made the changes in the web-common, ran grunt build, then went over to web-console and did the steps for the symlink but when I tried to run grunt build I got this error:

```Warning: Error: origin-web-common is not installed. Try running `bower install` or remove the component from your bower.json file. Use --force to continue.```

**Comment by jeff-phillips-18** [comment]
Same thing but kind of a shortcut: 

From your origin-web-common repo directory:

bower link

From your origin-web-console directory:

bower link origin-web-common

**Comment by spadgett** [comment]
@jeff-phillips-18 thanks, that sounds much easier

@rhamilto @benjaminapetersen FYI ^

**Comment by amarie401** [comment]
@jeff-phillips-18  thank you!

**Comment by benjaminapetersen** [comment]
@jeff-phillips-18 @spadgett nice.... contemplating making a note of that in our `README.md`. 😐

**Comment by spadgett** [comment]
> @jeff-phillips-18 @spadgett nice.... contemplating making a note of that in our README.md.

Please do :)

**Comment by spadgett** [comment]
We should link out to the related origin-web-* repos as well
