### ISSUE TITLE
Round of cleanup on Overview, Applications, Provisioned Services, etc

### ISSUE THREAD

**Issue by serenamarie125** [openshift/origin-web-console#1913]
A number of pages ( overview, applications, provisioned services, etc ) have many font colors, sizes and weights which become distracting.  Visuals should provide input to be sure that the visual hierarchy is correct, and that the strategy for font color, sizes & weights along with whether or not we use icons alongside our action links ( create / add ) is consistent and clean.

**Comment by spadgett** [comment]
Related cards:

https://trello.com/c/jytcj3Bl
https://trello.com/c/zHWEtHgj

**Comment by jwforres** [comment]
closing since this being tracked in trello
