### ISSUE TITLE
Certain toasts may need some text formatting 

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1924]
![screen shot 2017-08-10 at 2 10 47 pm](https://user-images.githubusercontent.com/280512/29186277-e79cabd0-7dd9-11e7-8d20-39b3e7f8db79.png)

@spadgett @sg00dwin

**Comment by spadgett** [comment]
Unfortunately, this is just a plain text string we pass to the notification service. We might need to update the toasts to optionally specify markup if we want to use things like `class="nowrap"` around `(status -1)`

**Comment by cdcabrera** [comment]
@spadgett had an inquiry on any limitations surrounding our use of using AngularPf Toasts? 

First glance at the alert component, looks like there are a couple of minimal diffs, mostly around how the alert/message object/array is looped through, and some of the linking/anchor tags

**Comment by benjaminapetersen** [comment]
We may be able to address this in tandem with PR #2001.  Could we do any of the following:

1. Add a "read more" link & hide the extra text.  If you click "read more", the alert could expand and perhaps hold a `<pre>` or `<code>` block with the server text.  Its not pretty text & we don't control it, but we could make some nice chrome.  

1. Add a "read more" link & hide the extra text.  If you click "read more", open the notification drawer in expanded view & highlight the notification w/all of its info.

Further discussion on [this comment](https://github.com/openshift/origin-web-console/pull/2001#issuecomment-327587103) and in [this reply](https://github.com/openshift/origin-web-console/pull/2001#issuecomment-327790513)

Via discussion w/ @sg00dwin && @cdcabrera

**Comment by benjaminapetersen** [comment]
@beanh66 @ncameronbritt if you want to chime in on these ideas since they land in the realm of design, thanks!

**Comment by cdcabrera** [comment]
PR #2001 looks like a perfect fit for expanding the messaging. The alternative quick fix was the potential for HTML string content in the messages, something like...

```html
<span ng-if="alert.message" ... ng-bind-html="trustAsHtml(alert.message)"></span>
<span ng-if="alert.details" ... ng-bind-html="trustAsHtml(alert.details)"></span>
```

Which if we're opposed to allowing HTML through the use of ```$sce``` might be funky to work around. The other thought was to use transclusion, but then something similar may pop up.

**Comment by benjaminapetersen** [comment]
Per my prev comment, quick mocks would look like this:

1.  Put the server generated message in some chrome that we can expand/collapse
![screen shot 2017-09-08 at 11 28 17 am](https://user-images.githubusercontent.com/280512/30219037-d2a28b58-9488-11e7-92f3-9398511f5820.png)

1. "Show more" opens the expanded drawer & highlights the notification in some way:  
![screen shot 2017-09-08 at 11 31 17 am](https://user-images.githubusercontent.com/280512/30219151-2f6432ba-9489-11e7-9401-d93a13a298b8.png)

Suggestions open for feedback.

**Comment by serenamarie125** [comment]
hey @benjaminapetersen designers are looking in, and will chime back in once we've talked it thru a bit

**Comment by cshinn** [comment]
@benjaminapetersen @spadgett We've talked it over and our ideal solution is that the toast itself should show only the bold portion of the message and a link to either "View Event" or "View Logs" that links to where the notification came from.

**Comment by spadgett** [comment]
@cshinn There's rarely a log or event with the error when we show in these toasts.

Usually that second sentence is really important. It tells you what the actual error was. This is sort of an edge case where it's less helpful.

**Comment by spadgett** [comment]
For context, this is the basic format of most error toasts. The second sentence contains the actual error from the server.

> **An error occurred saving the build.**
> Reason: user "sam" doesn't have authority to create builds with strategy "Custom"

I'm really hesitant to hide that second sentence because it tells the user what actually went wrong. In some cases, the server error message isn't great, but it's usually the only hope you have of fixing the problem.

**Comment by ncameronbritt** [comment]
@spadgett Is this toast (or subsequently, the notification drawer) the only place the user could find that error message?

**Comment by spadgett** [comment]
> Is this toast (or subsequently, the notification drawer) the only place the user could find that error message?

In most cases, yes.

**Comment by cshinn** [comment]
That being the case, I like what @benjaminapetersen showed above with the expandable message and the whole text in the drawer.

**Comment by spadgett** [comment]
We already have the expandable text, but the limit is set to longer than this particularly message.

**Comment by spadgett** [comment]
By the way, this particularly message is ours from DataService, so we can make the message better.
