### ISSUE TITLE
Clicking on an unresolved image may redirect you to the project list/ catalog page

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1925]
It cannot build the url quite yet:

![screen shot 2017-08-10 at 1 57 50 pm](https://user-images.githubusercontent.com/280512/29186967-233b6044-7ddc-11e7-8c71-9f6db5c486cb.png)
![screen shot 2017-08-10 at 1 57 55 pm](https://user-images.githubusercontent.com/280512/29186960-1d424612-7ddc-11e7-9ee8-645da934345a.png)

@spadgett

**Comment by spadgett** [comment]
@petervo
