### ISSUE TITLE
Builder images created with --service-catalog enabled don't create routes or services

### ISSUE THREAD

**Issue by danmcp** [openshift/origin-web-console#1944]
Using `oc cluster up --version=latest --service-catalog`

Creating a ruby application through the catalog doesn't create the route or service like it does without `--service-catalog`.

**Comment by danmcp** [comment]
@bparees FYI

**Comment by bparees** [comment]
it also doesn't present any of the "Advanced" options to let you choose if you want a route or not, add env variables, etc.

**Comment by spadgett** [comment]
@bparees There is a link to advanced options.

**Comment by bparees** [comment]
advanced options link isn't available when you are creating a new project in that dialog. opened issue https://github.com/openshift/origin-web-console/issues/1945
