### ISSUE TITLE
Project 'nameTaken' not being set properly in controllers

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-console#1955]
HTML files for process-template, from-file, and deploy-image all have: 

```<select-project ... name-taken="$ctrl.projectNameTaken"></select-project>```

However, the corresponding controllers do not set the variable ```projectNameTaken```, which should be set from a failure from the server after attempting to create a project which already has the name.  

Some comments from @spadgett:

"Normal users can't see all projects in the cluster, so you don't have a complete list of project names (used by ```osc-unique```). We still need to handle errors from the server creating the project because the name is already in use by someone else."

https://github.com/openshift/origin-web-console/search?utf8=%E2%9C%93&q=name-taken&type=

This is also true for ```order-service-controller``` in origin-web-catalog.

**Comment by dtaylor113** [comment]
Should be resolved similar to [createSecret](https://github.com/openshift/origin-web-console/blob/master/app/scripts/directives/createSecret.js#L232), or [deployImage](https://github.com/openshift/origin-web-console/blob/master/app/scripts/directives/deployImage.js#L366)

**Comment by dtaylor113** [comment]
Just tested the different areas.

deployImage, processTemplate,  and fromFile throw a toast notification when a project name is already taken:
![image](https://user-images.githubusercontent.com/12733153/32232329-3085eb1a-be2e-11e7-8cde-9d3b558cf552.png)

orderService and createFromBuilder shows an inline error message, this should probably be changed to throw a toast instead.
![image](https://user-images.githubusercontent.com/12733153/32232637-db2761f2-be2e-11e7-99a6-ff14f8a93fd1.png)

The `<select-project>` component uses `osc-unique` to trigger form validation errors immediately upon entering in an existing project name, and the parent controllers (deployImage, fromFile, etc..) which attempt to create the project, handle 'name already taken' errors returned from the server.   And, as this issue initially indicated, the `$ctrl.projectNameTaken` variable isn't in or used in these parent controllers.

So I don't think we need the `name-taken` binding in 
```
<select-project ... name-taken="$ctrl.projectNameTaken">`
```
I think initially this component was relying on parent controllers to indicate whether the project name was taken, but `<select-project>` does the immediate validation via `osc-unique` and the parent controllers handle 'nameTaken' errors returned from the server.

IMO, what needs to be done for this issue is:
1. Remove 'name-taken' binding from `select-project` in console and catalog.
2. Make toast notifications for project name already taken for orderService and createFromBuilder in catalog.
@spadgett, does this seem reasonable?  -thanks

**Comment by spadgett** [comment]
@dtaylor113 I think the biggest usability issue is entering a bunch of information into one of these forms and then seeing error on the results page with no way to recover. It's particularly a problem for environments like online that have thousands of projects and you can't know what's already used. I'd like to try to fix at least that aspect of this issue for 3.7.

cc @jwforres

**Comment by spadgett** [comment]
I do like that name taken highlights the specific field in error and forces you to change that before resubmitting the form.

**Comment by dtaylor113** [comment]
So for deployImage, processTemplate, and fromFile which do the toast notification you never leave the wizard page, so the form is still filled in and available.   We need to switch orderService and createFromBuilder to use the toast notifications in the same way.

**Comment by dtaylor113** [comment]
Hi @spadgett, I think we need to decide if we need both a toast notification and an form validation error.  Currently, it only throws a toast notification for 'projNameTaken' error is returned from server, and it only shows the form invalid for osc-unique.   
I've wired up deployImage for when it gets a 'projNameTaken' from server to do both the existing toast notification, and through proper use of the `<select-project>`'s name-taken attribute, the form now also gets the form invalid look...but do we need both?

![image](https://user-images.githubusercontent.com/12733153/32279644-c118f3ae-beef-11e7-922c-e6738842685b.png)

And should I/we be hiding the help text if there is an error?

**Comment by jwforres** [comment]
We should not be toasting this error, we should be using the form
validation.

**Comment by dtaylor113** [comment]
@jwforres, ok that's easy enough change. NotificationService has a 'skipToast' attribute.   I'm trying to find an example in the code but do you happen to know what the standard is for these errors?  Do we hide the help text when error? Seems strange to have the help text shown in red, seems like we should just show the error msg.  -thanks

**Comment by jwforres** [comment]
@dtaylor113 the request failure shouldn't go to NotificationService at all when we get this particular error code back

The help text and the error text need to be in separate nodes, the help text should maintain is normal color. Like in this example from build-config.html
![separate help text](https://user-images.githubusercontent.com/1467629/32283561-14c4ade4-befb-11e7-8dee-b15d37e792f7.png)

**Comment by dtaylor113** [comment]
So we don't want 'project name already exists' failures recorded in the Notification Drawer?

**Comment by jwforres** [comment]
Doesn't make sense to me in this context. We don't let you continue, and we
don't create anything else. We give you the error inline in the form.

**Comment by dtaylor113** [comment]
Fix for CreateFromBuilder and OrderService wizards up in Catalog PR: https://github.com/openshift/origin-web-catalog/pull/550.  
deployImage, processTemplate, and fromFile in Console to follow.
