### ISSUE TITLE
Web console should warn user when implicitly creating routes

### ISSUE THREAD

**Issue by npmccallum** [openshift/origin-web-console#1960]
Currently, the creation of a new S2I app creates services and routes implicitly. However, this behavior might surprise administrators who are not expecting the routes to be created implicitly. This possibly unexpected behavior can create an opportunity for security flaws. For example, an administrator could bring up an app with private data (such as social security numbers) which is now implicitly exposed to the world.

Instead, OpenShift should perform one or more of the following:

1. Warn the administrator that a route will be implicitly created to expose the service.
2. Confirm that the administrator wants to create the implicit route.

**Comment by enj** [comment]
xref openshift/origin/issues/15913

**Comment by benjaminapetersen** [comment]
We have had conversations about improving warnings for things like this in templates, however, I'm not quite sure what we can do about S2I via the web console.  @spadgett thoughts?

**Comment by enj** [comment]
I think the general idea was: if a route is going to automagically be created, let the user know about it.

**Comment by npmccallum** [comment]
I think there *might* be reason to change the default behavior. First, building a service manually doesn't expose it by default. So there is an internal inconsistency. Second, `oc new-app` also doesn't create the routes by default. So there is an external inconsistency. Given these two existing inconsistencies, there might be sufficient justification to change the default behavior.

I had proposed a checkbox to create the route automatically. It could be checked or unchecked by default. Unchecked would be consistent with the rest of OpenShift. However, checked would be consistent with the historical behavior. I don't have a dog in that fight.

**Comment by enj** [comment]
There is no default behavior.  The template is saying "create a route".  So the system does.  It just needs to tell you about it (just like it does for SAs).

**Comment by spadgett** [comment]
@enj This isn't for template, but for the s2i builder images

**Comment by enj** [comment]
Ah, so, does the web console create routes on its own or does the S2I stuff tell it to do so?

**Comment by spadgett** [comment]
@enj It creates them on its own. It's basically `oc new-app <git-url>`, except the console also creates a route by default. This was done originally in 3.0 because you couldn't create a route later in the console.

**Comment by enj** [comment]
> except the console also creates a route by default. This was done originally in 3.0 because you couldn't create a route later in the console.

Well that is unfortunate.

**Comment by benjaminapetersen** [comment]
You can now.  3.0 console was pretty bare bones back then.
