### ISSUE TITLE
The BuildConfig environment tab is awkward for a user with view permissions

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1969]
For a non-admin user, this experience is a bit strange:  

![screen shot 2017-08-25 at 4 21 55 pm](https://user-images.githubusercontent.com/280512/29731194-8a94ef5e-89b1-11e7-9094-69714286cc3b.png)

If you then click the link to show hidden vars:

![screen shot 2017-08-25 at 4 22 52 pm](https://user-images.githubusercontent.com/280512/29731227-ab222dc2-89b1-11e7-94f9-5c59b52f24c6.png)

My guess that we hide the readonly empty KVE, and update the message to remove the word `additional` if  `ng-if="'buildconfigs' | canI : 'update'"` is false, but still allow the user to click to see the expanded view.

related to #1438

@spadgett

**Comment by spadgett** [comment]
@benjaminapetersen Is this fixed by #1970?

**Comment by jwforres** [comment]
Just noting this is still an issue.
