### ISSUE TITLE
Service names can get cut off at certain viewport sizes.

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#1979]
Service name is cut off when looking in a category at just over 1200px.

@rhamilto 

![screen shot 2017-08-28 at 3 34 15 pm](https://user-images.githubusercontent.com/8974593/29791280-5dcf441e-8c0a-11e7-9101-42b0bf3a31f9.png)

**Comment by rhamilto** [comment]
Upstream fix:  https://github.com/openshift/origin-web-catalog/pull/415.  To resolve, a new release of https://github.com/openshift/origin-web-catalog is required.
