### ISSUE TITLE
"View log" links behave inconsistently

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#198]
Throughout the console, we have "View log" links.  With the introduction of pipelines, some of those "View log" links now link to Jenkins instead of the console.  Sometimes, clicking one of those links opens Jenkins in a new window.  Sometimes not.  If they're going to open a new window, we should decorate them with a new window icon as an affordance to the user.  Regardless, "View log" links should behave consistently for a given log type.

![screen shot 2016-07-20 at 4 50 54 pm](https://cloud.githubusercontent.com/assets/895728/17002914/971e0b54-4e9b-11e6-8c7e-129217a89415.PNG)

**Comment by spadgett** [comment]
Personally I've never liked the opens-in-a-new-window icon. Here it would show up twice and then repeated in each row.

I agree we should be consistent, and I think any link that unexpectedly leaves the web console should open in a new tab (Jenkins links, doc links, route links).

**Comment by rhamilto** [comment]
I am of the opinion that it's never ok to open a link in a new window as it breaks the back button and is user-hostile.  See mistake number 9. https://www.nngroup.com/articles/top-10-mistakes-web-design/

**Comment by spadgett** [comment]
#216 makes the link open in a new window with some other fixes.

@rhamilto Feel free to open a new issue for `target="_blank"` links in general if you think the behavior is wrong. I'm open to changing the behavior or decorating the links with an icon.
