### ISSUE TITLE
Entire notification drawer flashes on update

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1981]
@jeff-phillips-18 @benjaminapetersen We should look at adding a `track by` for event UID if possible (and add UIDs to other toasts when we add them to the drawer). Right now the entire drawer contents flashes because we haven't gotten `track by` right.

**Comment by spadgett** [comment]
Probably requires upstream angular-patternfly changes.

**Comment by spadgett** [comment]
![screencast 2017-08-29 07-58-53](https://user-images.githubusercontent.com/1167259/29819750-fe64d74c-8c8f-11e7-890d-3120b153c452.gif)

**Comment by spadgett** [comment]
@benjaminapetersen Per our conversation, let's remove any CSS animations until we can get `track by` working upstream.

**Comment by jeff-phillips-18** [comment]
@spadgett Do you think using track by $index will not help this issue?

**Comment by spadgett** [comment]
@jeff-phillips-18 I don't think so because the index in the array for a particular event changes when items are added and removed.

**Comment by spadgett** [comment]
Part of the problem is that the same event appears twice momentarily in the drawer.

Video:

![screencast 2017-08-29 12-33-49](https://user-images.githubusercontent.com/1167259/29832581-b045a876-8cb6-11e7-8b94-f7d9e4274250.gif)

Here's a frame from the video with the same item in the drawer twice:

![screen shot 2017-08-29 at 12 35 10 pm](https://user-images.githubusercontent.com/1167259/29832600-c475b9f8-8cb6-11e7-9221-03570fff96a4.png)

**Comment by spadgett** [comment]
Yeah I think it is because of a missing or bad `track by`. The item moves from the bottom of the list to the top, but AngularJS doesn't know that it's really the same item so you have the remove animation.
