### ISSUE TITLE
Overview has duplicate links to the secret details page from provisioned services list

### ISSUE THREAD

**Issue by beanh66** [openshift/origin-web-console#1982]
On the overview page, when provisioned services have bindings, both the secret name and "View Secret" are shown as links. Both links will take the user to the same secret details page. The "View Secret" link is not needed here.

![secret-links](https://user-images.githubusercontent.com/18057044/29819866-7000a7c8-8c90-11e7-9bfe-e88157642ff9.png)

**Comment by spadgett** [comment]
It's not always the same link... We kept the "View Secret" link so that it wasn't mysteriously missing from some rows.

Although with pod presets coming out, this will always be the case.

**Comment by spadgett** [comment]
@jeff-phillips-18 I think we should just take out the View Secret link for now and revisit later when pod presets / initializers return. Assigning to you since it's related to the pod preset card (although feel free to make this a separate PR).

**Comment by spadgett** [comment]
Looks like this has been fixed.

![openshift web console 2017-09-13 16-20-21](https://user-images.githubusercontent.com/1167259/30398741-78efd618-989f-11e7-9350-8f9f42e0ef46.png)
