### ISSUE TITLE
Update membership to use RBAC api

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1986]
There is a new API that replaces the old `rolebindings` API we are using.  The API references real objects, not virtual, and thus supports `watch`.  

API should be: `/apis/rbac.authorization.k8s.io/` in [this file](https://github.com/openshift/origin/blob/master/api/swagger-spec/openshift-openapi-spec.json) (cannot direct link line as file is too big for github to render a view).

@enj suggests updating to avoid the need to maintain backwards compatibility if the console is ever split out.

This may be worth considering along with issue #1219 and PR #1860 (and potentially opening as a Trello card instead of an issue, depending on size of work).

@spadgett

**Comment by benjaminapetersen** [comment]
Per comment from @enj: 
- `{cluster}role{binding}` so 4 resources
- the transition from `v1beta1` to `v1` in kube 1.8 had no changes AFAIK, so it will be trivial to change that part later

**Comment by benjaminapetersen** [comment]
[Origin PR to update to use Kubernetes RBAC](https://github.com/openshift/origin/pull/15021)

**Comment by spadgett** [comment]
@benjaminapetersen How close are the APIs?

**Comment by enj** [comment]
@spadgett they have subtle differences that are visible from the outside.  Specifically, RBAC is explicit in a lot of places where the old API was implicit.  Overall it is a lot nicer to use, and a lot more difficult to [accidentally] misuse.

**Comment by spadgett** [comment]
Might need a Trello card for this if the change isn't small.

**Comment by enj** [comment]
Would we ever want to run the web console on top of Kube?  This would be a requirement for that.

**Comment by benjaminapetersen** [comment]
I'm betting a Trello 😄 

@enj... I think we have too many OpenShift specific things to drop it right on Kube, but I could be incorrect there (& I don't know enough to speak to the strategy).

**Comment by spadgett** [comment]
It's not just membership, but also `AuthorizationService` that handles the `canI` checks.

**Comment by spadgett** [comment]
Created a Trello card: https://trello.com/c/R1ninKHf

Closing the issue since it's tracked in Trello.
