### ISSUE TITLE
Long project names in Notifications header overlap link

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#1993]
<img width="364" alt="screen shot 2017-08-31 at 9 42 57 am" src="https://user-images.githubusercontent.com/1874151/29926655-133855ba-8e32-11e7-971b-efccd0d376e6.png">

**Comment by spadgett** [comment]
@jeff-phillips-18 @benjaminapetersen FYI

**Comment by benjaminapetersen** [comment]
Nice catch. Hmm. Truncate or just drop the link down a line?

**Comment by spadgett** [comment]
Truncate seems find to me since you can already see the project name in the project bar. Maybe add a `title` attribute for hover.
