### ISSUE TITLE
proposal i10n openshift to chinese version

### ISSUE THREAD

**Issue by xiaods** [openshift/origin-web-console#1995]
Hi team, we would like to participate openshift community. we are China's startup based on Container service, Beijing Dataman Inc. 

we try to add a pr to demo i10n process for openshift codebase, anyone can guide us to standard it and improve it. thanks a lot. 

https://github.com/openshift/origin-web-console/pull/1994

**Comment by sspeiche** [comment]
FYI: There was some work done a year ago, not sure how relevant it is today https://github.com/openshift/origin-web-console/pull/51

**Comment by xiaods** [comment]
@sspeiche thanks for your guid, i think your hint it great case for our i10n process. we will refactor it and let it happen asap.

**Comment by benjaminapetersen** [comment]
@xiaods per your comment on #1994, I'll defer to @sspeiche @spadgett @jwforres
