### ISSUE TITLE
data-toolbar max width necessary for overview filter?

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1998]
Def like the new layout.  I'm curious if the data toolbar `max-width` is necessary, I think I prefer it filling the whole width:

![2017-09-01 14 06 17](https://user-images.githubusercontent.com/280512/29982216-dec3ef2c-8f1e-11e7-8dc8-db5656b0b389.gif)

I don't have a strong opinion, but the input is already pretty lengthy so having the drop down flush right feels a little more settled to me.  

@sg00dwin @rhamilto

**Comment by spadgett** [comment]
The example you have in the description is fine, but it might start to look silly at really wide screen widths (like fullscreen on a 30" display). I'd vote to leave it as-is, at least for now. We'll likely be adding more to the toolbar in the future.
