### ISSUE TITLE
Collapse long lines in resources inside my screen

### ISSUE THREAD

**Issue by kargakis** [openshift/origin-web-console#2002]
https://api.ci.openshift.org/console/project/ci/browse/config-maps/config

Some configs like the above have some nasty long lines and it would be great if we could collapse those inside the screen. It was also strange at start that I couldn't see the "See All" button and I had to scroll all the way through to the end.

**Comment by rhamilto** [comment]
Will be resolved when console is updated to use https://github.com/openshift/origin-web-common/releases/tag/v0.0.53
