### ISSUE TITLE
Double scrollbar in events sidebar

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2004]
<img width="367" alt="screen shot 2017-09-01 at 12 23 09 pm" src="https://user-images.githubusercontent.com/1167259/30034587-4a293fa8-9170-11e7-8ab9-62c3f9e4823b.png">

Related to #1932

cc @rhamilto

**Comment by sg00dwin** [comment]
The notification panel also behaves this way.   What is the patternfly recommendation? 
@serenamarie125b

<img width="351" alt="screen shot 2017-09-05 at 10 19 10 am" src="https://user-images.githubusercontent.com/1874151/30065703-c1e0b522-9223-11e7-80af-c4e92453e07a.png">

**Comment by spadgett** [comment]
cc @serenamarie125 

FWIW The notifications panel bother we less since it's a floating element with fixed height rather than being embedded in the page.

**Comment by spadgett** [comment]
@serenamarie125 For context, the issue is for the old events sidebar that we've had for a while, not necessarily for the notification drawer.
