### ISSUE TITLE
Long name projects cause horizontal and vertical scrollbars in the create modal

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#2007]
<img width="620" alt="screen shot 2017-09-05 at 9 25 24 am" src="https://user-images.githubusercontent.com/1874151/30063322-564de2b4-921c-11e7-8112-d446fcdd5a12.png">

**Comment by rhamilto** [comment]
This will be fix when the console is updated with the next version of catalog and common.
