### ISSUE TITLE
Layout problem with standalone service alerts

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#201]
![screen shot 2016-07-21 at 9 01 14 am](https://cloud.githubusercontent.com/assets/1167259/17023525/be6c603a-4f21-11e6-9063-e2f62ab6f38b.png)

/cc @jwforres

**Comment by spadgett** [comment]
I can fix the margins. The question is should the alerts appear on top or below when not in a service group?

![screen shot 2016-07-21 at 9 27 33 am](https://cloud.githubusercontent.com/assets/1167259/17024294/659ec2aa-4f25-11e6-8524-7c090b49babf.png)

**Comment by jwforres** [comment]
i think im ok with the notifications on top still
