### ISSUE TITLE
Landing page nav-tabs-pf have layout issues caused by upstream repo

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#2010]
![screen shot 2017-09-05 at 10 42 46 am](https://user-images.githubusercontent.com/895728/30068094-ac000e86-922a-11e7-9b40-a5f78b5a7f93.PNG)
![screen shot 2017-09-05 at 10 42 54 am](https://user-images.githubusercontent.com/895728/30068093-abac6a92-922a-11e7-9f49-c6765bb9bfd6.PNG)

https://github.com/openshift/registry-image-widgets/blob/master/listing.less#L465-L482 is the culprit.  These rules are not properly scoped (they apply to all .nav-tabs-pf in console) and are overly specific (use of !important).

cc: @petervo

**Comment by petervo** [comment]
https://github.com/cockpit-project/registry-image-widgets/pull/7
