### ISSUE TITLE
Allow the user to select containers when adding a secret to an application

### ISSUE THREAD

**Issue by jeff-phillips-18** [openshift/origin-web-console#2024]

**Comment by spadgett** [comment]
Here is what we do for config volumes:

https://github.com/openshift/origin-web-console/blob/master/app/views/add-config-volume.html#L174-L191

We can probably just reuse the `select-containers` directive.

**Comment by jeff-phillips-18** [comment]
Do we also want to allow the user to select specific keys and paths when using a volume?
