### ISSUE TITLE
Should warn when secret keys are not valid env var names

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2029]
In the "Add to Application" dialog, we should warn when some secret keys aren't valid environment variable names. These keys will be skipped when adding env variables.

cc @beanh66

**Comment by jeff-phillips-18** [comment]
Is this enough or should we list out which variables are invalid?

![image](https://user-images.githubusercontent.com/11633780/30217343-d920882c-9483-11e7-9faf-dc5dbb1d0d5c.png)

@beanh66 @spadgett
