### ISSUE TITLE
Log throws a js error generating the view archive link

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#204]
When the loggingURL is configured for the web console, going to the Log tab for a pod/build/deployment will throw a JS error when URI.js tries to expand the template.  I suspect this is something to do with our update to a new URI.js, they may have expanded their supported templating language (special characters) and we may have something in that kibana URL that is  incompatible.  Given all of the special characters in the kibana URL we probably need to switch to doing a string replace ourselves using native string replace or lodash stuff instead of using a URI.js template so that we dont hit this again later.

**Comment by benjaminapetersen** [comment]
Looking at it now.

**Comment by benjaminapetersen** [comment]
Yeah thats kinda ugly.

![screen shot 2016-07-21 at 3 02 26 pm](https://cloud.githubusercontent.com/assets/280512/17035160/ebcca058-4f53-11e6-80ca-096969dc12df.png)
