### ISSUE TITLE
Metrics vanish for remainder of session upon connection timeout

### ISSUE THREAD

**Issue by Vchabs** [openshift/origin-web-console#2042]
Sometimes my connection to metrics times out temporarily, even though hawkular is still running in openshift-infra. This leads the metrics to vanish for the remainder of my session duration. To get it back, I usually would have to refresh the session (close out of browser, re-open openshift). 

Is it possible to reconfigure the metrics service's is-available to refresh the metrics' status every few minutes if the connection failed?

**Comment by ttindell2** [comment]
+1
