### ISSUE TITLE
Provide equivalent of 'oc set volume --overwrite'.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin-web-console#2045]
If you attempt to mount a volume in a container of a pod, and try to name the volume definition the same as an existing volume definition, the web console will give you an error and not allow it.

![image](https://user-images.githubusercontent.com/507637/30256912-80931d9e-96f1-11e7-99bb-b48228f5bfac.png)

The problem is that the ability to reuse the existing volume definition, when it is the same underlying persistent volume claim, is necessary if you are attempting to share a volume between two different containers within the same pod.

When using the command line you can override any such error by using the ``oc set volume --overwrite`` option. A similar ability is needed in the web console.

There are possibly two choices. If the error comes up, show a checkbox to allow you to overwrite it. Or, maybe not even show the error if the volume definition exists but is for the same persistent volume claim. That is, make it intelligent enough to know that it can reuse the existing volume definition which has already been created for the same persistent volume claim.

Note that you cannot just create a second volume definition for the same underlying persistent volume as it seems having multiple volume definitions with different names, but for the same underlying persistent volume claim, against the one deployment configuration, cause deployment to hang.

**Comment by spadgett** [comment]
Reopening because there is an issue with the current fix.

**Comment by spadgett** [comment]
@GrahamDumpleton Making sure I understand the scenario: You want to be able to add the same PVC to different containers in the same pod? Do they need different mount paths? Otherwise you should be able to add it to all containers at once.

**Comment by GrahamDumpleton** [comment]
They needed to be added at different mount points in each container and with different sub path from within the volume as it was not intended they use the same data, but different parts of the shared volume.

**Comment by GrahamDumpleton** [comment]
As example:

```
                    "spec": {
                        "volumes": [
                            {
                                "name": "data",
                                "persistentVolumeClaim": {
                                    "claimName": "${APPLICATION_NAME}-data"
                                }
                            }
                        ],
                        "containers": [
                            {
                                "name": "wordpress",
                                ...
                                "volumeMounts": [
                                    {
                                        "name": "data",
                                        "mountPath": "/opt/app-root/src",
                                        "subPath": "wordpress-data"
                                    }
                                ]
                            },
                            {
                                "name": "mysql",
                                ...
                                "volumeMounts": [
                                    {
                                        "name": "data",
                                        "mountPath": "/var/lib/mysql/data",
                                        "subPath": "mysql-database"
                                    }
                                ]
                            }
```

**Comment by spadgett** [comment]
Thanks @GrahamDumpleton for explaining.

> Note that you cannot just create a second volume definition for the same underlying persistent volume as it seems having multiple volume definitions with different names, but for the same underlying persistent volume claim, against the one deployment configuration, cause deployment to hang.

@mfojtik @kargakis Is this a bug?
