### ISSUE TITLE
Not enough padding for overview loading message

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2049]
![screen shot 2017-09-11 at 1 30 09 pm](https://user-images.githubusercontent.com/1167259/30291759-dbdd35ee-9701-11e7-93a0-a4f8d70bf018.png)

**Comment by sg00dwin** [comment]
I'm unable to reproduce. The element is getting the correct margin-top
https://github.com/openshift/origin-web-console/blob/375e384589549fdcd8a63b3712eb9b43b160d3c6/app/styles/_overview.less#L361-L363

@rhamilto what are you seeing?

**Comment by rhamilto** [comment]
> @rhamilto what are you seeing?

Looks ok for me, too.

![screen shot 2017-09-11 at 4 13 54 pm](https://user-images.githubusercontent.com/895728/30294801-66267d8c-970c-11e7-8f65-8630e1b42742.PNG)

**Comment by spadgett** [comment]
I think there's a scrollbar on the loading page, and I accidentally scrolled

**Comment by rhamilto** [comment]
To resolve the issue where the scrollbar appears while "Loading..." is present, it looks like changing the [top](https://github.com/openshift/origin-web-console/blob/master/app/styles/_core.less#L111) [and](https://github.com/openshift/origin-web-console/blob/master/app/styles/_core.less#L134) [bottom](https://github.com/openshift/origin-web-console/blob/master/app/styles/_core.less#L144) margins on .empty-state-message and .empty-state-message [h2](https://github.com/openshift/origin-web-console/blob/master/app/styles/_core.less#L118) will fix the issue.  Needs further testing...

**Comment by spadgett** [comment]
Yeah, it's definitely the scrollbar. Here is the uncropped screenshot.

![screen shot 2017-09-11 at 1 30 09 pm](https://user-images.githubusercontent.com/1167259/30330978-88539e2e-97a4-11e7-9584-ccb927524d6a.png)
