### ISSUE TITLE
Add to project wizard modal-footer buttons can't be focused using keyboard tab

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#2065]
The 'next','create', and 'cancel' buttons can not be focused or entered using the keyboard.

**Comment by jeff-phillips-18** [comment]
This is fixed in Angular Patternfly 4.8.2

**Comment by spadgett** [comment]
Fixed upstream by https://github.com/patternfly/angular-patternfly/issues/603

Also tracked by https://github.com/openshift/origin-web-catalog/issues/406. Closing so we're not tracking this twice.
