### ISSUE TITLE
Should not link to secret until binding is ready

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2069]
On the overview, we link to the binding secret before the binding has finished. This link will not work until the binding is ready.

![screen shot 2017-09-13 at 4 13 47 pm](https://user-images.githubusercontent.com/1167259/30398517-bcc39ac4-989e-11e7-9af9-97b624e9dd41.png)

cc @jeff-phillips-18 @ncameronbritt

**Comment by ncameronbritt** [comment]
Is it possible to just wait until the binding is completed to add the anchor tag? You'd see the name of the secret that would be created, but it wouldn't be a link until it was ready.

**Comment by spadgett** [comment]
Yeah, that is what I was thinking as well
