### ISSUE TITLE
Overview should truncate long service class description text

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2072]
We currently don't truncate the text. It's possible for a service description to be any length.

**Comment by spadgett** [comment]
@cdcabrera We probably want to do this on the service instance details page, too.

**Comment by spadgett** [comment]
We might need to line clamp this instead of using the directive because otherwise we can't use the `linky` filter

**Comment by rhamilto** [comment]
> We probably want to do this on the service instance details page, too.

@sg00dwin, you'll want to do what you did on the overview for both the short and long description.  See  https://github.com/openshift/origin-web-console/blob/master/app/views/browse/service-instance.html#L70-L71
