### ISSUE TITLE
import yaml modal has an unnecessary scrollbar when launched from landing page

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2076]
When launched from the landing page, the Import YAML modal has a scrollbar, but not when launched from within a project.

Landing page:
<img width="1205" alt="screen shot 2017-09-14 at 11 32 35 am" src="https://user-images.githubusercontent.com/8974593/30438909-6f8f895a-9940-11e7-881e-004aa273c59c.png">

Project:
<img width="1195" alt="screen shot 2017-09-14 at 11 31 00 am" src="https://user-images.githubusercontent.com/8974593/30438828-38d9e068-9940-11e7-91cf-872bd2155e99.png">

**Comment by ncameronbritt** [comment]
Sorry, copied the wrong image the first time.

**Comment by rhamilto** [comment]
This is occurring because of the addition of the "Add to project" dropdown.  I'm assuming we don't want to increase the max-height of the modal for this one use case.  

And note:  if user chooses to "Create Project", additional fields appear.

![screen shot 2017-09-14 at 2 07 07 pm](https://user-images.githubusercontent.com/895728/30446058-0ca2a500-9956-11e7-854c-0e96d4b8d590.PNG)

**Comment by rhamilto** [comment]
An alternate approach to increasing the max-height of the modal would be to reduce the height of the editor when on the landing page.  But we'll still have the "Create Project" issue.

**Comment by spadgett** [comment]
I think Jessica set the editor height based on the dialog height before we added the select project dropdown. I'm OK with either fix. It does seem like the dialog is a little short to me, though.

I'm less worried about "Create Project."

**Comment by ncameronbritt** [comment]
@rhamilto @spadgett I glossed over the project picker. I'm not sure there's a real issue here. I mean, if the modal has a max height, then at some point it will need to scroll.

**Comment by spadgett** [comment]
I agree except we're tying to size the editor to exactly fit, but not doing it right in this instance.

**Comment by rhamilto** [comment]
I like the latter option as it doesn't require futzing with the modal max-height and eliminates double scrollbars.

Yea
![screen shot 2017-09-14 at 2 34 12 pm](https://user-images.githubusercontent.com/895728/30447410-0a850ba6-995a-11e7-8c83-f762dc194c7a.PNG)

Nay
![screen shot 2017-09-14 at 2 34 35 pm](https://user-images.githubusercontent.com/895728/30447414-111d4352-995a-11e7-9e60-a9fce0fcca2a.PNG)

I will PR the Yea if y'all are good with it.

**Comment by ncameronbritt** [comment]
If @spadgett is good with it, I am too.

**Comment by spadgett** [comment]
Works for me, thanks @rhamilto
