### ISSUE TITLE
Cannot upgrade angular-patternfly as it breaks the modal

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#2087]
Attempted to update `angular-patternfly` to latest `4.9.1` to pickup the accessibilty updates for modal, but the modals break:

![screen shot 2017-09-15 at 11 41 19 am](https://user-images.githubusercontent.com/280512/30491305-e109c166-9a0a-11e7-81da-d8742309e7cc.png)

Not sure what happened there.  Works fine on master, only change is `  "angular-patternfly": "4.9.1",` in `bower.json`.

@spadgett @jeff-phillips-18

**Comment by spadgett** [comment]
You need the latest Patternfly, too, but I still see the problem when bumping Patternfly.

**Comment by benjaminapetersen** [comment]
lol @rhamilto ping as well, didn't realize this is what you all were talking about in the irc chat.

**Comment by spadgett** [comment]
Should be fixed by https://github.com/openshift/origin-web-catalog/pull/438 when we bump catalog

**Comment by spadgett** [comment]
Fixed by #2103
