### ISSUE TITLE
Guided tour should have a way to dismiss it

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2089]
There is no way to get rid of the guided tour once it's started except by completing all of the steps. 
![screen shot 2017-09-15 at 1 18 18 pm](https://user-images.githubusercontent.com/8974593/30495099-9c198308-9a18-11e7-9c5c-2cccd79d5e0d.png)

There should be an X  in the top right of the tour points. See [documentation](https://github.com/openshift/openshift-origin-design/blob/master/web-console/1-homepage/project-panel.md#getting-started---guided-tour).

**Comment by jeff-phillips-18** [comment]
@ncameronbritt What browser are you using? I see the close button and clicking outside of the tour dialog also ends the tour.

**Comment by spadgett** [comment]
@jeff-phillips-18 Seems to happen when running in the console. This is Chrome.

![screen shot 2017-09-18 at 9 19 17 am](https://user-images.githubusercontent.com/1167259/30543850-89183af6-9c52-11e7-8d64-7f45a83bbb43.png)

**Comment by jeff-phillips-18** [comment]
I am running in console via chrome as well:

![image](https://user-images.githubusercontent.com/11633780/30544033-261c4450-9c53-11e7-9b17-46a34f24ab65.png)

**Comment by spadgett** [comment]
@jeff-phillips-18 Doesn't seem to happen in a development environment. Try against your cluster up console

**Comment by jeff-phillips-18** [comment]
Yeah, looks like the way hopscotch is including the background image for the close button :(

**Comment by spadgett** [comment]
Maybe we can override the styles to use a font icon.

cc @rhamilto @sg00dwin

**Comment by ncameronbritt** [comment]
A little later here, but I'm using Chrome. And I did find that I could close it by clicking where the X should appear.
