### ISSUE TITLE
Add to Application dialog cut off at some screen heights

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2095]
![screen shot 2017-09-16 at 10 41 02 am](https://user-images.githubusercontent.com/1167259/30513109-ab0fc5b2-9acb-11e7-9980-e7e58bdeaf38.png)

**Comment by spadgett** [comment]
Ignore the "object object" text in the screenshot. I had some local changes causing that.

**Comment by jeff-phillips-18** [comment]
@spadgett Are you working on this or shall I take it?

**Comment by spadgett** [comment]
I'm not working on it. I was thinking it would be good to have some general styles for these dialogs since I suspect we'll be using them a lot going forward.

cc @rhamilto who's looking at the overlay styles for https://trello.com/c/6zsvyyYu

**Comment by rhamilto** [comment]
Since Bootstrap/PatternFly modals already account for this situation, it seems like we should be using one of those instead of a custom solution.  Yea/nay?

**Comment by sg00dwin** [comment]
yea

**Comment by rhamilto** [comment]
> Since Bootstrap/PatternFly modals already account for this situation, it seems like we should be using one of those instead of a custom solution. Yea/nay?

@spadgett, @jeff-phillips-18, @cdcabrera

**Comment by jeff-phillips-18** [comment]
OK by me.

**Comment by cdcabrera** [comment]
+ 1 on a standard solution

**Comment by rhamilto** [comment]
@jeff-phillips-18, since you wrote the directive and are already familiar, do you want to migrate it to ModalsService?

**Comment by jeff-phillips-18** [comment]
@rhamilto sure thing.

**Comment by spadgett** [comment]
Fix should not be in origin-web-console
