### ISSUE TITLE
server.crt & server.key - documented ?

### ISSUE THREAD

**Issue by cmoulliard** [openshift/origin-web-console#21]
Hi,

Is it documented somewhere how you have generated (openssl, keytool, ...) your server.crt & server.key containing the SSL Certificate ?

**Comment by spadgett** [comment]
We used openssl. Did you need to generate a different one?

**Comment by cmoulliard** [comment]
No. Can you document or give the openssl cmds used to generate the CA Certificate and its child please for the Openshfit Web Console ? We need such example when we have to integrate an IdentityProvider (= Keycloak) with OSE

**Comment by spadgett** [comment]
@cmoulliard server.crt and server.key in this repository are self-signed certificates used only for localhost development. Running in OpenShift, the web console uses a certificate signed with ca.crt and ca.key from the master config directory, although the certificate can be changed in the OpenShift master config. You might find the `oadm ca` command helpful.

I would talk to @liggitt if you want to integrate a new identity provider.

**Comment by jwforres** [comment]
Any questions around certs and identity providers should go to the origin repo and tag @liggitt 

Closing this one based on age
