### ISSUE TITLE
Quota Notifications: Resetting/Restoring  "Don't Show Me Again" notifications

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-console#2122]
In the Notification Drawer for a quota warning a user may select "Don't Show Me Again" kabob menu option. This will permanently hide the quota warning for the project.    
We should be able to reset/restore the quota warning/notification if the quota/limit changes. I.e. if I purchase additional capacity, I should get notifications if I reach/exceed the new quota.

Probably need to add to [common/notificationService](https://github.com/openshift/origin-web-common/blob/master/src/ui-services/notificationsService.js):
```
var restorePermanentlyHiddenNotification = function (notificationID, namespace) {
     var key = notificationHiddenKey(notificationID, namespace);
     localStorage.removeItem(key);
};
```
Then figure out when to call the restore function from the console.

**Comment by jwforres** [comment]
Is this issue specifically for automatically resetting quota warnings? I believe we already have an issue for the user manually doing resetting them.

**Comment by dtaylor113** [comment]
> Is this issue specifically for automatically resetting quota warnings?

Yes, for automatically resetting quota warnings when limits or resources change.

**Comment by spadgett** [comment]
This is essentially the same as https://bugzilla.redhat.com/show_bug.cgi?id=1495427

I'm going to close this issue so we're not tracking it twice.

/close
