### ISSUE TITLE
Quota Notifications: Toast when user takes action which reaches quota

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-console#2124]
If the user takes an action that brings her to the quota, she should see a toast notification.  Not clear how to trigger/implement this.  What are all the entry-points/actions which may bring a user to quota?  Is there a way to watch for quota limits just reached?

**Comment by spadgett** [comment]
We need to determine if this is practical to implement.

cc @ncameronbritt

**Comment by spadgett** [comment]
I'm closing this as not practical to implement. It's expensive to watch quota. There are so many actions that can cause this in the UI, and I want to be careful about how much logic we duplicate around quota on the client generally.

/close
