### ISSUE TITLE
Provisioned service details page should include the service instance

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2128]
The service instance should appear next to the display name (where the timestamp is now).
![screen shot 2017-09-20 at 5 10 24 pm](https://user-images.githubusercontent.com/8974593/30667777-ad426eb2-9e26-11e7-9fd1-d34e440cdfa3.png)

See the documentation:
https://github.com/openshift/openshift-origin-design/blob/master/web-console/3-project-details/provisioned-service-details.md#details-page

**Comment by spadgett** [comment]
We should probably show the instance name in this table, too.

![openshift web console 2017-09-21 15-47-51](https://user-images.githubusercontent.com/1167259/30715425-50e24c1e-9ee4-11e7-830f-899abac8fc89.png)

**Comment by ncameronbritt** [comment]
Yep, good catch. That's also shown in the very top of that design doc.
