### ISSUE TITLE
Consider allowing upload of source code from the web console

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [openshift/origin-web-console#2171]
With the web file api https://developer.mozilla.org/en-US/docs/Web/API/File it is possible to upload files and interact with them using javascript. With https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory it is possible to upload entire directory and files in them. However this is a non standard feature and is not on a standards track, so yeah..................

**Comment by jwforres** [comment]
We were missing the card in trello for tracking this, added https://trello.com/c/4q908I64

We would probably only consider single file upload.
