### ISSUE TITLE
Could we add the sorting support for displaying tables

### ISSUE THREAD

**Issue by linzhaoming** [openshift/origin-web-console#2177]
The displaying tables in the web console doesn't provide the sorting support.  

There could be many data in the table. The sorting could help me to find my concernt easylly

<img width="1225" alt="2017-09-27 18 09 04" src="https://user-images.githubusercontent.com/1192635/30908253-a703a842-a342-11e7-8c63-54350a5e6f75.png">

**Comment by jwforres** [comment]
This is being tracked in trello https://trello.com/c/f6tBGkpM
