### ISSUE TITLE
Clarify call to action on image stream tags

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#2180]
Initially it doesn't seem like the table rows are clickable entities.  It may be because it is inconsistent with our other tables (I believe this is an external component).  I'd like to see some of the text linked within the row to help communicate that clicking here will bring the user to view another resource.

![screen shot 2017-09-27 at 3 26 39 pm](https://user-images.githubusercontent.com/280512/30933345-549d7c44-a398-11e7-9630-df51da91d026.png)

For comparison, our other tables:

![screen shot 2017-09-27 at 3 29 14 pm](https://user-images.githubusercontent.com/280512/30933488-b0c2469e-a398-11e7-92a6-3187694273a8.png)

**Comment by benjaminapetersen** [comment]
@spadgett 

@rhamilto @sg00dwin

**Comment by rhamilto** [comment]
The [hover color for list-pf is changing to blue](https://github.com/patternfly/patternfly/pull/798#issuecomment-338302210), which will align with what image streams are doing.  And we removed table-hover from all our non-clickable tables.  So we're a bit more consistent now with what blue hover means.  :)

**Comment by benjaminapetersen** [comment]
Yeah, hover colors help... I'd just like to see a link or a button.
