### ISSUE TITLE
EnvFrom in the Env Editors Interface Issues 

### ISSUE THREAD

**Issue by cdcabrera** [openshift/origin-web-console#2182]
EnvFrom
- [x] The drag and drop handle associated with updating the sequence order of EnvFrom values doesn't remain hidden when there is a single entry
- [x] Missing link for viewing Config Maps and Secret details. It would be helpful to see these details at the time of adding these bulk additions.
- [x] Minor copy revisit
- [x] Minor CSS color highlight and contrast issue on disabled selected values. The color needs adjustment, either the copy or the background... or both.
- Prefixes for EnvFrom values, see issue #2362 

EnvFrom & Variables 
- [x] Random refresh issue where a background process appears to run and reset some of the drop-downs causing them to collapse even though the user has them open
  - This refresh goes towards a larger issue around how watches on the parent view are providing updates, which also happens to affect the setting of individual environment values.
- [x] On saving, dependent on background processes, there appears to be a random flash of a hidden form. This also appears to happen when saving environment variables.

**Comment by cdcabrera** [comment]
@sg00dwin 

As discussed the initial fix around removing the ```disabled``` and ```active``` classes works.

However there appears to be a coincidental case when those 2 classes will still appear, still working on it from the JS side.

As a general heads up...

It's a case where a user has:
- selected the "first entry" in the Config Map and Secrets list, 
- then goes to add a second one
- the drop down list goes ahead and highlights the first entry which just so happens to be disabled (at least, that's how it's appearing on my local)

Attached a Gif
![oct-02-2017 11-30-01](https://user-images.githubusercontent.com/3761375/31086291-77e7248e-a767-11e7-90ba-38921cf9bc33.gif)

**Comment by cdcabrera** [comment]
@beanh66 @spadgett in process for completing some of the copy updates referenced around #2198 , wanted to make sure understood correctly about the sorting between Config Maps and Secrets. 

Right now we're seeing the opposite of what's referenced in the comments regarding the sort around the select lists. Trying to figure out if there are any other factors at play, if you could post a screen capture that would help out.

> [ ...noticed the links say "Config Map or Secret" but in the actual dropdown the secrets are listed first so we should be consistent... ]

The closest we could get to seeing something similar was when the select list displays at the bottom of the page:

![oct-03-2017 14-56-41](https://user-images.githubusercontent.com/3761375/31143695-147248a8-a84c-11e7-8864-01ee4b850124.gif)

**Comment by beanh66** [comment]
@cdcabrera Maybe I'm just running an old version! What you have looks great :)

**Comment by cdcabrera** [comment]
@beanh66 

Attached below for the reveal secret piece... 

![oct-20-2017 18-25-18](https://user-images.githubusercontent.com/3761375/31844044-58e18e6a-b5c4-11e7-822e-67ac32edceb5.gif)

@spadgett

**Comment by beanh66** [comment]
@cdcabrera Looks good, just feels like we may want a little more space between Value Details and Reveal Secret. Even just 5-10px would help. For cases where the revealed values are much longer, would those values wrap and the modal scroll as needed?

**Comment by jeff-phillips-18** [comment]
@beanh66 Shoul this look more like the config and bind parameters?

![image](https://user-images.githubusercontent.com/11633780/31890588-a6374330-b7d1-11e7-8750-437af3ccf2b7.png)

**Comment by jeff-phillips-18** [comment]
Really weird to me to have the hide/reveal action link in the title area. Shouldn't the title include the name of the secret rather than "Value Details" ?

**Comment by beanh66** [comment]
@jeff-phillips-18 Good point since it's a modal, that is kinda odd to have actions in the title bar. I don't think we need the secret name in the title bar but it actually would be more consistent to have the Reveal Secret link next to the secret name. @cdcabrera What about something like this: 
![screen shot 2017-10-23 at 9 34 45 am](https://user-images.githubusercontent.com/18057044/31891887-a7dd822c-b7d5-11e7-8166-33ee5524fbea.png)

**Comment by cdcabrera** [comment]
@beanh66 can move the Reveal Secret link no problem.

**Comment by beanh66** [comment]
@cdcabrera The link a user clicked to get this dialog would say "View Details," correct? @jeff-phillips-18 makes a good point about the "Value Details" not meaning much. Would it be possible to have the modal title be "Secret Details" if a secret and "Config Map Details" if a config map?

**Comment by beanh66** [comment]
![screen shot 2017-10-23 at 9 34 45 am](https://user-images.githubusercontent.com/18057044/31893286-32a81c2a-b7d9-11e7-9817-ba4200d9245c.png)

**Comment by cdcabrera** [comment]
@beanh66 funny you should mention the title changing @spadgett and myself talked about doing that, it is easily done. 

As for the navigation to get the modal to pop up... you are correct, it's the "View Details". Changing the reveal to something like "Reveal [Values]" does sound better to me.

**Comment by cdcabrera** [comment]
@beanh66 updated the code... can also apply a singular/plural context to "Reveal Value"/"Reveal Values" when only single entries happen.
  
![oct-23-2017 10-31-08](https://user-images.githubusercontent.com/3761375/31894776-594d38c0-b7dd-11e7-89b2-ae614d5a5d6e.gif)

**Comment by cdcabrera** [comment]
For the record... EnvFrom updates related to smaller screens, expanding out @sg00dwin 

<img width="426" alt="screen shot 2017-10-30 at 11 12 41 am" src="https://user-images.githubusercontent.com/3761375/32188180-799da6a0-bd7d-11e7-8904-3e38f7766285.png">

<img width="747" alt="screen shot 2017-10-30 at 11 15 00 am" src="https://user-images.githubusercontent.com/3761375/32188193-8541c2b6-bd7d-11e7-8e2f-7de7003b6cd7.png">

<img width="958" alt="screen shot 2017-10-30 at 11 15 11 am" src="https://user-images.githubusercontent.com/3761375/32188213-95744d8e-bd7d-11e7-9e12-c78a59674de1.png">

**Comment by beanh66** [comment]
@cdcabrera Why are there two ? icons once a user initiates an error? Wouldn't there just be a single field level help for the "Prefix" field?

**Comment by sg00dwin** [comment]
@beanh66 I'm doing some follow up changes from @jennyhaines, so I'll add the valid prefix message to the 'Prefix' label help tooltip and remove the second one so it will look like.

<img width="697" alt="screen shot 2017-10-30 at 3 19 59 pm" src="https://user-images.githubusercontent.com/1874151/32191139-64035fde-bd86-11e7-8bf2-30ae5139c10e.png">

**Comment by beanh66** [comment]
@sg00dwin perfect, thanks!

**Comment by spadgett** [comment]
The significant refresh issues have been fixed, and @jennyhaines' style recommendations have been implemented. Closing this issue since all of the concerns have been addressed
