### ISSUE TITLE
Look at consistency around the names of provisioned services and bindings

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2183]
We should look into being consistent around the names we use for provisioned services--sometimes we use the Service Class Display Name (e.g. in the catalog and the project overview), and in other cases we use the service instance name. Similarly, with bindings we have the binding resource and the secret.

**Comment by spadgett** [comment]
cc @rhamilto

**Comment by ncameronbritt** [comment]
For the binding wizard results we are currently showing the service instance name, and not the binding object name. The way the text reads, it would make sense to use the binding object.
![screen shot 2017-10-31 at 11 07 43 am](https://user-images.githubusercontent.com/8974593/32231661-8bf61a44-be2c-11e7-9438-a3b135a42ffd.png)
![screen shot 2017-10-31 at 11 13 49 am](https://user-images.githubusercontent.com/8974593/32231679-a0e50db6-be2c-11e7-8d20-df78bedc71a9.png)

**Comment by ncameronbritt** [comment]
In delete bindings, we list the secret, not the binding object. This behavior *may* make sense with pod presets. When you can be bound to an application or have a secret, it may help a user know which to delete (maybe?). So I'm not sure what to recommend there. Using the binding object would be consistent with what we're showing elsewhere, and with what we're describing the action as (i.e. "select binding to delete") for 3.7, but it may not be the most useful for 3.8 and beyond. @spadgett Think we should aim for consistency now and revisit this question once pod presets are back?
![screen shot 2017-10-31 at 11 15 08 am](https://user-images.githubusercontent.com/8974593/32231867-1b524afa-be2d-11e7-899f-3586c9952f0b.png)

**Comment by ncameronbritt** [comment]
Maybe with the above it's ok to use the binding object and just remove "secret" since that's the only type we can have in 3.7?

**Comment by spadgett** [comment]
+1, I'd just use the binding name here until we have pod presets back.

**Comment by ncameronbritt** [comment]
Also in the above screenshot, I'm not sure what "mongodb-persistent" is: It's neither the service instance name nor the service class display name. In general we privilege the Service Class display name in the UI, but maybe there's a case for using the service instance name. @spadgett

**Comment by ncameronbritt** [comment]
Fwiw, in the delete (deprovision) dialog we use the service instance name.
![screen shot 2017-10-31 at 11 26 28 am](https://user-images.githubusercontent.com/8974593/32232441-6c6e389e-be2e-11e7-9aaf-e7c1ade15510.png)

**Comment by ncameronbritt** [comment]
Binding as part of the provision flow names the service instance too, so that one should also be changed to use the binding object instead. 
![screen shot 2017-10-31 at 11 31 20 am](https://user-images.githubusercontent.com/8974593/32232859-6501219c-be2f-11e7-95eb-87096ecd669b.png)

**Comment by spadgett** [comment]
Yeah I don't have a strong opinion in most of these cases except one: I think we should continue to display the instance name in the service instance delete dialog so it's very clear which one you're deleting if you have more than one.

In most cases, I like showing the service class display name and using the instance name when needed to disambiguate (like we do on the overview).

**Comment by ncameronbritt** [comment]
That makes sense to me. The service class display name represents the thing you selected from the catalog, so I agree that it makes sense to use that except in cases where we want to be very clear (like deleting) or when the instance name is needed to disambiguate.

**Comment by rhamilto** [comment]
> Also in the above screenshot, I'm not sure what "mongodb-persistent" is: It's neither the service instance name nor the service class display name. In general we privilege the Service Class display name in the UI, but maybe there's a case for using the service instance name. @spadgett

Is coming from https://github.com/openshift/origin-web-console/blob/master/app/scripts/directives/unbindService.js#L90.  I'm unclear what this should change to.

**Comment by spadgett** [comment]
Yeah, it looks like we're not passing the service class to the filter, so it's not showing the service class display name:

https://github.com/openshift/origin-web-common/blob/master/src/filters/resources.js#L188
