### ISSUE TITLE
Test Flake: A Jasmine spec timed out. Resetting the WebDriver Control Flow.

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2200]
```
Running "protractor:default" (protractor) task
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://172.18.14.245:57776/wd/hub
Spec started
visiting url: create-project
visiting url: project/console-test-project-1506967814825/create
visiting url: project/console-test-project-1506967814825/browse/images
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
Protractor.get(https://localhost:9000/dev-console/project/console-test-project-1506967814825/browse/images) - reset url
```

**Comment by spadgett** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin_web_console/305

**Comment by spadgett** [comment]
Screenshot is just a loading screen:

![user adds a template to a project after creating a new project using the import yaml tab should process and create the objects in the template 6](https://user-images.githubusercontent.com/1167259/31092902-eb819f80-a77d-11e7-84a4-c4cccde95d92.png)

cc @benjaminapetersen

**Comment by benjaminapetersen** [comment]
Yeah I think in all this `e2e` stuff the dependencies aren't nailed down as well as we would like.  Selenium or webdriver versions seems to suddenly change and things get funny. :/

**Comment by spadgett** [comment]
> Selenium or webdriver versions seems to suddenly change and things get funny.

We probably should commit package-lock.json to avoid this stuff.

**Comment by benjaminapetersen** [comment]
Re: #2083

**Comment by spadgett** [comment]
Might be unrelated, but Firefox recently changed from 

52.3.0-2.el7_4 -> 52.4.0-1.el7_4

**Comment by spadgett** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin_web_console/304/
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_web_console/244/

It's failing on `Protractor.get`, but not every time. I wonder if we just need to bump the timeout.

**Comment by spadgett** [comment]
Timeout is only 3s. I can see the page taking longer than that to load. Since the tests take 20-30 minutes to run in Jenkins, we might want to bump this to something much higher.

> Error: Wait timed out after 3050ms

**Comment by benjaminapetersen** [comment]
I think its in here:

```bash
Spec started
visiting url: create-project
visiting url: project/console-test-project-1506965913119/create
visiting url: project/console-test-project-1506965913119/browse/images
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
Protractor.get(https://localhost:9000/dev-console/project/console-test-project-1506965913119/browse/images) - reset url
```

Tinkering locally, for some reason the click on "create" is no longer happening before the browser navigates to the next page (images).  So it never actually creates the resources, thus the tables are empty.

Thats the issue I've been working on the past 2 days locally, now its showing up in Travis.

**Comment by benjaminapetersen** [comment]
Here: https://github.com/openshift/origin-web-console/pull/2083/files#diff-74ba08d7a3f605db52c0916bda85d917R23

**Comment by spadgett** [comment]
`getPageTimeout` is set to 30s, so why is it timing out after 3s?

https://github.com/openshift/origin-web-console/blob/master/test/protractor.conf.js#L180

**Comment by benjaminapetersen** [comment]
I think its not waiting for anything, its just plowing through the rest of the tests and failing.  The `A Jasmine spec timed out. Resetting the WebDriver Control Flow.` doesn't quite seem to be truthful...

**Comment by spadgett** [comment]
Well we have `waitForUri`, but that's supposed to wait 5s. So where is 3s coming from?

https://github.com/openshift/origin-web-console/blob/9c144f35a308a00a12b1fcdde253cb740157f2bd/test/integration/helpers.js#L102-L106

https://github.com/openshift/origin-web-console/blob/9c144f35a308a00a12b1fcdde253cb740157f2bd/test/integration/helpers.js#L50-L59

**Comment by spadgett** [comment]
Testing an increase in the `waitForUri` timeout: #2203

**Comment by benjaminapetersen** [comment]
Nice, tinkering as well.

**Comment by benjaminapetersen** [comment]
My theory, I think its deeper. I don't believe it is timing out in the navigation, I think its timing out waiting for elements to be rendered to the page.  Since protractor is in sync w/Angular, it knowns when Angular is done (all promises resolved) for requesting the objects that never get created. So it is rendering empty tables, then the `element(by.cssContainingText())` never resolve to anything. 

However, your links above consistently timeout at `3050`, so thats weird.

**Comment by spadgett** [comment]
@benjaminapetersen I don't think you're wrong, but I think you're describing a different flake (#1685). This particular error consistently shows the white "Loading..." page in failure screenshots like discovery hasn't finished. I think it's just slow and timing out too soon.

I wonder if our pre-Angular bootstrap tasks are tripping Protractor up.

**Comment by spadgett** [comment]
https://github.com/angular/protractor/blob/1.7.0/docs/timeouts.md

**Comment by benjaminapetersen** [comment]
Oh that might be. I've read about custom bootstrapping causing problems.  Will see if I can dig up the reference.

**Comment by spadgett** [comment]
I'm pretty sure this was caused by the Firefox 52.3.0 -> 52.4.0 bump. Both the test and merge queues stopped working as soon as the installed Firefox package was updated. 52.4.0 is the latest ESR released a few days ago.

**Comment by spadgett** [comment]
Opened https://github.com/openshift/aos-cd-jobs/pull/704 to temporarily downgrade Firefox as a workaround

**Comment by benjaminapetersen** [comment]
Jenkins w/Firefox:

<img width="1222" alt="screen shot 2017-10-04 at 9 14 30 am" src="https://user-images.githubusercontent.com/280512/31194192-5d50e912-a914-11e7-8650-ed2e8a939196.png">

**Comment by spadgett** [comment]
Downgrading FF did not fix the tests :(

**Comment by spadgett** [comment]
Lowering severity as the tests are no longer flaking.

**Comment by benjaminapetersen** [comment]
Updating timeouts in PR #2083 here https://github.com/openshift/origin-web-console/pull/2083/files#diff-1a86c750617c5201796c35f6ba135f91R39
and here https://github.com/openshift/origin-web-console/pull/2083/files#diff-53424273570825c8ca0520f259622910R1

**Comment by spadgett** [comment]
This failure is no longer happening.

**Comment by ambicamahapatro** [comment]
Getting the error Jasmine spec timed out. Resetting the WebDriver Control Flow while executing the test suit but individually it runs fine. tried changing the protractor config defaultTimeoutInterval and changing the Jasmine framework to Jasmine from jasmine2. Still nothing works. can somebody plz help me
