### ISSUE TITLE
Button spacing on wizards is too tight

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2202]
@jhaines and @serenamarie125 noticed that the button spacing on the wizards doesn't follow PF's specs. 
![button_spacing](https://user-images.githubusercontent.com/8974593/31094762-41699938-a784-11e7-8da8-6efd3637a725.png)

**Comment by spadgett** [comment]
@jeff-phillips-18 FYI, looks like this is from angular-patternfly

<img width="1360" alt="screen shot 2017-10-02 at 3 17 27 pm" src="https://user-images.githubusercontent.com/1167259/31094930-e55d57b4-a784-11e7-8bc9-da224b06479e.png">

**Comment by jeff-phillips-18** [comment]
Patternfly's test page has 33px between Cancel and Back, and 8px between Back and Next

Angular Patternfly has 30px between Cancel and Back, and 5px between Back and Next

I don't see anywhere in the spec that specifies the correct spacing.

**Comment by rhamilto** [comment]
> Patternfly's test page has 33px between Cancel and Back, and 8px between Back and Next

The extra 3px to each is the result of display: inline-block on the buttons.

> Angular Patternfly has 30px between Cancel and Back, and 5px between Back and Next

This is correctly spacing as defined in CSS.

Markup differences between PatternFly and Angular PatternFly account for the differences in rendering between the two libraries (AP wraps the back and next buttons in a div, thus preventing the additional 3px).

Given this is an upstream bug, issues should be opened in PatternFly and Angular PatternFly to resolve.  @ncameronbritt, if this is still an issue, will you create those new issues and close this one?

**Comment by jeff-phillips-18** [comment]
Thanks for the analysis @rhamilto

**Comment by ncameronbritt** [comment]
Thanks @rhamilto closing this one.
