### ISSUE TITLE
Audit Upgrade of Phantom.js

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-web-console#221]
If we can upgrade `phantom.js` dependency, we can get rid of some of the flakiness in the install script.

x-ref: https://github.com/Medium/phantomjs/issues/572

**Comment by stevekuznetsov** [comment]
Seems like the changes should only be bug fixes.

**Comment by benjaminapetersen** [comment]
background info is that current version of PhantomJS is coming from Bitbucket, which has a rate limit on downloads.  They no longer use Bitbucket in newer versions, so if we can bump it up we can eliminate test flakes based on this issue.
