### ISSUE TITLE
Enhancements to next steps/results messaging

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#2217]
In https://github.com/openshift/origin-web-console/pull/2184, we didn't get to a few items and punted on them.  This issue is to track them so we tackle them in the near future.

- [ ] Display webhook info when appropriate inside wizard results (currently only shows on standalone next steps)
- [x] Show proper type of imported item in import wizard results (non-templates are generically called "YAML / JSON"). [sgoodwin] And resolve bug where `results-status-unknown` message displays instead of `results-status` success when importing [statefulset-hello.yaml](https://github.com/openshift-qe/v3-testfiles/blob/master/statefulset/statefulset-hello.yaml).
  <img width="411" alt="screen shot 2017-10-17 at 4 21 14 pm" src="https://user-images.githubusercontent.com/1874151/31687916-98c9c4c0-b358-11e7-99c0-61a40b0a3739.png">
- [x] Improve display of provision call failure message.  [Upstream message formatting improved](https://github.com/openshift/origin/pull/16663).
  <img width="921" alt="screen shot 2017-10-02 at 3 25 21 pm" src="https://user-images.githubusercontent.com/895728/31095252-31d10720-a786-11e7-9800-5d9614eed69f.PNG">
  <img width="604" alt="screen shot 2017-10-02 at 3 29 01 pm" src="https://user-images.githubusercontent.com/895728/31095336-828b0b20-a786-11e7-8423-e9c3c8979d00.PNG">
  <img width="910" alt="screen shot 2017-10-02 at 3 29 14 pm" src="https://user-images.githubusercontent.com/895728/31095349-8b910404-a786-11e7-8ba6-fc64e32177d1.PNG">
  ![screen shot 2017-10-03 at 11 27 16 am](https://user-images.githubusercontent.com/895728/31133544-d9f7c28e-a82d-11e7-9aef-c00752c68254.PNG)
- [ ] Add appropriate actions when failure occurs

**Comment by jhadvig** [comment]
The `Improve display of provision call failure message` item is blocked on https://github.com/kubernetes-incubator/service-catalog/issues/1435
@rhamilto @spadgett FYI

**Comment by spadgett** [comment]
I'm looking at the import YAML message now. We have a separate bug for it from QE:

https://bugzilla.redhat.com/show_bug.cgi?id=1505281
