### ISSUE TITLE
Should not be able to add the same secret or config map to an app twice

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2226]
It's doesn't make sense to add the same secret twice.

cc @cdcabrera

**Comment by jhadvig** [comment]
@spadgett do you mean the in the DC's Environment Variables section ? Or BC's Build Secrets section ?

**Comment by jhadvig** [comment]
@jeff-phillips-18 mind if I take this one ?

**Comment by jeff-phillips-18** [comment]
go for it @jhadvig

**Comment by spadgett** [comment]
@jhadvig I mean on the secret or config map page. There's an "Add to Application" button.

**Comment by jhadvig** [comment]
@spadgett what if the application contains two containers, where one of them already contains the secret/configMap... shouldn't we show the application if at least one of its containers doesn't contain the secret/configMap ?

**Comment by spadgett** [comment]
> shouldn't we show the application if at least one of its containers doesn't contain the secret/configMap ?

Good question. I think so.
