### ISSUE TITLE
PHP icon wrong in built binary

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2239]
The other icons are OK, but something is wrong with the PHP icon in the built openshift binary. It looks OK in a development environment.

![openshift web console 2017-10-10 08-22-17](https://user-images.githubusercontent.com/1167259/31386276-398a9cb0-ad94-11e7-8944-4c58712c50f0.png)

@jennyhaines FYI

**Comment by spadgett** [comment]
Reproducible with `grunt serve:dist`. I suspect a problem with our minifier.

**Comment by spadgett** [comment]
Updating grunt-svgmin fixes this.

**Comment by jennyhaines** [comment]
@spadgett @rhamilto - So this is resolved? If not, I can merge some vector paths and re-save the SVG.

**Comment by spadgett** [comment]
@jennyhaines This is resolved now. It was a problem with our builds.

I did notice that the PHP icon and the MySQL icon don't scale as well as some of the others, though. The PHP icon lettering doesn't look as clean at smaller sizes, and the MySQL one is hard to read. Not critical, but thought I'd mention it.

![openshift web console 2017-10-11 11-27-02](https://user-images.githubusercontent.com/1167259/31450343-2e00bf4e-ae77-11e7-9aa2-7b0dd8fab6d5.png)

**Comment by jennyhaines** [comment]
Hi @spadgett - I definitely see what you're saying! I just uploaded a new/optimized MySQL logo and PHP logo in that [Google Drive folder](https://drive.google.com/a/redhat.com/file/d/0Byx88a2G0Sw4b3lHR21kM0ZsUkU/view?usp=sharing). Thanks for pointing those out!
