### ISSUE TITLE
Edit build config page looks odd when there's no source repo

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#224]
It's a header with no content under it. This might not be uncommon for pipeline builds.

<img width="696" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/17122316/6440b59a-52a8-11e6-88e5-67b14838ceec.png">

@jwforres @jhadvig

**Comment by jhadvig** [comment]
@spadgett yeah I guess we can hide the "Source Configuration" header if the build strategy is `JenkinsPipelineBuildStrategy`
I can take a look on it if you dont mind.

**Comment by spadgett** [comment]
@jhadvig `JenkinsPipelineStrategy` builds can have source. I think we just need

```
ng-if="(build | buildStrategy).from"
```

 on the section?

**Comment by spadgett** [comment]
Sorry, I mean

```
ng=if="buildConfig.spec.source.type === 'None'"
```

**Comment by jhadvig** [comment]
@spadgett yep that should do it. Will update and send PR ASAP
