### ISSUE TITLE
Import YAML/JSON info page does not use SVG images

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#2242]
Presumably we want to swap the font icon for the SVG when importing?

<img width="907" alt="screen shot 2017-10-10 at 1 56 03 pm" src="https://user-images.githubusercontent.com/895728/31402132-12285d5e-adc3-11e7-8413-1ca248e1fcee.PNG">

**Comment by spadgett** [comment]
Yeah, missed this one :(
