### ISSUE TITLE
Other resources list empty for cluster admin

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#227]
I have created a project as "dev", and I can see a list of "other resources" I can use 

![image](https://cloud.githubusercontent.com/assets/78350/17135476/3a9cc336-5330-11e6-9fdc-bf1719d8d2c7.png)

If I log in as system:admin I can not see in the list of "other resources" any, even though I should be able to do everything.

![image](https://cloud.githubusercontent.com/assets/78350/17135521/7b99250a-5330-11e6-8c5b-a2b460c0afdf.png)

**Comment by spadgett** [comment]
@jorgemoralespou How are you logging in as cluster admin? I didn't think it was possible in the web console since it requires certificate auth.

/cc @liggitt @jhadvig

**Comment by jhadvig** [comment]
We are not displaying the resource list based on the permissions. Must be some other issue

**Comment by jorgemoralespou** [comment]
You can create a user and add it to system:admin group to be able to login.

````
oc adm policy add-cluster-role-to-user cluster-admin admin
````

**Comment by jhadvig** [comment]
I did just the same thing and I can see the whole list. Are there any other steps ?

**Comment by jorgemoralespou** [comment]
@jhadvig You're right, as this admin user can not see that dropdown in any project

**Comment by jorgemoralespou** [comment]
@jhadvig are you logged as admin user? Are you trying with the vendored ui in origin?

**Comment by jhadvig** [comment]
@jorgemoralespou yes on both questions. Created a cluster user and checked other resource list. It was there.
Weird :-/

**Comment by spadgett** [comment]
@jorgemoralespou Can you check the javascript console and dev tools network tab in your browser to see if there's an error somewhere? View -> Developer -> Developer Tools in Chrome.

**Comment by spadgett** [comment]
Nevermind, I can reproduce.

**Comment by spadgett** [comment]
@jhadvig It looks like we're not handling `rules['*/*']` in `AuthorizationService`?

<img width="215" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/17137312/926c92ee-5308-11e6-991e-dc07f1363566.png">

**Comment by spadgett** [comment]
> We are not displaying the resource list based on the permissions.

We do check.

https://github.com/spadgett/origin-web-console/blob/4ebe815d6c08b3fd86df29d4336e0f8ebf6d5d6a/app/scripts/controllers/otherResources.js#L53

**Comment by spadgett** [comment]
Making a P1 since it impacts other pages, too.
