### ISSUE TITLE
Environment variable editor should have column headings

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#228]
While in a BuildConfig Environment edition, I've found the new editor confusing as there's no names for the columns (may seem obvious they are key and value) but it's not.

![image](https://cloud.githubusercontent.com/assets/78350/17135817/f069f1a6-5331-11e6-9b31-38fd1e9a1ccc.png)

**Comment by spadgett** [comment]
@jwforres should we add an area/usability label?

**Comment by jwforres** [comment]
@spadgett sure i'll add it

**Comment by benjaminapetersen** [comment]
@rhamilto @ajacobs21e pulling you in for some additional opinion per our morning discussion.

**Comment by ajacobs21e** [comment]
@benjaminapetersen can you post a screenshot of what it looks like after clicking save? (aka not in edit mode)


Would it be an option to put the empty row (with the help text labels) at the top of the list?

**Comment by ajacobs21e** [comment]
Like this:
![screen shot 2016-07-26 at 2 28 57 pm](https://cloud.githubusercontent.com/assets/6415742/17150407/55e32cc2-533d-11e6-9a99-eacc0a779c61.png)

which would also be consistent.

**Comment by benjaminapetersen** [comment]
@ajacobs21e there is no longer an exit mode & normal mode.  "Save" will persist what you add but doesn't change the editor at all (you'll get an alert "success!" if it saves as it should).

**Comment by benjaminapetersen** [comment]
@ajacobs21e  ping!

**Comment by ajacobs21e** [comment]
@benjaminapetersen is it an option to match the labels section - like in the screenshot I added?

**Comment by benjaminapetersen** [comment]
An empty row of inputs that you cannot edit?  (readonly)

**Comment by spadgett** [comment]
Any reason not to use `label` elements?

**Comment by spadgett** [comment]
@ajacobs21e the label editor uses the same editor as env vars now, so it no longer looks like the screenshot you posted.

**Comment by ajacobs21e** [comment]
If the new row is now at the bottom for both and it's confusing which field is which then adding labels above each column would make sense. There's plenty of space to bump down the input fields and add a label row.
