### ISSUE TITLE
Getting started links need to be updated for OCP

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#2282]
The documentation link may be pointing to the wrong doc. We should decide which of the other links we want to be there.

The documentation link needs to be pulled from the openshift constants if its not already so that it correctly points to customized doc links, such as for Online.

**Comment by jwforres** [comment]
@sspeiche getting your input here on which links you want OOTB in OCP

**Comment by sspeiche** [comment]
These all look fine to me (after fixing the link for docs). There an issue with what is there?

**Comment by spadgett** [comment]
@jwforres The doc link looks like it's correct. We leave it set to `''` and the use `HELP_BASE_URL` to use the correct documentation link.

**Comment by jwforres** [comment]
@sspeiche i think the one i was most concerned with was pointing people to minishift for local development in an enterprise environment, since minishift is going to be using origin right?

**Comment by spadgett** [comment]
So I've verified that the documentation link is correct at least:

![screen shot 2017-10-17 at 3 38 07 pm](https://user-images.githubusercontent.com/1167259/31685572-6c23edb2-b351-11e7-99eb-1fcbfb8a679c.png)

**Comment by sspeiche** [comment]
@jwforres True, the link for CDK isn't great so maybe we could direct to https://developers.redhat.com/products/cdk/overview/ instead of littleshift?

Perhaps a top-level corporatey page like https://www.redhat.com/en/technologies/cloud-computing/openshift would work but I'd have to confirm the life of that URL
