### ISSUE TITLE
Vertical alignment is off for X on Clear All in notifications drawer

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#2286]
The vertical alignment of the X icon relative to the Clear All text seems off

![xbutton](https://user-images.githubusercontent.com/1467629/31682175-5527bc38-b347-11e7-8889-bee82f054603.png)

**Comment by rhamilto** [comment]
This is a bug in PatternFly and should be addressed upstream.  

Screenshot of https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/notification-drawer-vertical-nav.html
![screen shot 2017-10-17 at 3 02 21 pm](https://user-images.githubusercontent.com/895728/31683904-3812192c-b34c-11e7-868b-cdac714a9716.PNG)

**Comment by rhamilto** [comment]
Upstream PR to resolve: https://github.com/patternfly/patternfly/pull/783

**Comment by spadgett** [comment]
@rhamilto Is this fixed now that we bumped Patternfly?

**Comment by rhamilto** [comment]
> @rhamilto Is this fixed now that we bumped Patternfly?

Not yet.  Need a new PatternFly release that incorporates the change.
