### ISSUE TITLE
Incorrect mesage when trying to remove a project that is being deleted

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#229]
I deleted a project from command-line, and it was taking a while, since in the UI there was no indication that the project was being deleted, I tried to delete it again, and got an incorrect message:

![image](https://cloud.githubusercontent.com/assets/78350/17136450/b5b55a74-5335-11e6-822e-31d96e2c83d3.png)

**Comment by spadgett** [comment]
We're showing the error message from the API server. CC @deads2k @liggitt

**Comment by deads2k** [comment]
Sometimes deletion takes a while because namespace finalizers run.  Those finalizers remove the permissions that the project admin has to delete the project.

**Comment by deads2k** [comment]
Oh, was it a complaint about the weird phrasing?  I can see about making that a little more readable.

**Comment by jorgemoralespou** [comment]
@deads2k no, it wasn't a complain about that, and could understand the reasons.
@spadgett @jwforres Maybe there should an indication on projects that are being deleted in the project listing that the project is being deleted, or the icons "edit/delete" should be disabled to avoid this situation from the UI

**Comment by jorgemoralespou** [comment]
And if that's how it works (disabling the buttons when a project is marked for deletion), the watch does not work, as I could try to delete the project from the UI more than 5 seconds later deleting the project from CLI.

**Comment by spadgett** [comment]
Well I think we should fix the phrasing either way.

@jorgemoralespou The project should disappear from the list it's fully deleted. I'm not sure if we can detect an intermediate state. @deads2k ?

**Comment by deads2k** [comment]
> @jorgemoralespou The project should disappear from the list it's fully deleted. I'm not sure if we can detect an intermediate state. @deads2k ?

`Namespace.status.phase==Terminating`

**Comment by spadgett** [comment]
Hm, there should have been a warning icon if status.phase wasn't active.

https://github.com/spadgett/origin-web-console/blob/4ebe815d6c08b3fd86df29d4336e0f8ebf6d5d6a/app/views/projects.html#L24

I wonder if the watch failed.

**Comment by deads2k** [comment]
> I wonder if the watch failed.

I hate virtual resources so much.  Mind checking?

**Comment by jwforres** [comment]
@jorgemoralespou have you seen this again?

**Comment by jorgemoralespou** [comment]
@jwforres no
