### ISSUE TITLE
Navigation should be hidden immediately when switching to a page with no nav

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#2291]
If I go from my project to a page like About the left nav animates away and the about page content slides to the left.  That behavior is a little strange.

**Comment by beanh66** [comment]
@jwforres We have a design story to create an About Modal for OpenShift that follows the [PatternFly standards](http://www.patternfly.org/pattern-library/communication/about-modal/#/overview). In the meantime, wondering if we have this issue on other pages or just the about screen?

**Comment by jwforres** [comment]
@beanh66 yeah the Command Line Tools page which is accessible from that same ? dropdown

@spadgett are there any others left? The only ones we used to have were the full page forms which I assume are all now showing the left nav since they are all within a project.

**Comment by spadgett** [comment]
> are there any others left? 

Catalog landing page and the error page come to mind.
