### ISSUE TITLE
Click a left nav then hover another, first item should not stay selected

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#2292]
Click an item in the left nav that has a submenu, then hover over another item that has a submenu, you end up with something like this (clicked on Applications then hovered over Builds):

![screen shot 2017-10-17 at 4 36 34 pm](https://user-images.githubusercontent.com/1467629/31688129-62f58356-b359-11e7-8851-97fb37d7b7fc.png)

**Comment by jeff-phillips-18** [comment]
Clicking on Applications is a no-op. The display is still showing overview right?

**Comment by jwforres** [comment]
Right, so Overview is still active, which is correct.  It makes sense for Applications to be highlighted when you clicked it, but if you then hover over a different menu it felt weird to have the active one, the one you clicked, and the one you are hovering over all be in the lighter gray state.

**Comment by jeff-phillips-18** [comment]
I'm not sure we want Applications to be highlighted on click since it is not active, I think that is the issue.

**Comment by spadgett** [comment]
Yeah, the highlighting is a bug introduced by our workaround to make the nav keyboard accessible.

**Comment by jwforres** [comment]
So its specifically caused by the style in _vertical-nav.less that adds the active color when the link is focused. Clicking it gives it focus and hovering on the other ones doesn't change that.

We could trigger the style based on the is-hover class we manually add instead of using focus, but there is a delay before that class is removed which looks a little weird.
