### ISSUE TITLE
Click on a read notification just leaves focus on the notification

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#2293]
Right now if you click on an already read notification it looks like this (see blue focus outlines):

![screen shot 2017-10-17 at 4 51 59 pm](https://user-images.githubusercontent.com/1467629/31688868-afa60d2c-b35b-11e7-822a-187691a9e571.png)

I question whether we should even still have a click handler on a read notification, clicking it does absolutely nothing.

**Comment by jwforres** [comment]
@openshift/team-ux-review

**Comment by beanh66** [comment]
@jeff-phillips-18 I don't think we have this issue in PatternFly, but curious if you have seen it? Typically if a row is already marked as read, we would not see the blue outline. @jwforres I agree it is unnecessary.

**Comment by jwforres** [comment]
Yeah @spadgett thought this was probably a bug in our special handling of click events in our impl of the drawer.  Once its been marked as read I think we should remove the click handler and click target (no longer show the hand when hovering).

**Comment by spadgett** [comment]
It's specific to OpenShift notifications:

https://github.com/openshift/origin-web-console/blob/master/app/views/directives/notifications/notification-body.html#L1-L4

cc @benjaminapetersen

**Comment by benjaminapetersen** [comment]
We can remove that handler pretty easily:

```
ng-click="notification.unread && $ctrl.customScope.markRead(notification)">
```
There is no longer a click, but that doesn't affect the styling.  Working on a solution.

**Comment by benjaminapetersen** [comment]
Looking @ this with @sg00dwin.  So the patternfly [demo](http://www.patternfly.org/angular-patternfly/#/api/patternfly.notification.component:pfNotificationDrawer) appears to be tinkering with the focus. If I manually trigger the "focus" attrib in the web inspector, I can achieve the same effect:

Angular Patternfly:
![screen shot 2017-10-18 at 11 50 05 am](https://user-images.githubusercontent.com/280512/31728629-cfbf8788-b3fa-11e7-8fa7-4c538a532de9.png)

Patternfly: 
![screen shot 2017-10-18 at 11 53 30 am](https://user-images.githubusercontent.com/280512/31728697-fe7bbfce-b3fa-11e7-8bb0-a78d72278d08.png)

So there is something happening in the demo CSS that is not inherited in the actual component that is causing the focus to be hidden or clipped.

**Comment by benjaminapetersen** [comment]
The cause is our `tabindex="0"`:

```
<div
  class="drawer-pf-notification-inner"
  tabindex="0"
  ng-click="notification.unread && $ctrl.customScope.markRead(notification)">
```

**Comment by spadgett** [comment]
I don't think what we have no is accessible anyway since there is no `ng-keydown`. The `tabindex` doesn't help. `ng-click` won't be triggered by the keyboard.

Better to have an `sr-only` button for accessibility and take `tabindex` off?

**Comment by benjaminapetersen** [comment]
Thats true, the `ng-click` does not fire when pressing "enter".

I can do:
```html
  <button
    class="sr-only"
    ng-click="notification.unread && $ctrl.customScope.markRead(notification)">
    Mark Read
  </button>
```
It eliminates the focus. Its a bit of a strange experience in that you can tab to this button, but since it is hidden you don't get any visual feedback.

**Comment by spadgett** [comment]
> Its a bit of a strange experience in that you can tab to this button, but since it is hidden you don't get any visual feedback.

Maybe add `sr-only-focusable` and make it a link?

https://getbootstrap.com/docs/3.3/css/#helper-classes-screen-readers

**Comment by benjaminapetersen** [comment]
Ooo didn't know that one exists.  Gave it a swing and I get this (even after the change to a link, just did the gif as a button):

![2017-10-18 22 09 05](https://user-images.githubusercontent.com/280512/31750997-3b6745ba-b451-11e7-9f1d-90e350e800ad.gif)

Tinkering with this some more, I'll [WIP] the PR for now.

**Comment by spadgett** [comment]
Yeah we probably want to put it at the bottom of the notification content with good margins since it will be visible when focused.

**Comment by jwforres** [comment]
We still have a bug here that the hover still makes it look clickable even after the notification is read, the cursor needs to change to a pointer.

**Comment by jwforres** [comment]
The current behavior is what UXD is asking for, so closing. We can address any remaining concerns upstream in patternfly.
