### ISSUE TITLE
Pod initializing has no status icon

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#2295]
the PodInitializing state has no icon, now that builds use init containers this state is going to be very common in the console

![screen shot 2017-10-17 at 5 13 46 pm](https://user-images.githubusercontent.com/1467629/31689819-ab4a706c-b35e-11e7-93dd-c20c04a1bec2.png)

@openshift/team-ux-review

**Comment by beanh66** [comment]
@jwforres Is this similar to anything we already have? Not sure if in progress or building/ running icons would fit.

**Comment by jwforres** [comment]
@beanh66 the running icon wouldn't be completely inaccurate, it is running containers at that point, its just not running the "main" container(s) yet

@spadgett thoughts?

**Comment by spadgett** [comment]
I was thinking the pending icon, but I'm OK with running, too.

**Comment by jwforres** [comment]
so it looks like the pod is in Pending when the init containers are running

**Comment by beanh66** [comment]
Good point, the pending icon might make a lot of sense @spadgett! I forget if that is a new one @jennyhaines created or if OpenShift already has that icon elsewhere?

**Comment by jennyhaines** [comment]
Yes, I think the pending icon would work nicely. That was an icon I added recently. 
<img width="176" alt="pending" src="https://user-images.githubusercontent.com/24898297/31735990-73f7a5e0-b411-11e7-8e50-07e1e2bbd35e.png"> 
I do not remember seeing it used anywhere in OpenShift thus far.

Sidenote: I would not recommend using the "in progress" PF icon... in the latest icon user testing, it had unfavorable results, and I'll likely need to change it.

**Comment by jwforres** [comment]
@beanh66 @jennyhaines wdyt?

![podinit](https://user-images.githubusercontent.com/1467629/31737011-49099192-b414-11e7-9f90-8ec0da0811af.png)

**Comment by jennyhaines** [comment]
I really like it! @jwforres

**Comment by jeff-phillips-18** [comment]
Your eyes must be better than mine, I can't tell what that is, lol.

**Comment by jwforres** [comment]
I agree its a little hard to tell that its an hourglass icon at that font size :-\

so the one we use today for the "Pending" state in openshift is different, whichever one we use it should probably be the same one in both cases

This is what that one looks like:

![2017-10-18 15 30 26](https://user-images.githubusercontent.com/1467629/31738705-89694912-b419-11e7-89cc-f32db85aa701.gif)

**Comment by jwforres** [comment]
@jennyhaines @jeff-phillips-18 since we aren't using the matching patternfly icons in this context *yet* - until we do the font-awesome hourglass icon matches better since it doesn't have the surrounding circle

![initializing](https://user-images.githubusercontent.com/1467629/31772675-73c3b03a-b4ae-11e7-9d0a-cf75dd0fd1de.png)

Its also more clear at this font size that it is an hourglass.  I worry long term about the patternfly icons not being clear enough unless we increase the font size :(

**Comment by jennyhaines** [comment]
@jwforres - That is a good point. I'll make a note to take another look at our pending icon being freed of it's circle so it can be a little more clear at 14px! I will have to make some changes later on to another status icon, anyway, based on user testing. I think this font-awesome solution works for now.

**Comment by beanh66** [comment]
@jwforres Agreed, hour glass without the circle looks good here
