### ISSUE TITLE
We should block users from adding to project when we know it will fail.

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2297]
We should check for duplicate names BEFORE trying to add to a project to prevent errors, and to avoid a situation where the user has to clean up from a partial success, which can be very difficult in some cases.
![screen shot 2017-10-18 at 9 36 09 am](https://user-images.githubusercontent.com/8974593/31721635-ded5b7dc-b3e7-11e7-8d20-c4133a0fe419.png)
![screen shot 2017-10-18 at 9 38 51 am](https://user-images.githubusercontent.com/8974593/31721842-770afaee-b3e8-11e7-8e98-5271daa83c78.png)

**Comment by spadgett** [comment]
I'm not sure we can since we don't know what objects will be created. The broker handles that.

The template broker could check, but by that point, you already have the service instance object. So you're in the same spot with a failed instance.

In this case, cleanup should be deleting the instance and everything else is garbage collected.

cc @bparees @jwforres

**Comment by bparees** [comment]
+1 @spadgett

**Comment by jwforres** [comment]
Agreed we can't check this ahead of time.  But I'm wondering if we should be doing something in the creation dialog to let them go ahead and delete the instance when we see provisioning failed, instead of them finding it later on in their project. Unlike the old template processing, there is nothing obvious in this dialog that tells me that there were still objects created.

**Comment by spadgett** [comment]
Yeah I agree with letting users delete the instance directly from the results step. We have an open issue to add better failure actions (#2217). This might be something easy we can do to make it a little better.

**Comment by ncameronbritt** [comment]
This situation isn't limited to creating things through the catalog. And (I think) everyone agrees that the experience around this is not good. With the old template processing you see what's created, true, but you still have to go back and delete everything that was created successfully, and we don't make it explicit that that's what you should do (either that or delete your project and start over).

I knew Robb had adding the ability to delete from the results page on his list of to-dos, and adding that delete action is part of the [design](https://github.com/openshift/openshift-origin-design/blob/master/web-console/patterns/wizard-results.md#implementation-details). But I think it could be argued that preventing what seems like it ought to be a preventable error is preferable to making a mess and then having the user clean it up, even if we make that clean-up process easier.

**Comment by jhadvig** [comment]
+1 for having the ability to delete the instance in the failed result step. But shouldn't we also have this option in when creating a app not via the service catalog ?

![dalete](https://user-images.githubusercontent.com/1668218/31893477-ea928d70-b80b-11e7-9aa6-9964466b0ead.png)

**Comment by jwforres** [comment]
In theory we could actually do this now that GC is working.  We know
exactly what we created so we should be able to delete it, its definitely
more work though than just deleting the single service instance object.
There is a card for this in trello already https://trello.com/c/sV2UFxmK
 it says "template" but it really applies to new app as well.

We have a separate issue that we need to add the existence checks to the
new-app flow in the catalog.  The full-page new-app flow already attempts
to prevent naming conflicts.

**Comment by spadgett** [comment]
@dtaylor113 Has this since been fixed?

**Comment by spadgett** [comment]
I've verified this is fixed now.

![openshift web console 2018-02-13 15-35-42](https://user-images.githubusercontent.com/1167259/36172356-9dd2e8e2-10d3-11e8-92b3-087788154bef.png)

/close
