### ISSUE TITLE
No build logs/events for cluster-admin

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#230]
I have created a project as dev user and started a build.

I have a cluster-admin user:

````
oc adm policy add-cluster-role-to-user cluster-admin admin
````

As admin user I can not see the logs:

![image](https://cloud.githubusercontent.com/assets/78350/17137336/fb13b732-533a-11e6-8683-675414c8095d.png)

As dev user I can see the logs:

![image](https://cloud.githubusercontent.com/assets/78350/17137360/18311418-533b-11e6-9df1-9dfbdbd157f4.png)

Both should have privileges to see the logs.

**Comment by spadgett** [comment]
Same underlying issue as #227.

**Comment by spadgett** [comment]
See https://github.com/openshift/origin-web-console/issues/227#issuecomment-235249525 for the cause.
