### ISSUE TITLE
Marking all notifications can resurrect a cleared notification

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#2302]
Steps to reproduce:

- Open the notification drawer with a set of notifications
- Clear via the "x" a notification 
- Click "mark all read" at the bottom of the drawer 

All notifications currently in view are marked read, notifications previously cleared will suddenly become visible & will not be marked read.

**Comment by benjaminapetersen** [comment]
@jwforres @spadgett

**Comment by spadgett** [comment]
Fixed by #2346
