### ISSUE TITLE
Remove `service.alpha.openshift.io/dependencies` recommendation from templates doc

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2319]
https://docs.openshift.org/latest/dev_guide/templates.html#other-recommendations

The `service.alpha.openshift.io/dependencies` is no longer used by the web console overview.

**Comment by commandtab** [comment]
Sorry to resurrect this issue, but is there now no way to combine related services as displayed in the web UI? My once concise project views are now quite long.

Thanks ❤️

**Comment by spadgett** [comment]
The way to group resources is to give them the same `app` label, and they'll show up together in the "List By: Application" view.  If the "Application" headers are taking up too much space, you might try "List By: Resource Type" as well.
