### ISSUE TITLE
Config map keys should be top-aligned in details table 

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2320]
The keys are vertically center aligned in the table cell. When the config map has a large value that's expanded, the key is pushed off the screen. Also the width of the key column is sometimes small, causing the key name to wrap when the table could give it more width.

<img width="1240" alt="screen shot 2017-10-19 at 5 51 08 pm" src="https://user-images.githubusercontent.com/1167259/31796119-4e2811fc-b4f6-11e7-84ff-b095886d42cd.png">

<img width="1240" alt="screen shot 2017-10-19 at 5 51 12 pm" src="https://user-images.githubusercontent.com/1167259/31796124-5241ea7e-b4f6-11e7-9223-1a8d6699735f.png">

![openshift web console 2017-10-19 17-53-42](https://user-images.githubusercontent.com/1167259/31796166-76d9b4b6-b4f6-11e7-8687-1567078107ff.png)

**Comment by rhamilto** [comment]
We have this same issue with annotations.  And probably anywhere truncate-long-text is in use in a td.  I will fix all.

![screen shot 2017-10-20 at 11 20 08 am](https://user-images.githubusercontent.com/895728/31828582-aa20deca-b588-11e7-967c-30bdffb66081.PNG)
