### ISSUE TITLE
Overview bind parameters look odd

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2323]
The bind parameters are displayed on the overview now. I think this might be unintentional, but it's odd to show bind parameters and not instance parameters. I'd vote just to remove them.

If we keep them, the spacing looks wrong.

![screen shot 2017-10-20 at 8 51 17 am](https://user-images.githubusercontent.com/1167259/31821680-ef40e1cc-b573-11e7-889d-9f5668e478c5.png)

@jwforres @jeff-phillips-18 FYI

**Comment by spadgett** [comment]
Similar spacing problems on the provisioned service page:

![screen shot 2017-10-20 at 8 58 44 am](https://user-images.githubusercontent.com/1167259/31821968-e98c0652-b574-11e7-8c99-2e5effdf809f.png)

**Comment by jeff-phillips-18** [comment]
Fixed by #2326
