### ISSUE TITLE
Users with cluster-reader should not see "Add to Project" dropdown

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2329]
The users will not actually be able to create anything, but the dropdown should not be visible.

![openshift web console 2017-10-20 12-27-22](https://user-images.githubusercontent.com/1167259/31831591-0938ac5e-b592-11e7-806e-8f706f87d721.png)

**Comment by jwforres** [comment]
we weren't handling tokenreviews, podsecuritypolicyreviews, and podsecuritypolicyselfsubjectreviews in our list of review types to ignore for our can add to project check.  A user with project View doesn't have these.

**Comment by jhadvig** [comment]
Tested the change and the issue has been solved. If no other changes are required will close this issue.
@spadgett @jwforres fyi

**Comment by spadgett** [comment]
The only reason we might wait to close is that the change hasn't been merged to origin-web-console, but I'm OK closing, too. @jhadvig thanks for verifying the fix.

**Comment by jhadvig** [comment]
Ohh, sorry for that. Will know for next time :)

**Comment by jwforres** [comment]
Yep what @spadgett said :)
