### ISSUE TITLE
Change display of !isIncompleteBuilds on overview

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#233]
- [x] persist the latest !isIncompleteBuild pipeline and triggered builds on the overview (currently, all builds less than 5 minutes old appear)
- [x] make the persisted !isIncompleteBuild pipeline builds dismissible on the overview

For number 1, [change the filter being applied to the list of builds](https://github.com/openshift/origin-web-console/blob/master/app/scripts/controllers/overview.js#L320)?

Reuse the [existing triggers directive](https://github.com/openshift/origin-web-console/blob/master/app/scripts/directives/resources.js#L81) for number 2?

**Comment by rhamilto** [comment]
https://github.com/spadgett/origin-web-console/blob/114c7420beec32fd0e0f810af8a42c26ae30b7cd/app/scripts/controllers/pipelines.js#L64 is how Sam solved number 1 on the pipelines page.

**Comment by rhamilto** [comment]
Broken first attempt at number 1 at https://github.com/rhamilto/origin-web-console/commit/effaee723c725ac74bac69cd7abf2a607514a5f1

**Comment by benjaminapetersen** [comment]
Cool, I can pick up that filter and tinker with it some more.
