### ISSUE TITLE
Default instance parameter values are shown to project viewers as if they were real

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2331]
If you log into a project with a provisioned service as a viewer, the "reveal" parameters link is visible. Since you can't get secrets, you can't see the actual values. However, we show the default values in the list as if they were the actual values. We shouldn't show defaults for users who can't get secrets.

Related to #2317, but opening a separate bug to make sure we address this specifically.

**Comment by jeff-phillips-18** [comment]
Fixed by https://github.com/openshift/origin-web-console/pull/2355
