### ISSUE TITLE
how can i skip auth on webconsole

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin-web-console#2348]
i'm doing `oc proxy` which already exposes api on my host without oauth.
how can disable auth on origin-web-console?

**Comment by jwforres** [comment]
The console requires you to be logged in as a user, its always going to redirect to the oauth server if it doesn't find a token in LocalStorage.

**Comment by debianmaster** [comment]
thanks @jwforres  i will try with hard coding LocalStorage token
