### ISSUE TITLE
Unable to update APB

### ISSUE THREAD

**Issue by jmontleon** [openshift/origin-web-console#2349]
I am trying to update an APB via the web console. I tried updating postgresql_version from 9.4 to 9.5 in the UI and I see from the broker:

```
[2017-10-23T17:52:10.085Z] [ERROR] Tried to update non-updatable parameter, postgresql_database, on instance 89e306f9-47db-490d-97a2-756515511428.
```

I/we were expecting to just see updatable parameters in the request. If we should handle other parameters being sent we can make changes, otherwise maybe we're getting more than we should. Let me know how you'd like to handle it.

**Comment by spadgett** [comment]
The console shouldn't be sending values not in the update schema.

**Comment by spadgett** [comment]
Thinking about this more, I'm not sure what's right. If I `oc edit serviceinstance my-instance` to edit parameters, do I need to manually delete any param not in the update schema?

@pmorie

**Comment by jeff-phillips-18** [comment]
There may be other parameters being sent, but the values should not have changed. Do you know if they are changed or if it is a problem even sending them? Basically, we are creating a new secret with all the secret's parameters if one of the secret's parameters changes. So, we are updating the instance to use a new secret which could contain only one changed value.

**Comment by jmontleon** [comment]
Right now we error out if non-updatable parameters are sent. We could try to do something where we ignore them or ignore them if the values are not updated.

**Comment by spadgett** [comment]
It looks like service catalog only tries to send parameters that have changed to the broker:

https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_instance.go#L821-L825

I'm not sure how this works with a secretKeyRef, however, where the parameters are stored in a JSON blob.

@pmorie If we update the secret in place rather than creating a new secret, will the catalog only send the values that have changed?

**Comment by jmontleon** [comment]
I talked to @jmrodri and the feeling is that we should handle non-updatable/non-existent parameters smartly, but not reject the request. I don't think this is a hard change for us. If you guys agree I already have a PR more or less ready for ASB.

**Comment by spadgett** [comment]
@jmontleon It's probably a good idea, but I also don't think we should send parameters that don't validate against the update schema. It might be a problem for other brokers even if we change ASB.

**Comment by spadgett** [comment]
ASB has been updated to ignore extra parameters.

We are tracking the larger problem in an upstream issue: https://github.com/kubernetes-incubator/service-catalog/issues/1488
