### ISSUE TITLE
Overview is missing Container status info

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#236]
When I create an application from the web UI (add to project) I'll be redirected to the overview page. There, there is no indication of what's happening in the background, so I don't see if the image is being pulled down or the container is being created, or anything else. 
As a user/developer I want to see in the overview the states the pod is going through. 

cc/ @marekjelen

**Comment by spadgett** [comment]
> There, there is no indication of what's happening in the background, so I don't see if the image is being pulled down or the container is being created, or anything else. 

The donut shows different colors for the pod status with hover text. If it's pulling, you can hover and see "Pulling."

We're adding a monitoring page that might be more in line with what you want from the overview with an events sidebar, logs, and status for deployments, pods, and builds.

**Comment by jorgemoralespou** [comment]
@spadgett There's some things for which I think hover is enough, things like details on the pod, but to be honest, I don't think this is the case.
An overview is a dashboard where I see my application. After doing a new deployment, the first screen I'll see is this one, and there's some indications needed until at least I have my application deployed, otherwise I'll need to navigate away, or even move the mouse (If I'm smart enough to guess that behaviour).

This is something really required for developers. I've seen/heard so many complains about visual indication on Overview of what's happening doing demos/workshops.

cc/ @thesteve0 Do you have something to add?
