### ISSUE TITLE
Need to handle envFrom prefix

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2362]
Our environment from implementation does not handle the `prefix`. We need to make sure we're not dropping values with different prefixes minimally, but we should also let users see and change the prefix values.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L1698-L1700

**Comment by spadgett** [comment]
@jwforres @cdcabrera FYI

**Comment by spadgett** [comment]
@beanh66

**Comment by cdcabrera** [comment]
@spadgett @beanh66 Initial work, design input requested... 

Implemented a quick fix layout wise to get the code working, realize it's not pretty but should allow for opening the discussion...

![screen shot 2017-10-25 at 1 27 22 pm](https://user-images.githubusercontent.com/3761375/32013294-a3bfecc0-b988-11e7-8543-18fd41337e1e.png)

and a quick animation...

![oct-25-2017 13-25-42](https://user-images.githubusercontent.com/3761375/32013361-de4dcb14-b988-11e7-8ed7-91e00196e1aa.gif)

**Comment by spadgett** [comment]
I was thinking of having the Prefix input always visible. If it's blank, no prefix is set. Something like

```
Config Map / Secret     Prefix

[Select resource... ]   ________________   <drag> <x> View Details
[Select resource... ]   ________________   <drag> <x> View Details
...
```

**Comment by beanh66** [comment]
@spadgett I like that suggestion. Wondering if we can at least add the field level help icon to the right of the "Prefix" label so users can hover to find out what a prefix is for. Do you have a blurb to define that input already?

**Comment by spadgett** [comment]
>  Wondering if we can at least add the field level help icon to the right of the "Prefix" label so users can hover to find out what a prefix is for.

Yeah, I think a tooltip makes sense.

> Do you have a blurb to define that input already?

Maybe

"Optional prefix added to each environment variable name for this resource."

?

**Comment by cdcabrera** [comment]
Updated towards the recommendation @spadgett @beanh66 

![screen shot 2017-10-25 at 5 06 37 pm](https://user-images.githubusercontent.com/3761375/32023337-f0359a64-b9a6-11e7-80d2-bd0cb6d034e2.png)

**Comment by beanh66** [comment]
@cdcabrera The new prefix stuff looks good to me!  

As an aside, the Environment From text looks oddly small to me. @jennyhaines I know we were trying to use that style consistently in font size 10, but it looks off in this context. Thoughts? (Note, this is a separate "Environment From" section, but the "Container node-ex" label still applies to both the top and bottom sections)

**Comment by jennyhaines** [comment]
@beanh66 @cdcabrera @spadgett - I see what you're saying about the oddly small "Environment From" text, Colleen. To ensure the right hierarchy between the larger "Container node-ex" grouping, and the "Environment From" subgrouping, I have some suggested changes, labeled in the attached photo. Thoughts? (Also, I wonder if there is better wording for "Environment From" group?)
![recommendation](https://user-images.githubusercontent.com/24898297/32062725-5e745c4e-ba43-11e7-8de1-ce68097c6339.png)

**Comment by spadgett** [comment]
cc @sg00dwin
