### ISSUE TITLE
Updating just the plan on an APB is not possible

### ISSUE THREAD

**Issue by jmontleon** [openshift/origin-web-console#2379]
When I try to move the postgresql apb from prod to dev without modifying any parameters the Next button is grayed out on the parameter page if I opt not to change any options.

**Comment by spadgett** [comment]
@jmontleon Do you know if you have this fix?

https://github.com/openshift/origin-web-catalog/pull/531

If you select the other plan, does the button enable? I suspect it's showing you the wrong plan as selected.

**Comment by jmontleon** [comment]
I think this is working now that I've updated.
