### ISSUE TITLE
Close button for builds different size than alerts on overview

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#238]
This is obviously a minor issue, but I noticed it immediately.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/17178513/c1417c98-53e3-11e6-8c75-6b379ff9c7e1.png)

@jwforres @rhamilto

**Comment by rhamilto** [comment]
That was a deliberate decision as alert-sized close button felt way too big in context of the completed builds.

**Comment by spadgett** [comment]
I figured, but it still stood out to me. I think the problem is the build message looks so similar to the alerts, but a little different. Maybe give them the same size and font OR make them more visually distinct?

**Comment by rhamilto** [comment]
Apologies, @spadgett, as I managed to overlook this one in the run up to vacation, vacation, and then coming back to bug siege.  

@jwforres, @sg00dwin, @benjaminapetersen, y'all have thoughts on this one?

**Comment by jwforres** [comment]
not worried about it for 1.3

I think there is a larger problem with the style of those notifications, they overwhelm everything else there

**Comment by benjaminapetersen** [comment]
Agree re the notifications being a bit overwhelming. Curious if all the "x" can be the small version & if that would eliminate that minor distraction.
