### ISSUE TITLE
Parameter types not taken in consideration in the update UI

### ISSUE THREAD

**Issue by jmontleon** [openshift/origin-web-console#2380]
When updating the postgresql apb the version parameter of type enum is resulting in a free form text box rather than a drop down as during provision.

**Comment by spadgett** [comment]
@jmontleon It doesn't look like you've defined it as an enum in the update parameter schema.

cc @cfchase 

![openshift web console 2017-10-25 14-34-05](https://user-images.githubusercontent.com/1167259/32016333-a8eb28dc-b991-11e7-8204-d2f5268ccdef.png)

**Comment by jmontleon** [comment]
This is probably my bad. Let me take a look.

**Comment by jmontleon** [comment]
This is on me. Sorry I didn't check our side first. Submitting a PR to ASB

**Comment by spadgett** [comment]
No worries. Thanks @jmontleon. Let us know if it still doesn't work.
