### ISSUE TITLE
Poll quota on the Quota page

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#2405]
We already poll quota on Overview, we should start polling quota on the Quota page with the typical 1 minute interval.  This is the only page that doesn't live update so its a slightly weird experience if the user expects everything to be updating.

**Comment by spadgett** [comment]
/assign @dtaylor113 
/unassign @jwforres 

@dtaylor113 Do you want to take a look at this one?

**Comment by dtaylor113** [comment]
@spadgett, ok, will do
