### ISSUE TITLE
Should be able to enter % when doing load balance on multiple services

### ISSUE THREAD

**Issue by tracyrankin** [openshift/origin-web-console#241]
Currently in the UI, we're asking the user to enter a number from 1-256 to load balance across multiple services.  This is not intuitive because the rest of the UI presents the information in %.  Feedback came from @gshipley

**Comment by sspeiche** [comment]
I'd be in favor of doing something sooner than later. Perhaps it would be interesting to sketch out a design/prototype and see how bad/easy it is?
