### ISSUE TITLE
:Latest tag should state what version it is currently referring to

### ISSUE THREAD

**Issue by luciddreamz** [openshift/origin-web-console#242]
Jessica mentioned that in the future we will warn developers that :latest is a reference to the newest image we have available, but it is also unclear what version this is currently referring to. 

As an example, if I came to the web console as a PHP developer looking to deploy a REST API with Laravel, I might see php:latest and think it refers to a newer version of PHP than php:5.6. If nothing else this would not be entirely clear. We should tell people what version :latest is currently referring to in addition to warning users that the version will change.

**Comment by bparees** [comment]
@spadgett are you asking us to update the imagestream descriptions to state this, or are you going to update the console to programmatically look up what ":latest" is really pointing to (it has a follows relationship to another imagestreamtag, so that's how you can determine what it really references).

**Comment by luciddreamz** [comment]
@bparees This might just be a matter of adding the version to the imagestream descriptions since we have to update the tag in the imagestream for :latest anyways. That could probably be an OK fix.

**Comment by jwforres** [comment]
@luciddreamz just to verify, all you want is version information in the description for the image stream tag?  that would just be an update to the imagestream json

**Comment by luciddreamz** [comment]
@jwforres Yeah, I'll fix that for the online image streams. We can close this.

**Comment by bparees** [comment]
@luciddreamz if you're going to do it, why not do it in the origin imagestreams and then pull it down to online?

**Comment by luciddreamz** [comment]
Nothing really flows from origin to online like that with the image streams, but I guess I can separately update origin with the same changes. How should this make it's way to OCP?

**Comment by bparees** [comment]
@luciddreamz doing it in origin is sufficient, OCP syncs from origin.  @sdodson can confirm.

**Comment by sdodson** [comment]
@bparees Yes, we'll pick up whatever changes are made in origin in the installer.

**Comment by luciddreamz** [comment]
@sdodson Just to confirm, you don't want me to update the image streams here? https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v1.3/

**Comment by sdodson** [comment]
No, I'll sync everything over once they're merged into origin. Just
@sdodson on the origin PR so I know when it merges.
