### ISSUE TITLE
Linkify links in builder image descriptions

### ISSUE THREAD

**Issue by luciddreamz** [openshift/origin-web-console#243]
Jessica mentioned that in the future (or are currently) linkifying links in template descriptions. We should also do the same for builder images so that we can link out to relevant documentation.

For instance, with the [Ruby 2.0 builder image](https://github.com/openshift/online/blob/master/templates/image-streams.json#L73) in the OpenShift Online image stream, I may want to point users to the [OpenShift Online Docs on Ruby](https://docs.openshift.com/online/using_images/s2i_images/ruby.html) or directly to the [SCL S2I container readme](https://github.com/sclorg/s2i-ruby-container/tree/master/2.0).

As an example, if I came to the web console as a PHP developer looking to deploy a REST API with Laravel, I know that Laravel has very specific PHP package requirements. If I wanted to find out what is included with our PHP 5.6 S2I builder image my best best would be to look at the actual [source repo for the PHP 5.6 image](https://github.com/sclorg/s2i-php-container/tree/master/5.6). Included packages are not well documented elsewhere, and this would be hard for external users to find.

**Comment by jwforres** [comment]
@MarkDeMaria take a look at https://github.com/openshift/origin-web-console/blob/master/app/views/create/next-steps.html#L53

to see how we did this for templates

**Comment by jwforres** [comment]
Closing since we are doing this already  @luciddreamz if you want a specific documentation link annotation we should open an issue in origin and discuss that with @bparees separately
