### ISSUE TITLE
"Add to project -> Browse catalog" takes you out of your current project

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#2434]
When you're in a project, and you press "Add to project -> Browse catalog" or only "Browse catalog" you're taken out of your current project.
If I'm already in my project, it's obvious I want to deploy a service from the catalog into my project.

With origin 3.7.0-rc.0

![service_catalog_issue](https://user-images.githubusercontent.com/78350/32324114-54f8a4f0-c01e-11e7-9062-f2ed5fb8ea63.gif)

**Comment by spadgett** [comment]
@jorgemoralespou I agree. This is probably our top usability problem to fix.

@openshift/team-ux-review

**Comment by serenamarie125** [comment]
Agreed this is a huge issue.  Jeff is POCing some solutions.  We should also prioritize this http://openshift.github.io/openshift-origin-design/web-console/project-details/add-to-project#add-to-projects-with-quick-search to help with efficiency for power users who know what they want to add, and don't need to "browse"

**Comment by spadgett** [comment]
This was fixed in 3.9 by #2563
