### ISSUE TITLE
Catalog content overlay have a weird behavior

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#2435]
While browsing the catalog in a small resolution, and showing an overlay for the content of the category, there might be a category that goes to the bottom, seeming like it has disappeared. This behaviour is weird and confusing. It took me a while to figure out what happened.

![service_catalog_issue_2](https://user-images.githubusercontent.com/78350/32324313-166e077e-c01f-11e7-9dd2-7690918812ea.gif)

**Comment by spadgett** [comment]
@openshift/team-ux-review

**Comment by jwforres** [comment]
closing this one since @smarterclayton wants to dup on #2454
