### ISSUE TITLE
List row stays highlighted when closed on iOS

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2438]
After I close an open list row by tapping, it stays highlighted blue on iOS.

![iphone x - ios 11 0 2017-11-02 13-01-47](https://user-images.githubusercontent.com/1167259/32339460-32513926-bfce-11e7-91aa-87372d4a5ab6.png)

**Comment by rhamilto** [comment]
We need to look at [restricting :hover styling to non-touch devices](https://medium.com/@ennsu/disabling-hover-interactions-on-ios-acb034f32325).
