### ISSUE TITLE
Inconsistent shadow on cards

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#244]
This might be something rolled up into [this trello card](https://trello.com/c/1GZyhnXQ), but noticed the shadow on cards on the overview doesn't drop behind the entire card when there are alerts, builds, etc attached:

this:
![screen shot 2016-07-29 at 11 02 47 am](https://cloud.githubusercontent.com/assets/280512/17252811/0baec0b2-557c-11e6-81b9-7759594b8353.png)

vs:
![screen shot 2016-07-29 at 11 02 54 am](https://cloud.githubusercontent.com/assets/280512/17252816/10a9b3e2-557c-11e6-8ad7-63e50d284077.png)

@sg00dwin

**Comment by sg00dwin** [comment]
After a cursory look I believe just adding similar box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1) to the .service-group-triggers will correct this.

**Comment by sg00dwin** [comment]
nice catch - good eye!
