### ISSUE TITLE
Search bar background image shifts when switching categories on mobile landing page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2447]
The background image behind the search bar and browse catalog header on the landing page resizes and moves when switching categories.

I also noticed that the content behind flickers briefly when switching between categories and subcategories on a real device.

**Comment by rhamilto** [comment]
I suspect this is happening because of the (crazy) styling changes to the categories nav.

**Comment by rhamilto** [comment]
This is due to the way way mobile Safari handles background-sizing.  For some reason, it resizes the background with each content change (load of categories or projects and selection of category or subcategory).  I've not found a good workaround yet.

**Comment by rhamilto** [comment]
Per https://caniuse.com/#search=background-size
```
iOS Safari has buggy behavior with background-size: cover; + background-attachment: fixed;
```
