### ISSUE TITLE
Kebab menu clipped when last item in drawer

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2449]
![screen shot 2017-11-03 at 12 26 38 pm](https://user-images.githubusercontent.com/1167259/32384799-6ff8ee4e-c092-11e7-9df2-74f27f2d3543.png)

cc @jwforres

**Comment by dtaylor113** [comment]
Yes, see https://github.com/patternfly/angular-patternfly/issues/614

**Comment by spadgett** [comment]
We might need to implement a workaround if possible in origin-web-console for 3.7 until this is fixed upstream.

**Comment by jeff-phillips-18** [comment]
In angular-patternfly examples, the full menu is available by scrolling. What is the difference here? Why doesn't it scroll?

**Comment by dtaylor113** [comment]
@jeff-phillips-18 This PR is trying to address when the kabob menu gets cut off by the notification group boundary/container.
