### ISSUE TITLE
Select template from project with no identifying info is :(

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin-web-console#2455]
![image](https://www.dropbox.com/s/0om7zq1k5b2fbgo/Screenshot%202017-11-04%2015.40.07.png?raw=1)

We need to do a little better here.  List the types of objects in the template.  Give me a link to view the raw yaml.  Something.

**Comment by jorgemoralespou** [comment]
Tell people how to properly document templates.
I'm working on enhancing our templates to display properly on service catalog, and found that most of the templates out there in the world lack the proper annotations to display nicer.

**Comment by jwforres** [comment]
@jorgemoralespou we do, there is an entire guide for writing templates in the docs that seems to get ignored  :-(

https://docs.openshift.com/container-platform/latest/dev_guide/templates.html#writing-description

**Comment by jwforres** [comment]
@smarterclayton we can do something when the template is referenced as an actual template like select from project, but when its used as a service through the TSB then we have no idea what is in the template

Would rather reduce the differences in experience between our process template flow and our TSB service cat flow, as opposed to adding more.

**Comment by jwforres** [comment]
@openshift/team-ux-review

**Comment by spadgett** [comment]
As an aside, it would be nice if we can find a way for brokers that create resources in your namespace to tell us what they're creating. Then we could show it for both TSB and plain templates as well as ASB. It's helpful to know what services create k8s resources.

@ncameronbritt has made a similar comment.

Related to https://trello.com/c/alQ2I6Uz and https://trello.com/c/6NU32CyY

**Comment by jorgemoralespou** [comment]
@jwforres if you see the link provided, the annotations with prefix openshift.io, which are the ones that matter, where introduced in 3.6. Many templates have been created before that, and obviously you can not expect a user to go through every releases documentation to see what changed and update their instances.
This is what happened to me. I can't seem to find in the release notes where it says I should use those new annotations. That's what I meant.

**Comment by jwforres** [comment]
Good point. @bparees can yall add something in the upgrade doc to make sure ppl know to update their templates now that service catalog is on by default

**Comment by bparees** [comment]
@jwforres which upgrade doc are you thinking of?
