### ISSUE TITLE
Deploying a template from the catalog does not add "app" label

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#2456]
When the template creates the deployment and associated resources doesn't add the "app" label, so it's shown under "Other resources", which makes application component grouping impossible.

All these resources should have the same application label, and should be grouped together:

![image](https://user-images.githubusercontent.com/78350/32430864-3a764772-c325-11e7-9302-55b259b83c82.png)

There's not even the option to set up labels when deploying things from the template service broker, but I've open a separate issue https://github.com/openshift/origin-web-console/issues/2457

**Comment by jorgemoralespou** [comment]
Update:

Deploying an application from the TSB does not add an "app" label, as it does the template instantiation from project. I mistakenly thought "application" was the grouping label, but it's app, so the issue is that deploying from TSB, does not add the "app" label.

**Comment by spadgett** [comment]
This needs to be opened against the template service broker. With the current APIs, I don't believe there is a way for the console to set this.

cc @bparees @jim-minter @jwforres

**Comment by spadgett** [comment]
A workaround is to set the `app` label in the template itself, although then the user can't choose the app name.

**Comment by bparees** [comment]
won't fix.  adding an default app label is not template behavior.  (you don't get it if you run "oc process foo | oc create -f -" either.

**Comment by jim-minter** [comment]
@spadgett does the console do any grouping by provisioned service?  Is there any scope to improve that?

**Comment by jwforres** [comment]
@jim-minter yeah @ncameronbritt has designs in progress for that, think we are showing them at design review this thursday

**Comment by spadgett** [comment]
@jim-minter https://trello.com/c/alQ2I6Uz
