### ISSUE TITLE
When deploying from the TSB one can not set labels

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#2457]
When I deploy something from the template service Broker I need to set up the labels as I want things to be properly associated and selectable.

![image](https://user-images.githubusercontent.com/78350/32431030-e7d858e2-c325-11e7-985d-0a8bf747cd5b.png)

When you select a template from your project, you can add/edit the labels.

![image](https://user-images.githubusercontent.com/78350/32431100-24ab2678-c326-11e7-866c-0dad123bb82a.png)

**Comment by spadgett** [comment]
There's currently no way for the console to set labels on the resources created from the template when using the template service broker. Everything happens through the Open Service Broker API, which does not have a labels concept since it is not specific to Kubernetes. Many (most?) brokers won't be creating k8s resources at all.

The only workaround is to add the labels to the template itself (which I know is not exactly the same as letting the user pick).

cc @bparees @jim-minter @pmorie @jwforres

**Comment by bparees** [comment]
@jim-minter we added support for parameterizing labels in templates, right?

If so i think this is close as won't fix, you can write your template w/ parameterized labels and the user can customize those labels by providing parameter values when provisioning via the TSB.

**Comment by jwforres** [comment]
@bparees do you mean its just a single array data blob you can dump in, the experience of that won't be as good as we have today

**Comment by bparees** [comment]
@jwforres no, i mean that I believe you can write your template as:

```
{
  "kind": "Template",
  "apiVersion": "v1",
  "metadata": {
    "name": "mongodb-ephemeral"
  },
  "labels": {
    "${MY_LABEL_KEY}": "${MY_LABEL_VALUE}"
  },
```

So then the user can supply values for both of those parameters.

No, it's not quite as flexible as letting them provide an arbitrary set of labels, but it does let the user pick keys/values for labels the template author anticipated you'd want.

(Again i need @jim-minter to confirm you can do that, i'm pretty sure he added the feature but our docs don't seem to provide an example of it).

**Comment by jim-minter** [comment]
> @jim-minter we added support for parameterizing labels in templates, right?

That's #16605, which you're holding for 3.8.

**Comment by jim-minter** [comment]
FWIW I don't think this is directly fixable while staying within the spirit of the service broker; I think it would be better to make sure we've got sound capabilities around provisioning to new namespaces and binding across namespaces.

**Comment by bparees** [comment]
yes, supporting this in the same way that existing template flows support it today would mean leaking significant chunks of the abstraction.  That said, i'm not sure how this relates:

> I think it would be better to make sure we've got sound capabilities around provisioning to new namespaces and binding across namespaces.

i do think that is an issue (and probably more important) but it's orthogonal in my mind, to labeling.

**Comment by jim-minter** [comment]
I guess my point is that way the provisioned service is out of sight and boxed on its own into its own namespace, so labels aren't as necessary any more.

**Comment by spadgett** [comment]
We are looking at grouping the deployments from provisioned services together on the overview.

https://trello.com/c/alQ2I6Uz

We can also group things by pod preset selectors when pod presets are back.

@jorgemoralespou Can you expand on your use case some? How do want to use the labels? Is it for more than just grouping on the overview?

**Comment by jorgemoralespou** [comment]
Well, not really only for grouping, but the whole notion of the application that we're trying to standardize on revolves around being able to provide some appropriate labels to the components you're creating to better identify them as part of your application. So, app, component,... has meanings in many ways. I might want to show them grouped/filtered in the overview, or I might want to cascade delete some resources.

Put as an example a project/namespace where I deploy 1 application consisting of 2 microservices (springboot), both of them using mongodb.

I want to be able to label the resources so that:
- every resource has app=myapp
- each microservice has a label ms=service1 and the other ms=service2
- each component has a label for the component type, so the springboot will have component=springboot and the database will have component=database
- I want the services, routes, dcs, configmaps, secrets, etc... be labeled with the component they relate to, the microservice they belong to and the application they belong to

So that I can deploy, update, export the appropriate pieces of my application in an easy way. That's what labels and selectors are meant for.

So if you're saying that when I deploy a mongodb through the template service broker I will not be able to label the resources, and that it will inherit the labels from the template, so in order to be able to customize them I need to cater for that in the template itself, I'm guessing that I'd better not deploy things through the template service broker.

> Many (most?) brokers won't be creating k8s resources at all.
Template service broker will be the way to use templates to deploy k8s resources in your openshift cluster.

**Comment by bparees** [comment]
> So if you're saying that when I deploy a mongodb through the template service broker I will not be able to label the resources, and that it will inherit the labels from the template, so in order to be able to customize them I need to cater for that in the template itself, I'm guessing that I'd better not deploy things through the template service broker.

That's what i'm saying.  I don't understand why you conclude that this means you shouldn't deploy stuff through the TSB.  It seems pretty reasonable to me to say "if you want these resources to have a common label, use the mechanism provided to you by the template api, to provide a label for these resources".

In any case this repo is the wrong place to have this discussion, there's nothing the web console team can do about this.  i'm closing this issue and i've opened a trello card to add to our backlog[1], we'll consider it when we get there.  In the meantime, I consider "write your templates w/ proper labels" to be a perfectly reasonable solution to your problem.  It is in fact what we are doing for our own templates (Adding the app label explicitly).

[1] https://trello.com/c/7upa8IX4
