### ISSUE TITLE
Monitoring page: follow log link takes you to the bottom of the page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#248]
The follow link takes you to the bottom of the entire page, not the bottom of the log.

/cc @jwforres

**Comment by jwforres** [comment]
really that was working....

**Comment by jwforres** [comment]
@spadgett I actually cant recreate it, you'll have to show me tomorrow what you are seeing

**Comment by spadgett** [comment]
Might have been at mobile screen widths

**Comment by jwforres** [comment]
Ok yep it only happens at mobile, will look at that tmrw
