### ISSUE TITLE
Monitoring page: sparklines don't resize when events sidebar shown or hidden

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#249]
<img width="1073" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/17312203/100fc94e-581f-11e6-97e6-4deacd00a51d.png">

**Comment by jwforres** [comment]
@spadgett is there something i can trigger on the chart to tell it to re-render?

**Comment by jwforres** [comment]
looks like there is a resize api on the chart object

**Comment by spadgett** [comment]
Does flush() work?

**Comment by jwforres** [comment]
yep flush works, updated to use that instead
