### ISSUE TITLE
Pressing enter in Name field of deploy with Image Name, should not re-query image details.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin-web-console#2490]
When using the service catalog in 3.7-rc.0, if you select 'Image Name', and enter the image reference, eg., 'openshiftkatacoda/blog-django-py' and press enter, or select on the magnifying glass, it will query Docker Hub and pull down image details. That much is good.

The 'Name' field for the deployment will be set the name of the image, eg., 'blog-django-py'. If you edit the 'Name' field to change the name for the resources created and press enter in the 'Name' field, it will requery the details for the image from Docker Hub, throwing away the value of the 'Name' field you just entered.

Pressing enter in the 'Name' field should not do that. It should just accept the change.

![image](https://user-images.githubusercontent.com/507637/32581250-30c25e9a-c53d-11e7-9ba2-38c45d48a86e.png)

cc @jorgemoralespou

**Comment by spadgett** [comment]
Same as #1755, although I'm going to keep this issue since it has more detail.
