### ISSUE TITLE
Environment variable editor grabs focus always on page load

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#252]
On some forms, this causes the page to scroll to the bottom on page load.

/cc @jwforres @benjaminapetersen

**Comment by spadgett** [comment]
For example, when creating from a template, this is what you see on page load:

![screen shot 2016-08-02 at 10 01 17 am](https://cloud.githubusercontent.com/assets/1167259/17331262/2a26ea32-5898-11e6-98e7-50ce7c353946.png)

**Comment by benjaminapetersen** [comment]
related to this bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1362049

**Comment by jwforres** [comment]
changing to P1, cant ship with this behavior

**Comment by benjaminapetersen** [comment]
Fixed in 1.2.2 of kve, I'll PR the version bump in bower.json shortly.
