### ISSUE TITLE
free-stg is broken for me

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin-web-console#2529]
On safari, tried to login, looks like JS error accessing data that doesn't exist

![image](https://www.dropbox.com/s/cu1jmho4k0wpflh/Screenshot%202017-11-21%2011.53.04.png?raw=1)

**Comment by smarterclayton** [comment]
free-stg is 3.7 GA right now i think...

**Comment by spadgett** [comment]
Something is really broken on this cluster.

The console bower dependencies in this environment are older than the console code. I'm seeing back-level versions of at least lodash and origin-web-common. New functions added to these libraries are not defined, resulting in a runtime error loading the console. I don't believe the console was built correctly.

Looking over @jupierce's shoulder, `oc version` was reporting 3.6 while the console code is 3.7 as well.

cc @jwforres

**Comment by jwforres** [comment]
I'm getting different answers back about the version in the About page in the console.  It looks to me like at least one of the masters is not updated.

**Comment by spadgett** [comment]
Ah that could explain why vendor.js is out of date. If scripts.js is 3.7 served from master A and vendor.js is 3.6 served from master B, then I'd expect runtime errors like this.

**Comment by spadgett** [comment]
This might be a problem during upgrades as well if there is no session affinity.

**Comment by spadgett** [comment]
Closing as the free-stg environment was updated and the console is working now.
