### ISSUE TITLE
Ability to copy text from browser terminal

### ISSUE THREAD

**Issue by kargakis** [openshift/origin-web-console#2531]
I am not able to copy text from the Terminal tab of a pod - is it something not supported in the console or a quirk of my browser?

**Comment by jhadvig** [comment]
I've tried to reproduce the issue but without any luck. What version of origin and console (in case you are lunching console in dev mode) are you running ?

**Comment by kargakis** [comment]
> what browser ?

Firefox 57

> What version of origin and console (in case you are lunching console in dev mode) are you running ?

I can reproduce this in a couple of different clusters, both dev and our ci cluster which is `openshift v3.7.0-rc.0+bd64aab-99`.

The steps I am following is navigate to the terminal logs and try to copy paste either by selecting the text and right-click, or Ctrl+C (terminal signal), or Ctrl+Shift+C (opens a debugger and a couple of other windows in my browser).

**Comment by spadgett** [comment]
@kargakis I think you're seeing https://github.com/xtermjs/xterm.js/issues/1003. Unfortunately they haven't released xterm.js v3 with the fix yet.

**Comment by yvnicolas** [comment]
Not sure this is related or not but I can not copy paste either in Chrome when accessing the terminal tab on a mongo-db Pod. It is also "not friendly" with my AZERTY keyboard for non standard characters : even to enter a {, I need to use alt + ascii code...

**Comment by jwforres** [comment]
@yvnicolas xterm.js recently releases v3 and has a test example you can run https://github.com/xtermjs/xterm.js#demo

can you see if you still have these issues on their latest?  we plan to update during 3.10

**Comment by spadgett** [comment]
@yvnicolas Which OpenShift version are you using? We fixed several bugs in this area in 3.7.

**Comment by rhamilto** [comment]
Should be fixed by https://github.com/openshift/origin-web-console/pull/2849
