### ISSUE TITLE
[RFE] Badge to distinguish between templates and s2i builders in catalog

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#2538]
I have this in my catalog.

<img width="1033" alt="screen shot 2017-11-29 at 16 16 47" src="https://user-images.githubusercontent.com/78350/33382678-a354e9f2-d521-11e7-9ab9-566652ac9fca.png">

From the 2 on the right? Can anyone tell me what's what and how they are different?

Also, from the ones on the left, are they s2i builders or templates?

**Comment by jorgemoralespou** [comment]
cc/ @siamaksade

**Comment by siamaksade** [comment]
+1 very confusing indeed

**Comment by spadgett** [comment]
cc @sspeiche @jwforres 

Looks like one is a template and one is an image stream. See

https://github.com/jboss-openshift/application-templates/search?utf8=%E2%9C%93&q=%22OpenJDK+8%22&type=

I believe the `fis-*-openshift` image streams will soon be hidden with the latest updates.

**Comment by siamaksade** [comment]
@spadgett yes but an OpenShift user shouldn't need to do a GitHub search to discover that. The templates, s2i builders and other objects in the service catalog should be visually distinguishable

**Comment by spadgett** [comment]
> yes but an OpenShift user shouldn't need to do a GitHub search to discover that

Of course. Just figuring out where it's from so we can fix it.

I don't think we should have two out-of-the-box catalog items with basically the same display name and icon even if one is a template and one is a builder.

> s2i builders and other objects in the service catalog should be visually distinguishable

We used to have badges. I remember we discussed this in a design review, and the feedback for the 3.4 catalog was to remove them and purposely not differentiate. @jwforres or @rhamilto do you remember the reasoning?

It's even trickier now that we have service classes, too, so there are more kinds of items.

cc @openshift/team-ux-review

**Comment by ncameronbritt** [comment]
It doesn't necessarily make it obvious visually, but having faceted filters for the types of objects in the catalog (e.g. s2i, template, etc) could be one path for getting to the thing you're looking for. @spadgett I think we had a conversation about that at some point.

**Comment by rhamilto** [comment]
> @jwforres or @rhamilto do you remember the reasoning?

IIRC, we removed the badges because they were redundant and created visual noise.

**Comment by spadgett** [comment]
We could put labels like "Builder" / "Template" / "Service" on items so there's no confusion. I think that's more obvious than a badge.

**Comment by jwforres** [comment]
@spadgett do you mean after they select the icon and we open the dialog that it would have that text?  I don't think we could fit that kind of text with the icon/name.

@jorgemoralespou @siamaksade are you wanting visual differentiation between builders and services before clicking to open the dialog?

**Comment by spadgett** [comment]
> do you mean after they select the icon and we open the dialog that it would have that text? I don't think we could fit that kind of text with the icon/name.

I was thinking of using a smaller, muted font in the catalog itself. Not unlike what we do on the overview (but not necessarily the exact same style).

Not sure how it would look, but throwing it out there as an option.

**Comment by siamaksade** [comment]
@spadgett the label idea is reasonable. Bluemix does that but for a difference purpose

![screen shot 2017-11-29 at 22 12 00](https://user-images.githubusercontent.com/1174934/33399319-7f39e672-d552-11e7-93bd-64f2e3f5acc4.png)

@jwforres yes. it should be intuitive what an item in the catalog is before clicking on it.

**Comment by serenamarie125** [comment]
@jwforres I will create a design story around this.  Can someone confirm what the types are that we need to visualize?  Is it just 3 : builder/template/service?  Additionally, do we think it would be fair to say that one of those (service) doesn't need an indicator, but we could call out the other two?

**Comment by jorgemoralespou** [comment]
Why badges are redundant and make so much noise?
When I look into some implementations of badges (e.g. https://github.com/HazAT/badge) I think they serve a purpose really well. Obviously you can not cather for everything in badges, so only the most obvious and useful information (the type) should belong to a badge.
But, I do agree that labels provide for a mechanism to add more "additional" information that might be necessary in the future, to the first sight. I think that eventually, the catalog items would want to show labels to better visually distinguish items in a bloated catalog. Even if there's filtering, you will most likely always do a visual inspection of what you have in screen before filtering.

Customers will most likely want to have this visible (like in Bluemix catalog) and possibly configurable. Labeling objects is the most powerful mechanism a customer has for categorization. And when they do categorize, they want to be able to easy use that categorizations.

**Comment by rhamilto** [comment]
> Why badges are redundant and make so much noise?

Note my comment applies to the previous design, not the current one.

**Comment by spadgett** [comment]
This has been addressed in 4.x. At this time, we don't plan to rework the 3.11 catalog experience.
