### ISSUE TITLE
Replace resource apiGroup from 'extensions' to the appropriate group

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin-web-console#255]
After 3.3 we need to update apiGroups for some resources. Eg:
- `horizontalpodautoscalers` from `extensions` to `autoscaling`
- `jobs` from `extensions` to `batch`
- ...

The update includes the input for the `canI` filter in our views https://github.com/openshift/origin-web-console/blob/master/app/views/browse/deployment-config.html#L50 and also links https://github.com/openshift/origin-web-console/blob/master/app/views/browse/deployment-config.html#L52

**Comment by spadgett** [comment]
@DirectXMan12 does anything change for `horizontalpodautoscalers` switching from the `extensions` group to the `autoscaling` group?

**Comment by DirectXMan12** [comment]
there's the switch to the "implicit" default for CPU (CPU no longer defaults to a percentage at the API level -- there's just a default in the HPA controller).  There's also the actually working "don't scale on CPU when you have custom metrics scaling set".  The field names change slightly too -- (`scaleTargetRef` vs `scaleRef`, for instance).

**Comment by spadgett** [comment]
We've already migrated HPAs to use the `autoscaling` group. We're still using `extensions` for deployments and replica sets, however.

**Comment by spadgett** [comment]
#1813 migrated deployments to the `apps` API group.
