### ISSUE TITLE
Search catalog "View all..." link from within a project redirects to catalog without filter applied

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#2573]
<img width="343" alt="screen shot 2017-12-06 at 3 27 04 pm" src="https://user-images.githubusercontent.com/895728/33683752-faebe198-da99-11e7-89a1-fe80e3d219ec.PNG">

<img width="704" alt="screen shot 2017-12-06 at 3 27 11 pm" src="https://user-images.githubusercontent.com/895728/33683756-fff5bfb0-da99-11e7-8043-094eb2ee4993.PNG">

**Comment by spadgett** [comment]
That was temporary until we have #2563

**Comment by jeff-phillips-18** [comment]
Fixed by #2563
