### ISSUE TITLE
cannot scale statefulsets

### ISSUE THREAD

**Issue by kargakis** [openshift/origin-web-console#2581]
I cannot seem to scale a statefulset from the console.

Openshift version is v3.7.0-rc.0+bd64aab-99

**Comment by kargakis** [comment]
@openshift/sig-user-interface

**Comment by benjaminapetersen** [comment]
Correct, the api was not available for this when we initially implemented.  Going to check again and see if we have progress towards these features.

**Comment by spadgett** [comment]
https://trello.com/c/M4fAYrUT

**Comment by spadgett** [comment]
Requires https://github.com/openshift/origin-web-common/issues/308

**Comment by spadgett** [comment]
Now tracked by https://bugzilla.redhat.com/show_bug.cgi?id=1574559

/close
