### ISSUE TITLE
Dialog animates twice when first opened from masthead search

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2589]
When you search for a builder image in the masthead and select the item, the overlay animation appears to stutter the first time as if the animation is running twice.

/assign @rhamilto 
/kind bug
/priority p3
/area styles

**Comment by rhamilto** [comment]
What appears to be happening is the modal and overlay show and then animate.  The animation is triggered off the addition of the "ng-enter" class, so I'm guessing the "ng-enter" class is being applied after the element is already visible.

**Comment by rhamilto** [comment]
This bug also appears to be specific to builders.

**Comment by rhamilto** [comment]
Video with slow motion to make bug more apparent:  https://youtu.be/spBLZs50cB4
