### ISSUE TITLE
Scrollbar visible when deploy image dialog loads

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2590]
Obviously a minor issue -- and I think we might have previously fixed this? -- but the deploy image dialog is just a little too small to avoid the scrollbar when it loads. This might be because of the "Image search is only available..." message.

![openshift web console 2017-12-12 14-55-45](https://user-images.githubusercontent.com/1167259/33905576-14e02f98-df4d-11e7-8737-c277bdf78d1f.png)

/kind bug
/priority p3
/area styles
/assign @rhamilto

**Comment by rhamilto** [comment]
>  and I think we might have previously fixed this? 

Indeed we have.  The bug recurred because of the h2 font size change in https://github.com/openshift/origin-web-console/pull/2540.  Trivial fix forthcoming.
