### ISSUE TITLE
Gray background does not extend to bottom of screen in project catalog

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2592]
![screen shot 2017-12-12 at 3 40 19 pm](https://user-images.githubusercontent.com/1167259/33907357-ebc163b0-df52-11e7-8787-e7eb9a2839a0.png)

/kind bug
/assign @rhamilto @sg00dwin 
/area styles
/priority p3

@jwforres @jeff-phillips-18  FYI

**Comment by spadgett** [comment]
I'm not sure if this is intentional or not, but it looks strange to my eye.

**Comment by rhamilto** [comment]
Is this the final visuals?  The page feels *really* chopped up and unlike all other project pages.

**Comment by spadgett** [comment]
Mobile also looks odd:

![openshift web console 2017-12-12 16-02-11](https://user-images.githubusercontent.com/1167259/33908295-ed6c276a-df55-11e7-8c54-ca3dd74848dc.png)

**Comment by jwforres** [comment]
the top and bottom spacing around the category links also seems off to me in this context

**Comment by rhamilto** [comment]
@openshift/team-ux-review, are these visuals as intended?  In looking at the code, it appears these are just the inherited styles from the landing page.  I think this could be improved.

![localhost_9000_dev-console_project_myproject_overview ipad](https://user-images.githubusercontent.com/895728/33944035-e7031cb0-dfe8-11e7-8869-6bde4baf50af.png)

**Comment by serenamarie125** [comment]
Going to have Jenny take a look ...

**Comment by jennyhaines** [comment]
@rhamilto @spadgett @jwforres @sg00dwin  -

I took a look, and I agree that things are looking a little blocky! I think we'll need the grey background, so my vote would be to simplify it by having a full grey background, from top to bottom. (No more white behind the H1, or underneath the results.) I know that OpenShift currently does this with the "Create Route" screen, and I think we could do that exact same thing here. 

I also think we should be sticking with the same tabs style (with the underline) that we use across the rest of OpenShift. 

Thoughts?

![proposed_a](https://user-images.githubusercontent.com/24898297/33952885-2626c19a-e001-11e7-8d04-c6ec7d3225af.png)

![proposed_b](https://user-images.githubusercontent.com/24898297/33952891-2bce6b8e-e001-11e7-8049-880d852ff4b7.png)

**Comment by rhamilto** [comment]
@jennyhaines, what do you recommend for the mobile screens?  In the following screenshots, I've pared the landing-specific styles back as a starting point, leaving just default blue links.

![localhost_9000_dev-console_project_myproject_catalog_filter ruby iphone 6 plus](https://user-images.githubusercontent.com/895728/33998406-6421693c-e0b5-11e7-998a-fe127d34a0bc.png)

![localhost_9000_dev-console_project_myproject_catalog_filter ruby iphone 6 plus 1](https://user-images.githubusercontent.com/895728/33998413-682fa82c-e0b5-11e7-9736-377ef35a9b07.png)

![localhost_9000_dev-console_project_myproject_catalog_filter ruby iphone 6 plus 2](https://user-images.githubusercontent.com/895728/33998425-6c77aa6a-e0b5-11e7-9a32-fea26bab3cc9.png)

**Comment by jennyhaines** [comment]
@rhamilto - I'm looking at this for mobile:  Let me know what you think! I think we need to have a full discernible clickable area per mobile line item, hence the white containers. I also don't think the grey underneath the catalog results adds anything, so I'd suggest expanding the white down to the bottom of the mobile screen.

![mobile1](https://user-images.githubusercontent.com/24898297/34001850-1ad8950c-e0bf-11e7-9e65-edce1c9151c4.png)
![mobile2](https://user-images.githubusercontent.com/24898297/34001855-1e1af1e2-e0bf-11e7-8218-9cfb9dc4f93c.png)

**Comment by rhamilto** [comment]
Unfortunately it's going to be expensive and risky to bleed the white box to the edges at this stage in development.  As a compromise, are you ok with a gutter around the sides of the white box, @jennyhaines?  

![localhost_9000_dev-console_project_myproject_catalog iphone 5](https://user-images.githubusercontent.com/895728/34045519-389de53e-e177-11e7-979e-0728795597b2.png)

**Comment by jennyhaines** [comment]
Hi @rhamilto - that's fine with me, since it's too expensive at this stage. It looks better without the gutters, but it doesn't affect functionality to have them!
