### ISSUE TITLE
Try Sample Repository not pulling in "sampleContextDir" and "sampleRef"

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin-web-console#2599]
![no-advanced-prefill](https://user-images.githubusercontent.com/727196/34022912-1f6edab2-e110-11e7-9392-428c1fd0de33.gif)

**Comment by spadgett** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1519096

Fixed by https://github.com/openshift/origin-web-catalog/pull/579
