### ISSUE TITLE
Bug 1525819: Warning dialogue box disappears automatically when click out of the box

### ISSUE THREAD

**Issue by TheRealJon** [openshift/origin-web-console#2609]
When create a special resource by import json/yaml file, it will pop up a dialogue box, with "Create Anyway" and "Cancel" button, if user clicks out of the dialogue box accidentally, the box disappears automatically.

https://bugzilla.redhat.com/show_bug.cgi?id=1525819

**Comment by spadgett** [comment]
@TheRealJon Typically if we have a Bugzilla, we track it only in Bugzilla. Otherwise it's too easy for the issue and Bugzilla bug to get out of sync.
