### ISSUE TITLE
We have a second "admin" role appearing in the roles list

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#2619]
This is new.  Not sure why I can see two 'admin' roles.

![screen shot 2018-01-02 at 1 24 18 pm](https://user-images.githubusercontent.com/280512/34494856-52a79bee-efc0-11e7-90e8-85d4d755dd06.png)

@enj anything change with roles recently to cause a second admin?

**Comment by benjaminapetersen** [comment]
@jwforres @spadgett

**Comment by jwforres** [comment]
are you getting a cluster scoped admin role and a namespace scoped admin role?

**Comment by benjaminapetersen** [comment]
Very possible.  Its with a fresh "cluster up" so its OOTB.  It would be a new thing to get the namespaced scoped role I believe.

**Comment by jwforres** [comment]
@benjaminapetersen can you check the API responses and see if thats what it is?

**Comment by enj** [comment]
I see no such cluster role or role in a default cluster up.  Perhaps you are running with some kind of service broker that defines its own admin role?

**Comment by benjaminapetersen** [comment]
Nope, found it. Bug, PR coming in a min.
