### ISSUE TITLE
Put INACTIVITY_TIMEOUT_PERIOD into AssetConfig

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin-web-console#2626]
After https://github.com/openshift/origin-web-console/pull/2528 gets merged and the console is split into a pod and openshift-ansible, we need to  remove the **INACTIVITY_TIMEOUT_PERIOD** from the *constants.js* and add it into AssetConfig as a flag

@jwforres fyi

**Comment by spadgett** [comment]
/assign

Partially addressed by https://github.com/openshift/origin-web-console-server/pull/20

**Comment by spadgett** [comment]
Fixed by #2674
/close
