### ISSUE TITLE
Project overview empty state Add to Project button links to catalog page, but other add options not visible on the catalog page

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#2631]
<img width="1646" alt="screen shot 2018-01-05 at 10 21 46 am" src="https://user-images.githubusercontent.com/895728/34615289-6770cc0a-f202-11e7-97b5-a8e02d55eca8.PNG">

The result of clicking "Add to Project" in the previous screenshot brings you here, and the page has no mention of the other add methods:
<img width="1647" alt="screen shot 2018-01-05 at 10 23 21 am" src="https://user-images.githubusercontent.com/895728/34615333-87469c1c-f202-11e7-948e-5cd973da79b1.PNG">

The old create page had tabs at the top with the other add methods:
<img width="1647" alt="screen shot 2018-01-05 at 10 24 49 am" src="https://user-images.githubusercontent.com/895728/34615378-b1325868-f202-11e7-95b1-2fb098541686.PNG">

And the landing page has the other add options listed:
<img width="1646" alt="screen shot 2018-01-05 at 10 25 25 am" src="https://user-images.githubusercontent.com/895728/34615414-c93e624e-f202-11e7-9783-1feeb045c74a.PNG">

It seems like we should be consistent?

**Comment by dtaylor113** [comment]
Hi @rhamilto, I think I mentioned this briefly once, believe I was told that the 'Add To Project' dropdown contains those additional options.  IMO, I agree with you that they should be added to the top of the project catalog page, like we do on the catalog home page, to be consistent.

**Comment by ncameronbritt** [comment]
Adding @openshift/team-ux-review 

The PF empty state pattern offers the option to include secondary actions. One potential solution is to make the catalog the primary action and add the other options as secondary actions.
http://www.patternfly.org/pattern-library/communication/empty-state/#/design

**Comment by dtaylor113** [comment]
Here are the additional 'add to project' links as shown on the Catalog Home page:

![image](https://user-images.githubusercontent.com/12733153/34624211-724e52f8-f222-11e7-81c1-cece10ebf7b7.png)

I think it would be good to show them on top of the project catalog page:

![image](https://user-images.githubusercontent.com/12733153/34624222-81243770-f222-11e7-9057-437c350e4042.png)

**Comment by beanh66** [comment]
Thanks for bringing this up @rhamilto and @dtaylor113, we'll discuss some options at our design meeting this afternoon and get back to the group asap!

**Comment by beanh66** [comment]
@rhamilto we would like to move forward with the recommendation @dtaylor113 described where the 3 options are listed out on the top of the catalog page in the context of a project so we are consistent with the landing page catalog. See below: 
![screen shot 2018-01-08 at 2 50 40 pm](https://user-images.githubusercontent.com/18057044/34690004-8421f362-f485-11e7-8aff-77a3e4d929d6.png)

Please note, on smaller screen sizes the landing page catalog will condense these three options into a dropdown "Custom Add" as shown below. For the catalog page in context of a project, we would not display that "Custom Add" dropdown and instead would hide these options since they are always available via the "Add to Project" dropdown in the secondary masthead. 
![screen shot 2018-01-08 at 3 02 44 pm](https://user-images.githubusercontent.com/18057044/34689998-7db6c156-f485-11e7-99e4-a8efcde81339.png)

**Comment by beanh66** [comment]
We also discussed adding the three options to the existing empty state pattern and changing the name of the primary action to "Browse Catalog." See below for the recommendation: 
![screen shot 2018-01-08 at 3 18 17 pm](https://user-images.githubusercontent.com/18057044/34690467-49974362-f487-11e7-97b0-8a2543c26b86.png) 
This is consistent with examples shown in the [PF Empty State Pattern](http://www.patternfly.org/pattern-library/communication/empty-state/).

Let me know if you prefer I create a separate issue to tackle this piece.

**Comment by rhamilto** [comment]
> For the catalog page in context of a project, we would not display that "Custom Add" dropdown and instead would hide these options since they are always available via the "Add to Project" dropdown in the secondary masthead.

Playing devil's advocate, that's also true for the desktop resolutions.  

But at mobile, it's even less obvious what "Add to project" dropdown does because the "Add to project" label is replaced with a "+" icon.  

![screen shot 2018-01-08 at 3 21 37 pm](https://user-images.githubusercontent.com/895728/34690572-b38a2e4c-f487-11e7-9d1c-cb08e4879569.PNG)

I think there is value in maintaining the dropdown at both mobile and desktop, both landing and in-project.

**Comment by rhamilto** [comment]
> We also discussed adding the three options to the existing empty state pattern and changing the name of the primary action to "Browse Catalog."

I think this pre-empts the problem entirely.  It makes me wonder if the catalog page needs changing?

**Comment by rhamilto** [comment]
The overview's empty state message contains the following text above the action buttons:

> Use your source or an example repository to build an application image, or add components like databases and message queues.

That text is a bit cryptic as it relates to the empty state UI.  How do I do those things given the options below?  I think we probably want text that instructs the user to add something to the project using one of the add methods.  @openshift/team-ux-review?

**Comment by ncameronbritt** [comment]
Good point @rhamilto. I took a first crack at a new message, happy for feedback or to turn it over to a copywriter. :-)

"Browse the catalog for services like databases and message queues, as well as for tools to build container images from your source code. Or choose another method to add resources to your project."

**Comment by rhamilto** [comment]
>> Use your source or an example repository to build an application image, or add components like databases and message queues.

> That text is a bit cryptic as it relates to the empty state UI. How do I do those things given the options below? I think we probably want text that instructs the user to add something to the project using one of the add methods. @openshift/team-ux-review?

How about the following instead:

Add content to your project from the catalog of web frameworks, databases, and other components. Or deploy an existing image, create or replace resources from their YAML or JSON definitions, or select an item shared from another project.

**Comment by ncameronbritt** [comment]
I like that. Made one minor change.

Add content to your project from the catalog of web frameworks, databases, and other components. You may also deploy an existing image, create or replace resources from their YAML or JSON definitions, or select an item shared from another project.

**Comment by rhamilto** [comment]
@ncameronbritt, your proposal came in while I was drafting mine (it's not that I'm suggesting mine is better).

**Comment by ncameronbritt** [comment]
@rhamilto I'd also remove the Oxford comma from the first sentence, but that's just me :-)

**Comment by ncameronbritt** [comment]
@openshift/team-ux-review What do you guys think?

**Comment by jwforres** [comment]
Blasphemy, we use Oxford commas here

**Comment by cshinn** [comment]
@ncameronbritt I think that works really well. Except for removing the comma...

**Comment by cshinn** [comment]
From the PF style guide: "Use serial commas. A serial comma is the comma before the “and” in a series of three or more items: 'Item 1, item 2, and item 3.'"

**Comment by ncameronbritt** [comment]
Another possibility for the text: Combining my first sentence with @rhamilto's second sentence:

Browse the catalog for services like databases and message queues, as well as for tools to build container images from your source code. You may also deploy an existing image, create or replace resources from their YAML or JSON definitions, or select an item shared from another project.

**Comment by beanh66** [comment]
@rhamilto Chatted with the other designers and agreed, we can leave the in-project catalog as is. No need to add the 3 buttons to the catalog, making them available from the empty state should handle the concern.  Thanks!
