### ISSUE TITLE
Specify repository description and topic

### ISSUE THREAD

**Issue by php-coder** [openshift/origin-web-console#2645]
When I open https://github.com/openshift/origin-web-console I see a message that "No description, website, or topics provided." It would be good to have a short descriptions and at least [`openshift` topic](https://github.com/topics/openshift).

**Comment by spadgett** [comment]
/assign @jwforres 

I don't seem to have authority.

**Comment by php-coder** [comment]
@jwforres Ping

**Comment by jwforres** [comment]
yeah i dont even have that access, needs to be someone like @smarterclayton or @dobbymoodge

**Comment by dobbymoodge** [comment]
Someone come up with a good description and I'll add it. :D

**Comment by spadgett** [comment]
@dobbymoodge Maybe just

Web Console for the OpenShift Application Platform  https://www.openshift.org/

**Comment by dobbymoodge** [comment]
Done
