### ISSUE TITLE
Getting Error notification "the API version in the data (v1) does not match the expected API version (project.openshift.io/v1)"

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-console#2646]
I just tried the 'Create from URL' scenario  below using a clean console master branch which referred to `origin-web-common 3.9.0-alpha.4` and it worked fine.  I then changed console to use `origin-web-common 3.9.0-alpha.5` which has a number of commits since `-alpha.4`.  I believe the commits between `origin-web-common 3.9.0-alpha.4` and `alpha.5` are causing the 'Create from URL' issue below.

Using: docker v.1.12.6, oc  v.3.7.0-rc.0+fc8725b-108-dirty, go 1.8.3, latest docker images (`docker pull openshift/origin:latest & docker pull openshift/origin-service-catalog:latest`).

`oc cluster up --version=latest --service-catalog=true`

I enter the following url: `https://localhost:9000/dev-console/create?imageStream=nodejs&imageTag=4&name=nodejs&sourceURI=https:%2F%2Fgithub.com%2Fopenshift%2Fnodejs-ex.git&sourceRef=master&contextDir=%2F` 

and get to this point.  Clicking on [Create] project results in the following error notificaiton:

![image](https://user-images.githubusercontent.com/12733153/34730214-b8707902-f52c-11e7-8f25-ac9ce052c5a3.png)

`the API version in the data (v1) does not match the expected API version (project.openshift.io/v1)` ?

This may be causing the Jenkins Integration Test failures in PR: #2610

**Comment by dtaylor113** [comment]
I just tried this on a clean console master branch and it worked fine, so I believe changes I did in #2610 is causing the issue.  Dev branch: https://github.com/dtaylor113/origin-web-console/tree/preferred-home-page

**Comment by dtaylor113** [comment]
From the console log:
```
Uncaught TypeError: Cannot read property 'get' of undefined  extensions::StorageArea:26
POST https://localhost:8443/apis/project.openshift.io/v1/projectrequests 400 (OK)
hawtio-core.js:83 [OpenShift] Project 'asdf' could not be created. 
Object {data: Object, status: 400, config: Object}config: Objectdata: Objectheaders: (name)status: 400__proto__: Object
     consoleLogger @ hawtio-core.js:83
     onAdd @ hawtio-core.js:234
     (anonymous function) @ hawtio-core.js:241
     ContextualLogger.invoke @ logger.js:98
     ContextualLogger.error @ logger.js:92
     logger.error @ origin-web-common.js:4972
     (anonymous function) @ origin-web-common.js:764
     processQueue @ angular.js:16696
     (anonymous function) @ angular.js:16712
     Scope.$eval @ angular.js:17994
     Scope.$digest @ angular.js:17808
     Scope.$apply @ angular.js:18102
     done @ angular.js:12082
     completeRequest @ angular.js:12291
     requestLoaded @ angular.js:12219
```

**Comment by benjaminapetersen** [comment]
looking into this

**Comment by dtaylor113** [comment]
Throwing an error here:
https://github.com/openshift/origin-web-common/blob/master/src/components/create-project/createProject.js#L49

**Comment by spadgett** [comment]
@benjaminapetersen Looks like the project request does not use the API group in `ProjectsService.create()`

**Comment by benjaminapetersen** [comment]
@spadgett yup its this:

```JavaScript 
// projectService
var projectRequest = {
              apiVersion: "v1",
              kind: "ProjectRequest",
              metadata: {
                name: name
              },
              displayName: displayName,
              description: description
            };
```

**Comment by dtaylor113** [comment]
Do we have to wait until common gets a version bump and then console is changed to use the new version before we can really close this issue?  Issue isn't really 'fixed' in console yet.

**Comment by benjaminapetersen** [comment]
I think the bot auto-closed it per my comment.  Opened a PR w/a version bump a minute ago, Ill ref this bug && open a console PR now quick.
