### ISSUE TITLE
Need to document what versions of npm and node to use for origin repos.

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-console#2649]
All three origin repos (console, common, and catalog) contain `package-lock.json` files.  I believe we need to be using npm > 5.0 in order for npm to auto-update `package-lock.json`.  We should document this somewhere for developers so we're all on the same page.

We should determine npm, node, and nvm versions which are acceptable to use.

**Comment by benjaminapetersen** [comment]
My setup:
```
- node v6.10.2
- npm 3.10.10
```
If I should have `npm 5+`, then I'm def not updating the package.lock.  Not sure if we have anything validating that file.

**Comment by dtaylor113** [comment]
Would we need to update travis/jenkins to use npm 5+ as well?

**Comment by benjaminapetersen** [comment]
labelled a few things, not sure if `kind/security` is better... `package-lock.json` is pretty important for a few things.

**Comment by dtaylor113** [comment]
We have [this](https://github.com/openshift/origin-web-catalog/blob/master/.travis.yml#L5) in catalog's `.travis.yml` to ensure `npm 5+`.

**Comment by spadgett** [comment]
Looks like we're using this npm in Jenkins. It means the tests won't necessarily use the version from package-lock.json, although otherwise they should run fine. We might want to try to bump this to 5+.

npm.x86_64                    1:3.10.10-1.6.12.2.1.el7

cc @stevekuznetsov @jwforres

**Comment by spadgett** [comment]
We probably should be printing npm version somewhere in the install assets script so it's in the logs

**Comment by stevekuznetsov** [comment]
We have but one version of NPM available through `yum`:

```
$ yum list --quiet --showduplicates npm
Installed Packages
npm.x86_64                                                      1:3.10.10-1.6.12.2.1.el7                                                      @epel
```

If we want something else you'll need to install it custom in `origin-ci-tool`

**Comment by stevekuznetsov** [comment]
@spadgett every job has an `installed-packages.log` file in artifacts with a full package list

**Comment by spadgett** [comment]
Yeah that where I found the version, but it would be nice to see it directly in the logs like travis does

**Comment by dtaylor113** [comment]
@stevekuznetsov, so does what we have in Catalog repo not work?

We have [this](https://github.com/openshift/origin-web-catalog/blob/master/.travis.yml#L5) in catalog's `.travis.yml` to ensure `npm 5+`.

Catalog's travis log shows:
```
Updating nvm
$ nvm install 6
Downloading and installing node v6.12.2...
Downloading https://nodejs.org/dist/v6.12.2/node-v6.12.2-linux-x64.tar.xz...
Now using node v6.12.2 (npm v3.10.10)
$ node --version
v6.12.2
$ npm --version
3.10.10
$ nvm --version
0.33.8
before_install
$ if [[ `npm -v` != 5* ]]; then npm i -g npm@5; npm -v; fi
/home/travis/.nvm/versions/node/v6.12.2/bin/npx -> /home/travis/.nvm/versions/node/v6.12.2/lib/node_modules/npm/bin/npx-cli.js
/home/travis/.nvm/versions/node/v6.12.2/bin/npm -> /home/travis/.nvm/versions/node/v6.12.2/lib/node_modules/npm/bin/npm-cli.js
```
Could we use nvm in the other repos?  Can't actually tell if Catalog does use npm v5 with the '.travis.yml' 
@spadgett where can I view `installed-packages.log` for a Catalog PR/Build? -thanks

**Comment by spadgett** [comment]
@dtaylor113 That's Travis and not Jenkins. catalog repo doesn't run any tests in our Jenkins.

I don't think this is a huge issue necessarily since these are our dev dependencies and not what we ship. But the package-lock file is kind of useless if it's not being used by our CI. FWIW, I think package-lock was inadvertently committed in the console repo.
