### ISSUE TITLE
Membership page will not show custom roles in the filtereredRoles list by default

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#2653]
Now that we are back to a `whitelist` of roles in the web console, we have a dilemma that the console will not list custom roles (aside from the `show all roles` toggle). In theory, if a user goes through the trouble to create a custom role, it would be ideal to show that role by default, or at least give them the option somehow.  So maybe we do still need an `annotation` after all?

@jwforres @spadgett @enj

**Comment by enj** [comment]
This one is easy - _always_ show **role** objects + the whitelisted **cluster role** objects.

**Comment by benjaminapetersen** [comment]
+1 I like easy

**Comment by spadgett** [comment]
+1 to always showing roles

**Comment by benjaminapetersen** [comment]
Duplicated in bugzilla, so closing this one https://bugzilla.redhat.com/show_bug.cgi?id=1534415
