### ISSUE TITLE
Set home page modal has two different color gray backgrounds

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#2659]
![screen shot 2018-01-15 at 11 16 35 am](https://user-images.githubusercontent.com/895728/34951856-a370bf68-f9e5-11e7-972a-fc3f52865a19.PNG)

**Comment by spadgett** [comment]
The header also differs from the design here:

http://openshift.github.io/openshift-origin-design/web-console/patterns/masthead

Although as-implemented, it's probably closer to our other dialogs. Related to #2661
