### ISSUE TITLE
Need tech preview designation for pipelines

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#266]
Once https://github.com/openshift/origin/pull/10163 merges you will have to hunt to find your password, we should direct them to where they can find it.  This is temporary until we have oauth integration in jenkins.

**Comment by spadgett** [comment]
sorry @jwforres and @bparees, this is my fault

**Comment by bparees** [comment]
have to?  they *get to*.  this is a feature..... :)

**Comment by jwforres** [comment]
I'll start looking at this one
