### ISSUE TITLE
Tooltip arrow not aligned with icon on overview

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2664]
<img width="140" alt="screen shot 2018-01-15 at 7 04 24 pm" src="https://user-images.githubusercontent.com/1167259/34966071-f522b924-fa26-11e7-920d-74a3af209301.png">

/kind bug
/area styles
/priority p3
/assign @sg00dwin @rhamilto

**Comment by spadgett** [comment]
I also think it would look better if the icon were vertically centered. This spacing is a bit tight as well:

<img width="342" alt="screen shot 2018-01-15 at 7 11 24 pm" src="https://user-images.githubusercontent.com/1167259/34966178-eba49c36-fa27-11e7-9b44-18559d9737e4.png">

**Comment by sg00dwin** [comment]
@spadgett @rhamilto 
Are we ok with centering the tooltip above the `icon # text` block. Currently that's how `notification-icon` behaves. Personally I prefer having the larger hover target. 

If so would make `build-counts` to be the same. 

<img width="249" alt="screen shot 2018-01-16 at 12 55 38 pm" src="https://user-images.githubusercontent.com/1874151/35005378-31bffbcc-fac1-11e7-9893-38ded90ed279.png">
 
<img width="268" alt="screen shot 2018-01-16 at 12 58 23 pm" src="https://user-images.githubusercontent.com/1874151/35005377-31afb974-fac1-11e7-8be2-a7808bf6e91e.png">
<img width="263" alt="screen shot 2018-01-16 at 1 15 37 pm" src="https://user-images.githubusercontent.com/1874151/35005415-4dcbcee0-fac1-11e7-81bc-0ae870c7a21e.png">

<img width="186" alt="screen shot 2018-01-16 at 12 55 26 pm" src="https://user-images.githubusercontent.com/1874151/35005379-31ce6fa4-fac1-11e7-9f3b-91c226542df0.png">

**Comment by spadgett** [comment]
How does it look if there are multiple builds with different statuses?

**Comment by sg00dwin** [comment]
@spadgett 

Previous | New
------------ | -------------
<img width="167" alt="old-multiple-builds" src="https://user-images.githubusercontent.com/1874151/35008968-4125d54a-facc-11e7-8d57-9897f6cda4c9.png"> | <img width="183" alt="new-multiple-builds" src="https://user-images.githubusercontent.com/1874151/35008888-038d6572-facc-11e7-880f-6aa9e842aa17.png">

**Comment by sg00dwin** [comment]
@spadgett since we reverted back to the previous structure, is this still an issue?

**Comment by spadgett** [comment]
It still looks off to me. I assume we want it centered over the icon?
 
![screen shot 2018-01-23 at 12 31 21 pm](https://user-images.githubusercontent.com/1167259/35290809-67939b64-0039-11e8-8336-e39c18f3ede1.png)

**Comment by spadgett** [comment]
It might be horizontally centered over the icon + number, but it looks off because they aren't equal widths.

**Comment by spadgett** [comment]
I think this is very minor now. I'm just going to close.

/close
