### ISSUE TITLE
angular.module.component.controller.n.updateConfig TypeError

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#2666]
Can't quite tell where this is coming from due to `vendor.js` minification, will have to dig into it more. 

![screen shot 2018-01-15 at 9 56 38 pm](https://user-images.githubusercontent.com/280512/34969879-0117fee8-fa3f-11e7-8f9d-dc96d14a4943.png)

@spadgett @jwforres

**Comment by spadgett** [comment]
I suspect this is from the angular-patternfly update. @dtaylor113 can you take a look?

/assign @dtaylor113 
/priority p1

**Comment by dtaylor113** [comment]
Investigating
