### ISSUE TITLE
Config maps should linkify URLs

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2687]
It would nice if the URLs in config maps were clickable links:

![openshift web console 2018-01-19 09-29-42](https://user-images.githubusercontent.com/1167259/35155510-cfb27c60-fcfb-11e7-9bac-cf0d013e4ccd.png)

/assign
/priority p3
/area usability
/kind enhancement

**Comment by rhamilto** [comment]
We currently only optionally linkify in the non-truncated (expanded) text of truncate-long-text.  Presumably that's ok here?

**Comment by spadgett** [comment]
Yeah, I don't see a good way around it since we could truncate mid-URL
