### ISSUE TITLE
how to build bindata.go 

### ISSUE THREAD

**Issue by pennpeng** [openshift/origin-web-console#2694]
TODO - run script to build bindata.go from the dist in this repo 

hi , i can't find the script to build bindata.go

**Comment by spadgett** [comment]
If this is for 3.9, you need to clone the origin-web-console-server repo and run the vendor console script:

https://github.com/openshift/origin-web-console-server/blob/master/hack/vendor-console.sh

then rebuild the image

```
$ OS_BUILD_ENV_PRESERVE=_output/local/bin hack/env make build build-images 
```

For 3.8 and earlier, you run the same script, but in the origin repo:

https://github.com/openshift/origin/blob/master/hack/vendor-console.sh

/assign
/kind question
/close

**Comment by pennpeng** [comment]
@spadgett  hi，when i  run https://github.com/openshift/origin/blob/master/hack/vendor-console.sh，there is an error：
```
[root@oc-3 origin]# ./hack/vendor-console.sh 
Making sure go-bindata binary has been built...
go install: no install location for directory /home/origin/vendor/github.com/jteeuwen/go-bindata outside GOPATH
	For more details see: 'go help gopath'
go install: no install location for directory /home/origin/vendor/github.com/jteeuwen/go-bindata/go-bindata outside GOPATH
	For more details see: 'go help gopath'
[ERROR] PID 21383: hack/vendor-console.sh:23: `go install ./...` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/vendor-console.sh:23: `go install ./...`
[INFO]   Exiting with code 1.

```
i set gopath:
```
[root@oc-3 origin]# env GOPATH=/home/go ./hack/vendor-console.sh 
Making sure go-bindata binary has been built...
go install: no install location for directory /home/origin/vendor/github.com/jteeuwen/go-bindata outside GOPATH
	For more details see: 'go help gopath'
go install: no install location for directory /home/origin/vendor/github.com/jteeuwen/go-bindata/go-bindata outside GOPATH
	For more details see: 'go help gopath'
[ERROR] PID 20799: hack/vendor-console.sh:23: `go install ./...` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/vendor-console.sh:23: `go install ./...`
[INFO]   Exiting with code 1.

```

**Comment by spadgett** [comment]
@pennpeng Your `origin` directory needs be inside your `GOPATH`, for instance

```
/home/go/src/github.com/openshift/origin
```

**Comment by david-martin** [comment]
I hit this issue too locally.
Turns out I needed to have cloned the origin-web-console-server repo to within my $GOPATH
e.g. `/home/user/go/src/github.com/origin-web-console-server`

where $GOPATH is `/home/user/go`
