### ISSUE TITLE
When mini-pod-donut is visible it adds excess height to list-pf-item row, causing jump behavior when switching between deployment states. 

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#2696]
<img width="593" alt="screen shot 2018-01-22 at 11 59 31 am" src="https://user-images.githubusercontent.com/1874151/35233831-3f51fe88-ff6d-11e7-8f7e-fe7131142f7d.png">

![animatedgif](https://user-images.githubusercontent.com/1874151/35234033-d80e6120-ff6d-11e7-8d89-2e3b86ac5449.gif)

**Comment by spadgett** [comment]
We should check with metrics enabled, too.
