### ISSUE TITLE
Kebab doesn't align with list row content when metrics enabled

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2714]
The menu button is not vertically centered with the content.

![openshift web console 2018-01-24 12-49-55](https://user-images.githubusercontent.com/1167259/35348156-325f4b24-0105-11e8-8250-0e18cc8388fb.png)

/kind bug
/area styles
/priority p3
/assign @sg00dwin @rhamilto

**Comment by rhamilto** [comment]
Related to https://github.com/openshift/origin-web-console/issues/2696?

**Comment by rhamilto** [comment]
@spadgett, what's the secret to getting metrics running?  i pulled latest metrics image:

```
docker pull openshift/origin-metrics-hawkular-metrics
```

and clustered up using:

```
oc cluster up --version=latest --service-catalog --no-proxy=172.30.1.1 --metrics
```

but my pods won't run:

```
Using /usr/share/ansible/openshift-ansible/ansible.cfg as config file
ERROR! the playbook: playbooks/byo/openshift-cluster/openshift-metrics.yml could not be found
```

**Comment by rhamilto** [comment]
I suspect this was fixed with https://github.com/openshift/origin-web-console/issues/2696, but need to test once metrics are fixed.

**Comment by spadgett** [comment]
Looks OK now.

![screen shot 2018-02-13 at 3 33 59 pm](https://user-images.githubusercontent.com/1167259/36172271-587f14f0-10d3-11e8-9660-4e29959e07a8.png)

/close
