### ISSUE TITLE
Textarea can be expanded beyond the popover on Create Project

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2716]
![screen shot 2018-01-24 at 2 06 46 pm](https://user-images.githubusercontent.com/8974593/35352008-977027f8-0110-11e8-9634-5c2d536cae70.png)

**Comment by ncameronbritt** [comment]
FWIW, there seems to be some practical limit to how much text we can show for the project description--even with the hover feature. I pasted a lot more text than this in the description just to see what would happen.
![screen shot 2018-01-24 at 2 53 53 pm](https://user-images.githubusercontent.com/8974593/35354201-5530fc94-0117-11e8-828b-c09258beda5a.png)

**Comment by spadgett** [comment]
> FWIW, there seems to be some practical limit to how much text we can show for the project description

@ncameronbritt Yeah it's a known limitation. Let us know if you think it's an issue. It might depend on browser as well.

**Comment by ncameronbritt** [comment]
I don't think it's an issue, just mentioned it in case it was might be helpful to keep in mind for the fix. Like, not allowing the textarea to grow larger than the amount of content we can accommodate. Just throwing it out there.
