### ISSUE TITLE
Edit project popover doesn't point to the kebab

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2722]
![screen shot 2018-01-26 at 12 52 00 pm](https://user-images.githubusercontent.com/8974593/35453476-54a7965c-0298-11e8-9061-f3212eec18ab.png)

It happens to me regardless of screen width.

**Comment by spadgett** [comment]
/kind bug
/priority p3
/area styles
/assign @sg00dwin @rhamilto 

Looks like the same problem as #2684.
