### ISSUE TITLE
Stateful sets can be scaled from overview but not stateful set page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2723]
We should be consistent. I'm not sure there's a reason any longer to keep users from scaling them.

/assign @benjaminapetersen 
/kind bug
/priority p2

@jwforres FYI

**Comment by benjaminapetersen** [comment]
Agree, that doesn't make sense. I can look at this.

**Comment by benjaminapetersen** [comment]
Actually, I don't know if we are on the Overview page, I can scale my DC's but not my StatefulSets:

![screen shot 2018-01-30 at 10 36 48 pm](https://user-images.githubusercontent.com/280512/35604017-28d0e0e6-060e-11e8-9322-d2a96c02b3ba.png)

Investigating.

**Comment by benjaminapetersen** [comment]
Related to #2733, I'm trying to decide how to approach this/which to follow, since we have the `replicas` editor with & without the donut.

**Comment by spadgett** [comment]
Sometimes it can apparently?

![openshift web console 2018-01-31 08-45-06](https://user-images.githubusercontent.com/1167259/35626279-384ca0c8-0663-11e8-9ac1-1bca13952abc.png)

**Comment by benjaminapetersen** [comment]
Any idea why....?  I'll swing your way on that.

**Comment by spadgett** [comment]
I'm not sure why it wouldn't always be scalable.

https://github.com/spadgett/origin-web-console/blob/c5bb9ada6e7b73ba9355c7aad7b56cb6981af440/app/scripts/directives/overview/listRow.js#L142-L157

@jwforres any objection to just making stateful sets scalable now?

**Comment by spadgett** [comment]
Actually, nevermind. It doesn't work: "Reason: Cannot scale kind StatefulSet."

**Comment by spadgett** [comment]
I suspect it's the canI check that hides the arrows, but the check is skipped since I was logged in as cluster-admin.

**Comment by jwforres** [comment]
so despite you having authority to get the scale subresource on statefulsets, it still throws an error? what error code is it, 405?

**Comment by spadgett** [comment]
/assign

I have a fix as part of my fix for bug 1540916.
