### ISSUE TITLE
Can't see links when highlighted in logs

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2724]
![screen shot 2018-01-26 at 2 06 26 pm](https://user-images.githubusercontent.com/1167259/35456041-3aff986c-02a2-11e8-9d38-cfd345f6919c.png)

![screen shot 2018-01-26 at 2 06 30 pm](https://user-images.githubusercontent.com/1167259/35456043-3c3fee2a-02a2-11e8-9781-f1f82ee7a172.png)

/kind bug
/priority p2
/area styles
/assign @sg00dwin @rhamilto

**Comment by rhamilto** [comment]
https://css-tricks.com/almanac/selectors/s/selection/ to the rescue!
