### ISSUE TITLE
Change the Import YAML/ JSON dialog into a wizard

### ISSUE THREAD

**Issue by beanh66** [openshift/origin-web-console#2727]
Currently the Import YAML/JSON action can end up with a modal on a modal. See below:
https://user-images.githubusercontent.com/1874151/35239685-39a88bd4-ff7f-11e7-95a7-a0cfd5cee65b.png. Note: this is related to the issue here: https://github.com/openshift/origin-web-console/issues/2661

Revisit the design for this dialog and adjust into a wizard.

**Comment by beanh66** [comment]
@sg00dwin could you provide a clip of this flow? Not sure when the "Some items already exist" modal appears. We will need to review that and provide a design for this issue.

**Comment by sg00dwin** [comment]
Here are 2 use cases where a modal on top of existing modal appears. Is their a reason these can't be added as an additional step to the wizard?

**First scenario**
Uploading a yaml file of a replica set that already exists. The user is messaged that it already exists and must either replace or cancel before proceeding.

![create-modal-on-modal-aa](https://user-images.githubusercontent.com/1874151/36436808-607057ea-1633-11e8-8183-2ac86e3ea2ba.gif)

----
----
**Second scenario**
Before uploading a new file, in this case the sample pipeline, the user must choose a template configuration option.

![create-modal-on-modal-a](https://user-images.githubusercontent.com/1874151/36436819-657209c8-1633-11e8-948e-905df40c5d8d.gif)

**Comment by beanh66** [comment]
@sg00dwin @spadgett Met with the other designers and the following is our recommendation:

- First scenario:  Leave as is - the confirmation modal makes sense and works fine for this case. 
- Second scenario: Add steps to the wizard once they are needed:
![modals issue -01](https://user-images.githubusercontent.com/18057044/36670709-19a99b26-1ac7-11e8-8cd0-3f183185c453.png)
![modals issue -02](https://user-images.githubusercontent.com/18057044/36670708-19872820-1ac7-11e8-9ddd-f05b70397f56.png)
![modals issue -03](https://user-images.githubusercontent.com/18057044/36670707-1958f446-1ac7-11e8-872b-010a5bbc70d8.png)

**Comment by beanh66** [comment]
I want to be sure I understand the use case correctly @spadgett. Today it seems like we show the popup after the user clicks Create. Is there any scenario where we wouldn't need the user to specify whether they want to save or just process the YAML? If it would always be necessary, we should show all 4 steps to begin with!

**Comment by spadgett** [comment]
> Is there any scenario where we wouldn't need the user to specify whether they want to save or just process the YAML?

Yes. Usually you don't see any prompts. Here are the times you do:

1. If you paste YAML for a template
2. If one of the resources you're creating already exists
3. If creating a resource will put you over quota

Some of these checks require us to make requests to the server, so we don't try to perform them until the user clicks "Create."

**Comment by beanh66** [comment]
Thanks @spadgett that's what I figured. 
1. The above screenshots should make sense for this use case
2. The current implementation is fine with the confirmation modal on top of the wizard
3. Can you provide a screenshot of that use case?
