### ISSUE TITLE
Blue border can extend past bottom of tile in no deployments message

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#273]
![screen shot 2016-08-03 at 11 24 19 am](https://cloud.githubusercontent.com/assets/1167259/17371186/fa4d1f4a-596c-11e6-9fbe-ecd8d5570d1e.png)

/cc @sg00dwin @jwforres

**Comment by spadgett** [comment]
Hm, it's not just the no deployments message.

![screen shot 2016-08-04 at 2 25 00 pm](https://cloud.githubusercontent.com/assets/1167259/17413822/c5568efe-5a50-11e6-8319-46b3a85872fe.png)

**Comment by jhadvig** [comment]
Looked at this one and fixing the issue on the first screen https://github.com/openshift/origin-web-console/issues/273#issue-169160315 is quite simple, just removing `min-height`s in
https://github.com/openshift/origin-web-console/blob/master/app/styles/_overview.less#L157-L161

The second one would be a bit complicated.. one solution would be to compare the heights of services and swap them. But not sure if thats the ideal solution though :confused:
