### ISSUE TITLE
The `Configuration` tab on a ReplicationController page does not scale the same way as other resources

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#2733]
The `ReplicationController` page does not adjust to wider screens the same way that a `DC` or `Deployment` page does, possibly due to the donut

`https://localhost:9000/dev-console/project/myproject/browse/rc/rc-test?tab=details`
![screen shot 2018-01-29 at 11 52 42 am](https://user-images.githubusercontent.com/280512/35522690-02c3f858-04eb-11e8-85b6-5d360608839d.png)

`DC` page example, 1 replica, no donut:

`https://localhost:9000/dev-console/project/myproject/browse/dc/cakephp-mysql-persistent?tab=configuration`
![screen shot 2018-01-29 at 11 54 24 am](https://user-images.githubusercontent.com/280512/35522762-3094e620-04eb-11e8-8dc5-c246a02aaabc.png)

`Deployment` page example, 2 replicas, still no donut (?):

![screen shot 2018-01-29 at 11 56 16 am](https://user-images.githubusercontent.com/280512/35522880-856c5818-04eb-11e8-9af5-c2efc87d703b.png)

`ReplicaSet` page example, 2 replicas, does have a donut:

![screen shot 2018-01-29 at 12 13 54 pm](https://user-images.githubusercontent.com/280512/35523923-f745c36e-04ed-11e8-8d22-1657ec26d1b4.png)

It's a little odd when the donut appears, and when it does not.  I expect not to see a donut if we have 1 replica, but did expect to see it if 2+, but that is not the pattern.  

Also noting that the tab sets are different, `ReplicationController` and `ReplicaSet` still have a `Details` tab (`perhaps is a separate issue`):

![screen shot 2018-01-29 at 11 59 45 am](https://user-images.githubusercontent.com/280512/35523086-fe4a2292-04eb-11e8-8d1f-42474e75dfdf.png)

![screen shot 2018-01-29 at 11 59 51 am](https://user-images.githubusercontent.com/280512/35523087-fe58af88-04eb-11e8-961f-7dc4f7f6c9f4.png)

![screen shot 2018-01-29 at 12 00 00 pm](https://user-images.githubusercontent.com/280512/35523088-fe92b16a-04eb-11e8-8c25-c8454c0a7f19.png)

![screen shot 2018-01-29 at 12 04 22 pm](https://user-images.githubusercontent.com/280512/35523320-977f7db8-04ec-11e8-8e98-be694bfb2745.png)

@jwforres @spadgett

**Comment by benjaminapetersen** [comment]
I haven't labeled this yet as I'm not quite certain on the reasoning behind the differences.

**Comment by spadgett** [comment]
The donut is only there for a specific deployment version. There could be more than one donut if a rollout is in progress, so it's a little tricky. I think it's reasonable to show something like we show on the overview for that case. I'm not sure if we're pulling pods on this page at all.

/area usability
/kind enhancement
/priority p3
