### ISSUE TITLE
Deploy Image - Tag textarea sometime unavailable

### ISSUE THREAD

**Issue by 0polar** [openshift/origin-web-console#2737]
### Version
OpenShift Online v3

### Current Result
1. In project page (e.g. https://console.starter-us-west-1.openshift.com/console/project/YOUR_PROJECT_NAME/overview), click "Add to Project - Deploy Image", choose "Image Stream Tag", input tag
2. "Tag" textarea have no dropdown, user can't input/choose the tag
<img width="1235" src="https://user-images.githubusercontent.com/29332484/35546187-080c9088-056b-11e8-9b91-3761d3241226.png">

### Expected Result
1. In home page (e.g. https://console.starter-us-west-1.openshift.com/console), click "Deploy Image", choose "Image Stream Tag", input tag
2. "Tag" textarea have dropdown, user can input/choose the tag
<img width="1235" alt="2018-01-30 11_03_21-openshift web console - pale moon" src="https://user-images.githubusercontent.com/29332484/35546358-e552c0e8-056b-11e8-9432-42b0d6adf81a.png">

**Comment by spadgett** [comment]
This is also now tracked by https://bugzilla.redhat.com/show_bug.cgi?id=1541939

Closing the issue so we don't have duplicate bugs. @0polar We're still looking at the problem, but will use Bugzilla to track.

@rhamilto FYI

/close
