### ISSUE TITLE
DaemonSets shows up twice under Other Resources

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#2751]
![screen shot 2018-02-01 at 3 38 57 pm](https://user-images.githubusercontent.com/280512/35702088-19e60a08-0766-11e8-8be8-8054b04d5d61.png)

**Comment by benjaminapetersen** [comment]
Do we need a bump to common before we close this out?

**Comment by spadgett** [comment]
> Do we need a bump to common before we close this out?

@benjaminapetersen i'm ok either way :)

**Comment by spadgett** [comment]
/close

Fixed when we bumped common in #2800
