### ISSUE TITLE
Deploy from public Docker image in web console [Feature Request]

### ISSUE THREAD

**Issue by 0polar** [openshift/origin-web-console#2755]
Version: OpenShift Online v3

In web console, there is only source-to-image (Browse Catalog), there is no option to deploy from public Docker image such as `oc new-app gitlab/gitlab-ce`.

**Comment by spadgett** [comment]
From within your project, select Add to Project -> Deploy Image -> Image Name and enter a public image like `gitlab/gitlab-ce`. This will give you the same result as the `oc` command.

Note that some images won't run if they require root access. Hope this helps.

/assign
/kind question
/close
