### ISSUE TITLE
Bad wrapping of source URL after icon in image stream tag page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2770]
Note that in other places we put the external link icon after the link in the console UI

![openshift web console 2018-02-06 09-18-06](https://user-images.githubusercontent.com/1167259/35864082-b751c988-0b1e-11e8-9884-d823d764d562.png)

/area styles
/kind bug
/priority p3

@petervo

**Comment by spadgett** [comment]
/assign @rhamilto @sg00dwin 

This probably needs to be changed in the common image registry components, but assigning to Robb and Steve for now.

**Comment by rhamilto** [comment]
A markup change is all that is needed to resolve this.  https://github.com/cockpit-project/registry-image-widgets/blob/master/views/image-body.html#L10
