### ISSUE TITLE
Type error in oscRouting

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#2780]
```JavaScript 
// lin 302, looks like we assume the array exists when it might not be an array
if(!hideSlider && scope.route.alternateServices.length === 1)
```

![screen shot 2018-02-07 at 1 24 02 pm](https://user-images.githubusercontent.com/280512/35935448-8c751152-0c0e-11e8-90ef-b562c73a8d10.png)

@TheRealJon

**Comment by TheRealJon** [comment]
@spadgett @benjaminapetersen Taking a look at this now.
