### ISSUE TITLE
Service item names are align to the left

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin-web-console#2798]
After fetching the latest master and navigating to the web-catalog I see that the service item names are align to the left. I believe that the names should be align to the middle.
After some investigation I see that the ` -webkit-box-orient: vertical;` style is missing, even though it's present in dependent [less file](https://github.com/openshift/origin-web-common/blob/fcbf93f82722d5b5b4233a6c9f26932e33227564/src/styles/_mixins.less#L11)
Screens:
![download](https://user-images.githubusercontent.com/1668218/36095260-bc0c5812-0ff1-11e8-9ecb-7075b9960d20.png)
![screenshot at 2018-02-12 12-53-29](https://user-images.githubusercontent.com/1668218/36095773-e55f60ae-0ff3-11e8-8cd3-3e04a182192f.png)

 

Can reproduce in both FF and Chrome.

@spadgett @sg00dwin any idea whats causing the issue ?

**Comment by jhadvig** [comment]
So for some reason I'm not able to reproduce the issue any more. Weird. Guys could you try to pull the latest master and see if you can reproduce the issue ? If not I will close the issue. 
Thanks !

**Comment by spadgett** [comment]
@jhadvig I'm not seeing the problem. If you're running with `grunt serve`, this can sometimes happen after a `git pull` or `bower install` when the page loads before grunt has had time to finish compiling the less.

I'm going to close for now. Feel free to reopen if you can reproduce.

/close
