### ISSUE TITLE
Add a Notification Banner To Openshift Web Console

### ISSUE THREAD

**Issue by ttindell2** [openshift/origin-web-console#2804]
It would be nice to have the ability to easily set a notification banner for outages in the Openshift Web Console.

**Comment by spadgett** [comment]
@ttindell2 Is something like this sufficient?

https://docs.openshift.org/latest/install_config/web_console_customization.html#system-status-badge

**Comment by ttindell2** [comment]
Yes actually that looks pretty good. Didnt realize this existed
