### ISSUE TITLE
monitoring: prioritize salient info, deprioritize empty sections

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-web-console#2808]
I am trying to monitor some builds, so in the monitoring page I type in the names I would like to search for. My view first has pods, deployments and stateful sets in the listing. My filter matches nothing for those categories. On a smaller screen, I almost thought it was broken since I didn't scroll down to see builds. If the sections are empty from the filter or because there are no objects of that type in the namespace, maybe those sections could be placed below sections that actually have data?

/cc @spadgett

**Comment by spadgett** [comment]
@openshift/team-ux-review

**Comment by stevekuznetsov** [comment]
Or if possible since there is already a drop-down to filter by sections, set that filter programmatically.

**Comment by spadgett** [comment]
Hiding empty sections when a filter is enabled is easy enough as long as we catch the case where everything is filtered.

**Comment by cshinn** [comment]
@spadgett a good way around this may be to knock empty sections to the bottom of the list. That way, we still communicate the same message, but actual results are always visible/prioritized.
