### ISSUE TITLE
Build constantly failing without any error details!

### ISSUE THREAD

**Issue by diggschauhan** [openshift/origin-web-console#2815]
Hi
This is the first time I am using openshift so excuse any basic mistake. I added a new project pointed to public git repo. Trying to build it and getting following error. I am getting warning for babel but surely that should make the build fail? Any help would be appreciated. Thanks!

Cloning "<the repo>" ...
--
  | Commit:	567b12cc7dd3bd816a395d974deebd6adfdcfffb (removing watch)
  | Author:	jay
  | Date:	Tue Feb 20 21:28:10 2018 +0000
  | Pulling image "registry.access.redhat.@<the secret key>" ...
  | ---> Installing application source ...
  | ---> Building your Node application from source
  | npm WARN deprecated babel-preset-latest@6.24.1: We're super ߘ蠠excited that you're trying to use ES2017+ syntax, but instead of making more yearly presets ߘ� Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user ߘ We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0  a read and help test it out in beta! Thanks so much for using Babel ߙﬠplease give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
  | npm WARN deprecated babel-preset-es2017@6.24.1: ߙ젠Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
  | npm WARN deprecated babel-preset-es2016@6.24.1: ߙ젠Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
  | npm WARN deprecated babel-preset-es2015@6.24.1: ߙ젠Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

**Comment by spadgett** [comment]
Is there any more to the log?

This isn't specific to the web console, so isn't the best forum. I'd recommend the openshift users mailing list.

https://lists.openshift.redhat.com/openshiftmm/listinfo/users

@bparees any idea?

/kind question

**Comment by bparees** [comment]
no idea, would be useful to know what repo you were trying to build and to see the rest of the build log as @spadgett said.

**Comment by diggschauhan** [comment]
Thanks for replying. No that is it, hence all the more difficult to understand what is going on. I tried from terminal as well but get same logs. Is there anyway I can get detailed logs?

oc logs build/nodejs-mongo-persistent-4

**Comment by diggschauhan** [comment]
@bparees if you mean the git repo. it is https://github.com/diggschauhan/cezerin.git  

and the one in openshift is 

oc start-build nodejs-mongo-persistent -n slick

**Comment by bparees** [comment]
it's possible your container is getting OOM killed.

**Comment by diggschauhan** [comment]
Does that mean the application is trying to use more resources than allocated to it? I have 2 cores and 1 gb memory assigned to the application i think.

**Comment by diggschauhan** [comment]
Can you please let me know is it possible to run command tools in openshift 3? I couldnt find a place to import my keys for ssh connection on web console anymore? I thought may be i would connect and run commands manually to see what is going on

**Comment by spadgett** [comment]
@diggschauhan Help Menu -> Command Line Tools has a link to the download and a command to login with your token.

**Comment by diggschauhan** [comment]
@spadgett thanks i will give it a try.  and i did check and the pod says OOM killed. not sure why is that happening?

**Comment by spadgett** [comment]
> the pod says OOM killed. not sure why is that happening?

@bparees ^

**Comment by bparees** [comment]
@diggschauhan it means something (in this case probably npm) used more memory than your pod is allowed to use.  Try raising your resource limits on your build.  https://docs.openshift.org/latest/dev_guide/builds/advanced_build_operations.html#build-resources
