### ISSUE TITLE
Editing a BC triggers password manager  despite there being no obvious passwords/logins on the page

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2834]
Happens with 1Password on a Mac

[screen shot 2018-02-21 at 12 02 34 pm](https://user-images.githubusercontent.com/8974593/36494179-531b591a-16ff-11e8-8b78-0bdeea166216.png)

**Comment by spadgett** [comment]
It looks like `autocomplete="off"` fixes this for 1password at least.

/assign
/priority p3

**Comment by spadgett** [comment]
I think I spoke too soon. I had autofill disabled for localhost.
