### ISSUE TITLE
Remove extraneous "Jenkins Build" text/link on overview and pipeline page

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin-web-console#284]
Currently there is a link to the corresponding Jenkins job (labeled "Jenkins Build") throughout the UI, namely the Overview and Pipeline details page. This is sitting next to text that says "View logs".
I find it very confusing, is it going to do a Jenkins Build? "View logs" is a verb + noun, "Jenkins Build" really is noun + noun. It also doesn't buy you much since "View logs" already lands you in Jenkins within the context for that Job anyway.

It is also giving that link/text too much focus to the end user and inconsistency with other types of builds. My proposal is to remove it from the Overview and from the Pipeline listing view. If it belongs anywhere, it would be on the details page for the pipeline itself.

![screen shot 2016-08-04 at 11 06 53 am](https://cloud.githubusercontent.com/assets/727196/17407173/5af78afc-5a34-11e6-9c96-8b2b38b25973.png)

**Comment by jwforres** [comment]
would like an opinion from @ajacobs21e or @sjcox-rh on this

**Comment by sspeiche** [comment]
@ajacobs21e or @sjcox-rh let me know if you'd like to discuss. I think I have a pretty strong case on why this just seems to add some clutter at this point and highlights Jenkins a little too much.

**Comment by ajacobs21e** [comment]
@sspeiche I believe the intent is to eventually have only the link to our logs and the 'jenkins build' link is only a stopgap until we can import the log into into the console.
