### ISSUE TITLE
Streamline simple service grouping scenarios

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin-web-console#285]
Now, if I have 2 services and I want to group them it makes me select the 2nd one. It would be good/nice if user didn't have to expand drop down and select the only option.

Some possible ways to improve:
 * if only 2, don't prompt and just group
 * if only 2, have dialog show and prefill with only option...user just can hit ok

Ideally some of the services would be hidden in larger deployments, like pipelines, which give me all the jenkins gunk

**Comment by spadgett** [comment]
I can automatically select the first service.

@jwforres Do you think we should filter out infrastructure services from the list?

**Comment by jwforres** [comment]
Maybe we should not let you group a service that is already grouped to another service, that would prevent that duplication issue we were looking at earlier and would keep Jenkins services from showing up

**Comment by spadgett** [comment]
Probably a good idea, although you would still see the primary jenkins service, just not jenkins-jnlp

**Comment by jwforres** [comment]
i might argue that primary services that have children already shouldn't show up in the list either

**Comment by sspeiche** [comment]
I think it would be a very common pattern to have an already grouped service be "grouped again".
Take for example a DB service I use for multiple microservices capabilities (product catalog, payments, product reviews, ...). I do this quite often with my demo, create multiple apps (.NET or Node.js) and consume the same backend DB server (MongoDB).

**Comment by titabrado** [comment]
i created my wordpress service and mysql but when i want to group it i can't i only see create route any help
