### ISSUE TITLE
host environment variable for postgresql database

### ISSUE THREAD

**Issue by diggschauhan** [openshift/origin-web-console#2866]
Hi,
In latest version 3, i am not able to locate the host name or any environment variable related to it for postgresql database server i created. I am not sure how would i connect to it using my dot net core application (connection settings) from inside other openshift pod or for that matter outside openshift.

Any help is appreciated. Thanks!

**Comment by spadgett** [comment]
@diggschauhan Do you know if you're running with service catalog enabled? If you are, you'll see a "Provisioned Services" section on the overview. You can create binding with the connection info in a secret if using service catalog.

Here is some doc on PostgresSQL: 

https://docs.openshift.org/latest/using_images/db_images/postgresql.html

cc @bparees 
/kind question

**Comment by spadgett** [comment]
Closing since this is a question and we haven't heard back. Let us know if you still need help.

/close
