### ISSUE TITLE
Change the empty state for the Import YAML/ JSON wizard

### ISSUE THREAD

**Issue by beanh66** [openshift/origin-web-console#2868]
Can we change the Import YAML/JSON wizard to have a single line of instructions with an empty state added to the editor area to be more clear on the interaction? Proposed design below:
![proposed - code empty state](https://user-images.githubusercontent.com/18057044/36909247-813cfb7e-1e0b-11e8-875f-cddd2915780a.png)
This matches what we have done in a recent Cockpit [issue](https://github.com/cockpit-project/cockpit/pull/8434) as well. The icon color is pf-black-500.

For reference, the OpenShift Import YAML Wizard currently looks like this on initial load: 
<img width="899" alt="screen shot 2018-03-02 at 11 08 00 am" src="https://user-images.githubusercontent.com/18057044/36908703-05f0dd38-1e0a-11e8-82d0-6ff0b1854f56.png">

FYI @spadgett @openshift/team-ux-review

**Comment by ncameronbritt** [comment]
We have basically this same widget on the config map editors. I wonder how that empty state will feel on those pages. You'd get a new editor with the same empty state for every key-value pair you add. 
![screen shot 2018-03-09 at 4 14 00 pm](https://user-images.githubusercontent.com/8974593/37230379-5504be5c-23b5-11e8-84f4-62a49ea55462.png)

**Comment by ncameronbritt** [comment]
Not related to this specific issue, but something else that's a little strange in this context is that the value is not the file, as the label implies, but rather the contents of the text editor.

**Comment by beanh66** [comment]
I feel okay about showing the empty state inside that text area each time the component shows up. I agree the "Value" label is a bit strange. Do we need that or  can we change it to be more inline with the instructions suggested for the Import YAML wizard?

**Comment by ncameronbritt** [comment]
The use case here is a little more complicated than import YAML. Here the key and the value together constitute "one thing". And I wonder if users are more likely to type or paste here than on Import YAML. 

I mocked up [some ideas](https://redhat.invisionapp.com/share/SJG9H6R7U5V). But again, I think these issues are somewhat tangential to the one you opened here.

**Comment by beanh66** [comment]
Thanks @ncameronbritt, I like your ideas and good question on the expectations here. I like a combination of things from your Invision screens. The line separator, better spacing, and moving the links. Wondering if it also makes sense to move the syntax help into a tooltip on an info icon, either a single one at the top or adding them to the fields individually. Adding a mock of what I mean below:
![new mockup 10](https://user-images.githubusercontent.com/18057044/37366281-6c4b0804-26d6-11e8-9459-580ee784454f.png)

Should we create a separate issue for this you think @ncameronbritt?

**Comment by ncameronbritt** [comment]
I think it probably makes sense to separate the empty state for the text editor from this key-value editor. I believe @dtaylor113 is working on a similar editor for creating generic secrets.

Re. the helper text, I don't feel strongly one way or the other about using field-level help here. I'm not 100% convinced the Key field needs it at all. We do validation, so if you enter a duplicate key, you'll see an error if you enter a duplicate key. For the Value section, I would assume this would be consistent with whatever we do for Import YAML.

**Comment by dtaylor113** [comment]
> I mocked up some ideas. But again, I think these issues are somewhat tangential to the one you opened here.

Hi @ncameronbritt, I like [your ideas](https://redhat.invisionapp.com/share/SJG9H6R7U5V) which remove the textbox for Value, that IMO is the confusing part.  New users (like myself) tend to try to type something into that Value textbox, when (as you pointed out) the the actual 'value' is the contents of the text area (which can be directly entered or uploaded from a file).

So in this sense, I'm not sure if an empty state works as one can type into the textarea.

**Comment by ncameronbritt** [comment]
Seems like we should queue this up for the next design review.

I wonder if users are more likely to be typing or pasting into the editor for these key-value pairs than for the import YAML option. I know that all are *possible* for both cases, but which are most likely.

**Comment by dtaylor113** [comment]
Also, @spadgett mentioned that users can upload file contents with base64/binary data, not sure how that looks in the textarea/editor.

**Comment by ncameronbritt** [comment]
I think it's also worth noting--and the directions on the config map page now sort of spell this out--that you're using the *contents* of a file. Let's say I use a file for the value when I create my config map. If I go back to edit it, there's no indication of what that file was, or even that it came from a file. It's only the contents.

**Comment by beanh66** [comment]
Yeah I see what you mean @ncameronbritt since the name of the file is irrelevant, the contents are important. Curious what @gdoyle1 is thinking for the import file pattern. I know she had some examples that used the Browse link style too. It's more dev work to change the component I'm guessing but seems like it is worth exploring.

**Comment by spadgett** [comment]
> Also, @spadgett mentioned that users can upload file contents with base64/binary data, not sure how that looks in the textarea/editor.

Secrets (and in 3.10 config maps too) can have binary content, so we might have to show something else in place of the text area when the file has non-printable characters.
