### ISSUE TITLE
DISABLE_SERVICE_CATALOG_LANDING_PAGE: true results in infinite digest loop upon `grunt serve`

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#2892]
In constants.js, if DISABLE_SERVICE_CATALOG_LANDING_PAGE is set to true, an infinite digest loop occurs upon `grunt serve`-ing the console and the app doesn't fully render.

<img width="1647" alt="screen shot 2018-03-13 at 8 49 25 am" src="https://user-images.githubusercontent.com/895728/37342703-bb68c8a8-269b-11e8-8c9b-60effc5d0406.PNG">

To work around the bug, manually enter https://localhost:9000/dev-console/catalog in the browser address bar.

**Comment by rhamilto** [comment]
This appears to be Chrome-specific and related to redirection to login.

**Comment by dtaylor113** [comment]
Hi, I'm having trouble reproducing this.  I changed the value in constants.js and executed `grunt serve`, the Project List page was displayed with no errors:
![image](https://user-images.githubusercontent.com/12733153/37346176-083a9c66-26a5-11e8-8cf1-1a4b26f9933f.png)
URL is `https://localhost:9000/dev-console/catalog` but it correctly redirects to Project List.
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

Are app devs using `DISABLE_SERVICE_CATALOG_LANDING_PAGE`?  I thought this was a tech preview flag which was eventually going away.

**Comment by rhamilto** [comment]
@dtaylor113, I'm seeing the bug when I run `grunt serve` and the browser tab gets opened.  Do you have another tab that has an active session?

You may be correct that `DISABLE_SERVICE_CATALOG_LANDING_PAGE` is going away.  @spadgett?

It's also possible this bug only affects developers of the console?

**Comment by dtaylor113** [comment]
@rhamilto, yes for me a new browser tab does open, and loads the Project List page.
It would be good to understand the impact of this;  is it really a P1?  -thanks

**Comment by rhamilto** [comment]
@dtaylor113, I can also reproduce by manually changing my URL to https://localhost:9000/dev-console/ in Chrome's address bar.

**Comment by spadgett** [comment]
@rhamilto and @dtaylor113 Do either of you have a console homepage set? Might be related.

We should remove this option and the old catalog. The problem is some of our tests depend on them, so they'll need to be updated.

**Comment by dtaylor113** [comment]
@rhamilto, unfortunately, not for me.  I enter https://localhost:9000/dev-console/ and it correctly redirects to https://localhost:9000/dev-console/catalog and loads the Project List.

**Comment by rhamilto** [comment]
> @rhamilto and @dtaylor113 Do either of you have a console homepage set? Might be related.

Bingo.  That's the culprit.  I didn't realize it, but mine was set to "My Projects List".  So the bug is not browser-specific, it's specific to having a home page set.

**Comment by dtaylor113** [comment]
@rhamilto, @spadgett, ok, thanks, I see it now

**Comment by dtaylor113** [comment]
@spadgett, so is the fix to remove this option from constants.js and app.js, or make it work with `DISABLE_SERVICE_CATALOG_LANDING_PAGE`  -thanks

**Comment by dtaylor113** [comment]
> @spadgett, so is the fix to remove this option from constants.js and app.js, or make it work with DISABLE_SERVICE_CATALOG_LANDING_PAGE -thanks

nvm, I have a simple fix.

**Comment by spadgett** [comment]
I'm going to make this a P2 since this isn't a documented / supported extension.
