### ISSUE TITLE
Deploy image wizard should provide a list of tags for an image stream

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2895]
If I attempt to deploy an image from an Image Stream Tag, I should see a list of tags once I select a namespace and image stream. As a user, I would expect that if I can see namespaces and image streams listed in their respective dropdowns, then I should be able to see tags as well.  

As things are implemented now, I have to know the tag, type it and hit enter for the image metadata to be loaded. Actually, I have to click on that widget twice--once to change it to a text input and again to enter the field so I can type. 

If it is not possible to list available tags, and the user does indeed have to provide the tag, then I would expect to see that field represented as a text input rather than the dropdown selector so that the expectations are clearer. 

![screen shot 2018-03-13 at 4 50 03 pm](https://user-images.githubusercontent.com/8974593/37369611-fce84684-26df-11e8-969d-a6540660e98c.png)

**Comment by ncameronbritt** [comment]
So this works for me today, but it didn't yesterday...

**Comment by spadgett** [comment]
@ncameronbritt I suspect you hadn't yet pushed to a tag yesterday if you just deployed the template. The list will be empty if no tags exist yet. Maybe the answer is to make it more clear when that's the case.

IIRC, It is possible to type a tag name that doesn't exist yet in this dialog.

**Comment by ncameronbritt** [comment]
I believe I was having the same thing even from the openshift namespace yesterday. Maybe it was just some weird anomaly? I'll close this and reopen if I hit it again.
