### ISSUE TITLE
No line separator under select project for service catalog items

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2907]
On  the configuration step for provisioned services there is no line separator under the select project dropdown. There is for builders. 

Service:
![screen shot 2018-03-21 at 1 42 48 pm](https://user-images.githubusercontent.com/8974593/37728544-ed94cd9c-2d10-11e8-981a-13698c6fe90c.png)

Builder:
![screen shot 2018-03-21 at 2 02 26 pm](https://user-images.githubusercontent.com/8974593/37728539-e832e19a-2d10-11e8-997e-1ff6676ea0d0.png)

cc @beanh66

**Comment by beanh66** [comment]
We also use the line separator in the Deploy Image and Import YAML wizards. It's nice when "Create Project" is selected since that area then becomes 4 fields related to the project.

**Comment by dtaylor113** [comment]
Ok, I see the logic flaw in Order Service and why the divider isn't being show.  
The divider does appear for Create from Builder, Deploy Image, Import YAML, and Create from Template.
