### ISSUE TITLE
Console merge queue is broken due to change in cluster up flags

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2912]
`--version` has been replaced with `--tag` in 3.10+. This likely affects the origin-web-console-server repository as well.

See https://github.com/openshift/origin/pull/18938

/assign @jhadvig

**Comment by spadgett** [comment]
@jwforres FYI

**Comment by spadgett** [comment]
Broken for the origin-web-console-server job as well:

https://github.com/openshift/aos-cd-jobs/blob/2c26c7acaae3503a3b48ec13477bf636e897bb20/sjb/config/test_cases/test_branch_origin_web_console_server_e2e.yml#L19

**Comment by jhadvig** [comment]
PR: https://github.com/openshift/aos-cd-jobs/pull/1271

**Comment by jhadvig** [comment]
Shall I update it in [test_branch_origin_service_catalog.yml](https://github.com/openshift/aos-cd-jobs/blob/2c26c7acaae3503a3b48ec13477bf636e897bb20/sjb/config/test_cases/test_branch_origin_service_catalog.yml#L69) and [test_pull_request_origin_service_catalog.yml](https://github.com/openshift/aos-cd-jobs/blob/2c26c7acaae3503a3b48ec13477bf636e897bb20/sjb/config/test_cases/test_pull_request_origin_service_catalog.yml#L68) as well?

**Comment by spadgett** [comment]
Fixed by https://github.com/openshift/aos-cd-jobs/pull/1271
