### ISSUE TITLE
Resource type heading could use a bit of space below it

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#2915]
For example, "Deployments" sits right on top of the first row.

<img width="996" alt="screen shot 2018-03-23 at 11 18 23 am" src="https://user-images.githubusercontent.com/895728/37837682-3ce99680-2e8c-11e8-9c90-1f5254d1543e.PNG">

**Comment by spadgett** [comment]
Seems to be a regression since 3.9.

**Comment by rhamilto** [comment]
I'm guessing I caused it with the route display change on the Applications view.  SMH.  Will fix.
