### ISSUE TITLE
Application deployment issue in openshift container platform 3.6

### ISSUE THREAD

**Issue by jeetdutta10** [openshift/origin-web-console#2931]
Post installation of openshift container platform 3.6 (running on RHEL 7.4 , Docker version 1.12.6 and ansible version 2.4) which was done using ansible playbook, we are getting below issue while deploying the below application.In our Environment we have two servers:
Server1: master + 1 node
Server2: 1 node

**Error message:**
Running post commit hook ...
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
1..1
ok 1 - use inventory;
Pushing image docker-registry.default.svc:5000/test3/dancer-mysql-example:latest ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Registry server Address:
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: After retrying 6 times, Push image still failed due to error: Get https://docker-registry.default.svc:5000/v1/_ping: dial tcp 172.30.34.198:5000: getsockopt: no route to host 

**Ansible hostfile configuration while doing the installation:**
[OSEv3:children]
masters
nodes
[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=openshift-enterprise
openshift_disable_check="docker_storage,package_version"
# deployment_type will be “openshift_enterprise” for OCP
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
[masters]
xxx.ec2.internal
[nodes]
xxx.internal openshift_node_labels="{'region': 'infra'}" openshift_schedulable=true
xxx.ec2.internal openshift_node_labels="{'region': 'prod'}" openshift_schedulable=true

**Comment by spadgett** [comment]
@jeetdutta10 This doesn't seem specific to the web console, which this repository is for. I'd either ask in the openshift users mailing list or open an issue in the openshift/origin repository.

https://lists.openshift.redhat.com/openshiftmm/listinfo/users
https://github.com/openshift/origin/issues

cc @bparees 

/kind question
/close
