### ISSUE TITLE
Sorting action should be available on OpenShift Console pages

### ISSUE THREAD

**Issue by serenamarie125** [openshift/origin-web-console#2974]
A sort action should be available on OpenShift console pages.  Currently it's omitted from the majority of pages.  

Including sort capability will improve the user experience.

Associated design GH Issue: https://github.com/openshift/openshift-origin-design/issues/86

**Comment by bittner** [comment]
1. For most pages a default sort order of "last updated first" could probably make sense (e.g. Builds > Images, Resources > Secrets).
1. The project "Overview" page may need to have a "(Last Updated)" entry added to the "List By" drop-down box. Or find a different way, consistent with other pages, to display information sorted by event time.

**Comment by spadgett** [comment]
This is implemented in the 4.0 console where you can sort each table column by clicking on the header.

![pods okd 2018-11-08 13-29-57](https://user-images.githubusercontent.com/1167259/48219419-7a1bbc80-e35a-11e8-8db9-487083af650d.png)

/kind enhancement
/close
