### ISSUE TITLE
Increase DeploymentConfig name maximum length to 63 characters in Web Console

### ISSUE THREAD

**Issue by tobiasrdm** [openshift/origin-web-console#2991]
In Openshift Web Console, the DeploymentConfig name is limited to 24 characters. But in `oc` command line the maximum length is 63 characters.

It's needed to increase the Web Console limit to match the `oc` command line.

Verified in Openshift version 3.7.

**Comment by tobiasrdm** [comment]
In the source code there are 4 points with limit to 24 characters: https://github.com/openshift/origin-web-console/search?utf8=%E2%9C%93&q=maximum+length+of+24+characters&type=

**Comment by spadgett** [comment]
The limit was originally there since service names could only be 24 characters. It looks like that's no longer the case, so we should be able to increase it to 63. (Thanks for letting us know about that.)

**Comment by spadgett** [comment]
This does seem to break generated routes however since the service name + routing suffix is longer than 63 characters. I'm not sure the best way around that.
