### ISSUE TITLE
Cannot access web console with latest `oc cluster up`

### ISSUE THREAD

**Issue by dymurray** [openshift/origin-web-console#3001]
I am seeing the following error when trying to access the web console when running:
`oc cluster up --public-hostname=172.17.0.1 --enable=service-catalog,template-service-broker,router,registry,web-console,persistent-volumes,sample-templates,rhel-imagestreams`.

When I go to accept the insecure cert the browser redirects me to 127.0.0.1:8443, then I accept that cert and it redirects me to 172.17.0.1:8443/oauth/authorize?client_id=<client_id> which displays the following error:
```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"eyJ0aGVuIjoiL2NhdGFsb2ciLCJub25jZSI6IjE1MjI2NzUwMzA0MDgtMTc2Mjg4MjM0MjE1MjcxNzYwMDExNzk5OTc5OTgzMDI5ODg0MTcwMjU1OTM4NzYyODYyODQ3NjYzMzMzMDQ5NzAzMzkzODA4MzA1MCJ9"}
```

**Comment by spadgett** [comment]
@dymurray If you check `oc describe configmaps - n openshift-web-console`, does `consolePublicHostname` match what you provied in `--public-hostname`?

cc @deads2k

**Comment by dymurray** [comment]
@spadgett Not it does not. It is set to `https://127.0.0.1:8443/console`

**Comment by jmontleon** [comment]
Same here:

oc describe configmaps -n openshift-web-console 
Name:         webconsole-config
Namespace:    openshift-web-console
Labels:       <none>
Annotations:  <none>

Data
====
webconsole-config.yaml:
----
{"kind":"WebConsoleConfiguration","apiVersion":"webconsole.config.openshift.io/v1","servingInfo":{"bindAddress":"0.0.0.0:8443","bindNetwork":"tcp4","certFile":"/var/serving-cert/tls.crt","keyFile":"/var/serving-cert/tls.key","clientCA":"","namedCertificates":null,"maxRequestsInFlight":0,"requestTimeoutSeconds":0},"clusterInfo":{"consolePublicURL":"https://127.0.0.1:8443/console/","masterPublicURL":"https://127.0.0.1:8443","loggingPublicURL":"","metricsPublicURL":"","logoutPublicURL":""},"features":{"inactivityTimeoutMinutes":0,"clusterResourceOverridesEnabled":false},"extensions":{"scriptURLs":[],"stylesheetURLs":[],"properties":null}}

**Comment by jmontleon** [comment]
For workaround if I set consolePublicHostname to https://172.17.0.1:8443/console and restart the web console container it works again.

**Comment by saadlu** [comment]
> consolePublicHostname

where do you set that?

**Comment by spadgett** [comment]
@saadlu The console public URL should be based on  `--public-hostname` by default. It's not something you would want to change for cluster up most likely.

**Comment by saadlu** [comment]
@spadgett 

thanks for the reply

so trying to use `--public-hostname` with `oc cluster up`

but after entering username/password I get redirected to 127.0.0.1 over and over again

I have deleted the `openshift.local.clusterup` file and re-tried and on 3.11 it does not seem to work. 

Note that with 3.10 it does seem to work - but I can't access the URL of the dashboard from another machine the same network. Please note that ping to the hostname and nmap to the port (8443) does work from another machine. Unless of course I misunderstood public-hostname really means here.

**Comment by jmontleon** [comment]
@saadlu does logging in at  `:8443/console/catalog` instead of `:8443/console` allow you to log in? I get redirected back to a login prompt if I try to login after opening `:8443/console`, but if I log in starting at `:8443/console/catalog` I am OK.
