### ISSUE TITLE
Generic CRD support

### ISSUE THREAD

**Issue by fabiand** [openshift/origin-web-console#3007]
We had CRDs, now with Operators even more: Can the web console gain generic CRD support?

At best generic CRD and optional bundling of CRD/Operator + plugin to Web Console.

I think it's pretty optimistic to assume that every CRD will have it's own UI, thus having generic support would be good. At least to see what's going on on the cluster.

**Comment by spadgett** [comment]
CRDs should show up under Resources -> Other Resources. This gives some minimal support in the UI. At least you can list them and edit YAML.

We are working on converging OpenShift console and Tectonic console, which also has better support for CRDs as well as other admin features.

**Comment by spadgett** [comment]
We have better support for CRDs in the cluster console for 3.11 and converged console in 4.0. There is a dedicated CRDs nav item and pages for CRDs and CR instances. We're also looking at improving the printer columns in lists under https://github.com/openshift/console/pull/682

Closing since this is now implemented.

/kind enhancement
/close

**Comment by spadgett** [comment]
Here's a screenshot of the CRD list view:

![screen shot 2018-11-08 at 1 26 07 pm](https://user-images.githubusercontent.com/1167259/48219207-e649f080-e359-11e8-9e89-341747329be3.png)

**Comment by fabiand** [comment]
This is nice!

What about the CRs - are they also shown?

**Comment by spadgett** [comment]
Yeah, you can list CRs and view them (including YAML). Screenshots of an example CronTab CR:

![cr-list](https://user-images.githubusercontent.com/1167259/48277410-97af5b80-e418-11e8-9387-4a87bbf2154f.png)

![cr-details](https://user-images.githubusercontent.com/1167259/48277415-9b42e280-e418-11e8-87b8-def1556d717e.png)

**Comment by fabiand** [comment]
Nice!

Could CRDs be annotated with something in order to get a custom UI for modifying a CR of a specific CRDs?

So something for the ui which openapi  is for the api? :)
