### ISSUE TITLE
web console try to load resource from  10.1.135.64 through my browser

### ISSUE THREAD

**Issue by dove-young** [openshift/origin-web-console#3008]
I am trying OpenShift  v3.7.2-282e43f on RHEL 7.4.  Docker version 17.06.2-ce

I started openshift via `openshift start`.  I can login via `oc` and run applications in it.  

When I tried to access to the web consolse, I was stuck and redirected to this URL after timeout.

https://10.1.135.64:8443/oauth/authorize?client_id=openshift-web-console&response_type=code&state=eyJ0aGVuIjoiLyIsIm5vbmNlIjoiMTUyNzY1OTcyMzAyOC0xNTIwMDc1NjE2MjkzOTQzMzAxODI3MTExMDM1ODIzNDQ5NjUxOTM3MzkzOTg2MTg1ODE5NTI2MTQ2NjE5NjA1MjY2MzMxMDQ5MTM3MDQ3In0&redirect_uri=https%3A%2F%2F10.1.135.64%3A8443%2Fconsole%2Foauth

I got these error message in server log.

```
W0530 01:56:21.323902   12141 container_manager_linux.go:747] CPUAccounting not enabled for pid: 12141
W0530 01:56:21.323938   12141 container_manager_linux.go:750] MemoryAccounting not enabled for pid: 12141
E0530 01:56:21.667684   12141 dnsmasq.go:105] unable to periodically refresh dnsmasq status: The name uk.org.thekelleys.dnsmasq was not provided by any .service files
E0530 01:56:22.399075   12141 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: du command failed on /var/lib/docker/overlay/692eeb3e302cee63b50908a5984e58a86d363656a43c42c2a2b0058f75b5999d with output stdout: , stderr: du: cannot access ‘/var/lib/docker/overlay/692eeb3e302cee63b50908a5984e58a86d363656a43c42c2a2b0058f75b5999d’: No such file or directory
 - exit status 1, rootInodeErr: cmd [find /var/lib/docker/overlay/692eeb3e302cee63b50908a5984e58a86d363656a43c42c2a2b0058f75b5999d -xdev -printf .] failed. stderr: find: ‘/var/lib/docker/overlay/692eeb3e302cee63b50908a5984e58a86d363656a43c42c2a2b0058f75b5999d’: No such file or directory
; err: exit status 1, extraDiskErr: du command failed on /var/lib/docker/containers/c724465d8bdf07740d42387472911b5dab99cca96c8c9e25aec916e25005a872 with output stdout: , stderr: du: cannot access ‘/var/lib/docker/containers/c724465d8bdf07740d42387472911b5dab99cca96c8c9e25aec916e25005a872’: No such file or directory
 - exit status 1
E0530 01:56:51.668544   12141 dnsmasq.go:105] unable to periodically refresh dnsmasq status: The name uk.org.thekelleys.dnsmasq was not provided by any .service files
E0530 01:57:21.679808   12141 dnsmasq.go:105] unable to periodically refresh dnsmasq status: The name uk.org.thekelleys.dnsmasq was not provided by any .service files
```

And since the `10.1.135.64` is internal IP address, why you want to access to it from web browser?

```
ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1430 qdisc noqueue state UNKNOWN qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 10.1.135.64/32 scope global tunl0
       valid_lft forever preferred_lft forever
```

**Comment by spadgett** [comment]
> And since the 10.1.135.64 is internal IP address, why you want to access to it from web browser?

You should pass `--public-hostname` to `openshift start` to use a different hostname. But I'd recommend either using `oc cluster up` if you are setting up a local cluster for development or openshift-ansible if you're setting up a production cluster.

/assign
/kind question

**Comment by vorburger** [comment]
Just FYI, in case anyone else finds this by search like I just did: The equivalent of the `--public-hostname` arg to `openshift start` for openshift-ansible appears to be the `openshift_master_cluster_public_hostname` inventory variable.

However for me ([over in this issue](https://github.com/vorburger/opendaylight-coe-kubernetes-openshift/issues/7)) that doesn't really fully help - it solves the problem for the first step when the https://38.145.32.68:8443/console correctly redirects to https://38.145.32.68:8443/oauth/authorize (instead of https://openshift-master.rdocloud:8443/oauth/authorize before I set that public hostname, when I initially never even got as far as the login page), but now after I type _developer/developer_ it still wants to send me to `https://openshift-master.rdocloud:8443/console/oauth?code=...` instead of staying on 38.145.32.68.
