### ISSUE TITLE
Integrity check fails for ariya/esprima when running npm install

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#3012]
Best I can tell, jshint references a fork of esprima (master branch?) that can cause integrity checks to periodically fail when running `npm install`. Looks like we have an old version of jshint.

From package-lock.json:

https://github.com/openshift/origin-web-console/blob/master/package-lock.json#L4847-L4864

```json
        "esprima": {
          "version": "https://github.com/ariya/esprima/tarball/master",
          "integrity": "sha512-W5+ntA5gmzYpBFDpLLw7yAJPohkq5yKF8JnP9UOaXSfnKcibZQcIM9anoxztmB2NwRWLLidEseBbuCdwgQsnig==",
          "dev": true
        },
        "jshint": {
          "version": "1.1.0",
          "resolved": "https://registry.npmjs.org/jshint/-/jshint-1.1.0.tgz",
          "integrity": "sha1-mYe5C4YFVsvH84DVdVoj1QQhNRM=",
          "dev": true,
          "requires": {
            "cli": "0.4.5",
            "esprima": "https://github.com/ariya/esprima/tarball/master",
            "minimatch": "0.4.0",
            "peakle": "0.0.1",
            "shelljs": "0.1.4",
            "underscore": "1.4.4"
          }
        },
```

Ben, can you take a look?
/assign @benjaminapetersen 

@smarterclayton fyi

**Comment by benjaminapetersen** [comment]
Sure thing!  Have that dump of the integrity check handy?

**Comment by benjaminapetersen** [comment]
Leaning towards bumping `grunt-contrib-jshint` to `1.1.0` (its only one bump) and letting it take care of the dependencies.  Looking over the whole `grunt-contrib-*` block to see if we want to keep them in sync for any reason:

```javascript 
"grunt-contrib-clean": "1.0.0",
"grunt-contrib-concat": "1.0.0",
"grunt-contrib-connect": "1.0.2",
"grunt-contrib-copy": "1.0.0",
"grunt-contrib-cssmin": "1.0.1",
"grunt-contrib-htmlmin": "1.3.0",
"grunt-contrib-imagemin": "1.0.0",
"grunt-contrib-jshint": "1.1.0",
"grunt-contrib-less": "1.3.0",
"grunt-contrib-uglify": "3.0.1",
"grunt-contrib-watch": "1.0.0",
```

**Comment by benjaminapetersen** [comment]
Currently, the `espirma` `"integrity": "sha512-W5+ntA5gmz..."` is under the 
`dependencies` of `htmlhint` `"version": "0.9.6"`, which is under the dependency of 
our `grunt-htmlhint` `"version": "0.4.1"`.  I'm going to bump our `grunt-htmlhint` 
as well && see if that solves us.

For clarity:

```
- grunt-htmlhint 0.4.1
   - requires htmlhint 0.9.6
     - requires espirma master
```

**Comment by spadgett** [comment]
You should be able to reproduce this currently on the enterprise-3.9 branch.

**Comment by benjaminapetersen** [comment]
@spadgett do you think #3023 is sufficient, or also #2863, or something beyond?
I'm not sure if we have a clear path forward that makes sense.

**Comment by spadgett** [comment]
I think removing package-lock.json is probably the best thing short term. The "right" fix IMO is to switch from grunt -> webpack and jshint -> eslint, but I'm not sure how much effort to put in that since we're switching to the openshift/console base. (I don't like that we're stuck on old versions of things because we're tired to grunt.)

**Comment by benjaminapetersen** [comment]
Agree.  So maybe we are happy with the short-term fix being the long-term & just moving on...
