### ISSUE TITLE
origin-web-console cannot access from outside

### ISSUE THREAD

**Issue by eric-hon** [openshift/origin-web-console#3014]
version: origin 3.9.0， origin-web-console 3.9.0，docker 1.13.1
myhost IP: 192.168.2.86 dev1，centos 7.5 1804;
hostname: dev1
i try this:
oc cluster up --public-hostname=192.168.2.86
and cd origin-web-console  code dir,modify app/config.js two lines:
var masterPublicHostname = '192.168.2.86:8443';
var devConsoleHostname = '192.168.2.86:9000';

oc edit oauthclient openshift-web-console to see the file, some info is:
redirectURIs:
- https://192.168.2.86:8443/console
- https://192.168.2.86:9000/
- https://localhost:9000/

run the origin-web-console:
grunt serve --hostname=0.0.0.0

in the localhost's browser https://localhost:9000 is ok,

but in another host，browser  cannot link to the https://192.168.2.86:9000/ ,
how to solve it? 
thanks!

**Comment by eric-hon** [comment]
i also have a cluster:
master: 192.168.2.80
node1: 192.168.2.81
node2: 192.168.2.82

the code origin-web-console on the master,an i change masterPublicURL to 192.168.2.80 on /etc/origin/master/master-config.yaml,
i set openshift start --write-config=/opt/test --public-master=192.168.2.80
the

the oc edit oauthclient openshift-web-console is:
redirectURIs:

https://192.168.2.80:8443/console/
https://master.avit.com:8443/console/
https://localhost:9000
https://192.168.2.80:8443
https://192.168.2.80:9000
i run it: grunt serve grunt serve --hostname=0.0.0.0
another host is 192.168.100.109, but cannot access to https://192.168.2.80:9000 .

how can i solve it?

**Comment by spadgett** [comment]
When you say you "cannot access" the console, do you mean you see connection refused?

/kind question
/assign

**Comment by eric-hon** [comment]
yes,the browser was refused,no found the host.but the 8443 is OK.

**Comment by spadgett** [comment]
It needs to take you to the login page, which is part of the master, so this is expected. After you login, does it take you back to https://192.168.2.80:9000/ ?

**Comment by eric-hon** [comment]
yes,the cluster is back to login page

**Comment by eric-hon** [comment]
i solved it , because the firewalld,i stop it. thanks!

**Comment by spadgett** [comment]
Glad you got it working. Good luck!

/close
