### ISSUE TITLE
the source code origin-web-console can't connect to cluster(use ansible-playbook)

### ISSUE THREAD

**Issue by eric-hon** [openshift/origin-web-console#3027]
use ansible-playbook install the cluster is:
192.168.2.60  master-avit-1
192.168.2.61  node-avit-1
192.168.2.62  node-avit-2
and "oc edit oauthclient openshift-web-console" is:
redirectURIs:
\- https://master-avit-1:8443/console/
\- https://192.168.2.60:9000
on the source app/config.js:
var masterPublicHostname = '192.168.2.60:8443';
var devConsoleHostname = '192.168.2.60:9000';
run it:
grunt serve --hostname=0.0.0.0.
in the localhost,it can be access.(https://localhost:9000 is ok.)
and the url can be access: https://192.168.2.60:8443 is ok.
but on another host , it can't connect to cluster.( https://192.168.2.60:9000 can't connect  ).
how can i do? thanks!

**Comment by spadgett** [comment]
I would guess you have a firewall blocking the request from other hosts.

/kind question

**Comment by eric-hon** [comment]
@spadgett the cluster three hosts firewall: firewall-cmd --state,all are "not running".
