### ISSUE TITLE
Openshift web console local setup of source code update , build and redeploy with v3.9.0

### ISSUE THREAD

**Issue by demouiuser** [openshift/origin-web-console#3029]
Hello All, 

I am new with openshift development.
I have to setup openshift web console locally to change the source code, build and redeploy the openshift   web console ui with our changed source code to customize the openshift web console ui.

Can any one tell me the exact procedure of the above?

I have to work on v3.9.0.

**Comment by spadgett** [comment]
See the README for building the JS dist files:

https://github.com/openshift/origin-web-console#getting-started

Then you'll need to vendor the changes into the origin-web-console-server project:

https://github.com/openshift/origin-web-console-server#vendoring-origin-web-console

Finally you can build the origin-web-console-server image with this command:

```
$ OS_BUILD_ENV_PRESERVE=_output/local/bin hack/env make build-images
```

The 3.9 release is tagged:

https://github.com/openshift/origin-web-console/tree/v3.9.0

/kind question
/assign

**Comment by demouiuser** [comment]
Thanks for the solution,

Now, i am facing an issue with below command 
oc create namespace openshift-web-console
###############
Error from server (Forbidden): namespaces is forbidden: User "system" cannot create namespaces at the cluster scope: User "system" cannot create namespaces at the cluster scope
###############

Kindly provide resolution.
Thanks in advance.

**Comment by spadgett** [comment]
You need to be cluster-admin to create openshift-* namespaces. You might be able to use

```
$ oc login -u system:admin
```

**Comment by demouiuser** [comment]
Thanks for the update.
I am following below link to setup openshift development environment.

https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#download-from-github
I have followed below mention steps on CentOS7.
1) git clone of openshift/origin at openshift folder
2) Go to the origin folder than run below command 
    2.1 ) hack/env hack/build-base-images.sh
    2.2)  hack/env make release
Now, i have to run oc cluster up command with locally created image name
Kindly provide some suggestions on below mentioned query.

a) What would be the image name after performing the steps 2.1 and 2.2?

b) Command to up oc cluster with locally created openshift image?

After performing the web console set up using below link 
https://github.com/openshift/origin-web-console#getting-started
c) How would be connect locally created customized web console image with oc cluster up?

**Comment by spadgett** [comment]
I'd tag the image however you want and then update the webconsole deployment in the openshift-web-console namespace to use your image tag

**Comment by demouiuser** [comment]
How to tag our locally created openshift image image using "hack/env hack/build-base-images.sh" and  "hack/env make release" command?
