### ISSUE TITLE
Issue with origin-web-console ui customization environment setup

### ISSUE THREAD

**Issue by amrit28** [openshift/origin-web-console#3032]
Hello All,
I have to customize the openshift web console ui through source code.
I have followed below mentioned steps:
1 .  Git clone the origin-web-console
2. Install Nodejs and npm
3. Install grunt-cli and bower by running npm install -g grunt-cli bower
4. Install dev dependencies by running hack/install-deps.sh
5. changes the configuration specific to our ip address:
 5.1   app/config.local.js -> change local host with host ip address
 5.2  origin-web-console/Gruntfile.js -> change local host with host ip address
6.   Run command "grunt build" and  "grunt serve" in origin-web-console to launch the openshift webconsole
7.  It executed successfully and launched on https://xx.xx.xx.xx:9000
Now, when i am trying to access this url then it opens the url and suddenlly it is redirecting to 

"https://xx.xx.xx.xx:8443:8443/oauth/authorize?client_id=openshift-web-console&response_type=code&state=eyJ0aGVuIjoiLyIsIm5vbmNlIjoiMTUyOTU5ODQ4NzA1Mi0zOTM2MTcxNzYzODU3Mjg0MDA3MTY4ODM4MzE0OTQxMzQ5Nzc0OTgxOTM3MzA1NzI4Mjg1MzYxODU0MDI4MDA0NDcyNTMxNzMxNDQwNjM0In0&redirect_uri=https%3A%2F%2F172.30.65.137%3A9000%2Fdev-console%2Foauth"

and after that it shows "This site can’t be reached" error.

So, can any one provide the solution for that?

**Comment by mclitao** [comment]
vim /etc/origin/master/master-config.conf
corsAllowedOrigins:
- //127\.0\.0\.1(:|$)
- //172\.99\.0\.88:8443$
- //172\.99\.0\.88:9000  this line add ip addr
- //localhost(:|$)
