### ISSUE TITLE
Feat: UI for Cron Jobs

### ISSUE THREAD

**Issue by jesperpedersen** [openshift/origin-web-console#3038]
It would be nice to have a UI for Cron Jobs, and their status under "Other Resources".

At the moment you will have to use `oc delete cronjobs/jobname` to in order to delete, which isn't ideal when you are trying to do a complete work flow in the web console.

Thanks for considering.

**Comment by jesperpedersen** [comment]
Thanks for the feedback Sam

**Comment by spadgett** [comment]
This is implemented in the admin ("cluster") console for 3.11 and will be in the converged console for 4.0.

/close

**Comment by spadgett** [comment]
Here's a screenshot of the list view. We also have details pages for cron jobs and jobs.

![cron jobs okd 2018-11-08 13-24-56](https://user-images.githubusercontent.com/1167259/48219135-b7337f00-e359-11e8-836e-a9af1ec88ec5.png)

**Comment by jesperpedersen** [comment]
Thanks Sam !
