### ISSUE TITLE
The build  origin-web-console development exchange king kong encountered a problem

### ISSUE THREAD

**Issue by mclitao** [openshift/origin-web-console#3061]
1:yum install npm
2: npm install -g grunt-cli bower
3: bower install --allow-root
4: chmod +x ./hack/*.sh
5: make build
6: ./hack/install-deps.sh 
7: oc edit oauthclient openshift-web-console
                  14 redirectURIs:
                  15   - https://172.99.0.88:8443/console/
                  16   - https://172.16.5.88:8443/console/
                  17   - https://172.99.0.88:9000  <- change
8: vim app/config.local.js
                   var masterPublicHostname = '172.99.0.88:8443';
                   var devConsoleHostname = '172.99.0.88:9000';
9: vim Gruntfile.js
            613 baseUrl: grunt.option('baseUrl') || ("https://172.99.0.88:9000/" + contextRoot + "/")
            620 baseUrl: grunt.option('baseUrl') || ("https://172.99.0.88:9000/" + contextRoot + "/"),
            629 baseUrl: grunt.option('baseUrl') || ("https://172.99.0.88:9000/" + contextRoot + "/"),
            688 '{"redirectURIs":["' + (grunt.option('baseUrl') || "https://172.99.0.88:9000/") + '"]}'

I follow the above steps

[root@openshift origin-web-console]# grunt serve --hostname=0.0.0.0.
Running "serve" task
Running "clean:server" (clean) task
>> 1 path cleaned.

Running "wiredep:app" (wiredep) task

Running "less:development" (less) task
>> 1 stylesheet created.
>> 1 sourcemap created.

Running "copy:styles" (copy) task
Copied 74 files

Running "copy:localConfig" (copy) task

Running "replace:index" (replace) task
>> 1 replacement in 1 file.

Running "connect:livereload" (connect) task
Started connect web server on https://localhost:9000

Running "watch" task
Waiting...
(node:24826) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3

*******But I can't get certified********
Always get stuck on the login page
https://172.99.0.88:8443/login?then=%2Foauth%2Fauthorize%3Fclient_id%3Dopenshift-web-console%26response_type%3Dcode%26state%3DeyJ0aGVuIjoiLyIsIm5vbmNlIjoiMTUzNDQwNjI3MDA1Mi0xNjQ0MDI0MjMxMDcyODc2OTk3Mjg0NzUyMjkxMzMxNDg2MDg3NjQzNTczNzkyMzI0NDA3NjcwNzgzNjIwOTAzNzU0NDMxMzk4MjcwMDY1In0%26redirect_uri%3Dhttps%253A%252F%252F172.99.0.88%253A9000%252Fdev-console%252Foauth

Who can help me? Thank you very much

**Comment by mclitao** [comment]
Certification to do so
cat /opt/origin/config/master/service-signer.crt > /opt/webui/origin-web-console/tls/tls.crt 
cat /opt/origin/config/master/service-signer.key > /opt/webui/origin-web-console/tls/tls.key

**Comment by mclitao** [comment]
Failed to load https://172.99.0.88:8443/api/v1: **No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin** 'https://172.99.0.88:9000' is therefore not allowed access.
17:04:40.210 oauth?code=aMSHrlYe9KOitR34XYN0CmjiwERMsquP5BkgnP5U0KQ&state=eyJ0aGVuIjoiLyIsIm5vbmNlIjoiMTUzNDkyMzc2MDkzNC0zMjk1MzM5ODg5MTY5NDUyOTMwNzc1NzY0Nzc3ODEyNTk1MTk4NzgyOTQxMjU2MjY5MjIyMDg5Mzg0ODk0OTI4MjU3Mjg3NTE3MSJ9:1 Failed to load https://172.99.0.88:8443/apis: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://172.99.0.88:9000' is therefore not allowed access.
17:04:40.212 oauth?code=aMSHrlYe9KOitR34XYN0CmjiwERMsquP5BkgnP5U0KQ&state=eyJ0aGVuIjoiLyIsIm5vbmNlIjoiMTUzNDkyMzc2MDkzNC0zMjk1MzM5ODg5MTY5NDUyOTMwNzc1NzY0Nzc3ODEyNTk1MTk4NzgyOTQxMjU2MjY5MjIyMDg5Mzg0ODk0OTI4MjU3Mjg3NTE3MSJ9:1 Failed to load https://172.99.0.88:8443/oapi/v1: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://172.99.0.88:9000' is therefore not allowed access.

**Comment by spadgett** [comment]
You need to edit master-config.yaml on the master to allow CORS access from your IP (property `corsAllowedOrigins`)

/kind question

**Comment by mclitao** [comment]
Thank you very much @spadgett 
The problem was
