### ISSUE TITLE
RFE: periodSeconds for readiness and liveness probes in the details page and health check editor

### ISSUE THREAD

**Issue by fgiloux** [openshift/origin-web-console#3063]
Hi

In the details page of a pod it is possible to see the settings for the readiness and liveness probes that have been configured. For instance:
 Readiness Probe: GET /health on port 8080 (HTTP) 10s delay, 1s timeout
 Liveness Probe: GET /api/healthcheck on port 8080 (HTTP) 120s delay, 1s timeout

The parameter "periodSeconds" (the interval between calls) in the object definition is however missing.

In a similar way when you edit health checks of a deployment configuration it is possible to set the initial delay, the timeout for the call but not the period between calls.

It would be nice to have that.

Thanks,

Frédéric

**Comment by spadgett** [comment]
Hi, this is now possible in OpenShift 4.5. See https://github.com/openshift/console/pull/4931

For 3.x, unfortunately you will have to still edit the YAML. We don't plan to backport this change at this time.
