### ISSUE TITLE
Provide HiDPI aware favicon

### ISSUE THREAD

**Issue by jkroepke** [openshift/origin-web-console#3073]
Hi,

since https://github.com/openshift/origin-web-console/commit/5afd81a896cbcce454d6b7d8ac3e9ea6f865f9ab

the favicon (with the logo) isn't HiDPI aware anymore. On a Retina Mac the icon on browser tabs is blurred.

**Comment by spadgett** [comment]
Thanks for letting us know. This will be fixed in the 4.0 console at https://github.com/openshift/console.

Closing since this is fixed next release.

/close
