### ISSUE TITLE
Webconsole dont recognize Template Changes

### ISSUE THREAD

**Issue by ElytschaOne** [openshift/origin-web-console#3074]
Hello,

I use openshift enterprise so i dont know if this is right here. maybe i will ask for that also directly by redhat.

version: Openshift Enterprise v3.10

I want do deploy a custom template, after i deployed it, it shows up correctly when i enter:
![image](https://user-images.githubusercontent.com/43177135/45366061-33217d00-b5de-11e8-82a6-0db8c6c4b4ba.png)

but when i enter the webconsole there the template don't gets recognized.
if i reboot the openshift cluster (sometimes 1 time is enough, sometimes 2 reboots are needed) btw. after some time (15-20 minutes) the template shows up in the webconsole and is deployable.

Same thing happens when i delete the template, then it is gone when i take a look with "oc get templates" but it shows still up in the webconsole for 15-20 minutes (or for 1 btw. 2 reboots)

So my question is, is that a bug or is there a cache or something which causes this issues

**Comment by spadgett** [comment]
If you're using the Template Service Broker, it will take up to the 15 minute relist duration to update. You can force an update with

```
$ oc edit clusterservicebrokers template-service-broker
```

and increment the `relistRequests` property. You will also need to refresh the web console.

/assign
/kind question
