### ISSUE TITLE
How to lock (navigation) toolbar(s)

### ISSUE THREAD

**Issue by komajaro** [openshift/origin-web-console#3093]
Is there a way to lock the toolbar (location below) consisting of the following tabs: Details, Environment, Metrics, Logs, Events while scrolling Logs ?

Example toolbar  location:
Log into Openshift Origin -> Choose a project -> Applications -> Deployments -> deployment_name -> deployment_number

openshift v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657

**Comment by spadgett** [comment]
Yeah, the 4.0 console at https://github.com/openshift/console will scroll the log content inside the tab pane so that the top tabs are always visible. Is this the behavior you wanted?

**Comment by spadgett** [comment]
Here's a screenshot of how it looks now:

![screen shot 2018-11-08 at 1 27 52 pm](https://user-images.githubusercontent.com/1167259/48219294-24471480-e35a-11e8-8994-153580dfb278.png)

Closing as this has been implemented.

/kind question
/close
