### ISSUE TITLE
Console is blocked while waiting for selfsubjectrulesreview

### ISSUE THREAD

**Issue by emilal** [openshift/origin-web-console#3095]
We have a project where creating a selfsubjectrulesreview takes a little over 1 minute to complete. The effect is that the web console will delay drawing until the POST to create a selfsubjectrulesreview times out after 30s and returns a 504. For other projects it takes something on the order of 1s to complete.

Appending a `?request-timeout=90s` makes the request complete successfully, but would make the console even slower to render.

The user experience would be better improved if the request timeout was shortened, at least for resources that look like they have a fallback / aren't critical.

I don't know *why* creating a selfsubjectrulesreview is so slow for this project, and googling around doesn't give me the impression that slow selfsubjectrulesreviews are common.

**Comment by spadgett** [comment]
Thanks for the report. Which console and what OpenShift version are you seeing this in?

@enj Any idea why the selfsubjectrulesreview would be so slow?

**Comment by enj** [comment]
Everything backing that resource is cached so not sure what would cause the issue.  Taking over 3 seconds sounds super slow IMO...  Does that namespace have a lot of roles and role bindings?

**Comment by emilal** [comment]
Yes, turns out it did. Clearing those out fixed the problem. Thanks, and my apologies for the inconvenience. :)
