### ISSUE TITLE
3.11 web console fail to expand PVC if resourcequota defined in project

### ISSUE THREAD

**Issue by gripenk** [openshift/origin-web-console#3096]
OKD 3.11 (enabled ExpandPersistentVolumes), with Netapp Trident NAS storageclass (v18.10) (enabled allowVolumeExpansion)

I can enlarge PVC via both web console or oc cli if the project does not have resourcequota.
If project has a "hard" resourcequota on "requests.storage", I can only enlarge the PVC via oc cli. Web console fails and show "Can't be greater than ."

CentOS Linux release 7.5.1804 (Core)
ansible 2.6.5
openshift-ansible-3.11.37-1.git.0.3b8b341.el7.noarch

**Comment by cloudbehl** [comment]
@spadgett I will have a look and will try to replicate.

 Do I need to send a mail for getting added as an openshift member?

**Comment by spadgett** [comment]
@cloudbehl It'd be good to do, but shouldn't stop you from submitting a PR.

**Comment by spadgett** [comment]
It only prevents me from assigning the issue.

**Comment by cloudbehl** [comment]
> @cloudbehl It'd be good to do, but shouldn't stop you from submitting a PR.

Understood!
