### ISSUE TITLE
Projects visibility difference between oc tool and web console for system:admin user

### ISSUE THREAD

**Issue by opotmans** [openshift/origin-web-console#3103]
**#####Issue Description**
Related to Web console

**#####Description**
Seems that the project visibility is different between oc tool and web console for system:admin bug or expected feature by the openshift developers.

**#####Tools Version**
Openshift version 3.11
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

**>Steps To Reproduce**
1. Using the oc tool
oc login -u system:admin
Logged into "https://xxx.xxx.xxx.xxx:8443" as "system:admin" using existing credentials.
You have access to the following projects and can switch between them with 'oc project <projectname>':
  * default
    kube-dns
    kube-proxy
    kube-public
    kube-system
    myproject
    openshift
    openshift-apiserver
    openshift-controller-manager
    openshift-core-operators
    openshift-infra
    openshift-node
    openshift-service-cert-signer
    openshift-web-console
    system-project
I see all the projects
oc project default 
--> switch to project default
oc get pods
NAME                            READY     STATUS      RESTARTS   AGE
docker-registry-1-nvkkb         1/1       Running     0          30m
persistent-volume-setup-8gftz   0/1       Completed   0          31m
router-1-srvjs                  1/1       Running     0          30m
2. log on the web console with system:admin
don't see all the projects and the related pods
![image](https://user-images.githubusercontent.com/23280026/50397883-9beaca80-0773-11e9-8720-607e7c306d8a.png)

click on view all projects
![image](https://user-images.githubusercontent.com/23280026/50397921-dce2df00-0773-11e9-81ce-47687c4face9.png)

**##### Current Result**
difference between the oc tool and the web console for the visibility of the projects
oc tool --> see all the projects (cluster-admin)
web console --> see only the projects created with the web console of the oc tool.

**##### Expected Result**
Have a coherency for the visibility of the projects between oc tool and web console maybe a problem of right or configuration to make at the level of master.yaml...
Maybe this is an expectation to have a difference between oc command and web console or there exists an hidden command to show it via a web console.

**Comment by spadgett** [comment]
@opotmans Sorry for not responding sooner. You're almost certainly logged in as a different user from the CLI. You can't log in as `system:admin` in the console since that requires certificate authentication.

Try `Copy Login Command` from the user menu, then check `oc get projects`. You should see the same list.

/kind question

**Comment by opotmans** [comment]
Sorry for the delay of my answer but meanwhile I found the solution to my problem and switch on another problem with istio ;-)
this is a misinterpretation between the system:admin account which is used for using the oc command which is authenticated with a certificate and the system/admin account which is used with the web console.
Maybe interesting to deactivate it on the web console to avoid this misunderstanding
from my side, i just create an additional user with oc and give him the cluster-admin role to have the visibility of all the projects on the web console...


Olivier
