### ISSUE TITLE
The latest tag has a broken OperatorHub page

### ISSUE THREAD

**Issue by ghost** [openshift/origin-web-console#3107]
It used to work just a few hrs ago, not I can see that tags have been updated with the latest version and this error comes up:

![image](https://user-images.githubusercontent.com/5337267/51413428-ebd36c00-1b3c-11e9-89d2-efd7859ff26a.png)

**Comment by eivantsov** [comment]
Wrong repo. Closing

**Comment by spadgett** [comment]
Duplicate of https://github.com/openshift/console/issues/1112

/close
