### ISSUE TITLE
Issue with Web Console UI customization

### ISSUE THREAD

**Issue by ramnar** [openshift/origin-web-console#3115]
Hi,
I am trying to customize the link in Help Section->Command Line Tools->Get Started with CLI in openshift Web Console

I followed the below openshift UI Customization documentation to do the same

https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/configuring_clusters/install-config-web-console-customization

I have tried to do the following to achieve the same

- Update the yaml file of the config map of the web console as below

    extensions:
      properties: {}
      scriptURLs:
        - https://github.com/ramnar/origin-web-console/blob/master/extensions/local-extensions.js
      stylesheetURLs:
        - https://github.com/openshift/origin-web-console/blob/master/extensions/examples/online-extensions.css

Unfortunately it is not working. Any guidance regarding this will be of great help.

My end objective actually is to add a new item in the webconsole catalogue. I was trying first to see if any customization will work in the first place.

**Comment by spadgett** [comment]
The GitHub URL looks like it will serve JavaScript, but it's actually serving HTML. You'll need to host the extension somewhere that it will serve the original files with correct `Content-Type` headers. (Note that just clicking the "Raw" link on GitHub won't work since it serves the content as `text/plain`.)

/kind question
/close

**Comment by ramnar** [comment]
Hello,
i hosted the java script file in another server.Still I am not able to customize the webconsole.


Can you suggest what Iam doing wrong?
Regards,
Ram.

**Comment by spadgett** [comment]
That seems fine. Can you check in browser developer tools network tab that your JS is loaded? You could also inspect the HTML to see if there is a script tag for it.
