### ISSUE TITLE
Docker strategy is deprecated but still shown as a sample on the Cluster Console

### ISSUE THREAD

**Issue by beezerbt** [openshift/origin-web-console#3124]
hi
Before i begin, i want to make it clear that I have not tested what I am about to report on Origin, but on the Enterprise paid version.
If this negates this issue, then so be it. 
Here goes:
Openshfit details: Paid Professional version. Version Information: 
![image](https://user-images.githubusercontent.com/9202512/56493820-a6825a00-64f0-11e9-8085-352695ffc850.png)
Been trying to create a build from a Dockerfile in Openshift. Its tough going. So I tried to use the existing templates in the Cluster Console. One of which is the Docker one. When i press "Try it" it generates a sample BuildConfig, when I try to then Create it, it gives me the error: 
![image](https://user-images.githubusercontent.com/9202512/56493845-b8fc9380-64f0-11e9-8d5c-d21c572c6d1a.png)

**Comment by spadgett** [comment]
Hi, @beezerbt. It looks like the cluster admin has disabled the Docker build strategy. Any chance this is OpenShift Online? Docker build strategy is disabled in that environment.

I'd recommend building the image locally and pushing to an image registry like quay.io.

**Comment by beezerbt** [comment]
Thank you I will do so and yes that is Openshift Online indeed. Thank you for your speedy feedback.

**Comment by spadgett** [comment]
Sure thing, good luck!
