### ISSUE TITLE
auth error

### ISSUE THREAD

**Issue by jaaazzz** [openshift/origin-web-console#3133]
First，The version of my openshift origin is v1.5.0-rc0, and the version of origin-web-console is v3.11. Can this work?

The problem is that I log in to https://192.168.230.233:9000, jump to https://192.168.230.133:8443/login?then=%2Foauth%2Fauthorize%3Fclient_id%3Dopenshift-webconsole%26response_type%3Dcode%26state%3DeyJ0aGVuIjoiLyIsIm5vbmNlIjoiMTU2MTk1MDgwNzMzNi0xNzQ4NzAzODYzNzAyMzg2Mzc3Mzc4OTgyOTI1MzE5ODI3NzQ5OTE0MTc1MTY0NDU4MTI5OTk2NDg4MzM3MDUxNjMwNTIxOTk5OTQ2MTYzIn0%26redirect_uri%3Dhttps%253A%252F%252F192.168.230.133%253A9000%252Fdev-console%252Foauth , enter the account and password, jump to https://192.168.230.233:9000 blank page, and then jump to https://192.168.230.133:8443/login
![openshift](https://user-images.githubusercontent.com/15264991/60408675-7fcc5800-9bf2-11e9-88f2-83fa84da48e7.gif)
How can i fix it?Thanks!

**Comment by spadgett** [comment]
> First，The version of my openshift origin is v1.5.0-rc0, and the version of origin-web-console is v3.11. Can this work?

I don't think this is the cause of the issue you're seeing, but these versions are not compatible for other reasons. 3.11 console uses newer APIs not available in that origin version.

Have you added `https://192.168.230.233:9000/` to the redirect URLs in the `openshift-web-console` OAuthClient?
