### ISSUE TITLE
Events Table Columns Should Scale When Necessary

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-web-console#314]
It seems like the table column widths are fairly static, so often it ends up that fairly short things get truncated and two-word entries get split on lines.

![screenshot from 2016-08-08 11-31-28](https://cloud.githubusercontent.com/assets/7328370/17485435/c7594422-5d5b-11e6-9f79-a4f4cfa0b520.png)

**Comment by spadgett** [comment]
We changed it to use static widths to fix https://github.com/openshift/origin/issues/8578. It also makes the table much less jittery when typing in the filter input. Otherwise the columns constantly resize as you type.

**Comment by spadgett** [comment]
See also discussion in https://github.com/openshift/origin/pull/8636

**Comment by jwforres** [comment]
but RC events are very likely, should we be making the default width wide enough for that at least

**Comment by spadgett** [comment]
@jwforres Hm, for me, "Replication Controller" isn't wrapping. Maybe fixed in 1.3 already?

![screen shot 2016-08-11 at 9 18 22 am](https://cloud.githubusercontent.com/assets/1167259/17589783/9f5d568e-5fa4-11e6-9172-1b3d2358bc0f.png)

**Comment by spadgett** [comment]
Although long identifiers are overflowing the table.

**Comment by spadgett** [comment]
@stevekuznetsov I'm going to close given the reasoning above. I think on balance fixed widths are better for this table. Created #346 for the overflow problem, which we'll need to fix.
