### ISSUE TITLE
ConsoleExternalLogLink resource replaces only the first of two same variables in hrefTemplate field.

### ISSUE THREAD

**Issue by VladMasarik** [openshift/origin-web-console#3143]
After creating a ConsoleExternalLogLink instance, which in the `hrefTemplate` field specifies two variables of the same name, for example `${resourceNamespace}`, only the first variable is replaced by real value when displayed in the Web Console. The second variable, stays unchanged e.g. `${resourceNamespace}`.

**Comment by spadgett** [comment]
Fixed by https://github.com/openshift/console/pull/3745

Note that the 4.x console repo is openshift/console.

/kind bug
/assign
