### ISSUE TITLE
Starter plan unavailable

### ISSUE THREAD

**Issue by 5mgig** [openshift/origin-web-console#3144]
I would like to enroll in free tier for a test drive, but there's no starter plan opt on the [signup](https://manage.openshift.com/register/plan) page, only with two other premium plans pro/fuse provided, which confounds me since the starter plan is still featured on the site. Does redhat have nixed the free plan registration for openshift online but not yet announce, or it's just a hiccup?

**Comment by spadgett** [comment]
Sign-ups are temporarily disabled while we perform some logistical maintenance around adding new users. They should be available again soon. Thanks for your patience.
