### ISSUE TITLE
Web console incorrectly turns substrings into email links in template message

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#315]
This is actually an issue with the AngularJS `linky` filter.

https://docs.angularjs.org/api/ngSanitize/filter/linky

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/17489824/da765664-5d6d-11e6-9859-753c0a51611f.png)

/cc @jwforres

**Comment by jwforres** [comment]
@spadgett would the linky method you created in that other PR help us here, do we care about email links in the post-processing message?
