### ISSUE TITLE
Cannot access cluster console 3.11

### ISSUE THREAD

**Issue by freeeflyer** [openshift/origin-web-console#3158]
The "cluster console" does not work..

##### Version
```
# oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://tataouine:8443
openshift v3.11.0+bd0bee4-337
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce
1. Install OKD (with ansible, see attached inventory file here : [inventory.txt](https://github.com/openshift/origin-web-console/files/3850947/inventory.txt))
2. Connect to web console console and login (you now see the app catalog)
3. Click on "Application console" dropdown, then choose "Cluster console"

##### Current Result
"server console.apps.okd.xxx.xxx.xxx does not accept connections"
##### Expected Result
I don't know, I've never seen it work, Maybe something about nodes and all stuff about the cluster ?
##### Additional Information
see the result of command 
`oc adm diagnostics > /tmp/oc_adm_diagnostics.txt` 
here:
[oc_adm_diagnostics.txt](https://github.com/openshift/origin-web-console/files/3850949/oc_adm_diagnostics.txt)

**Comment by freeeflyer** [comment]
Well I think it may be a router problem.. my pod "router-2-deploy" is in error..

**Comment by spadgett** [comment]
Right, the 3.11 cluster console is only accessible behind a route, and it looks like your router is broken:

```
ERROR: [DClu2007 from diagnostic ClusterRouter@openshift/origin/pkg/oc/cli/admin/diagnostics/diagnostics/cluster/router.go:162]
       The "router" DeploymentConfig exists but has no running pods, so it
       is not available. Apps will not be externally accessible via the router.
```

**Comment by freeeflyer** [comment]
> Right, the 3.11 cluster console is only accessible behind a route, and it looks like your router is broken:

I came to this conclusion too..
I'm stuck and I don't know how to diagnose my router (or router deployment pod) problem
All I have as a diagnosis stuff is that :
```
# oc logs pod/router-2-deploy
--> Scaled older deployment router-1 down
--> Scaling router-2 to 1
error: update acceptor rejected router-2: pods for rc 'default/router-2' took longer than 600 seconds to become available
```

When it is trying to launch the actual router pod the only thing I have is that: 
```
# oc logs pod/router-2-29vg7
I1115 17:33:15.874559       1 template.go:297] Starting template router (v3.11.0+bd0bee4-337)
I1115 17:33:15.878996       1 metrics.go:147] Router health and metrics port listening at 0.0.0.0:1936 on HTTP and HTTPS
E1115 17:33:15.890563       1 haproxy.go:392] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: no such file or directory
```

I'm a bit lost.

**Comment by spadgett** [comment]
cc @ironcladlou

**Comment by freeeflyer** [comment]
As it seems to be a router issue, I've put it there : https://github.com/openshift/router/issues/63

**Comment by spadgett** [comment]
Thanks, closing in favor of openshift/router#63

/close
