### ISSUE TITLE
Multi Master - Web Console Not Working

### ISSUE THREAD

**Issue by garrotemar** [openshift/origin-web-console#3165]
I have a cluster with 3 masters and 4 compute nodes.
Initially my cluster was 1 master and 2 nodes, then I added 2 masters and 2 compute nodes. After a while and restart several times api and controllers, I find that I cannot log into the development console https://master0.example.com:8443. When I try to authenticate, it redirects me to another master
https://master1.example.com:8443 and won't let me authenticate.

This with a single master did not happen to me.

OKD 3.11

Regards ... Marcelo

**Comment by spadgett** [comment]
I'm not sure all the config that needs to change to add masters. You really want to set that up when installing a cluster. Are your masters behind a load balancer? Console expects a single public hostname for the API server.

Note that the docs call out moving from a single master to multiple masters after install as unsupported:

https://docs.openshift.com/container-platform/3.11/install/example_inventories.html#multiple-masters

**Comment by garrotemar** [comment]
My architecture is "Multiple Masters Using Native HA with Co-located Clustered etcd" without the LB. In other words, the Application Console does not have it balanced, if the console (routes) yes, through an external load balancer.

Thanks ... Marcelo
