### ISSUE TITLE
Browse Other Resources errors when CRD plural is complicated

### ISSUE THREAD

**Issue by afcollins** [openshift/origin-web-console#3168]
Description:
A CustomResourceDefinition defines a "broken plural", i.e. that is more than adding an 's' to the singular name.  Example: singular='index', plural='indexes'

Browse > Other Resources page is unable to fetch these objects, and throws errors.
Also, Add to Project > Import YAML is unable to import valid resources of the CRD Kind (that can indeed be created via CLI).

Version: enterprise 3.11.146

Actual behavior:
1) An error is thrown claiming 'Unknown resource: indexs/group.company.com/v1'
1) valid resources of the CRDs of that Kind are not shown.
2) valid resource manifests of the CRD cannot be imported as YAML through the UI.

Expected Behavior:
1) Web Console uses the configured spec.names.plural from the CRD, when available, in both Add to Project > Import YAML and Browse > Other Resources.

**Comment by BrianBreniser** [comment]
Reproducible in the openshift playground

[openshift_plural_bug.gz](https://github.com/openshift/origin-web-console/files/4228359/openshift_plural_bug.gz)

Example files that can reproduce the bug on https://learn.openshift.com/playgrounds/openshift311/

Notice how the badcustomobject.yaml can be created with `oc create -f badcustomobject.yaml` but cannot be created by the "Import YAML / JSON" dropdown of the web console.

**Comment by spadgett** [comment]
This was fixed as part of https://bugzilla.redhat.com/show_bug.cgi?id=1753601. Please update to 3.11.161 or newer. If you still see the problem, feel free to reopen the issue. Thanks!

**Comment by spadgett** [comment]
Closing as this is fixed in the latest 3.11.

/remove-lifecycle stale
/close
