### ISSUE TITLE
Cannot open web console

### ISSUE THREAD

**Issue by lian233** [openshift/origin-web-console#3169]
step 1:
docker run -d --name "origin" \
        --privileged --pid=host --net=host \
        -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
        -v /var/lib/docker:/var/lib/docker:rw \
        -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes:rslave openshift/origin start

step 2:
open  https://172.16.8.27:8443/console

![image](https://user-images.githubusercontent.com/14799111/79295794-31334480-7f0c-11ea-8c63-99ace3b93c2c.png)

**Comment by spadgett** [comment]
Running OpenShift this way does not install the web console since it is no longer part of the master. You'll need to use `oc cluster up` instead.

https://github.com/openshift/origin/blob/release-3.11/docs/cluster_up_down.md

**Comment by lian233** [comment]
oh  thank you
