### ISSUE TITLE
Do not reveal information on error pages and when not authenticated

### ISSUE THREAD

**Issue by klaus-halfmann** [openshift/origin-web-console#3177]
As of some security assessment we found that the console will reveal a lot of information even when showing 
an error page or even when use is not authenticated. E.g. I found:
    <script type="text/javascript">
window.SERVER_FLAGS = {
	"consoleVersion":"v6.0.6-10295-g53a543b19",
	"authDisabled":false,
	"kubectlClientID":"",
	"basePath":"/",
	"loginURL":"https://console-openshift-console...",
	"loginSuccessURL":"https://console-openshift-console....",
	"loginErrorURL":"https://console-openshift-console...",
	"logoutURL":"https://console-openshift-console....",
	"logoutRedirect":"",
	"requestTokenURL":"https://oauth-openshift....",
	"kubeAdminLogoutURL":"https://oauth-openshift....",
	"kubeAPIServerURL":"https://api.de99.qivicon.com:6443",
	"prometheusBaseURL":"/api/prometheus",
	"prometheusTenancyBaseURL":"/api/prometheus-tenancy",
	"alertManagerBaseURL":"/api/alertmanager",
	"meteringBaseURL":"/api/metering",
	"branding":"azure",
	"customProductName":"",
	"customLogoURL":"",
	"statuspageID":"","
	"documentationBaseURL":"https://docs.openshift.com/container-platform/4.5/",
	"alertManagerPublicURL":"https://alertmanager-main-openshift-monitoring...",
	"grafanaPublicURL":"https://grafana-openshift-monitoring...",
	"prometheusPublicURL":"https://prometheus-k8s-openshift-monitoring....",
	"thanosPublicURL":"https://thanos-querier-openshift-monitoring...",
	"loadTestFactor":0,
	"GOARCH":"amd64",
	"GOOS":"linux"};
    </script>

This can be used to determine exact versions and other attack vectors, which should be avoided.

Expected:
* When console is called without authentication no such information is revealed.
* In case of Error pages (404, 502 ...) No interval information is shown.
* In case of normal operattion only the need information is revealed
** which part of the portal needs the GOARCH or GOOS information?

Its OK to switch on/off this feature we a flag, so developer builds will not be affected.

In case I am wrong here please direct me to the correct place ...

**Comment by spadgett** [comment]
Hi, sorry for the delay in responding. https://github.com/openshift/console is probably the repo you meant.

Version information is available outside of the console using the API server version endpoint. We've previously had a Bugzilla on this (https://bugzilla.redhat.com/show_bug.cgi?id=1437573), but we have opted not to change this for the following reasons:

* Upstream Kubernetes' stance is that the version is public information, and we don't want to drift from upstream
* There is a small set of known attack vectors today – they could just try them all.... It would only (minimally) slow attacks down to not know the version information
* Security through obscurity is not a long-term security solution

**Comment by klaus-halfmann** [comment]
OK, I will tell our Security People ....
