### ISSUE TITLE
Where can I configure the session cookies to be non-persistent?

### ISSUE THREAD

**Issue by klaus-halfmann** [openshift/origin-web-console#3178]
As of a security Assessment we must make the openshift session cookies non-persistent.
And valid for a maximum of 12 hours.

Please give me a hint wher and how in openshift I may configure this.

The docs at e.g. https://docs.openshift.com/container-platform/4.6/rest_api/config_apis/console-config-openshift-io-v1.html do not help me in any way

With openshift 4.6 some aspectes of the cookie can be configured
[Configuring the internal OAuth server](https://docs.openshift.com/container-platform/4.6/authentication/configuring-internal-oauth.html)

Still checking the persistany of that cookie.

**Comment by spadgett** [comment]
Hi, sorry for the delayed response. For 4.6, you should open issues in the openshift/console repo. This is the repo for the 3.x console.

You can configure the OAuth access token duration using this procedure:

https://docs.openshift.com/container-platform/4.6/authentication/configuring-internal-oauth.html#oauth-configuring-internal-oauth_configuring-internal-oauth

That will not change the expiration of the cookie itself in the browser, but the session will expire and not longer be valid. It's also possible to configure an inactivity timeout, which the web console will honor.
