### ISSUE TITLE
OKD - Failed to pull image "docker.io/openshift/origin-console:v3.11.0"

### ISSUE THREAD

**Issue by gmanera** [openshift/origin-web-console#3182]
I am experiencing a critical issue with my OKD cluster where I'm unable to reestablish the Web Console UI. The pod responsible for the console is failing to start, showing an ErrImagePull error status.

When I try to pull the image docker.io/openshift/origin-console:v3.11.0 directly on the node, it also fails, stating that the repository does not exist or there is no pull access. Is the repository discontinued?

Here is the error log for your reference:

[core@praiadoluz ~]$ oc get pods -n openshift-console
NAME                      READY   STATUS         RESTARTS   AGE
console-8b77cb7b4-qqphx   0/1     ErrImagePull   0          7s

And the describe pod output:

Status:         Pending
IP:
IPs:            <none>
State:          Waiting
  Reason:       ImagePullBackOff
...
Events:
  Warning  Failed          9s               kubelet            Failed to pull image "docker.io/openshift/origin-console:v3.11.0": rpc error: code = Unknown desc = repository docker.io/openshift/origin-console not found: does not exist or no pull access
  Warning  Failed          9s               kubelet            Error: ErrImagePull

Environment:

    OpenShift version: 3.11.0
    Node: okd-master01.sol.gabriela.br/10.30.132.9
    Kubernetes Version: v1.11.0+d4cacc0
    OS: v3.11.784

Attempts to Resolve:

    Tried pulling the image directly from the node, which also failed.
    Checked network connectivity and confirmed that's not the issue.

Questions:

    Has the repository been moved or deprecated?
    What are the alternative steps to reestablish the Web Console?

**Comment by vinibodruch** [comment]
I couldn't find the repo either in the dockerhub, I've got error 404. It seems like it was deleted or something like that.


- ![image](https://github.com/openshift/origin-web-console/assets/39421214/45128a76-9a2e-4482-ab83-e5c363aeca6a)
- ![image](https://github.com/openshift/origin-web-console/assets/39421214/7fcee864-567a-4500-ac5f-01a915084172)-
- ![image](https://github.com/openshift/origin-web-console/assets/39421214/abcd588e-419a-482c-9357-da1dc031febb)
