### ISSUE TITLE
Top nav dropdowns are appearing lower than they should

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#323]
The distance between the content of the nav items and where the dropdown appears seems off

![nav_dropdown](https://cloud.githubusercontent.com/assets/1467629/17517449/8081c766-5e11-11e6-8cb0-98609485699c.png)

**Comment by rhamilto** [comment]
@sg00dwin, do you recall if this is always how they have been positioned?  @jwforres, are you suggesting this is a regression or just something you noticed?

**Comment by jwforres** [comment]
Just something I noticed

**Comment by sg00dwin** [comment]
@rhamilto these were part of the pf alt nav

**Comment by rhamilto** [comment]
Moar betta, @jwforres and @sg00dwin?

![screen shot 2016-08-16 at 10 25 18 am](https://cloud.githubusercontent.com/assets/895728/17702412/ca08db1a-639b-11e6-82ba-ae2ae4a6d83d.PNG)

**Comment by jwforres** [comment]
I think that looks better
