### ISSUE TITLE
Env variable editor should warn if you navigate away with unsaved changes

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#332]
It's easy to miss the Save button on the page and navigate away with unsaved changes when editing environment variables. We should prompt users before losing their edits.

**Comment by benjaminapetersen** [comment]
Looking at this & fishing around to see if we have prompts setup anywhere else already.

**Comment by beanh66** [comment]
@benjaminapetersen Not sure if you found instances of this type of prompt anywhere else but I noticed this issue which is probably similar: https://github.com/openshift/origin-web-console/issues/1095

I think the two should be visually consistent!

**Comment by spadgett** [comment]
This was fixed as part of https://trello.com/c/aeh71wF7
