### ISSUE TITLE
Sort dropdown for events table looks like it controls what to filter

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#333]
Using 1.3.0-alpha.3 I filter by Reason:

![image](https://cloud.githubusercontent.com/assets/78350/17526698/a559334c-5e68-11e6-88d8-e6e66dd19e5e.png)

I type in the keyword something and the filter does act on the whole event:

![image](https://cloud.githubusercontent.com/assets/78350/17526725/c42143c8-5e68-11e6-8ead-ccb5d562b4f8.png)

And also:

![image](https://cloud.githubusercontent.com/assets/78350/17526735/d0c0353a-5e68-11e6-99b6-269b681623aa.png)

**Comment by spadgett** [comment]
Some discussion on the Patternfly sort select in another PR starting here:

https://github.com/openshift/origin-web-console/pull/199#issuecomment-234575909

@ajacobs21e We might want a label on the sort control after all. When placed beside a filter, it looks like you're selecting something to filter, not sorting the table.

**Comment by spadgett** [comment]
@MarkDeMaria FYI
