### ISSUE TITLE
Usability issue attaching domain name to route 

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin-web-console#336]
When creating a route, it is unclear how to direct a personal domain name to your app. A "Hostname" can be provided (see attached image), however no public IP address or hostname is found anywhere to point the domain name to.

In OpenShift V2, you could create a CNAME record and point it to the host name that was automatically generated when creating an app, this does not seem to be the case in V3.

![screenshot from 2016-08-09 18-19-25](https://cloud.githubusercontent.com/assets/3902875/17535657/f454b22e-5e5d-11e6-8e25-2a56389a6eca.png)

**Comment by spadgett** [comment]
This is all I can find in the docs:

https://docs.openshift.org/latest/dev_guide/routes.html

> DNS resolution for a host name is handled separately from routing; your administrator may have configured a cloud domain that will always correctly resolve to the OpenShift Origin router, or if using an unrelated host name you may need to modify its DNS records independently to resolve to the router.

But I don't see any instructions for getting the router's IP address to set that up.

/cc @jwforres

**Comment by juanvallejo** [comment]
@spadgett  Thanks for the help! Turns out I needed to:
- Leave the "Hostname" field blank for it to create a route with an automatically generated
- Update my domain name DNS settings - create a CNAME record that points to the automatically generated hostname from the previous step
- Create a second route with the "Hostname" pointing to my domain name

Working example (hack day app): http://v3.pictre.org/cats

**Comment by jwforres** [comment]
Based on the discussion we had with @liggitt it sounds like we really need some kind of support from the router writing back to the routes to do anything better here, you need to know how the router that is serving your particular route is exposed externally.

**Comment by qimuxi1990** [comment]
@juanvallejo I have tried your solution: 1. auto-generate host. 2. add CNAME DNS record. 3. create new route with the domain name in CNAME record.
But it does not work properly, throwing an **'Application is not available'** Page.

**auto-generated host works fine:** [welcome to openshift](http://nodejs-mongodb-example-qimuxi1990-nodejs-ex.44fs.preview.openshiftapps.com/)

**new route:** [my domain](http://www.muxiqi.com)
![image](https://cloud.githubusercontent.com/assets/11479458/19191076/d3c1c846-8c6e-11e6-81d1-6e79011215ab.png)

**Route Settings:**
![image](https://cloud.githubusercontent.com/assets/11479458/19191064/c72638c4-8c6e-11e6-9397-0e45878dd4de.png)

Did I do something improper? Thank you!

**Comment by juanvallejo** [comment]
@qimuxi1990 it looks like you've followed the  steps fine. Check your `Target port` though, you don't seem to have one set for the auto-generated hostname.

**Comment by qimuxi1990** [comment]
@juanvallejo I have changed it to web (8080/TCP) now. This auto-generated hostname still works fine but the new route still shows **Application is not available**.

![image](https://cloud.githubusercontent.com/assets/11479458/19199634/f50350c8-8c92-11e6-87d0-df68c5d1c31e.png)

There YAML:
auto:
```YAML
apiVersion: v1
kind: Route
metadata:
  name: nodejs-mongodb-example
  namespace: qimuxi1990-nodejs-ex
  selfLink: /oapi/v1/namespaces/qimuxi1990-nodejs-ex/routes/nodejs-mongodb-example
  uid: de36b339-8bdd-11e6-ad3a-0e3d364e19a5
  resourceVersion: '216237582'
  creationTimestamp: '2016-10-06T15:59:31Z'
  labels:
    app: nodejs-mongodb-example
    template: nodejs-mongodb-example
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: nodejs-mongodb-example-qimuxi1990-nodejs-ex.44fs.preview.openshiftapps.com
  to:
    kind: Service
    name: nodejs-mongodb-example
    weight: 100
  port:
    targetPort: web
status:
  ingress:
    -
      host: nodejs-mongodb-example-qimuxi1990-nodejs-ex.44fs.preview.openshiftapps.com
      routerName: router
      conditions:
        -
          type: Admitted
          status: 'True'
          lastTransitionTime: '2016-10-06T15:59:31Z'
```
mine:
```YAML
apiVersion: v1
kind: Route
metadata:
  name: my
  namespace: qimuxi1990-nodejs-ex
  selfLink: /oapi/v1/namespaces/qimuxi1990-nodejs-ex/routes/my
  uid: 11c719b3-8c8b-11e6-8a06-0ebeb1070c7f
  resourceVersion: '216268505'
  creationTimestamp: '2016-10-07T12:39:20Z'
  labels:
    app: nodejs-mongodb-example
    template: nodejs-mongodb-example
spec:
  host: www.muxiqi.com
  to:
    kind: Service
    name: nodejs-mongodb-example
    weight: 100
  port:
    targetPort: web
status:
  ingress:
    -
      host: www.muxiqi.com
      routerName: router
      conditions:
        -
          type: Admitted
          status: 'True'
          lastTransitionTime: '2016-10-07T12:39:20Z'
```

**Comment by juanvallejo** [comment]
@qimuxi1990 hm, everything looks fine to me, can you post the yaml for your `nodejs-mongodb-example` service? (its type should be `ClusterIP`)

**Comment by qimuxi1990** [comment]
@juanvallejo okay, here it is:
```YAML
apiVersion: v1
kind: Service
metadata:
  name: nodejs-mongodb-example
  namespace: qimuxi1990-nodejs-ex
  selfLink: /api/v1/namespaces/qimuxi1990-nodejs-ex/services/nodejs-mongodb-example
  uid: de39aee3-8bdd-11e6-ba92-0e63b9c1c48f
  resourceVersion: '212528295'
  creationTimestamp: '2016-10-06T15:59:31Z'
  labels:
    app: nodejs-mongodb-example
    template: nodejs-mongodb-example
  annotations:
    description: 'Exposes and load balances the application pods'
spec:
  ports:
    -
      name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: nodejs-mongodb-example
  portalIP: 172.30.33.225
  clusterIP: 172.30.33.225
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer:
```

**Comment by juanvallejo** [comment]
@qimuxi1990 Could you try adding this line under `spec.selector`? (either above or below the `name` field)
```
app: nodejs-mongodb-example
```
 Everything else looks okay, so if this does not work, I would try re-deploying your app

**Comment by qimuxi1990** [comment]
@juanvallejo After that the service moved to the bottom red circle (it was at the top red circle previously):

![image](https://cloud.githubusercontent.com/assets/11479458/19201068/166dd7c2-8c9a-11e6-8e59-169e59cc3035.png)

And the auto-generated route does not work and throws '503 Service Unavailable' after that, while the user-created one stills shows the 'Application is not available'.

I tried re-deploying, rebuilding, but no one works.

**Comment by juanvallejo** [comment]
@qimuxi1990 Hm, try undoing the last step (remove `app: nodejs-mongodb-example`). It looks like the issue might be at the cname record; are you setting it so that it points to the auto-generated hostname on your domain name settings?

**Comment by qimuxi1990** [comment]
@juanvallejo 
Yes, the record is: 
![image](https://cloud.githubusercontent.com/assets/11479458/19250064/7debe646-8f06-11e6-992c-e76577dd0fb0.png)

And also I found an URL forwarding will do the trick, redirecting to the auto-generated hostname and show the page. But the URL address in address bar is the auto-generated hostname, which is not exactly what I want.

Thank you!

**Comment by juanvallejo** [comment]
@qimuxi1990 :/ everything looks to be fine, not sure why it's still not working with a CNAME record. @enj Care to give this a look?

**Comment by enj** [comment]
@juanvallejo I don't see anything wrong based on what's posted here / from curl / DNS.  Perhaps compare your working Route and Service yaml files to @qimuxi1990's?

**Comment by jwforres** [comment]
@mfojtik effectively to fix the usability problems around this we would need to know for a particular Route what the external IP address is for the router serving the route.  Not sure this is even possible.

**Comment by mfojtik** [comment]
@jwforres I would ask somebody in networking team @knobunc ?

**Comment by knobunc** [comment]
You could get the IP address for the router, but there may be multiple routers that serve the route, and they may have different configuration.  Also, you really don't want the IP address, you want to set the DNS for your domain to a CNAME for the router so that IP changes don't break your DNS.  And we can't know what DNS name the router admin prefers we use.

In my mind it is up ti the cluster admins to publish information on what routers people should use, and what dns name to set the CNAME to.

This is the same as bug 1347822 [link](https://bugzilla.redhat.com/show_bug.cgi?id=1347822).

**Comment by spadgett** [comment]
> In my mind it is up ti the cluster admins to publish information on what routers people should use, and what dns name to set the CNAME to.

@knobunc Is it reasonable to add some config option or annotation an admin can set with this info? Then web console could show it when the user is looking at the route.

**Comment by knobunc** [comment]
@spadgett but what would set the annotation?

The best I can see is that you would tell the router (through an ENV or something) what it's canonical DNS name is (that the admin wants it to advertise).  And, if set, it would set some standard annotation on the route object.

The problem with that is that a single route can be served by multiple routers, so then which would write the annotation?

You could put the information into the router status that each router writes to the route.  But then the GUI may have multiple choices to show the user, and they would need docs from the cluster admin to know which to use.

Thoughts?

**Comment by spadgett** [comment]
Ideally it's something the system would set, but if not possible (for all the reasons you give), even a message or a link the cluster admin can set in master-config.yaml would help. Otherwise, how will a user know where to find this information?

We do something similar for project requests:

https://docs.openshift.org/latest/admin_guide/managing_projects.html#disabling-self-provisioning

There is a custom `projectRequestMessage` that we show when a user can't create a project in web console.

**Comment by liggitt** [comment]
I'd expect that information to show up in the route status. Need to allow for per-router information here

**Comment by knobunc** [comment]
@liggitt so, we take an optional per router "DNS name setting" and pass that through in the per-router route status?  Is this better than just getting the router id from the status and reading an annotation on the router pod?

**Comment by liggitt** [comment]
Wouldn't the router be responsible for setting that information in the status? Also, normal users can't see the router pod, and I'd expect information like this to be more structured than an annotation

**Comment by knobunc** [comment]
The router can set that.  But it needs to be told the DNS name that it should advertise.  It should not be posting the IP address (well, at least not by default) because the IP address we know may not be the one they want to use outside.  And they probably should be using a DNS name not an IP anyway so that the people consuming the information are isolated from IP address changes.

(And sorry for making your message look silly, I realized as soon as I hit post that people may not be able to read the router pod, so I edited and deleted it)

**Comment by liggitt** [comment]
sure, option to the router for what to record would make sense... I wouldn't depend on the router auto-determining its own IP or assuming that is the right thing to record

**Comment by knobunc** [comment]
Opened Trello card https://trello.com/c/BLASUOQC

**Comment by pecameron** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1393489

**Comment by luvemil** [comment]
So, what is the proper way of setting up a custom domain name? The solution proposed above to
- create a route with an automatically generated hostname
- add a CNAME record to my domain that points to that
- create a new route with my domain
doesn't seem to work. I get a 503 response with "Application not available". Inspecting the HTTP request I can see that it is sent to the same IP as the hostname provided by OpenShift, so I guess the CNAME record resolves correctly.

I guess the only solution for now is to do a hard redirect?

**Comment by pecameron** [comment]
@luvemil please take a look at openshift/origin pr 12195, comments are welcome.

**Comment by bulejava** [comment]
how to resolved? i have the problem? @spadgett  
is custom domain not supported?https://bugzilla.redhat.com/show_bug.cgi?id=1404221

**Comment by spadgett** [comment]
@bluejava Based on the bug you've linked, I'm guessing you're asking about OpenShift Online? I don't believe custom routes are supported yet for Online. See

https://docs.openshift.com/online/dev_guide/routes.html#custom-route-and-hosts-and-certificates-restrictions

**Comment by bulejava** [comment]
@spadgett 
i just want to using my domain(www.duomaile.com) to open this page whis is accessed by  http://simple-web-9pbm.1d35.starter-us-east-1.openshiftapps.com/
but now show "Application is not available", but  cloud domain which generated by openshif is ok.
domain cname is done ，www.duomaile.com  is linked to openshif success,but cant reach my app


![333](https://cloud.githubusercontent.com/assets/7552764/26556953/5f164736-44d0-11e7-8115-74f999454a88.png)

**Comment by sspeiche** [comment]
Customer domains aren't available in Online Starter, see https://www.openshift.com/pricing/index.html

**Comment by bulejava** [comment]
@sspeiche thank u,maybe disable this feature for starter is a better User Experience

**Comment by spadgett** [comment]
@bulejava I agree it's confusing the UI lets you set it when it won't work.

cc @jwforres

**Comment by sspeiche** [comment]
@bulejava yes, was thinking the same thing. Thanks for the feedback

cc @abhgupta

**Comment by trickeyd** [comment]
Hi - Had the same problem and eventually found this page. Looking at the pricing page linked above there is no payed, or 'pro' option available yet. So how are people managing to do this exactly? 

I am very confused as to what I have been spending time working on if there is no upgrade option. Information seems very hard to come by. Everything seems to be about the legacy v2 which I also can't sign up for now.

**Comment by spadgett** [comment]
@trickeyd OpenShift Online Pro was announced today:

https://blog.openshift.com/announce-pro-tier/

**Comment by irfanfadilah** [comment]
Holy sh*t, this is works: https://github.com/openshift/origin-web-console/issues/336#issuecomment-238880987 I've been looking for this, thanks!

Btw, I'm free user too, but custom domain is working fine, basically you need 2 Routes, one auto generated, and one using your domain name, e.g.: app.example.com, don't forget to set your DNS too.

**Comment by sspeiche** [comment]
To be clear, custom domains on free (starter) tier shouldn't work and is reserved for the paid (pro) tier, it is a bug. See https://www.openshift.com/pricing/index.html

**Comment by aviggiano** [comment]
I can confirm that this solution works [336#issuecomment-238880987](336#issuecomment-238880987) on the free tier.

### On Openshift:

![screenshot from 2017-09-26 15-38-16](https://user-images.githubusercontent.com/3029017/30877662-c2104dc4-a2d0-11e7-90cc-a8b6f4a8f3ab.png)

### On my DNS settings

![screenshot from 2017-09-26 15-38-52](https://user-images.githubusercontent.com/3029017/30877731-f7288652-a2d0-11e7-87af-076cfeefed53.png)

### dig

```
 $ dig www.viggiano.com.br

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.viggiano.com.br
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26135
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;www.viggiano.com.br.		IN	A

;; ANSWER SECTION:
www.viggiano.com.br.	2836	IN	CNAME	linkedin-redirect-viggiano.1d35.starter-us-east-1.openshiftapps.com.
linkedin-redirect-viggiano.1d35.starter-us-east-1.openshiftapps.com. 3600 IN CNAME starter-us-east-1-infra-1319228685.us-east-1.elb.amazonaws.com.
starter-us-east-1-infra-1319228685.us-east-1.elb.amazonaws.com.	60 IN A	54.84.228.9
starter-us-east-1-infra-1319228685.us-east-1.elb.amazonaws.com.	60 IN A	34.230.198.208

;; Query time: 19 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Tue Sep 26 15:40:34 BRT 2017
;; MSG SIZE  rcvd: 234
```

**Comment by bytesun** [comment]
I have couple domains. One works fine, and another(www.sunorth.org) doesn't work, but sub domain works(new.sunorth.org).

**Comment by Download** [comment]
So... I have an Openshift Online v3 Pro Account. When creating my app I set the hostname to the one I want. I was looking for info on how to set up the CNAME record but instead of a good information page I found this issue only...

Do I have to recreate my app with a generated domain name and then perform the tricks mentioned in this thread or what? The issue is closed apparently but for me the problem is still open. I have no idea what to do. This was pretty simple in v2 and the web console even linked to instructions for setting up the CNAME.

Any help would be greatly appreciated. A pointer to the docs (if any) would suffice. I can't find them. The v2 docs are very persistent and all my searches I keep finding all this info about v2 but not v3.

**Comment by sspeiche** [comment]
Best does I could find where at: https://docs.openshift.com/online/dev_guide/integrating_external_services.html#defining-a-service-for-an-external-database
searching for cname references, not sure it exactly matches what you are trying to do

**Comment by spadgett** [comment]
@Download If the router for your Online Pro cluster has a canonical hostname set, you should see a message like #1194 when looking at a route with a custom hostname. Let us know if you aren't seeing that. If not, we should update the configuration with the router hostname.

@sspeiche @abhgupta FYI

**Comment by Download** [comment]
@sspeiche Yes I found those docs as well but they are only slightly related.
@spadgett Thanks for the tip I will try this out.

Red Hat really should create a separate documentation entry for setting up custom hostnames. They recognize it's a very important feature, because it's in the shortlist of features in the Plan comparison tables. Starter Plan does not support custom domain names, Pro plan does. There are only about 10 features in that table. But in the docs there is no mention of it anywhere. That's just weird.

If someone with influence on the docs / features in the different plans reads this, I got one more tip: 

Make sure the Pro plan gets at least one GiB of persistent storage included. Currently you get 1 GiB in the Starter plan, but 0 GiB in the Pro plan. Apart from the fact that it's really weird that the 50$ Pro plan has less than the free Starter plan in this respect, it also causes a really bad first user experience. My attempts to creating a MySQL database kept failing with some pretty noisy error reports that somewhere in them said something about quota limits exceeded. Only after calling the support desk did I figure out that the Pro plan starts out with no persistent storage at all and you actually have to upgrade your plan and add a GiB of storage manually (at 1$/month) before you can create a database. To me this was really unexpected and left a very sour feeling.

In their defense, the support from Red Hat (after a bumpy start in which they redirected my call all over the globe, ending in Barcelona) was really great and they even gave me a month free to compensate for the bad initial experience. But really Red Hat should change the Pro plan as to prevent this.

**Comment by Download** [comment]
@spadgett 

I looked at the route for my app, but unfortunately, the message shown in the issue you linked to is not there. Without this message, is there another way to find out where the CNAME record should point to?

I'm willing to try anything to get this to work because without this my site will go down as soon as the v2 goes EOL end of this month...

This is what I am seeing:

![screenshot](https://image.ibb.co/muqtBG/openshift.png)

**Comment by wgordon17** [comment]
@Download Today, the quickest way of determining what your CNAME record should be to create a default route (by leaving 'host' blank). Then you can create a route with 'host' set to your custom domain, and point the CNAME for your custom domain to the default route.

We have a number of improvements coming that will make this value much more clear and apparent.

And also, for the *easiest* solution, you should use the following value for your CNAME on Pro

    elb.b9ad.pro-us-east-1.openshiftapps.com

**Comment by Download** [comment]
@wgordon17 Thank you! I'm getting a bit desparate because of the impending doom when v2 goes offline in a day... So thanks for your quick response!

I will try your suggestions and let you know if it helped.

**Comment by Download** [comment]
@wgordon17 

Hurray!! Success!! Thank you, thank you, thank you!!

I finally have a (still default app) running under my own custom domain thanks to your help! 
If we ever meet, I owe you a beer!

Check out the default app in all it's glory, running under my custom domain here:
https://api.bridalapp.com/

You saved my day!

**Comment by wgordon17** [comment]
@Download Congratulations! I'm glad to help! Additionally, as a Pro user, you can add Basic Support to your [account](https://account.openshift.com) and be able to open support cases at the [Red Hat Customer Portal](https://access.redhat.com/support)

**Comment by spadgett** [comment]
Reopening based on feedback in https://github.com/openshift/origin-web-console/pull/1194#issuecomment-333160295

**Comment by writemevenkat** [comment]
@wgordon17 Trying to create a route with external public hostname but for some reason the hostname field is disabled. I'm trying with OC v3 starter plan. Will it work or should i buy pro ?

**Comment by wgordon17** [comment]
Starter does not allow custom URLs. You can see more differences between
Starter and Pro on the pricing page,
https://www.openshift.com/pricing/index.htm
<https://www.openshift.com/pricing/index.html>.


From: Venkat Muthu <notifications@github.com> <notifications@github.com>
Reply: openshift/origin-web-console
<reply@reply.github.com>
<reply@reply.github.com>
Date: February 25, 2018 at 17:08:36
To: openshift/origin-web-console <origin-web-console@noreply.github.com>
<origin-web-console@noreply.github.com>
CC: Will Gordon <wgordon@redhat.com> <wgordon@redhat.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [openshift/origin-web-console] Usability issue attaching
domain name to route (#336)

@wgordon17 <https://github.com/wgordon17> Trying to create a route with
