### ISSUE TITLE
Route warning icon can wrap to next line in routes table

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#34]
![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/15518188/a1243730-21c9-11e6-8197-8a03ce284fb5.png)

**Comment by jwforres** [comment]
Name can be kind of long so i don't really want to add nowrap around it

**Comment by spadgett** [comment]
Non-breaking space between route name and icon? Then it will still wrap at `-` chars.

**Comment by jwforres** [comment]
Sure

**Comment by sg00dwin** [comment]
@spadgett a non-breaking space would only work if the text and icon were in a string that had the same parent, currently the name and warning icon are siblings.
... or is their something else you are thinking?

I was speaking with @rhamilto about the placement and are in agreement in preference of having the icon before the text. This would also alleviate separate issues where the icon is hidden on truncated strings.

**Comment by spadgett** [comment]
> a non-breaking space would only work if the text and icon were in a string that had the same parent, currently the name and warning icon are siblings.

Would it work if the _warnings-popup template didn't have spaces between the span elements?

> I was speaking with @rhamilto about the placement and are in agreement in preference of having the icon before the text. This would also alleviate separate issues where the icon is hidden on truncated strings.

We should discuss. We always show it to the right today, and we'd want to be consistent everywhere. Not crazy about the text not left aligning. We don't truncate name here, so that shouldn't be a problem (in this specific spot anyway).

**Comment by rhamilto** [comment]
> Would it work if the _warnings-popup template didn't have spaces between the span elements?

Nope.  I just tried this.  

The only thing that works is to add white-space: nowrap, which we don't want because that prevents wrapping all together.  I think we have to live with this one if the icon is to come after the name.
