### ISSUE TITLE
Image not defined as builder can be used as builder

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#343]
I want to deploy a mongodb database (which is not a builder/s2i image).
There's the option to deploy the template using the latest image available, but because I want to deploy a previous version of the database, I click "Additional images":

![image](https://cloud.githubusercontent.com/assets/78350/17582500/558c7924-5fac-11e6-9a78-2b03f87e08ba.png)

I then want to deploy a mongodb 2.6, I click on it and it shows the screen for s2i/builder images, which asks for a git repo, although this image is not s2i and does not have a "builder" tag.

![image](https://cloud.githubusercontent.com/assets/78350/17582528/8f7f078c-5fac-11e6-97c4-19d20a8ae271.png)

````
oc get is/mongodb -o json -n openshift
{
    "kind": "ImageStream",
    "apiVersion": "v1",
    "metadata": {
        "name": "mongodb",
        "namespace": "openshift",
        "selfLink": "/oapi/v1/namespaces/openshift/imagestreams/mongodb",
        "uid": "330622bc-5e7e-11e6-bb2e-525400b263eb",
        "resourceVersion": "635",
        "generation": 2,
        "creationTimestamp": "2016-08-09T22:11:19Z",
        "annotations": {
            "openshift.io/image.dockerRepositoryCheck": "2016-08-09T22:12:02Z"
        }
    },
    "spec": {
        "tags": [
            {
                "name": "2.4",
                "annotations": {
                    "description": "Provides a MongoDB v2.4 database",
                    "iconClass": "icon-mongodb",
                    "tags": "mongodb",
                    "version": "2.4"
                },
                "from": {
                    "kind": "DockerImage",
                    "name": "openshift/mongodb-24-centos7:latest"
                },
                "generation": 2,
                "importPolicy": {}
            },
            {
                "name": "2.6",
                "annotations": {
                    "description": "Provides a MongoDB v2.6 database",
                    "iconClass": "icon-mongodb",
                    "tags": "mongodb",
                    "version": "2.6"
                },
                "from": {
                    "kind": "DockerImage",
                    "name": "centos/mongodb-26-centos7:latest"
                },
                "generation": 2,
                "importPolicy": {}
            },
            {
                "name": "3.2",
                "annotations": {
                    "description": "Provides a MongoDB v3.2 database",
                    "iconClass": "icon-mongodb",
                    "tags": "mongodb",
                    "version": "3.2"
                },
                "from": {
                    "kind": "DockerImage",
                    "name": "centos/mongodb-32-centos7:latest"
                },
                "generation": 2,
                "importPolicy": {}
            },
            {
                "name": "latest",
                "annotations": {
                    "description": "Provides a MongoDB database",
                    "iconClass": "icon-mongodb",
                    "tags": "mongodb"
                },
                "from": {
                    "kind": "ImageStreamTag",
                    "name": "3.2"
                },
                "generation": 1,
                "importPolicy": {}
            }
        ]
    },
````

**Comment by spadgett** [comment]
@jorgemoralespou This is the reason for the warning when you expand the section. We wanted to give people a way to still use an image that is not properly tagged as a builder. We can probably make the message better and direct them to the deploy image tab.

**Comment by spadgett** [comment]
Or we could remove the additional images list entirely

@jwforres @bparees Thoughts?

**Comment by bparees** [comment]
@spadgett we should keep the additional images list. people don't always know to use the builder tag and it's nice to give them a way to still access the image, especially in case their admin registered it incorrectly, so they aren't in a position to fix it.

**Comment by bparees** [comment]
but we should have a way to just deploy an image that is not a builder, the console equivalent to "oc new-app centos/mongodb-32-centos7 -e MONGODB_USER=foo -e MONGODB_PASSWORD=bar".

**Comment by spadgett** [comment]
> but we should have a way to just deploy an image that is not a builder, the console equivalent to "oc new-app centos/mongodb-32-centos7 -e MONGODB_USER=foo -e MONGODB_PASSWORD=bar".

We have that now. There's a "Deploy Image" tab that does it.

**Comment by jwforres** [comment]
it does bring up the question, why can't I browse a catalog for images that I can deploy...  but if we start doing that we will get into situations where people are deploying DB images without all the other stuff that should get created with them

**Comment by spadgett** [comment]
Part of the reason is we didn't want to load all image streams from all namespaces you can access to create a catalog. Although we could make you pick a namespace and then build a catalog from those images. I worry if it's going to create further confusion about templates vs builder vs image though since they'd all look basically the same.

**Comment by spadgett** [comment]
Thoughts on this message as a fix for 1.3, and then revisit it as part of the Trello card?

https://trello.com/c/xlQaSaxT

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/17589306/f9054e74-5fa1-11e6-9b68-7e6154043cc8.png)

**Comment by jwforres** [comment]
seems reasonable to me

**Comment by jorgemoralespou** [comment]
@spadgett Thanks, seems reasonable to me as well
