### ISSUE TITLE
Wait timed out test flake

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#35]
I've seen this a few times now, recently in #33.

```
1)  authenticated e2e-user new project when creating a new project should be able to show the create project page
  - Error: Wait timed out after 3028ms
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_web_console/8/console

**Comment by spadgett** [comment]
Also https://github.com/openshift/origin-web-console/pull/22#issuecomment-220419317

**Comment by spadgett** [comment]
Screenshot from #33

![authenticated_e2e-user_new_project_when_creating_a_new_project_should_be_able_to_show_the_create_project_page_png__1024x1987_](https://cloud.githubusercontent.com/assets/1167259/15519881/96cf4240-21d1-11e6-958d-d468ae1ed274.png)

**Comment by spadgett** [comment]
Also #38, see

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_web_console/11/console

**Comment by spadgett** [comment]
#38 has the same screenshot as above, https://github.com/openshift/origin-web-console/issues/35#issuecomment-221400798

**Comment by spadgett** [comment]
Again

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_web_console/19/console

But different screenshot:

<img width="533" alt="authenticated_e2e-user_new_project_when_creating_a_new_project_should_delete_a_project_png__1024x1987_" src="https://cloud.githubusercontent.com/assets/1167259/15592799/a66150be-2374-11e6-95dc-16d4f6fc8a3c.png">

**Comment by spadgett** [comment]
Also

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_web_console/32/

**Comment by spadgett** [comment]
Should be fixed by #92

**Comment by jwforres** [comment]
based on the screenshots it looks like we have more than one issue, #92  will only fix the second one

**Comment by spadgett** [comment]
I think I've only seen the first screenshot once. It's usually the second.

**Comment by spadgett** [comment]
Haven't seen this since #92.
