### ISSUE TITLE
Need a way to copy full log text

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#356]
For logs with thousands of lines, it's very annoying to select the text manually in the web console. It would be nice to provide a link that either copies the content or at least selects it for the user.

**Comment by jhadvig** [comment]
Would the selection select only the last thousand lines that we currently display ?

**Comment by spadgett** [comment]
Yeah, I think so. I'm not sure we'd want to copy more to the clipboard. We did increase the limit to 5000 lines

**Comment by jhadvig** [comment]
Yeah true that.
Would be great to have a way how to download the whole log as a text file && copy to clipboard just the lines that we actually render. 
Maybe a `Get logs` drowpdown btn that would display two options:
1. `Download full log`
2. `Copy displayed log`

Although not sure about the wording

**Comment by spadgett** [comment]
Yeah the original designs had a download log / open as plain text, but we didn't have a good way to authenticate and serve the content as plain text.

**Comment by benjaminapetersen** [comment]
Simplest way I could think of is save the log in session storage, then load a sibling `log.html` file, read it out and write it out in a `<pre>` and be done with it.  Not sure if that seems too simplistic though.

**Comment by spadgett** [comment]
I was thinking of clipboard.js, although not sure how well it would work with tables and line numbers.

**Comment by spadgett** [comment]
Or even a "Select all" link that highlighted the log content. That would work on mobile.
