### ISSUE TITLE
How to add in project t tag

### ISSUE THREAD

**Issue by array-yz** [openshift/origin-web-console#36]
As a result of our project requirements, I need the pod in the pageThe DetailsThe EnvironmentLogsThe EventsPut a label, the introduction of the company server page links, what should I do?

**Comment by jwforres** [comment]
Are you just trying to add a label to a pod?  If you modify your deployment config (Actions -> Edit YAML) you can have it automatically add labels to your pods.  Or you can individually edit Pods to add labels to them.

**Comment by jwforres** [comment]
Closing for lack of information. Please provide more detail if you would like to reopen it.
