### ISSUE TITLE
Overview "Deployment running" text hard to read

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#399]
This has changed recently. I believe the text might be inheriting styles intended for the arrow. The text is too light and the "View Log" link doesn't have enough margin.

![screen_shot_2016-08-17_at_10_09_25_am](https://cloud.githubusercontent.com/assets/1167259/17739357/d92fc172-6462-11e6-90f3-779b2449b8d1.png)

/cc @jwforres @rhamilto @sg00dwin

**Comment by rhamilto** [comment]
Yep, you're correct @spadgett.  @sg00dwin to fix.
