### ISSUE TITLE
Link to the new Command Line Tools page from About page instead of duplicating info

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#40]
The new Command Line Tools page looks great!  Nice work, @jhadvig!

![screen shot 2016-05-26 at 11 39 59 am](https://cloud.githubusercontent.com/assets/895728/15580421/b09bc78c-2336-11e6-8a1e-795550dad968.PNG)

I noticed that we're duplicating some information on the About page about the CLI, however.

![screen shot 2016-05-26 at 11 41 26 am](https://cloud.githubusercontent.com/assets/895728/15580472/dd5b5b7a-2336-11e6-9856-f03085cc3276.PNG)

Perhaps we revise that last sentence to:

> With the OpenShift command line interface (CLI), you can create applications and manage OpenShift projects from a terminal. To get started using the CLI, visit the [Command Line Tools](/command-line) page.

Thoughts, @jwforres, @spadgett, @benjaminapetersen, @sg00dwin?

**Comment by jhadvig** [comment]
@rhamilto yeah I would prefer to point to the Command Line Tools page :+1:

**Comment by jwforres** [comment]
@rhamilto sure open a PR

**Comment by benjaminapetersen** [comment]
agree.
