### ISSUE TITLE
Tooltip cut off for overview metrics charts

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#415]
![screen_shot_2016-08-18_at_8_17_14_am](https://cloud.githubusercontent.com/assets/1167259/17773424/5be92054-651c-11e6-86e4-7a76bbd46942.png)

/cc @jwforres

**Comment by jwforres** [comment]
I was thinking about it this morning, we could have the X overflow hidden
and the y overflow visible, then the tooltips work but the charts aren't
visible when they slide out to the left.
