### ISSUE TITLE
Empty divs taking up vertical space on overview when no deployments yet exist

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#421]
the appearance of the overview with #413 
![screen shot 2016-08-18 at 3 58 22 pm](https://cloud.githubusercontent.com/assets/895728/17789878/14461c84-6562-11e6-9f73-4c9c3d0b3241.PNG)

the offending markup
![screen shot 2016-08-18 at 9 11 05 am](https://cloud.githubusercontent.com/assets/895728/17789883/1896d29c-6562-11e6-86ce-a6a8e99e62c4.PNG)

**Comment by rhamilto** [comment]
This bug only occurs when the empty containers are scrolled off the page (that is, the viewport is shorter than the page contents).

**Comment by spadgett** [comment]
I'm able to reproduce by unchecking all triggers creating from source.

![screen shot 2016-08-19 at 8 55 28 am](https://cloud.githubusercontent.com/assets/1167259/17810377/caf82b10-65ea-11e6-8784-94af6eb9af20.png)

**Comment by spadgett** [comment]
OK, the bug I'm seeing is a little different and impacts a lot of pages. The `surface-shaded` style doesn't go to the bottom of the page in many cases. After a certain point, there's a white background:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/17810793/445dfaaa-65ed-11e6-938d-2c6bf4ccc680.png)

**Comment by rhamilto** [comment]
@spadgett, possible browser caching issue?  I can only reproduce on the overview when there aren't any deployments...

**Comment by spadgett** [comment]
Did you pull latest master? Only seeing it since the IE has scroll fix

**Comment by rhamilto** [comment]
@spadgett, yup.  Latest commit in my local master is https://github.com/openshift/origin-web-console/commit/4d411df7541262b055757656f1bc843576c9f75f

**Comment by spadgett** [comment]
Ah, my fault. I had a local change...

**Comment by rhamilto** [comment]
@spadgett, phew!

I did discover we've got a couple of different visual defects on the overview page in Safari.  paging @sg00dwin?

<img width="1233" alt="screen shot 2016-08-19 at 10 32 06 am" src="https://cloud.githubusercontent.com/assets/895728/17813229/7afc223e-65f8-11e6-9dc7-d134b953ae6c.PNG">

**Comment by spadgett** [comment]
I had opened #423, but it doesn't cover everything in the screenshot :/

**Comment by rhamilto** [comment]
@spadgett, the hack described in https://github.com/openshift/origin-web-console/issues/423#issuecomment-241043531 would also make this bug less obvious as it would make the empty white space gray.

**Comment by spadgett** [comment]
It seems to be the `height: 100%` on the div with content:

![screen_shot_2016-08-19_at_11_33_30_am](https://cloud.githubusercontent.com/assets/1167259/17815118/efdcaf30-6600-11e6-909e-be1aa4778955.png)
