### ISSUE TITLE
Blue border can extend past bottom of tile

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#423]
![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/17813024/97cb7cd0-65f7-11e6-8abe-9a43f9142030.png)

Related to #273

**Comment by rhamilto** [comment]
a quick, dirty hack to fix the white edges bug is to add

```
  .middle { // hack to quickly, safely fix a safari bug
    background-color: red;
  }
```

to [line 18 of _overview.less](https://github.com/openshift/origin-web-console/blob/master/app/styles/_overview.less#L18).

**Comment by spadgett** [comment]
How does that affect pages with a white background?

**Comment by rhamilto** [comment]
@spadgett, it doesn't as it is specific to the overview.

**Comment by spadgett** [comment]
Ah OK, didn't see it was under `.overview`. I think we should go ahead with that change. Can you open a PR?
