### ISSUE TITLE
Env var editor headers still visible when last var removed

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#431]
When I remove the last variable, the headers are still present, which looks a little strange. Should `x` on the only row should just clear the inputs? Or maybe we hide the headers when there are no values.

![screen shot 2016-08-19 at 3 23 54 pm](https://cloud.githubusercontent.com/assets/1167259/17821707/fd9b3fa4-6620-11e6-814b-0bd5dfe501e5.png)

/cc @jwforres

**Comment by benjaminapetersen** [comment]
Hmm. Yeah, x on the only row clearing the inputs seems good, this is def a little weird.
