### ISSUE TITLE
The label of `compute-resource`  is empty

### ISSUE THREAD

**Issue by maybelinot** [openshift/origin-web-console#436]
`compute-resource` label on [edit-request-limit](https://github.com/openshift/origin-web-console/blame/e6249b0435b9fea2401cbc7297de16d1cdcbe172/app/views/_edit-request-limit.html#L31) page now is empty, but was `"Limit"`.

I guess this change came along with this [commit](https://github.com/openshift/origin-web-console/commit/ec2c54de681b3e28a439f602894fdd60336a67cf#diff-d9bc3832e1b412cfd48b47098bf8100eL178).

@spadgett can you clarify this issue?

**Comment by spadgett** [comment]
@maybelinot Can you post a screenshot?

It might be intentional. Do you know if your cluster is configured for overcommit? If these settings are in place, the web console behaves differently.

https://docs.openshift.org/latest/admin_guide/overcommit.html#configuring-masters-for-overcommitment

**Comment by maybelinot** [comment]
![screenshot from 2016-08-18 17-29-14](https://cloud.githubusercontent.com/assets/5212597/17854493/5f41f000-6873-11e6-8b11-7759d86565a4.png)

@spadgett I'm testing Online STG env and don't know how cluster is configured.

**Comment by spadgett** [comment]
@maybelinot Yeah, it's working as intended. In that configuration, you can't set the memory request, so we only show one "Memory" label for each container.

**Comment by maybelinot** [comment]
@spadgett So there is no "Limit" label because "Request" label not used?
hmm, that's interesting, thanks for explanation!
