### ISSUE TITLE
"Other Resources" layout problem on iOS

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#443]
The filter control is cut off and the message in the table has unusual padding.

<img width="487" alt="screen shot 2016-08-22 at 12 53 41 pm" src="https://cloud.githubusercontent.com/assets/1167259/17863399/830dd942-6867-11e6-9113-72a3431703bc.png">

**Comment by jwforres** [comment]
the padding is caused by the table layout showing data-title as a prefix on mobile, need to check what we do for this in our other tables

**Comment by spadgett** [comment]
Similar problems on the storage page

<img width="487" alt="screen shot 2016-08-22 at 12 56 41 pm" src="https://cloud.githubusercontent.com/assets/1167259/17863522/ecb52594-6867-11e6-9f89-5a3a606d69b8.png">

**Comment by spadgett** [comment]
@jwforres see https://github.com/openshift/origin/pull/7178
