### ISSUE TITLE
Missing pie chart when all route weights set to 0

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#444]
<img width="826" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/17867251/b546e646-6877-11e6-9c74-18c5025b92a3.png">

/cc @jwforres

**Comment by jwforres** [comment]
well thats fun

**Comment by spadgett** [comment]
Also minor display issue with the "No Traffic" message

<img width="935" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/17867637/4ce3d850-6879-11e6-9eab-f89a53498c35.png">
