### ISSUE TITLE
Build number wraps on overview even at wide screen widths

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#461]
![screen_shot_2016-08-23_at_2_27_18_pm](https://cloud.githubusercontent.com/assets/1167259/17904554/c88d07be-693d-11e6-827f-5fff3ca313b9.png)

/cc @jwforres @rhamilto

**Comment by rhamilto** [comment]
@spadgett, I'm not able to reproduce this.  Tips on setup?

**Comment by spadgett** [comment]
@rhamilto Hm, I'm only seeing this in the built openshift binary, not in the my development environment

**Comment by rhamilto** [comment]
This appears to be a whitespace issue related to template minification?

**Comment by rhamilto** [comment]
Removing the whitespace in https://github.com/openshift/origin-web-console/blob/master/app/views/_triggers.html#L14-L16 appears to fix it.

**Comment by jwforres** [comment]
Fixed in #468
