### ISSUE TITLE
We should be joining log messages that are split across multiple websocket frames

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#472]
Long lines (> 2048 bytes) will be split across multiple websocket frames. Today the console treats every message as a unique line.  We should only be creating new table rows in the log output when we actually get newline characters, and be appending to an existing line until we reach a newline.

**Comment by jwforres** [comment]
cc @liggitt @spadgett

**Comment by jwforres** [comment]
We should also handle getting multiple lines in a single message (\n character mid-frame) and split those into multiple table rows.

**Comment by benjaminapetersen** [comment]
Doing some investiating on this, the `\n` newline character, as well as natural line breaks in the console itself, tend to have either no effect or strange effect when sent to the log viewer in the web console.  Adding these screenshots as documentation to what I'm finding:

![screen shot 2018-01-31 at 5 10 54 pm](https://user-images.githubusercontent.com/280512/35650348-bb8c4510-06a9-11e8-8d5d-d3ea5e9fc5ed.png)

![screen shot 2018-01-31 at 5 08 07 pm](https://user-images.githubusercontent.com/280512/35650225-61487772-06a9-11e8-9f6c-e12f8c1277bc.png)

1. Resize your terminal window, regardless of size, it will "send" a message to the web console when you get to the end of the line, but then send the same message again when you finally press enter (the second will be complete).
2. I don't think there are newline `\n` chars in the messages sent
3. Explicitly including newline `\n` characters doesn't change how the messages are sent (this may be expected)

**Comment by benjaminapetersen** [comment]
` oc logs -f mydc-1-x7mw5-debug` gets a very similar output as is sent to the web console.  For example, as above, when reaching the end of the terminal line a partial message will be sent & displayed both in the web console && in the terminal that is following the log, then the full message will be sent again when the user types `enter`.  

I think behavior changes may need to happen at a higher level than the web console.
