### ISSUE TITLE
Spacing a little off when adding a template with no parameters

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#480]
<img width="784" alt="screen_shot_2016-08-25_at_9_10_55_am" src="https://cloud.githubusercontent.com/assets/1167259/17970281/eed7f142-6aa3-11e6-8e49-685687b50ccb.png">

**Comment by jwforres** [comment]
wow a template with no parameters, this may be the first one i've seen

**Comment by jwforres** [comment]
because a Template with no parameters might as well be a List, unless you plan on storing the Template itself

I feel like this would look less odd if we had the summary at the top of what was going to be created

**Comment by rhamilto** [comment]
This should just be a simple CSS fix.  

> I feel like this would look less odd if we had the summary at the top of what was going to be created

What do you mean, @jwforres?

**Comment by jwforres** [comment]
We have proposed in the past that for templates we let you know what is
actually going to be created.

There are arguments for and against that though.

**Comment by spadgett** [comment]
> We have proposed in the past that for templates we let you know what is
> actually going to be created.

Won't that ruin the surprise?
