### ISSUE TITLE
Warn that a deployment config is waiting on an image

### ISSUE THREAD

**Issue by kargakis** [openshift/origin-web-console#490]
https://github.com/openshift/origin/issues/9041

> It might be nice to know in web console that the deployment is waiting for something. (image update)

**Comment by jwforres** [comment]
We tell you this in the overview now. Would be good to do the same on the DC History tab  cc @spadgett

**Comment by spadgett** [comment]
For reference, the overview change was #755.

**Comment by spadgett** [comment]
I think this makes sense to do as part of #497 for the dc empty state message
