### ISSUE TITLE
Forwarding to initially-requested page for not-logged-in user is broken

### ISSUE THREAD

**Issue by ALRubinger** [openshift/origin-web-console#50]
Observed on current Origin `latest` Docker image (`upstream/master`).  Unsure what corresponding version of the newly-extracted `origin-web-console` applies.

1) As a user who is not logged in, request a page from the console, for instance:

`https://10.1.2.2:8443/console/project/default/overview/`

2) Observe the console redirect to the login page:

`https://10.1.2.2:8443/login?then=%2Foauth%2Fauthorize%3Fclient_id%3Dopenshift-web-console%26response_type%3Dtoken%26state%3D%257B%2522then%2522%253A%2522%252Fproject%252Fdefault%252Foverview%2522%252C%2522nonce%2522%253A%25221464575117627-188965410684100422701140277249369410143364625528371304029883494082064318640%2522%257D%26redirect_uri%3Dhttps%253A%252F%252F10.1.2.2%253A8443%252Fconsole%252Foauth`

3) Enter credentials (ie. `admin`/`admin`) and hit "Log In".  Observe interstitial redirect:

`https://10.1.2.2:8443/console/oauth#access_token=56EXHu57Ddj0nNS3a06lGI2FshWIJicPNfdy79QtAKI&expires_in=86400&state=%7B%22then%22:%22/project/default/overview%22,%22nonce%22:%221464575217400-4009554928223396578558102190174732909820355798996169206124878501852858850331%22%7D&token_type=Bearer`

4) End result is the Console Overview page:

`https://10.1.2.2:8443/console/`

Was expecting end result of the initially-requested page:

`https://10.1.2.2:8443/console/project/default/overview/`

Requesting @spadgett triage. :)

**Comment by spadgett** [comment]
I can reproduce.

**Comment by ALRubinger** [comment]
Top-notch support, @spadgett; you're hired.  Thanks!
