### ISSUE TITLE
Trailing action separator visible after "View archive" when logs load

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#507]
If you've setup Kibana, there's a trailing separator with no value after it when the logs are still loading.

![screen_shot_2016-09-01_at_11_03_18_am](https://cloud.githubusercontent.com/assets/1167259/18172906/6fe40bcc-7035-11e6-96e3-8724fce6daa7.png)

/cc @jwforres @benjaminapetersen

**Comment by benjaminapetersen** [comment]
Was just seeing that as well. :/
