### ISSUE TITLE
Runtime error on nextSteps page only when a java app is selected

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#512]
To reproduce: 
- follow the new project flow
- choose one of the java apps (`wildfly 10`, `wildfly 9`, `wildfly 8`)
- enter a name & use the sample git repository

The following error will appear in the console:
 
![screen shot 2016-09-02 at 4 19 33 pm](https://cloud.githubusercontent.com/assets/280512/18217226/9f960c54-7129-11e6-95d0-66a5d79f7140.png)

This only happens with a java app.  I suspect it is passing an entries list as an `{ }` instead of an `[ ]` at some point, but I have not yet tracked it down.  It appears to happen right at the button click (API call), so I suspect it may have something to do with mapping an `[ ]` back to an `{ }` (labels?).

@jwforres @spadgett

**Comment by benjaminapetersen** [comment]
This issue does not appear using php, ruby, perl or node apps.

**Comment by jwforres** [comment]
Can you add env vars and / or labels successfully during the create flow for those images? Or is this breaking one of those two things.

**Comment by jwforres** [comment]
Just tried, it does not seem to breaking setting env vars or labels on anything. So its not a blocker but we need to fix this in 1.4

**Comment by benjaminapetersen** [comment]
Yeah it doesn't break anything. I tinkered with it a good bit Friday but didn't find the root problem. I think it is a JS update after the request submits, then sets the Val to a non-array right as the page changes.

**Comment by spadgett** [comment]
I think the problem is that `$scope.labels` is changed from an array to an object here:

https://github.com/spadgett/origin-web-console/blob/e7a0c0a8f703d5429f70b78223abb31856a66670/app/scripts/controllers/create/createFromImage.js#L315

**Comment by benjaminapetersen** [comment]
Nice, working on a fix.

**Comment by benjaminapetersen** [comment]
Gonna check out the rest of the instances of label editor as well:
- [x] create/fromimage.html
- [x] directives/deploy-image.html
- [x] edit/autoscaler.html
- [x] newfromtemplate.html

**Comment by benjaminapetersen** [comment]
The above were all fine because the tranfomation output was on a new object, not back on the original `$scope.labels`, so no error.
