### ISSUE TITLE
Web console auth error from networked machine

### ISSUE THREAD

**Issue by SpeedyH30** [openshift/origin-web-console#513]
I know this probably is the place for this and I'm probably being dim but... I have openshift origin running on my home server using virtualbox and the all in one image from vagrant. I can access the web console on the server/host browser. If I try to connect to the console on any other machine on the network I get the openshift origin top bar and loading in the middle of the screen http://prntscr.com/cef6r1. I then redirect 

`https://10.2.2.2:8443/oauth/authorize?client_id=openshift-web-console&response_type=token&state=%7B%22then%22%3A%22%2F%22%2C%22nonce%22%3A%221473154175516-732980838400759397438941884072194457589317990572519793743003436498987331068051%22%7D&redirect_uri=https%3A%2F%2F10.2.2.2%3A8443%2Fconsole%2Foauth`

Then I time out. I am unsure of the reason for this behavour 

@liggitt I see in a different thread you have made comment on how to fix a similar issue.

This is the out put from` oc edit oauthclient openshift-web-console`
apiVersion: v1
grantMethod: auto
kind: OAuthClient
metadata:
  creationTimestamp: 2016-08-09T22:11:09Z
  name: openshift-web-console
  resourceVersion: "9513"
  selfLink: /oapi/v1/oauthclients/openshift-web-console
  uid: 2cc9c093-5e7e-11e6-bb2e-525400b263eb
redirectURIs:
- https://10.2.2.2:8443/console/
- http://localhost:9000
- https://localhost:9000

secret xxxxxxx......

Any thoughts from anyone would be appreciated

**Comment by jwforres** [comment]
You need to set the masterPublicURL in the master config or the console is going to keep trying to hit the master API on the internal URL.

https://docs.openshift.org/latest/install_config/master_node_configuration.html

**Comment by SpeedyH30** [comment]
well this is the Master that comes with the all in one image and as it has a masterPublicURL set surely this shouldn't be an issue?

`admissionConfig:
  pluginConfig: null
apiLevels:
- v1
apiVersion: v1
assetConfig:
  extensionDevelopment: false
  extensionProperties: null
  extensionScripts: null
  extensionStylesheets: null
  extensions: null
  loggingPublicURL: ""
  logoutURL: ""
  masterPublicURL: https://10.2.2.2:8443
  metricsPublicURL: https://hawkular-metrics.apps.10.2.2.2.xip.io/hawkular/metrics
  publicURL: https://10.2.2.2:8443/console/
  servingInfo:
    bindAddress: 0.0.0.0:8443
    bindNetwork: tcp4
    certFile: master.server.crt
    clientCA: ""
    keyFile: master.server.key
    maxRequestsInFlight: 0
    namedCertificates: null
    requestTimeoutSeconds: 0
auditConfig:
  enabled: false
controllerConfig:
  serviceServingCert:
    signer:
      certFile: service-signer.crt
      keyFile: service-signer.key
controllerLeaseTTL: 0
controllers: '*'
corsAllowedOrigins:
- 10.2.2.2:8443
- 127.0.0.1
- localhost
disabledFeatures: null
dnsConfig:
  allowRecursiveQueries: true
  bindAddress: 0.0.0.0:8053
  bindNetwork: tcp4
etcdClientInfo:
  ca: ca.crt
  certFile: master.etcd-client.crt
  keyFile: master.etcd-client.key
  urls:
  - https://10.2.2.2:4001
etcdConfig:
  address: 10.2.2.2:4001
  peerAddress: 10.2.2.2:7001
  peerServingInfo:
    bindAddress: 0.0.0.0:7001
    bindNetwork: tcp4
    certFile: etcd.server.crt
    clientCA: ca.crt
    keyFile: etcd.server.key
    namedCertificates: null
  servingInfo:
    bindAddress: 0.0.0.0:4001
    bindNetwork: tcp4
    certFile: etcd.server.crt
    clientCA: ca.crt
    keyFile: etcd.server.key
    namedCertificates: null
  storageDirectory: /var/lib/origin/openshift.local.etcd
etcdStorageConfig:
  kubernetesStoragePrefix: kubernetes.io
  kubernetesStorageVersion: v1
  openShiftStoragePrefix: openshift.io
  openShiftStorageVersion: v1
imageConfig:
  format: openshift/origin-${component}:v1.3.0-alpha.3
  latest: false
imagePolicyConfig:
  disableScheduledImport: false
  maxImagesBulkImportedPerRepository: 5
  maxScheduledImageImportsPerMinute: 60
  scheduledImageImportMinimumIntervalSeconds: 900
jenkinsPipelineConfig:
  enabled: true
  parameters: null
  serviceName: jenkins
  templateName: jenkins
  templateNamespace: openshift
kind: MasterConfig
kubeletClientInfo:
  ca: ca.crt
  certFile: master.kubelet-client.crt
  keyFile: master.kubelet-client.key
  port: 10250
kubernetesMasterConfig:
  admissionConfig:
    pluginConfig: null
  apiLevels: null
  apiServerArguments: null
  controllerArguments: null
  disabledAPIGroupVersions: {}
  masterCount: 1
  masterIP: 10.2.2.2
  podEvictionTimeout: 5m
  proxyClientInfo:
    certFile: master.proxy-client.crt
    keyFile: master.proxy-client.key
  schedulerArguments: null
  schedulerConfigFile: ""
  servicesNodePortRange: 30000-32767
  servicesSubnet: 172.30.0.0/16
  staticNodeNames: null
masterClients:
  externalKubernetesClientConnectionOverrides:
    acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
    burst: 400
    contentType: application/vnd.kubernetes.protobuf
    qps: 200
  externalKubernetesKubeConfig: ""
  openshiftLoopbackClientConnectionOverrides:
    acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
    burst: 600
    contentType: application/vnd.kubernetes.protobuf
    qps: 300
  openshiftLoopbackKubeConfig: openshift-master.kubeconfig
masterPublicURL: https://10.2.2.2:8443
networkConfig:
  clusterNetworkCIDR: 10.128.0.0/14
  externalIPNetworkCIDRs: null
  hostSubnetLength: 9
  ingressIPNetworkCIDR: ""
  networkPluginName: ""
  serviceNetworkCIDR: 172.30.0.0/16
oauthConfig:
  alwaysShowProviderSelection: false
  assetPublicURL: https://10.2.2.2:8443/console/
  grantConfig:
    method: auto
    serviceAccountMethod: prompt
  identityProviders:
  - challenge: true
    login: true
    mappingMethod: claim
    name: anypassword
    provider:
      apiVersion: v1
      kind: AllowAllPasswordIdentityProvider
  masterCA: ca-bundle.crt
  masterPublicURL: https://10.2.2.3:8443
  masterURL: https://10.2.2.2:8443
  sessionConfig:
    sessionMaxAgeSeconds: 300
    sessionName: ssn
    sessionSecretsFile: ""
  templates: null
  tokenConfig:
    accessTokenMaxAgeSeconds: 86400
    authorizeTokenMaxAgeSeconds: 300
pauseControllers: false
policyConfig:
  bootstrapPolicyFile: policy.json
  openshiftInfrastructureNamespace: openshift-infra
  openshiftSharedResourcesNamespace: openshift
  userAgentMatchingConfig:
    defaultRejectionMessage: ""
    deniedClients: null
    requiredClients: null
projectConfig:
  defaultNodeSelector: ""
  projectRequestMessage: ""
  projectRequestTemplate: ""
  securityAllocator:
    mcsAllocatorRange: s0:/2
    mcsLabelsPerProject: 5
    uidAllocatorRange: 1000000000-1999999999/10000
routingConfig:
  subdomain: apps.10.2.2.2.xip.io
serviceAccountConfig:
  limitSecretReferences: false
  managedNames:
  - default
  - builder
  - deployer
  masterCA: ca-bundle.crt
  privateKeyFile: serviceaccounts.private.key
  publicKeyFiles:
  - serviceaccounts.public.key
servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: master.server.crt
  clientCA: ca.crt
  keyFile: master.server.key
  maxRequestsInFlight: 500
  namedCertificates: null
  requestTimeoutSeconds: 3600
volumeConfig:
  dynamicProvisioningEnabled: true`

**Comment by jwforres** [comment]
what hostname do you want to access the web console and API from when you
arent on your local box?  that hostname MUST be the masterPublicURL

**Comment by SpeedyH30** [comment]
Right I see. so even if  dialing into the host that port forwards to 10.2.xxxxx I still need the host ip in there rather then 10.2xxxxx? or even the URL I am trying to use whilst on an external network.

**Comment by jwforres** [comment]
yes, masterPublicURL must be the URL you plan to use from an external
network

**Comment by SpeedyH30** [comment]
@jwforres well I have done it and I now get even less 
on local host I now get

Secure Connection Failed

The connection to h30.xxxxx.xxxx:8443 was interrupted while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…


and on other networked machines and external I get this site cant be reached

**Comment by jwforres** [comment]
Your first issue is related to the self-signed certs openshift creates for you out of the box.  The easiest thing to do is delete your existing config and run
```
openshift start --write-config=/some/directory --public-master=your-hostname
```
To re-generate config that will have the correct self-signed certs for your hostname.

Your second issue sounds like your other machines in the network can't even reach your server's hostname, have you tried pinging the hostname on those machines?

**Comment by jwforres** [comment]
In your original screenshot you use the IP address to access the machine from your other servers, is there some reason you are trying to do a hostname instead?  public master can be an IP instead of a hostname.  This should at least fix your second problem.  Either that or add the hostname -> IP address to your hosts file on those other machines.

**Comment by SpeedyH30** [comment]
oh so the ip there was on a LAN networked machine.
The hostname h30.xxxxx.xxxxx is my home network address is whilst i am away from my home office, which is 80% of the time at conferences and the like.

**Comment by SpeedyH30** [comment]
and yea i can reach the sever and ssh into it externally

**Comment by SpeedyH30** [comment]
ah @jwforres you beautiful girl the 

`openshift start --write-config=/some/directory --public-master=your-hostname`

did the trick

I could kiss you.

Thanks very much for your patience

**Comment by lpshikhar** [comment]
@jwforres Any Idea how public master can be set when using "oc cluster up" instead of going the traditional docker image route ? Thanks in advance.

**Comment by spadgett** [comment]
@lpshikhar `oc cluster up` also takes a `--public-hostname` parameter

**Comment by lpshikhar** [comment]
@spadgett Its not working on the GCP installation when I pass my external IP as the public hostname.

**Comment by spadgett** [comment]
@csrwng Can you help? ^

**Comment by csrwng** [comment]
@lpshikhar when you say it's not working ... which part doesn't work? If you're also trying to access routes, you'll most likely need to specify a --route-suffix as well

**Comment by lpshikhar** [comment]
@csrwng When I try to do a cluster up using --publi-hostname, the cluster refuses to go up stating the service was not able to ping the IP. I tried editing in openshift cluster the following file (oc edit oauthclient openshift-web-console) to allow the internal IP to talk to external IP, but that doesnt work too. I have read the documentation on installing openshift on GCP but it doesnt mention the cluster up ways to configure openshift.

**Comment by csrwng** [comment]
@Ipshikhar so with the public hostname, don't specify a numeric ip... but do specify one with --routing-suffix=[numeric ip].xip.io. I haven't tried on GCP, but on AWS, I know what works is something like `--public-hostname=ec2-x.compute-1.x-x-x-x.amazonaws.com --routing-suffix=x.x.x.x.xip.io`

**Comment by eric-hon** [comment]
i have a cluster:
master: 192.168.2.80
node1: 192.168.2.81
node2: 192.168.2.82

the code origin-web-console on the master,an i change masterPublicURL to 192.168.2.80 on /etc/origin/master/master-config.yaml,
i set openshift start --write-config=/opt/test --public-master=192.168.2.80
the 

the oc edit oauthclient openshift-web-console is:
redirectURIs:
- https://192.168.2.80:8443/console/
- https://master.avit.com:8443/console/
- https://localhost:9000
- https://192.168.2.80:8443
- https://192.168.2.80:9000

 another host is 192.168.100.109, but cannot access to https://192.168.2.80:9000 .

how can i solve it?
