### ISSUE TITLE
Remove trigger button wraps to next line on mobile

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#515]
![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/18279764/a8f87b12-7424-11e6-8f50-26ace8ee019b.png)

/cc @jhadvig

**Comment by spadgett** [comment]
I suggest we remove the extra left margin in the subsections. I prefer it left aligned.

**Comment by jhadvig** [comment]
@spadgett yeah that would make sense
