### ISSUE TITLE
Slightly different styles for remove buttons on edit build config page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#521]
Minor issue obviously, but I noticed the remove "x" button is slightly different for triggers and env vars. Env var has a lighter gray style and looks larger.

<img width="585" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/18316651/78c05c92-74e9-11e6-80bf-872005c3044d.png">

**Comment by jwforres** [comment]
this is no longer valid, the webhooks now have "Remove" links
