### ISSUE TITLE
Different icon representing storage on create-pvc page

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#528]
The icon used on the create-pvc page (fa-hdd-o) is a different icon than the one we use to denote storage in the primary nav (pficon-container-node).  Presumably, these should be the same icon since they're meaning the same thing.

![screen shot 2016-09-08 at 3 02 38 pm](https://cloud.githubusercontent.com/assets/895728/18362961/0bff2b0e-75d6-11e6-8501-6c5365f32fae.PNG)

![screen shot 2016-09-08 at 3 04 39 pm](https://cloud.githubusercontent.com/assets/895728/18362963/101a1104-75d6-11e6-9034-42c220e78a8c.PNG)

**Comment by sg00dwin** [comment]
@rhamilto @jwforres  Which should be designated for storage? The nav uses pficon-container-node and there's also a pficon-storage-domain

http://www.patternfly.org/styles/icons/

**Comment by jwforres** [comment]
@ajacobs21e

**Comment by ajacobs21e** [comment]
@jwforres @sg00dwin @rhamilto  I'm not familiar enough with the terminology to know which icon makes more sense. Is one more intuitive?

**Comment by ajacobs21e** [comment]
do any of these make more sense?
http://www.patternfly.org/styles/icons/cheatsheet/#_

pficon-volume
fa-database
pficon-cluster
