### ISSUE TITLE
creating things from templates/image streams in other projects

### ISSUE THREAD

**Issue by gaelL** [openshift/origin-web-console#53]
I have a project/namespace dedicated to build and share all my custom images using the registry-viewer role to make my images "public".

Now I would like to be able to use these image on the web console from an other namespace.

But for now the web console only search in the local namespace and the "openshift" namespace.

It could be great to have a way to use images or templates from another specified namespace.

Regards,

**Comment by spadgett** [comment]
We've started looking at this as part of the design in

https://trello.com/c/xlQaSaxT

I've linked back to your issue from the Trello card.

**Comment by jwforres** [comment]
Please subscribe to the trello card for future discussion
