### ISSUE TITLE
hack/install-deps.sh fails on Fedora 23

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin-web-console#536]
Running `./hack/install-deps.sh` manages to install most, but not all of the dependencies on Fedora 23. I receive the following error once it attempts to install `https://registry.npmjs.org/grunt-contrib-connect/1.0.1`:

```
[install-assets] npm install --unsafe-perm
[ERROR] Command 'npm install --unsafe-perm' failed with rc 34, logs:
npm http GET https://registry.npmjs.org/grunt-contrib-connect/1.0.1
npm http 304 https://registry.npmjs.org/grunt-contrib-connect/1.0.1
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/connect-livereload
npm http GET https://github.com/gruntjs/node-http2#fix-return-value
npm http GET https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/portscanner
npm http GET https://registry.npmjs.org/opn
npm http GET https://registry.npmjs.org/serve-index
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/opn
npm http 200 https://registry.npmjs.org/portscanner
npm http 200 https://registry.npmjs.org/connect
npm http 304 https://registry.npmjs.org/serve-index
npm http 200 https://github.com/gruntjs/node-http2#fix-return-value
npm http 200 https://registry.npmjs.org/connect-livereload
npm ERR! not a package /home/jvallejo/tmp/npm-17863-M8wMZ5Ak/1473786075777-0.050269320141524076/tmp.tgz
npm ERR! Error: ENOENT, open '/home/jvallejo/tmp/npm-17863-M8wMZ5Ak/1473786075777-0.050269320141524076/package/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.6.6-200.fc23.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /home/jvallejo/Documents/go/src/github.com/openshift/origin-web-console
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! path /home/jvallejo/tmp/npm-17863-M8wMZ5Ak/1473786075777-0.050269320141524076/package/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm http 304 https://registry.npmjs.org/morgan
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jvallejo/Documents/go/src/github.com/openshift/origin-web-console/npm-debug.log
npm ERR! not ok code 0
```
Link to [/home/jvallejo/Documents/go/src/github.com/openshift/origin-web-console/npm-debug.log](http://pastebin.com/dmxNkv57)

I can get around this issue by "manually" installing the rest of the dependencies:
`npm install grunt-contrib-connect async...`

However, if I attempt to install the package `grunt-contrib-connect` with the specific version on `package.json`, I get the same error as above:

`npm install grunt-contrib-connect@1.0.1`

##### Additional, minor issue

While setting up the web console locally, I followed these steps in the README file:

1. Install Nodejs and npm
2. Install grunt-cli and bower by running npm install -g grunt-cli bower (may need to be run with sudo)
3. Install ruby
4. Install bundler gem install bundler
5. Install Go per steps 1 - 3
6. Install dev dependencies by running hack/install-deps.sh
7. Launch the console and start watching for asset changes by running `grunt serve`. This should open https://localhost:9000/ in your default browser.

However, once I managed to get all of the dependencies installed, I received the following error when running `grunt serve`:

```
grunt serve cannot find where you keep your bower packages
```

This was solved by running:
1. `bower install`
2. `grunt build` 

*before* running `grunt serve` (though I am not sure which of the two solved it).

cc @jwforres

**Comment by jwforres** [comment]
hack/install-deps.sh runs bower install, grunt server won't work if you havent run bower install, which im guessing got missed since the npm install flaked out and bower runs after npm

**Comment by jwforres** [comment]
the README is also outdated as steps 3&4 haven't been needed for awhile (since we switched from SASS to Less)

**Comment by jwforres** [comment]
@jhadvig @fabianofranz are either of you on fedora 23, if so can you reproduce this?

**Comment by jwforres** [comment]
@juanvallejo what version of grunt-contrib-connect were you able to install cleanly on 23?  we may just need to bump the version

**Comment by fabianofranz** [comment]
I'm on f24.

**Comment by juanvallejo** [comment]
@jwforres 
> what version of grunt-contrib-connect were you able to install cleanly on 23?

grunt-contrib-connect 1.0.2

**Comment by jwforres** [comment]
@juanvallejo  can you try bumping the version in bower.json to 1.0.2 and run hack/clean-deps.sh and hack/install-deps.sh and see if it can complete cleanly, if so go ahead and open a PR with that change
