### ISSUE TITLE
.data-toolbars have incorrect bottom padding in IE

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#546]
IE (incorrect)
![screen shot 2016-09-16 at 4 32 13 pm](https://cloud.githubusercontent.com/assets/895728/18600470/ba8bbd8a-7c2b-11e6-83aa-6ab1a745199f.PNG)

Chrome (correct)
![screen shot 2016-09-16 at 4 36 19 pm](https://cloud.githubusercontent.com/assets/895728/18600479/c779884c-7c2b-11e6-8082-7269384d4606.PNG)

**Comment by rhamilto** [comment]
https://github.com/openshift/origin-web-console/blob/master/app/styles/_data-toolbar.less#L51 is causing the bug, but it appears https://github.com/openshift/origin-web-console/blob/master/app/styles/_data-toolbar.less#L49-L54 could all go?

**Comment by sg00dwin** [comment]
@rhamilto IIRC those where needed for some browser. I'm testing to see if I can isolate which.

**Comment by rhamilto** [comment]
@sg00dwin, thanks.  It looks like a lot of these styles may be unnecessary as I've stripped away a whole lot of _data-toolbar.less in my debugging, and the results are the same minus the IE bug.  I've got more testing to do before PR-ing though.

**Comment by sg00dwin** [comment]
@rhamilto I found a regression bug in IE11 where the .data-toolbar-filter should expand as needed. I'm working on a fix.
https://github.com/openshift/origin-web-console/issues/551
