### ISSUE TITLE
ImageStreamResolver can make multiple requests for the same image stream image

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#548]
See https://github.com/openshift/origin-web-console/issues/523#issuecomment-245369576

**Comment by jwforres** [comment]
The fix for this is low-level in data service.  If we have a GET in flight we should keep a list of promises to resolve/reject once the GET finishes, similar to what we do with the callback lists for watch.

**Comment by spadgett** [comment]
Lowering the severity since it will happen much less often now.
