### ISSUE TITLE
One of the images has no text in web console using pipelinetemplate.json

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#55]
<img width="776" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/15806965/1464c770-2b1e-11e6-9256-5be5ad33897f.png">

Using `examples/jenkins/pipeline/pipelinetemplate.json`.

/cc @jwforres

**Comment by liggitt** [comment]
is this related to deployment configs being allowed to contain empty image names in their podspecs? I think some are being set to `" "` to avoid trying to pull bogus images before the dc is updated by a image change trigger

**Comment by spadgett** [comment]
@liggitt Yeah, looks like it.

https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/pipelinetemplate.json#L270

**Comment by liggitt** [comment]
https://github.com/openshift/origin/issues/9167 is proposing making `image` an optional field for dc podspecs to allow an image change trigger to populate it. asked in that pr what the UI should look at as a fallback if the dc image is empty

**Comment by spadgett** [comment]
@liggitt Didn't see an answer in https://github.com/openshift/origin/pull/9167. Any thought on what to put here?

**Comment by liggitt** [comment]
@spadgett I think something like this:

1. iterate over `spec.triggers`
2. find triggers of type `ImageChange` where `imageChangeParams.containerNames` includes the container name whose image is set to the empty string (or possibly where `imageChangeParams.containerNames` is null or an empty list?)
3. the `from` field of that ImageChange trigger references an imageStreamTag that will be used to populate the container's image field

**Comment by liggitt** [comment]
@bparees, can you confirm this method ^

**Comment by bparees** [comment]
mostly confirmed.  I don't think containerNames can be null/empty (for buildconfigs we do offer that sort of defaulting, but i don't think DCs do).  @kargakis would need to confirm though.

also not sure if the from field can reference a straight ImageStream or it always references an IST.

I had thought we discussed the need for this with @jwforres or even concluded the console was already doing this (ignoring the image field and displaying the ICT reference instead, when there was one)?

**Comment by kargakis** [comment]
> mostly confirmed. I don't think containerNames can be null/empty (for buildconfigs we do offer that sort of defaulting, but i don't think DCs do). @kargakis would need to confirm though.

I don't remember off hand but it seems this is correct:
https://github.com/openshift/origin/blob/7d6a536172ff82a6a60fbc51a71c35409e9017a0/pkg/deploy/api/validation/validation.go#L408

> also not sure if the from field can reference a straight ImageStream or it always references an IST.

Always an IST: 
https://github.com/openshift/origin/blob/7d6a536172ff82a6a60fbc51a71c35409e9017a0/pkg/deploy/api/v1/defaults.go#L103
https://github.com/openshift/origin/blob/7d6a536172ff82a6a60fbc51a71c35409e9017a0/pkg/deploy/api/validation/validation.go#L397

**Comment by jwforres** [comment]
Bumping priority to a P2 because the pipeline example has two of these images showing up blank.  We should really get this fixed

**Comment by spadgett** [comment]
> Bumping priority to a P2 because the pipeline example has two of these images showing up blank. We should really get this fixed

Also a problem for the DB templates.
