### ISSUE TITLE
immutable resources are busting the data cache 

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#550]
When we load a lot of immutable resources, like ImageStreamImage, they are keyed per resource, so they are busting the data cache which is limited to 25 keys.  Immutable resources probably need a separate data cache.

**Comment by jwforres** [comment]
They also aren't getting pulled out of the cache correctly because of https://github.com/openshift/origin/pull/10996

**Comment by benjaminapetersen** [comment]
Curious about a ballpark on # of items for this.  Would we just hard code a map of names of things that are immutable & swap between the two caches?

**Comment by jwforres** [comment]
the numbers vary greatly depending on the project. I started a fix yesterday already that splits off a separate cache for immutable items, since when we get immutable items we get individual items by a direct key and not via a List on a resource type
