### ISSUE TITLE
LIMIT_REQUEST_OVERRIDES aren't hiding the requests input anymore

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin-web-console#554]
At one point, when the config had:

- memoryRequestToLimitPercent / cpuRequestToLimitPercent

The requests input boxes were hidden from the user as it's a redundant field, however in 1.3.0 they appear to be back

**Comment by xingxingxia** [comment]
> At one point, when the config had:

That point should be since https://bugzilla.redhat.com/show_bug.cgi?id=1324825#c18 , which seems to cover only one situation of plugin config places mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1372618#c6 . Therefore caused this issue.

**Comment by sosiouxme** [comment]
Should be fixed with https://github.com/openshift/origin/pull/11045
