### ISSUE TITLE
Deleted projects never disappear from view

### ISSUE THREAD

**Issue by ALRubinger** [openshift/origin-web-console#56]
Steps to reproduce:

1) Log into OpenShift Console
2) Create new project with some default values
3) Go back to Home
4) Delete the project you'd just created
5) Status of the project shows marked for deletion
6) Item does not disappear on its own when it's deleted; console needs a refresh

![screenshot4](https://cloud.githubusercontent.com/assets/199891/15852538/602b5cc6-2c6f-11e6-95a6-7dd869546387.png)

**Comment by ALRubinger** [comment]
Minor issue for me, noncritical, just noting it for the team.

**Comment by spadgett** [comment]
@jwforres Project watch from @deads2k merged right? We're just not using it yet?

**Comment by deads2k** [comment]
> Project watch from @deads2k merged right?

It merged a while back.  Let me know if its bugged.

**Comment by marmendo** [comment]
I see this issue is already closed but doesn't look to be fixed in OCP 3.6
![captura de pantalla de 2017-10-30 09-48-59](https://user-images.githubusercontent.com/8353285/32161967-b027c640-bd57-11e7-85cd-e7d8fa5d6b43.png)

**Comment by spadgett** [comment]
@marmendo I suspect this is a different underlying cause. If you still see the projects after a console refresh or running `oc projects`, it's something else. I'd open a new issue in the openshift/origin repository.
