### ISSUE TITLE
_pod-details.html uses pod.status.hostIP, which is removed in 1.4

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#561]
```
$ ag hostIP
app/views/browse/_pod-details.html
33:        <dd>{{pod.spec.nodeName || 'unknown'}} <span ng-if="pod.status.hostIP && pod.spec.nodeName != pod.status.hostIP">({{pod.status.hostIP}})</span></dd>
```

See https://github.com/openshift/origin/releases/tag/v1.3.0
@jwforres

**Comment by jwforres** [comment]
is there a replacement, or is it gone completely, the release notes don't specify @smarterclayton

**Comment by jwforres** [comment]
since we already handle pod.status.hostIP not existing, removing the reference isn't important.  its currently still being returned by the API, so we will keep showing it as long as the API returns it and its different than the spec.nodeName

**Comment by jwforres** [comment]
i am still seeing pod.status.hostIP even in 1.5, im not sure those release notes were correct, either way we gracefully fallback when its not there so im closing this
