### ISSUE TITLE
Moment.js warning in image tag page

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#570]
This will be an error in the near future, will have to sift and find where we are using Moment.js & update accordingly:

![screen shot 2016-09-21 at 2 49 36 pm](https://cloud.githubusercontent.com/assets/280512/18724536/c0eacb84-800a-11e6-8d68-aaacd9399215.png)
(Error appeared on browse/images/<image-name>/latest)

**Comment by spadgett** [comment]
Also noticed this... @benjaminapetersen are you seeing that as well?

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/18724672/461738e2-800b-11e6-870e-5fb14c9cee4a.png)

**Comment by benjaminapetersen** [comment]
Yup! Thats prob even more concerning eh?

**Comment by jwforres** [comment]
cc @dperpeet

**Comment by benjaminapetersen** [comment]
Running the demo of `image-widgets` works fine, I suspect we see this issue cuz our moment.js is slightly older, though only a few points.

**Comment by stefwalter** [comment]
Do you have a case where this fails? Can you hover over the 'Invalid Date' and take a screenshot of the actual raw date displayed in the tooltip?

**Comment by stefwalter** [comment]
@benjaminapetersen or @spadgett ^^

**Comment by spadgett** [comment]
@stefwalter 

<img width="604" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/19118559/c198f732-8aea-11e6-8352-5586db591370.png">

Try

```
oc new-app https://github.com/openshift/nodejs-ex.git
```

and check the image that's built.

**Comment by spadgett** [comment]
cc @petervo

**Comment by petervo** [comment]
Fixed between, https://github.com/cockpit-project/registry-image-widgets/pull/5 and https://github.com/cockpit-project/registry-image-widgets/pull/1

**Comment by spadgett** [comment]
Closing since this is fixed in registry-image-widgets
