### ISSUE TITLE
auth error

### ISSUE THREAD

**Issue by meagon** [openshift/origin-web-console#591]
while I edit the configuration file``` app/config.local.js ```  as below:
```
window.OPENSHIFT_CONFIG = {
  apis: {
    hostPort: "https://192.168.0.100:8443",
    prefix: "/apis"
  },
  api: {
    openshift: {
      hostPort: "https://192.168.0.100:8443",
      prefix: "/oapi"
    },
    k8s: {
      hostPort: "https://192.168.0.100:8443",
      prefix: "/api"
    }
  },
  auth: {
    oauth_authorize_uri: "https://192.168.0.100:8443/oauth/authorize",
    oauth_redirect_base: "https://192.168.0.100:9000/",
    oauth_client_id: "openshift-web-console",
    logout_uri: ""
  },
  loggingURL: "",
  metricsURL: ""
};

window.OPENSHIFT_VERSION = {
  openshift: "dev-mode",
  kubernetes: "dev-mode"
};
```

I got auth error in my browser, what shall i do?
```json
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.",
"state":"{
       \"then\":\"/about\",
     \"nonce\":\"1474796593168-41174279103419956733134844421336946256181316082146166602229818590576472807592747\"}"
}
```

**Comment by liggitt** [comment]
Make sure the host/port of the oauth_redirect_base is one of the valid redirect urls in the openshift-web-console OAuthClient. You can do `oc edit oauthclient openshift-web-console` to add it if needed.

**Comment by spadgett** [comment]
@meagon Are you still seeing this? If you are running the web console on localhost:9000, can you try this command as cluster admin?

```
oc patch oauthclient/openshift-web-console -p '{"redirectURIs":["https://localhost:9000"]}'
```

**Comment by jwforres** [comment]
@meagon is `https://192.168.0.100:9000/` the host and port you are accessing the console on? if so then adjust what @spadgett said slightly and replace https://localhost:9000 with https://192.168.0.100:9000

**Comment by jwforres** [comment]
closing this since there has been no response, if you are still having issues please re-open
