### ISSUE TITLE
Metrics not showing in multi tenant environment

### ISSUE THREAD

**Issue by webtonize** [openshift/origin-web-console#598]
While trying out OpenShift Origin (v1.2.1. ansible installed) in a multi-tenant network plugin setup, I found metrics only showing for the openshift-infra and default projects in the web GUI. 

Other Projects (tenants) do not show any data in the metrics graphs for the pods.

The [hawkular metrics documentation](http://www.hawkular.org/docs/rest/rest-metrics.html#_tenant_header) shows a `Hawkular-Tenant: my-tenant` must be set in the HTTP request header. However when I check my Chrome Browser requests with Fiddler, I do see requests going to my hawkular-metrics pod, but without the tenant header being set for the project.

**Comment by spadgett** [comment]
The web console should be setting the `Hawkular-Tenant` request header. Could something in the network configuration be removing `Access-Control-Allow-Headers` in the OPTIONS response from Hawkular?

@webtonize Can you check if this is in the OPTIONS response in Fiddler?

<img width="713" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/18888771/bbba95d8-84c7-11e6-89cf-f6b8ac921da6.png">

/cc @jwforres @mwringe

**Comment by mwringe** [comment]
@webtonize what does the browser show is the response from this request?

**Comment by webtonize** [comment]
It seems I made a mistake in setting up fiddler correctlyh, fiddler does now show the tenant header being set, but i still have empty graphs for everything but the default project however. 

But being new to OpenShift and Docker, I guess I need to do some more reading first. ;-)

**Comment by mwringe** [comment]
@webtonize there shouldn't be anything which causes metrics to appear for one project and not another. So it is very strange you are encountering this.

Is this a single node cluster of OpenShift? Or are you running a multi node OpenShift cluster?

If its multi node and you can only read metrics on one node and not another, then there are a few things which could cause this problem (especially if the clocks on these nodes are not using and synchronised with an NTP server)

**Comment by webtonize** [comment]
It's a multi node cluster with 1 master/node and 2 nodes. I am looking at NTP at the moment cause I found that the HyperVisor's clocks are not all in sync. Since I upgraded my OS installation to 1.3 rpm, I still have the same problem and some graphs that do get shown have "holes" in them, that seem to get fixed at the same time as NTP updates the clock...

Thanks!

**Comment by webtonize** [comment]
Turned out te be a clock issue indeed. Conflicting setting where a poorly managed hypervisor was setting the system clock, as well as the ntp service on the OS nodes itself. Disabled the setting for the VM's syncing to the hypervisor and that did the trick.

Now have stats on all projects, thanks again for all the help.

**Comment by mwringe** [comment]
Awesome, glad to hear it is now working for you :)
