### ISSUE TITLE
Icon not centered on creation success message on overview

### ISSUE THREAD

**Issue by ajacobs21e** [openshift/origin-web-console#603]
![screencapture-192-168-99-100-8443-console-project-testproject-overview-1474998496223](https://cloud.githubusercontent.com/assets/6415742/18888258/84b57028-84c5-11e6-816f-78a1d8f36628.png)

check icon isn't centered vertically in the white box. please center it. @rhamilto

**Comment by spadgett** [comment]
I think the problem is that the top padding is larger than the bottom padding? I wouldn't expect the icon to be centered when the box grows (for instance when details are expanded or the text wraps).

**Comment by ajacobs21e** [comment]
PatternFly alerts have the icon centered on the top line of text, although the default / common use case is to have only one line of text. 

We should either
- use patternfly inline alerts
- decide to center on top line of text
- decide to center between the two lines of text (which would be centered in box for the common use case of one line of text & one line of link text)

Is there a reason this isn't using PatternFly?
