### ISSUE TITLE
"No deployments" message on overview is misleading

### ISSUE THREAD

**Issue by ajacobs21e** [openshift/origin-web-console#604]
![screencapture-192-168-99-100-8443-console-project-testproject-overview-1474998820710](https://cloud.githubusercontent.com/assets/6415742/18889278/48719038-84ca-11e6-8da4-9506d28633ec.png)

The large deployment block states there are no deployments but the pipeline row says a deployment is pending the build. The "no deployments" message implies that something is wrong or that the user has to take an action other than waiting.

I propose updating this message to state that the deployment is pending.

**Comment by spadgett** [comment]
+1, related to https://bugzilla.redhat.com/show_bug.cgi?id=1367379

**Comment by spadgett** [comment]
Fixed by https://github.com/openshift/origin-web-console/pull/755
