### ISSUE TITLE
Add custom categories in "Add to Project"

### ISSUE THREAD

**Issue by yadavnikhil** [openshift/origin-web-console#61]
Can i add more custom categories to "Add to Project" page more easily from external point instead of modifying create.js for them? If not can we have a feature of having add/delete these categories from UI directly & use them?

**Comment by spadgett** [comment]
@yadavnikhil Unfortunately, not currently. We have a Trello card open to improve the add to project catalog. I've linked to your issue from there.

https://trello.com/c/xlQaSaxT

**Comment by jwforres** [comment]
closing since this has been linked from the trello card
