### ISSUE TITLE
Option to allow the user to toggle individual metrics on overview

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin-web-console#619]
We've had to disable the overview metrics because it became just too resource intensive (both client and server sided), this is very obvious when the user has a lot of deployments in one project.

It'd be nice if we could give the user the option to click where the overview metrics used to be to show the metrics for that specific deployment/service. Metrics end up being quite hidden when they have to be disabled on the overview.

**Comment by spadgett** [comment]
@andrewklau Do you know roughly how many deployments you had when you saw the problem?

The metrics are only fetched and displayed for the deployments visible on the page, so I wouldn't expect too much impact on page load (at least until you start scrolling).

**Comment by andrewklau** [comment]
There was about 10 deployments in the project at that time. We also started splitting some of the projects up which has led to a much better experience.

**Comment by spadgett** [comment]
We're exploring ideas in https://trello.com/c/QxbqJsoK. Some of the early designs show a lot fewer metrics at once, which might address the problem.

cc @ajacobs21e

**Comment by spadgett** [comment]
@andrewklau #1335 should improve the performance you're seeing. In our initial testing, it scales better than before, and we don't show metrics sparklines until you expand a row.
