### ISSUE TITLE
ENV variable manager sluggish with lots of variables

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin-web-console#620]
We had a case where a pod had two containers, both with about 20+ ENV variables set. This ended up being very sluggish for the user when scrolling down and modifying these ENV variables.

Perhaps they could be split by a dropdown box similar to the terminal and logs. Although if an individual container still had a lot of ENV variables it would still also be quite slow.

**Comment by jwforres** [comment]
we definitely shouldn't be sluggish at 40 env vars, its not that many.  1000 would have been a different story.  @benjaminapetersen consider this next up after the membership stuff is done

**Comment by benjaminapetersen** [comment]
@andrewklau did you mean "sluggish" as in browser lag/response? I'm creating a few scenarios with a fairly absurd # of env vars and not experiencing that thus far.  However, I can definitely see that the user experience is less than idea at a certain point.

**Comment by andrewklau** [comment]
@benjaminapetersen yeah browser response when scrolling it kept jolting as I scrolled up and down the list (also when using the browser search function)

**Comment by spadgett** [comment]
@andrewklau Any chance there was a deployment in progress or something that could trigger many page updates?

**Comment by andrewklau** [comment]
@spadgett there were a few deployments happening in the project, can't remember if it was for the one being modified. This occurred around the same time we were seeing #621 so possibly related

**Comment by jwforres** [comment]
Ahhh OK, I can buy this causing a problem. So Ben you will need to set up a
pod crash loop example that has a bunch of env on it.

**Comment by benjaminapetersen** [comment]
Right. I don't think the editor itself has this performance issue so much as we are allowing it to be used when things are in flux.   Thinking about how to solve -- is it reasonable to disable the editor in certain states?

**Comment by spadgett** [comment]
@benjaminapetersen You might even use `$timeout` to simulate frequent digest loops and profile the KVE in Chrome to see where the time is spent.

**Comment by spadgett** [comment]
We have no `track by` here, which is probably contributing to this.

**Comment by spadgett** [comment]
Forgot the link...

https://github.com/spadgett/origin-web-console/blob/8c8ea04543ee0e3bb427c8af4120f960dfb0f4a2/app/views/directives/key-value-editor.html#L23

**Comment by spadgett** [comment]
#2416 should at least partially fix this.
