### ISSUE TITLE
ENV variable manager and crashing pods

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin-web-console#621]
This left a bad experience for a user who's pod kept crashing due to an incorrectly set ENV variable. 

When he went to edit the ENV variable in the console, because the pod kept restarting it was triggering a restart. By the time he had edited the ENV variable, the pod would've crashed and tried again, the web console would then force him to refresh the ENV variables and start again.

**Comment by jwforres** [comment]
@spadgett the fix you were looking into for only checking the env vars to trigger the warning should help with this issue
