### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#623]
My error console recently gets flooded with these messages:
<img width="507" alt="screen shot 2016-10-04 at 10 43 04 am" src="https://cloud.githubusercontent.com/assets/280512/19078776/5c229cbc-8a1f-11e6-9141-ee8bd2aa2b12.png">
I think it comes from a missing extension in an `@font-face { }` declaration on a `url` rule.

@rhamilto @sg00dwin bet either of you might have a better guess than i do?

**Comment by rhamilto** [comment]
[glyphicons are part of Bootstrap](https://github.com/twbs/bootstrap/blob/master/less/glyphicons.less#L11), but the font files Bootstrap includes aren't making it in to our dist.  I will add a PR to fix.  See http://stackoverflow.com/a/35038344

**Comment by rhamilto** [comment]
By the way, which glyphicon are you using?  Is there not a PatternFly or Font Awesome substitute?

**Comment by benjaminapetersen** [comment]
Hmm. I'm not doing anything new with icons, i just noticed my console getting noisy :)
They must have made it in somewhere else already.

**Comment by rhamilto** [comment]
Correction:  the font files were included, but the pathing to them was incorrect.  #625 resolves.
