### ISSUE TITLE
Select field on monitoring page collapses too narrow causing the text and down caret icon overlap

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#627]
It looks like setting a min width on .ui-select-bootstrap would correct it.

![screen shot 2016-10-05 at 1 36 02 pm](https://cloud.githubusercontent.com/assets/1874151/19124437/32dffc40-8b01-11e6-9f47-1c726c658bfd.png)

**Comment by sg00dwin** [comment]
@rhamilto thoughts?

**Comment by rhamilto** [comment]
@sg00dwin, hmf.  That wasn't happening in my branch (see #611).  Need to figure out where this bug came from...

**Comment by rhamilto** [comment]
@sg00dwin, https://github.com/openshift/origin-web-console/commit/d139242f5fe0567145f8917f4d19291fcf253c3c#commitcomment-19308886

**Comment by jhadvig** [comment]
I've added this rule cause in case of long text in the ui-select box the text overflowed:
![screenshot-42](https://cloud.githubusercontent.com/assets/1668218/19149914/839319b0-8bc4-11e6-96a0-dbc34d4c4842.png)

![screenshot-43](https://cloud.githubusercontent.com/assets/1668218/19149919/867ec714-8bc4-11e6-8a29-be8758cd1c84.png)

**Comment by rhamilto** [comment]
@jhadvig, IMO, it'd be better to make that rule specific to the context in which you need that fix (by either adding a class or using existing markup to add specificity to the selector since you're overriding the default.  @sg00dwin, agree/disagree?

**Comment by spadgett** [comment]
It seems strange that ui-select doesn't handle that on its own, unless we're overriding some of its styles causing the overflow.

**Comment by rhamilto** [comment]
Digging in further, the bug appears to be the result of an existing ui-select bug compounded by our own CSS.  Still diagnosing...

**Comment by jhadvig** [comment]
Yeah, I was surprised myself that they are not handling it, although it's known issue. They are just providing solution how to handle the issue by adding custom css.

**Comment by jhadvig** [comment]
@rhamilto well I can do that but then then I guess we would have to update all the ui-select tags with that class, cause it's a general issue

**Comment by rhamilto** [comment]
@jhadvig, I've found the fix in newer releases of ui-select; working on updating and testing now...
