### ISSUE TITLE
Overview app heading reused for all services in the same template

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#629]
If a template contains more than one service and the services aren't grouped, each service section has the same app name. (`oc new-app` will add the `app` label to each service, which we display.) This is a little confusing.

The `app` labels are displayed in the web console, but aren't used for grouping, so they can be repeated.

/cc @jwforres @thoraxe

**Comment by jwforres** [comment]
If we've got multiple primary services with the same APP label, display "APP-LABEL (service name)" or something similar
