### ISSUE TITLE
Icon for .dotNet

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#633]
There's no icon for .dotNet so that can be properly shown when added as a Builder Image in an ImageStream

**Comment by jwforres** [comment]
step 1 we would need an icon in the iconFont, step 2 we would need the iconClass set in the imagestream  @bparees

**Comment by bparees** [comment]
@jwforres am i to infer that @sg00dwin owns getting us the icon?

**Comment by jwforres** [comment]
Yep he is working on it

**Comment by jwforres** [comment]
the updated icons are in the web console code, but we need the .NET imagestream updated by the SCL team still

**Comment by bparees** [comment]
we still need to get the imagestream updated.  @jerboaa can you update the .NET imagestream definition to include the new icon reference that @sg00dwin has made available?

**Comment by jwforres** [comment]
the iconClass should be icon-dotnet

**Comment by bparees** [comment]
@jerboaa the reference looks like this: https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json#L18

and as @jwforres just said, the name is "icon-dotnet"

**Comment by jerboaa** [comment]
@bparees Sure. In future, please open issues here: https://github.com/redhat-developer/s2i-dotnetcore/issues

**Comment by jerboaa** [comment]
@bparees Uhm, it already is `icon-dotnet`. What do you want me to do? https://github.com/redhat-developer/s2i-dotnetcore/blob/master/dotnet_imagestreams.json#L23

**Comment by bparees** [comment]
@jerboaa nothing i guess. @jwforres ?  I guess we pre-emptively referenced the icon correctly?

**Comment by jwforres** [comment]
Looks like it, so yep we should be good to close this now.
