### ISSUE TITLE
Ordering of quotas table

### ISSUE THREAD

**Issue by ajacobs21e** [openshift/origin-web-console#634]
<img width="1440" alt="screen shot 2016-10-06 at 9 16 21 am" src="https://cloud.githubusercontent.com/assets/6415742/19151857/085fb7a0-8bc7-11e6-8090-cc4db04c8c97.png">

Graphs show request on left, limit on right
But table shows limits first then request

The first 4 rows of table should match the ordering of graphs (left to right => top to bottom) then additional information in rows 5+

**Comment by spadgett** [comment]
We should sort the remaining items as well. Right now they're in random order.
