### ISSUE TITLE
Multiple routes on a service difficult to see with long routes

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin-web-console#64]
I have 2 routes, first one is long (as typical with some of our cluster naming) and can't see info about secondary routes.

![screen shot 2016-06-15 at 9 35 54 am](https://cloud.githubusercontent.com/assets/727196/16081691/96d063f2-32dc-11e6-8b99-d0a8122c261b.png)

![screen shot 2016-06-15 at 9 36 22 am](https://cloud.githubusercontent.com/assets/727196/16081714/a8bb51e4-32dc-11e6-9f60-af445f6f6aaf.png)

**Comment by jorgemoralespou** [comment]
And in new UI, don't even show up.

````
oc new-project multiroute
oc new-app kubernetes/guestbook
oc expose svc/guestbook
oc expose svc/guestbook --name=guestbook2
oc expose svc/guestbook --name=guestbook3

$oc get routes
NAME         HOST/PORT                                    PATH      SERVICE              TERMINATION   LABELS
guestbook    guestbook-multiroute.apps.10.2.2.2.xip.io              guestbook:3000-tcp                 app=guestbook
guestbook2   guestbook2-multiroute.apps.10.2.2.2.xip.io             guestbook:3000-tcp                 app=guestbook
guestbook3   guestbook3-multiroute.apps.10.2.2.2.xip.io             guestbook:3000-tcp                 app=guestbook
````

![screen shot 2016-06-17 at 18 02 20](https://cloud.githubusercontent.com/assets/78350/16156682/afc66fca-34b5-11e6-898f-9a44fc903c4e.png)

**Comment by spadgett** [comment]
Yes, how important do you think the message is? It is not part of the new design currently.

**Comment by jorgemoralespou** [comment]
@spadgett Do not follow. What is important is to see that there is multiple routes mapped to this service.
Whether is display a message that show there is more, or just displaying them all, or only a fe (say 3, and then ... to see them all)

**Comment by spadgett** [comment]
@jorgemoralespou I ask because we've been trying to aggressively remove things from the overview to keep it from getting too dense. So my question is this important enough to show? We have less space for a message in the new design as well.

**Comment by jorgemoralespou** [comment]
@spadgett i think it is important at least graphically show there is more than one route. Which one will be display? In case there is many routes it will be very confusing that a user only sees one and that there is no indication that there is more, as it happened to me. Not sure if it's important to show them all, for it's important to indicate in some way that there are more routes, and a way to see them (though a link or hover or whatever).

**Comment by spadgett** [comment]
One possibility

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/16744933/7aa58dc4-4781-11e6-8d92-8ef6d5b5787e.png)

**Comment by spadgett** [comment]
Or

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/16745079/42539a6e-4782-11e6-9fee-adb7cc7fce18.png)

**Comment by sspeiche** [comment]
For A, I wonder what long routes look like. For example, http://hellomvc-sspeiche-dotnet.44fs.preview.openshiftapps.com/. I also worry what it looks like when we have summary info when collapsed.

For B, I worry about adding more vertical space but could be ok with summary info. Plus >1 route is somewhat rare.

**Comment by jorgemoralespou** [comment]
@spadgett I would go with option 2.

**Comment by jwforres** [comment]
Duplicate bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1355964

**Comment by jwforres** [comment]
and yeah i prefer option 2 as well

**Comment by spadgett** [comment]
I was considering a badge with a number or a tooltip as well.

@sspeiche I'll make sure long routes work.
