### ISSUE TITLE
Warning sometimes appear under the wrong deployment

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin-web-console#641]
Went from deployments back to the overview page, and notices about healthchecks all appeared under the second deployment. The first deployment had an active build running.

![image](https://cloud.githubusercontent.com/assets/2239920/19175521/0adecc8e-8c83-11e6-907b-6c236686b260.png)

All those containers are from different deployment.

**Comment by jwforres** [comment]
@andrewklau were you able to recreate this consistently?  what version were you running on at the time?

**Comment by andrewklau** [comment]
I just realised, all three of those notices were for deployments without a service. 

At the time, refreshing the page multiple times the issue still appeared.
Checking it now, the issue no longer appears anymore. I also don't seem to be able to reproduce it.

**Comment by spadgett** [comment]
I haven't been able to reproduce unfortunately. @andrewklau Were you doing anything else on the CLI with the overview open when this happened?

**Comment by andrewklau** [comment]
I also haven't been able to reproduce it. The project had the same deployments etc but the console is now 1.3.1

The only other thing active was a running build. Possibly fixed with the different version. I'll reopen this if I can manage to reproduce it.
