### ISSUE TITLE
RFE: be able to get to route details from overview page

### ISSUE THREAD

**Issue by soltysh** [openshift/origin-web-console#658]
Currently the overview page allows me to get to details of the objects it presents (deployment, service), except for route:
![untitled](https://cloud.githubusercontent.com/assets/576341/19273543/3517bc02-8fcd-11e6-9d53-a459767baa10.png)

Clicking route will take me to its destination, which is perfectly valid, but sometimes I'd like to be able to get to the route details quickly. 
Currently, the only option is to go through Applications->Routes->my route. How about having small (details) next to the route link which would do just that?

**Comment by jwforres** [comment]
a decision will be made on this as part of https://trello.com/c/QxbqJsoK

**Comment by spadgett** [comment]
You can do this now that #1335 has merged
