### ISSUE TITLE
The web console needs a warning / error dialog

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#659]
Related to [this comment](https://github.com/openshift/origin-web-console/pull/562#issuecomment-252977567) by @spadgett 

To summarize, our current dialog with an alert inside is not ideal, we should be able to use the alert modal but give it a class or something to change its presentation.

Current example:

![screen shot 2016-10-11 at 2 00 02 pm](https://cloud.githubusercontent.com/assets/280512/19282224/6ac0ac86-8fbb-11e6-88a3-f8b640ded4f6.png)

@jwforres @rhamilto @sg00dwin in case anyone wants to chime in on how this should be styled.

**Comment by sg00dwin** [comment]
I agree with @rhamilto In this use case the alert message should be part of the model text with a warning icon.

**Comment by rhamilto** [comment]
If the border, background color, and extra padding are removed from the alert within the context of a modal, the result looks like:

![screen shot 2017-06-29 at 3 11 50 pm](https://user-images.githubusercontent.com/895728/27705870-5d4f44d2-5cdd-11e7-98cb-b0702762c7b0.PNG)

This can be achieved with only CSS changes.  Thoughts?  

Tagging @jwforres, @spadgett so they get emails.

**Comment by jwforres** [comment]
we were wanting to change the general style of these modals anyway, they
feel out of place with the rest of the look and feel.  so we may want to
think about our long term direction for these before making a change

**Comment by rhamilto** [comment]
What's the history on the modal background color being gray?  The PatternFly default is white...

**Comment by jwforres** [comment]
It had something to do with the patternfly modal at the time requiring a title bar and it was weird having a title for what was just a simple confirmation dialog (at the time).  The style unfortunately spread to slightly more complex confirmation dialogs.

**Comment by jwforres** [comment]
I also suspect it originated when the console had a very different color scheme than it does today.  e.g. the original 3.0/3.1 styles like https://blog.openshift.com/wp-content/uploads/pod-list.png

**Comment by beanh66** [comment]
@benjaminapetersen I'm thinking we should follow a similar suggestion to what exists on the [Binding  design docs](http://openshift.github.io/openshift-origin-design/web-console/project-details/binding-in-project) See below:
<img width="961" alt="screen shot 2017-10-13 at 4 10 39 pm" src="https://user-images.githubusercontent.com/18057044/31564551-40e07a4e-b031-11e7-9cf0-1f8782a72d93.png">
