### ISSUE TITLE
Remove tech preview designation from pipelines

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#669]

**Comment by jwforres** [comment]
@bparees let us know when we are ok to do this

**Comment by bparees** [comment]
probably when this goes in: https://github.com/openshift/origin/pull/11065

**Comment by bparees** [comment]
(and that will go in after @gabemontero's oauth stuff has all landed in our jenkins image)

**Comment by bparees** [comment]
you're ok to do this.
