### ISSUE TITLE
Got both success and warning alerts when saving env variables

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#676]
Sometimes when you save env variables, you see both a success alert saying the resource was updated and a warning saying the resource was updated in the background. Neither of these alerts were visible before I clicked "Save." This was editing a deployment.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/19388345/1f9875b6-91ed-11e6-9db6-4a9560c5b729.png)

/cc @jwforres @benjaminapetersen

**Comment by benjaminapetersen** [comment]
Hmm. I can take a look if you want to pass it on.

**Comment by spadgett** [comment]
Related to #621. I think we should try to detect if the env var values have changed before showing the warning rather than warning for any update.

**Comment by spadgett** [comment]
@benjaminapetersen If it's specific to deployments, you can use this YAML.

https://github.com/openshift/origin-web-console/blob/master/test/testdata/k8s-deployments.yaml

**Comment by jwforres** [comment]
Definitely related to #621 once the PR to allow us to use PATCH goes in we'll fix these two together

**Comment by spadgett** [comment]
I believe this is happening because we're not resetting the form to pristine on successful update, so the watch callback results in the warning.

**Comment by spadgett** [comment]
The watch callback sometimes happens before the PUT callback, so the form is not set back to pristine in time.
