### ISSUE TITLE
Create secret page has awkward negative space on left-hand side

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#677]
During @jhadvig's sprint demo, I noticed the create secret page has awkward negative space on left-hand side.  Presumably this is a simple issue in the template/css.

![screen shot 2016-10-14 at 11 11 22 am](https://cloud.githubusercontent.com/assets/895728/19392646/abf87daa-91ff-11e6-991b-1c8e3408a2e4.PNG)

**Comment by spadgett** [comment]
Yeah, these were just his local changes. They haven't merged yet.

**Comment by jhadvig** [comment]
I was just using the layout we have in the `Create Route` page

![screenshot-50](https://cloud.githubusercontent.com/assets/1668218/19393186/f9f524b6-9233-11e6-9753-18f5f5fa640f.png)

**Comment by spadgett** [comment]
Ah we should fix it there. Might only happen at very wide screen sizes.
