### ISSUE TITLE
Integration Test UX Is Bad

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-web-console#688]
The integration test should either start and clean up an OpenShift server to do the tests against or fail when one is not up. The current flow doesn't fail on the `add-redirect-uri` step if it fails, which is weird.

**Comment by spadgett** [comment]
> The current flow doesn't fail on the add-redirect-uri step if it fails, which is weird.

Whatever we change, we need to make sure the tests still run in a development environment where this step will always fail.

**Comment by stevekuznetsov** [comment]
>  in a development environment where this step will always fail

Why?

**Comment by liggitt** [comment]
because the apiserver often isn't running at localhost, it's running inside a `cluster up` container

**Comment by stevekuznetsov** [comment]
My steps for running these tests:
```
$ oc cluster up
$ oc login -u system:admin
$ hack/test-headless.sh test-integration
```

In this series of steps I see a successful patch happen.

**Comment by jwforres** [comment]
We typically cluster up inside vagrant, we are running our tests outside
vagrant

**Comment by spadgett** [comment]
We might just take the `add-redirect-uri` step out now that the merge queue uses cluster up where it's not needed.
