### ISSUE TITLE
service with no route and no app label doesn't have the Create Route action

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#690]
If I have a service that has no route pointing to it, and that also does not have an app label on it, then there is no option to create a route.

**Comment by jwforres** [comment]
cc @spadgett

**Comment by spadgett** [comment]
Related card: https://trello.com/c/QxbqJsoK

@ajacobs21e FYI

**Comment by ajacobs21e** [comment]
@spadgett thanks, I'll add this to the list of reqs.

**Comment by spadgett** [comment]
This is fixed in the new overview for 3.6.

https://github.com/openshift/origin-web-console/pull/1335
