### ISSUE TITLE
Image from quay.io shows up as a Docker Hub image

### ISSUE THREAD

**Issue by kargakis** [openshift/origin-web-console#691]
![image](https://cloud.githubusercontent.com/assets/3900799/19517133/a5a1755c-95ff-11e6-8f62-cb54fd89b6e7.png)

Not sure if this is a web console bug or something else. Found during the hack day (today:))

**Comment by jwforres** [comment]
I would prefer we default to not saying where its from when we don't have the registry ref available, should just be changing this line

```
<span ng-if="mode === 'dockerImage'">from {{import.result.ref.registry || "Docker Hub"}},</span>
```
