### ISSUE TITLE
Edit deployment menu item should not appear below pause

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#692]
Edit is probably more important.

**Comment by jwforres** [comment]
depends on whether you want to Promote them pausing before the start editing, i could see either way

**Comment by spadgett** [comment]
I feel like it should at least be above the separator.

![screen shot 2016-10-25 at 4 38 33 pm](https://cloud.githubusercontent.com/assets/1167259/19703354/87f6c53a-9ad1-11e6-99da-e2251cf990d7.png)

**Comment by spadgett** [comment]
We might want to reorder some of those action or at least adjust the names (Set Resource Limits -> Edit Resource Limits?)

**Comment by jwforres** [comment]
Fixed in https://github.com/openshift/origin-web-console/pull/784
