### ISSUE TITLE
Project membership: roles not sorted in last dropdown

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#700]
Roles are not sorted in last select (for new users).

![screen shot 2016-10-20 at 5 59 30 pm](https://cloud.githubusercontent.com/assets/1167259/19605324/6cf5d430-9787-11e6-8d2a-90bff8177435.png)

**Comment by benjaminapetersen** [comment]
Ok ill hit this when I get back. I think there is an error message with some poorly formatted text I need to take care of as well.
