### ISSUE TITLE
Can't type in tag for ICT when an image stream has no existing tags

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#745]
Editing a deployment config, I can't type in tag "latest" for an image stream that doesn't have any tags yet. The control lets me type, but the value is cleared as soon as it loses focus. There's no way to save the new value.

![screen_shot_2016-10-26_at_3_45_00_pm](https://cloud.githubusercontent.com/assets/1167259/19742503/543a2620-9b93-11e6-87e3-56fe6d6fc994.png)

/cc @jhadvig @jwforres

**Comment by spadgett** [comment]
Sorry confusing this with the build config editor, which supports typing tags. Although do we want that here, too? I don't see a reason to block it.

**Comment by jhadvig** [comment]
@spadgett not really sure if it makes sense to track the tag that might not exist. 
If we decide to do this please let me know... will update it asap :)

**Comment by spadgett** [comment]
That's fine. I'll close. When I opened the issue I was thinking it was supported and not working.

**Comment by jwforres** [comment]
agreed, i dont see a reason to prevent it
