### ISSUE TITLE
Pipelines and Secrets pages have border underneath h1, but no filter

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#779]
I noticed the Pipelines and Secrets pages are outliers in that they have borders underneath the h1, but do not include the filter toolbar.  Comparable pages Quota and Membership do not have the border.

<img width="1018" alt="screen shot 2016-11-01 at 10 26 25 am" src="https://cloud.githubusercontent.com/assets/895728/19893079/466d1a40-a01e-11e6-9c7c-5b7521929a45.PNG">

<img width="1015" alt="screen shot 2016-11-01 at 10 31 31 am" src="https://cloud.githubusercontent.com/assets/895728/19893207/bab33b1e-a01e-11e6-95bd-87d02bc6f0d6.PNG">

**Comment by sg00dwin** [comment]
I suggest all secondary level pages (any page that can be directly navigated to from the primary nav) have consistent header structure, and would have the header with the single border. And other pages that are tertiary (eg. /builds/pipelines/sample-pipeline) would not.

@rhamilto your thoughts?

**Comment by rhamilto** [comment]
@sg00dwin, sounds good to me.  Consistency is key for me.
