### ISSUE TITLE
Display of metrics visual bug

### ISSUE THREAD

**Issue by ALRubinger** [openshift/origin-web-console#78]
Instructions:

Open Overview page
Expand service
Observe as shown
![screenshot20](https://cloud.githubusercontent.com/assets/199891/16202286/03a3057a-36e3-11e6-8119-99bb72669414.png)

```
Google Chrome	51.0.2704.84 (Official Build) (64-bit)
Revision	9125d1d23608a4fe105afb75b0c480a8dd3eef93-refs/branch-heads/2704@{#705}
OS	Linux 
```

**Comment by ALRubinger** [comment]
cc @spadgett @jwforres

**Comment by ALRubinger** [comment]
![screenshot21](https://cloud.githubusercontent.com/assets/199891/16202381/6a0e490a-36e3-11e6-9ab6-038d770b9512.png)

The above screenshot also shows the issue in Firefox 47.0/Linux.

The "Catapult" application looks fine:

![screenshot22](https://cloud.githubusercontent.com/assets/199891/16202412/969792a6-36e3-11e6-91e5-07c27804cfdf.png)

**Comment by ALRubinger** [comment]
After some time, the console autocorrects:

![screenshot24](https://cloud.githubusercontent.com/assets/199891/16203502/9f75ad4a-36e8-11e6-8b31-5546d382257b.png)

..however the current build and pipeline is not shown.  Will file that in another issue.

**Comment by spadgett** [comment]
I suspect this is an interaction between c3.js and uib-collapse where c3 sizes the chart before it's visible.

**Comment by spadgett** [comment]
#69 has fixed this indirectly.
