### ISSUE TITLE
Different select styles on add to project page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#785]
We have a mix of normal HTML `select` elements and `ui-select` elements on the create from source page now that we've added secrets. They have different styles that clash. We should consider switching them all to `ui-select` for consistency.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/19904448/03c1efa6-a049-11e6-94a8-dadbac3ac0bb.png)

cc @jwforres @rhamilto

**Comment by jhadvig** [comment]
Part 1 : https://github.com/openshift/origin-web-console/pull/1024
