### ISSUE TITLE
Console Overview page does not show current build 

### ISSUE THREAD

**Issue by ALRubinger** [openshift/origin-web-console#79]
![screenshot24](https://cloud.githubusercontent.com/assets/199891/16203532/be453c36-36e8-11e6-87df-914b051bc911.png)

cc: @spadgett @jwforres

**Comment by ALRubinger** [comment]
Expected (RHT only, sorry!):

  https://drive.google.com/a/redhat.com/file/d/0BxppHkjprXoJSks2eFZEd25aUGM/view?usp=sharing

**Comment by spadgett** [comment]
Can you try adding this annotation?

https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/pipelinetemplate.json#L23-L25

**Comment by ALRubinger** [comment]
Thanks!  Fixing this for ourselves by enabling this feature via the annotation suggested.  We tracked here: https://github.com/redhat-kontinuity/catapult/issues/133

Closing as not an issue with the OpenShift Console.
