### ISSUE TITLE
Webhook URL wrong

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin-web-console#790]
Builds -> build name --> edit

The webhook url is incorrectly shown as:

https://api/oapi/v1/namespaces/project.metadata.name/buildconfigs/buildConfig.metadata.name/webhooks/xyz/generic

Seems project.metadata.name and buildConfig.metadata.name is not properly parsed. CLI shoes the correct webhook url

OpenShift: v1.3.1

**Comment by spadgett** [comment]
@andrewklau Thanks for letting us know. This is fixed in 1.4 by #673. Also tracked by

https://bugzilla.redhat.com/show_bug.cgi?id=1384617
