### ISSUE TITLE
DataService.list to update

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#799]
The instances of `DataService.list` that we need to update now that it supports promises.

- [x] create/createFromImage.js
- [x] attachPVC.js
- [x] create/browseCategory.js
- [x] create.js
- [x] createRoute.js
- [x] deployment.js
- [x] edit/buildConfig.js
- [x] deploymentConfig.js
- [x] edit/autoscaler.js
- [x] edit/deploymentConfig.js
- [x] edit/route.js
- [x] membership.js
- [x] otherResources.js
- [x] quota.js
- [x] secrets.js
- [x] setLimits.js
- [x] replicaSet.js

**Comment by spadgett** [comment]
Let's skip overview.js and topology.js, which will both be removed soon

**Comment by benjaminapetersen** [comment]
Sounds good.

**Comment by MarkDeMaria** [comment]
@benjaminapetersen I'm not seeing settings.js. Is that deprecated code?

**Comment by spadgett** [comment]
It's been removed.

**Comment by benjaminapetersen** [comment]
@MarkDeMaria if the file is not there, you can cut the todo.  Also, if the actual `.controller('WhateverName')` isn't listed in the `app.js` file under routes, its stale & we can eliminate it rather than update.

**Comment by spadgett** [comment]
Added newOverview.js

**Comment by spadgett** [comment]
Verified that the remaining items are done.

/close
