### ISSUE TITLE
Deployment config page should show hooks

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#807]
We let you edit hooks, but you can't view them on the deployment config page. Generally I feel like we should show you anything that we let you edit. The hooks are important as well.

@jwforres Let me know if you think this is large enough for a card.

**Comment by spadgett** [comment]
(I'm not proposing this for 1.4.)

**Comment by jwforres** [comment]
there already is a card :)

https://trello.com/c/2rDfr6Ma
