### ISSUE TITLE
Removal of the image trigger from autodeploy shouldn't remove the trigger 

### ISSUE THREAD

**Issue by kargakis** [openshift/origin-web-console#808]
![autodeploy](https://cloud.githubusercontent.com/assets/3900799/19946782/9f29a18a-a145-11e6-9c6d-275b30a7d8fd.png)

Unselecting "New image is available" shouldn't remove the ICT from the DC. It should just set it to automatic=false. In that way user errors like https://bugzilla.redhat.com/show_bug.cgi?id=1383804 will be greatly reduced where a user creates a new DC, doesn't want to have automatic deployments, but when tries to deploy they get image pull errors because we cannot resolve their images. It would be great to have this fixed for 1.4.

**Comment by spadgett** [comment]
@jhadvig Can you help check if we're presenting the `automatic` properly correctly for image change triggers in the deployment config editor?

**Comment by jhadvig** [comment]
@spadgett yes, tested it and if the ICT is enabled the `automatic: true` is present in the `imageChangeParams`

**Comment by spadgett** [comment]
@jhadvig I was wondering if we need separate checkboxes in the dc editor. Something like

[ ] Track image stream tag

(image stream tag dropdowns here when checked)

[ ] Deploy automatically when the image changes

Then if I uncheck deploy automatically, it doesn't remove the trigger. It just sets `automatic: false`.

@kargakis Would this make sense?

**Comment by kargakis** [comment]
@spadgett yes, makes sense. If you are not tracking an image stream tag, the second option should be disabled.

**Comment by spadgett** [comment]
@kargakis When setting `automatic: false`, would we change `spec.template.spec.containers[n].image` to point back to the image stream tag? Generally it's set to a specific sha.

**Comment by kargakis** [comment]
`spec.template.spec.containers[n].image` is always set by the trigger controller. Users need to set the from object reference in the ImageChange trigger to track the image stream tag.
