### ISSUE TITLE
Bad right click / open in new tab behavior on tags on add to project page 

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#81]
On the add to project page the tags on images and templates are actually links, this means the right click context menu -> open in new tab option is accessible.  However the href will just point the user back to the project list page (homepage).  We could:

1) Disable the right click context menu on those links
or
2) Set the href to the current page plus a query param for a filter

I prefer we do (2) since its reasonable to want to link to the page with a tag pre-filtered (e.g. from docs / blog posts / etc)

**Comment by spadgett** [comment]
This seems to be a problem everywhere we use `href=""` (which is what angular recommends). Does it work to use `<button class="btn btn-link">`?

http://getbootstrap.com/css/#buttons-options

**Comment by jwforres** [comment]
I think in other places where we actually have things that look like links
yes, though these tags in particular have their own hover styling so we'd
probably have to do some extra work.  In theory shouldn't be too bad.
These seems like a reasonable option (3) to me.

**Comment by spadgett** [comment]
These specific tag links no longer exist since the page has been redesigned in #701. @jwforres OK to close?
