### ISSUE TITLE
Hawtio-core.js logs random things

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#818]
Not entirely sure why yet:
![screen shot 2016-11-03 at 4 40 57 pm](https://cloud.githubusercontent.com/assets/280512/19984360/5eef9f08-a1e4-11e6-87da-e5478e220e4a.png)

**Comment by jwforres** [comment]
Found the problem, the deployment controller is using Logger but didnt add it to the dep list at the top.  So its actually using the Logger that comes with hawtio-core which just wraps console.log

**Comment by jwforres** [comment]
we are actually doing this in a bunch of places @spadgett

**Comment by benjaminapetersen** [comment]
Oh? So Logger from Hawtio is different than our Logger service...
