### ISSUE TITLE
Custom input select box requires explicit "enter"

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#832]
Originally reported on this Trello card: https://trello.com/c/365NeA8Y/502-8-web-console-managing-project-membership-evg-ux-p2

When adding a role to a service account on the membership page, if the user wants to add an unlisted project an explicit "enter" or "tab" selects the project name, but it isn't added to the list in a semi-persistent way.  When the user types in a new name it replaces the old (similar to the edit build config page that lets the user choose a github tag or enter an unlisted).  

It would be ideal for these to linger until "done editing" is clicked, even if the user inputs more than one project.  The problem is that if a user doesn't have any access to a project, we don't have a way to know a match, so we may end up filling the drop down list with a bunch of partial text.  For example, if the project name is "My Awesome Project" and we are simply debouncing before an add, we could fill up the list with "My", "My Awe", "My Awesome Pr", etc.  That would also be an unpleasant user experience. 

Not sure if this is really fixable without an explicit match w/o filling the list with clutter, but opening the issue in case something comes up.

**Comment by xingxingxia** [comment]
If not fixable, a '?' icon aside that prompts current usage when hovered on, will be helpful :)
