### ISSUE TITLE
Catalog word breaks awkward in some browsers

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#834]
Because we use the `work-break-all`, some of the word breaks are awkward in IE and Firefox. For instance, "Ephemeral" is broken mid-word. I'd like to see if there is a fix for #828 without this side effect.

![dashboard](https://cloud.githubusercontent.com/assets/1167259/20060904/6149945e-a4cb-11e6-906b-7febb4aa22c4.png)

/cc @jwforres @sg00dwin @rhamilto

**Comment by rhamilto** [comment]
@sg00dwin, I know you put a lot of work and research in to [the word break mixins](https://github.com/openshift/origin-web-console/blob/master/app/styles/_mixins.less#L43-L60).  Based on what I've read of your comments there, I don't think there is an alternative.  True?

**Comment by spadgett** [comment]
I might even prefer clipping the word in the rare case when there's a long word with no places to break (since we can break on template names with `-` already). We've made the common case a little worse.
