### ISSUE TITLE
Adding service account a little confusing

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#850]
The project dropdown is in the roles column, so it looks like I'm adding role `oc`. Also the other names have a prefix, so it looks like you should type "oc/my-name" in the input, which is an invalid name. I think we at least need labels for the inputs since they don't correspond to the column headings, or maybe move them. Placeholder text in the name input wouldn't hurt.

<img width="692" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/20113265/b6cca6bc-a5bd-11e6-997b-98689ea041b1.png">

cc @benjaminapetersen @jwforres @ajacobs21e

**Comment by spadgett** [comment]
We should also use `ng-pattern` for the name invalid to prevent someone submitting a value we know won't work.

**Comment by benjaminapetersen** [comment]
Agree on both, was looking at the placement of the namespace picker as well.  I think it was natural cuz it fit the space, but it is completely unintuitive.  

Ill self assign.

**Comment by spadgett** [comment]
Should we list the service accounts in the selected namespace like we do for `istag-select`? It could be

<img width="971" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/20119756/c5366188-a5d7-11e6-9821-46f6051a8b35.png">

Here it could be:

[Namespace] / [Service Account]

**Comment by benjaminapetersen** [comment]
We could, just make the service accounts tab be 4 columns instead of 3. It would jitter a bit when switching from other tabs, but seems like the right way to solve.

**Comment by ajacobs21e** [comment]
I don't understand the data here so I don't have any suggestions. I'm happy to talk through it if @spadgett or @benjaminapetersen have time to explain it to me - unless you guys figured it out already?

**Comment by benjaminapetersen** [comment]
@ajacobs21e I think @spadgett's suggestion will work great, but happy to explain anytime if you are curious!

**Comment by ajacobs21e** [comment]
@benjaminapetersen Sam's suggestion works then! thanks

**Comment by benjaminapetersen** [comment]
related to #1191 & can perhaps fix together
