### ISSUE TITLE
Update or remove deprecated deploy CLI example

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#866]
See https://github.com/openshift/origin/releases/tag/v1.4.0-alpha.1

> oc: deprecate 'deploy --latest' in favor of 'rollout latest --again' #11287

We still show `deploy --latest` as a CLI example in the UI.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/20230803/d4a44c4c-a82b-11e6-9c42-c3746bf79cf5.png)

I'd prefer to just remove that since you can start deployments from the web console.

**Comment by jwforres** [comment]
@mfojtik @bparees @sspeiche do any of you have an opinion on keeping vs removing the Manual CLI triggers for DCs and BCs.  Do we think anyone is actually using that given that you can hit Deploy or Build in the console?

**Comment by bparees** [comment]
Personally I like UIs that teach/show me the CLI equivalent for what it is doing for me, it's a useful learning tool.

**Comment by sspeiche** [comment]
Maybe we can have something like the "What's a jenkinsfile?" link, that says: "Teach me how to do this on the CLI?" and not have the cli commands available by default.
