### ISSUE TITLE
Pod - Log tab - 'follow' and 'go to top' links combination

### ISSUE THREAD

**Issue by antonioberben** [openshift/origin-web-console#872]
Hi there,

Here a bit of feedback to improve user experience (Not sure if it is already planned or even solved in late releases)

I have noticed that, once I am in the middle of the logs I need to click on `Follow` (to go to bottom) and then click to 'Go to top' to got finally to the top of the screen to reach the menu.

It would be nice if to go to top, I do not need to click on Follow link.

Use-case:

You have a huge log traces. Longer that the screen high.
You scroll down to the middle to check some log trace.
To go top you have to:
1. Click on 'Follow' blue link and then 'Go to top'
or 
2. Scroll up with mouse (which is tedious)

Cheers!

**Comment by jwforres** [comment]
Should evaluate the use of https://github.com/filamentgroup/fixed-sticky as part of this issue.  See old issue https://github.com/openshift/origin/issues/8175

**Comment by rhamilto** [comment]
https://github.com/filamentgroup/fixed-sticky won't work in our context because it assumes body is scrolling (not some inner element).  I had started a [branch utilizing the polyfill](https://github.com/rhamilto/origin-web-console/tree/issue-1322-sticky) when I discovered the limitation.

**Comment by spadgett** [comment]
cc @ncameronbritt
