### ISSUE TITLE
Pod - Terminal tab

### ISSUE THREAD

**Issue by nennete** [openshift/origin-web-console#873]
hi there,

A bit of feedback to improve user-experience.

Once I access to the terminal in a pod, it would be very nice if the console holds the previous commands. I mean the up/down arrow function to go through the history.

Cheers!

UPDATE:
It looks like in some other OS that works. On a Ubuntu and chrome as browser, the arrows do not work. thank you.

**Comment by spadgett** [comment]
@nennete 

* Can you make sure you are testing the same pod and container on both platforms? Just want to eliminate the possibility that it's a limitation of the shell for a particular container.
* Does Ctrl-P and Ctrl-N work in place of the arrow keys? Do the left and right arrow keys move the cursor properly?
* Do you see the same problem with `oc rsh <pod-name> -n <project-name>`?

**Comment by nennete** [comment]
@spadgett First, thank you for your early help.

- Trying different pods, from different services, same results.
- Ctrl+P / Ctrl+N does not work in UI
- Neither in command line through `oc rsh ...`

But, my version is quite old (oc v.1.2.0 ; kubernetes v1.2.0). I will try to install, within following days, the last version to double check.

Thank you.

**Comment by spadgett** [comment]
@nennete I suspect history just isn't enabled in your shell. I don't think it's anything specific to the web console. If you type `bash` in the terminal to start a bash shell, does history work?

**Comment by nennete** [comment]
Thanks for your help and sorry for this late answer.

You are right. In my containers I do not start the bash. And that is the thing.

Thanks a lot.

**Comment by spadgett** [comment]
Glad I could help.
