### ISSUE TITLE
Membership error message abuts title header

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#878]
![screen shot 2016-11-15 at 1 45 46 pm](https://cloud.githubusercontent.com/assets/895728/20318829/ebee99fa-ab39-11e6-8ab6-b68f3650824b.PNG)

Presumably there should be some space between the header border and the text.

**Comment by spadgett** [comment]
Seems like basically the same problem as #803.

**Comment by spadgett** [comment]
@sg00dwin do you mind double checking the various pages from #796 to make sure there aren't other messages that we've missed?

**Comment by sg00dwin** [comment]
yep I'll check those
