### ISSUE TITLE
Buildconfig editor "learn more" links don't point to section

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin-web-console#879]
As a user of the contextual help, I would expect ... well...help in context. Instead I'm always pointed to https://docs.openshift.com/online/welcome/index.html

It would be ideal to drop the end user in a section that provided some contextual help. It would be even better to have some quick tool tip help instead of a new tab opening with toplevel docs.

**Comment by spadgett** [comment]
Appears to be the same as

https://bugzilla.redhat.com/show_bug.cgi?id=1393771
