### ISSUE TITLE
Not obvious what the colors mean in the image stream tag layers tab

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#881]
There is no legend or tooltip for what each color means. Could also be a problem for colorblind users?

<img width="638" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/20349428/6a46e2b4-abd8-11e6-905b-1e4a13ebb7bd.png">

cc @jwforres @sspeiche

**Comment by jwforres** [comment]
cc @dperpeet

**Comment by jwforres** [comment]
@stefwalter looking at the image widgets code I see you are deciding whether its an ADD based on size https://github.com/openshift/registry-image-widgets/blob/master/layers.js#L78

Is there a reason 8KB was picked for that? or is it arbitrary?

**Comment by stefwalter** [comment]
I think it's arbitrary. FWIW, Openshift still doesn't include proper layer data in ImageStreamImage data ... but obviously we can change the behavior here if it's causing problems for Openshift. I'd help review a pull request.

**Comment by jwforres** [comment]
@mfojtik see stef's comment above.  I know things are changing relative to how image information is being stored and fetched, will that change what layer data is available to us?

**Comment by jwforres** [comment]
@stefwalter I do think arbitrarily deciding something is an ADD based on size is a confusing behavior to a user.  I think no matter whether we can get all the data we want in the layers that we should probably take out that part of the code that decides its an ADD.

If we've only got one color of dots in the console it eliminates the need for adding a legend until the time when we get the correct labels coming back which would say "ADD" or "RUN" in them.  We will get a PR open to the image widgets to fix this, thanks!

**Comment by mfojtik** [comment]
@legionus PTAL ^

**Comment by jwforres** [comment]
@stefwalter the registry-image-widgets repo is missing a Gruntfile, what are you using to build the dist?
