### ISSUE TITLE
Blank login success page when `/login` missing url params

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin-web-console#888]
Related Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1369854

Opening this issue mostly for feedback / discussion

When logging in through the web-console without any redirect information `https://localhost:8443/login`, a blank page is displayed after a successful attempt. This makes sense, as the server only seems to attempt an http redirect if the `then` parameter it receives is not empty here https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/auth.go#L757-L764

In order to avoid this however, I was wondering if there could simply be a default value for the `then` parameter that is sent to the server? Also, would a change like this take place on the login page template? https://github.com/openshift/origin/blob/master/pkg/auth/server/login/templates.go#L2399

cc @liggitt  @fabianofranz @jwforres

**Comment by liggitt** [comment]
if we can come up with a reasonable default redirect, I would redirect a request to /login that did not specify a `then` param there *prior* to login

**Comment by jwforres** [comment]
the project list seems like the most reasonable choice

**Comment by liggitt** [comment]
login server doesn't know anything about the console. I was considering redirecting to `/`, which would forward to `/console` if enabled, which would kick into a regular login flow. Critically, the console needs to be expecting the login to set up the proper csrf/nonce/state stuff to avoid a warning about an unexpected OAuth flow appearing

**Comment by juanvallejo** [comment]
@liggitt I added
```
if len(then) == 0 {
    then = "/"
}
```

right before this line https://github.com/openshift/origin/blob/master/pkg/auth/server/login/login.go#L172 and it successfully forwards to `/console` allowing me to arrive at the projects list page. Although I'm assuming this behavior should be left for the client to handle, rather than "fixing" it server side?

**Comment by liggitt** [comment]
fixed in https://github.com/openshift/origin/pull/11961
