### ISSUE TITLE
Change constants.js help links to use configurable base URL

### ISSUE THREAD

**Issue by damemi** [openshift/origin-web-console#896]
In [constants.js](https://github.com/openshift/origin-web-console/blob/enterprise-3.4/app/scripts/constants.js#L12), each doc link is hardcoded to direct to container platform docs. This means that for environments that extend these links, such as online and dedicated, a full copy of this list needs to be maintained and updated any time the link changes in constants.js.

Since the only difference is the base URL (ie, `https://docs.openshift.com/container_platform/3.4/`), propose changing these links to use a configurable `window.OPENSHIFT_CONSTANTS.HELP_BASE_URL` variable to reduce the number of variables that need to be maintained.

Example:
`"cli": window.OPENSHIFT_CONSTANTS.HELP_BASE_URL+"/cli_reference/overview.html",`

**Comment by jwforres** [comment]
@damemi it will be in OCP 3.5, docs PR for reference on how to customize it https://github.com/openshift/openshift-docs/pull/3268

**Comment by damemi** [comment]
@jwforres is there any reason it needs to wait for 3.5?

**Comment by jwforres** [comment]
@damemi only significant blockers are going into 3.4 at this point
