### ISSUE TITLE
Align Table Columns When Possible

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-web-console#904]
Unclear if this is technically difficult to do, but on pages with lots of tables, it would be nice to have the columns aligned when possible, for example this looks a little jumbled:

![tables](https://cloud.githubusercontent.com/assets/7328370/20489550/02cdf3c0-afd9-11e6-9f6f-082383598dc4.png)

**Comment by spadgett** [comment]
We could use fixed column widths.

**Comment by spadgett** [comment]
cc @rhamilto
