### ISSUE TITLE
Millicore Doughnut Seems Out-of-Place on Metrics Overview

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-web-console#912]
In the metrics overview, the CPU millicore doughnut takes up a huge amount of screen real-estate and breaks up the flow of the page:
![cores](https://cloud.githubusercontent.com/assets/7328370/20525126/fa0e2684-b08b-11e6-9487-0ebbf8cefc5b.png)

**Comment by stevekuznetsov** [comment]
The header (97 available of 100 millicores) may be sufficient to get the point across, especially if the horizontal rule doesn't travel across the entire screen below it? Or the header and doughnut could go to the left of the graph? I don't know, I'm not a designer :)

**Comment by spadgett** [comment]
Agree that it looks odd. We have a Bugzilla tracking.

https://bugzilla.redhat.com/show_bug.cgi?id=1387286

**Comment by spadgett** [comment]
Closing in favor of the Bugzilla bug
