### ISSUE TITLE
`canI` checks for adding storage to deployment are wrong

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#914]
https://github.com/spadgett/origin-web-console/blob/da4a37d40751c459a7d0fad33ab92006efc14f78/app/views/browse/deployment.html#L170-L178

We should make a `canI` check against `deployments`, not `deploymentconfigs`.

cc @jwforres

**Comment by jhadvig** [comment]
I guess we can close this one since the issue has been taken care of in https://github.com/openshift/origin-web-console/pull/891

@spadgett thoughts ?

**Comment by spadgett** [comment]
Yep, thanks.
