### ISSUE TITLE
orderByDisplayName filter isn't stable

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#915]
<img width="775" alt="screen shot 2016-11-22 at 11 04 39 am" src="https://cloud.githubusercontent.com/assets/895728/20531087/9fde3e48-b0a3-11e6-992e-abddbd5c18ed.PNG">

When display names are the same, the filter should consistently sort by the name.  It randomly flakes.

**Comment by spadgett** [comment]
Let's fix this for the project list as well. I believe it has the same problem.
