### ISSUE TITLE
buildconfig/pipeline in project X doesn't display in project Y

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin-web-console#917]
```
openshift v3.3.1.3
kubernetes v1.3.0+52492b4
```

Given the following buildconfig in a project called "cicd-00":

```YAML
apiVersion: v1
kind: BuildConfig
metadata:
  name: nationalparks-pipeline
  namespace: cicd-00
  selfLink: /oapi/v1/namespaces/cicd-00/buildconfigs/nationalparks-pipeline
  uid: bfdc9779-b0d9-11e6-a269-28d24452c2ce
  resourceVersion: '75434'
  creationTimestamp: '2016-11-22T17:33:15Z'
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "nationalparks", "namespace": "explore-00", "kind": "DeploymentConfig"},{"name": "nationalparks-live", "namespace": "explore-00", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: idiYvqEk
    -
      type: Generic
      generic:
        secret: WoyHjRRf
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node {\n  stage 'Build'\n  openshiftBuild(buildConfig: 'nationalparks', namespace: 'explore-00', showBuildLogs: 'true')\n  \n  stage 'Deploy Dev'\n  openshiftDeploy(deploymentConfig: 'nationalparks', namespace: 'explore-00')\n\n  stage 'Test Dev'\n  sh 'curl -s http://nationalparks.explore-00.svc.cluster.local:8080/ws/data/load'\n  sh 'curl -s http://nationalparks.explore-00.svc.cluster.local:8080/ws/data/all | grep -q \"Grand Canyon National Park\"'\n  \n  stage 'Deploy Live'\n  input 'Promote the Dev image to Live?'\n  openshiftTag(srcStream: 'nationalparks', srcTag: 'latest', destStream: 'nationalparks', destTag: 'live', namespace: 'explore-00', destinationNamespace: 'explore-00')\n  // openshiftDeploy(deploymentConfig: 'nationalparks-live', namespace: 'explore-00')\n}"
  output:
  resources:
  postCommit:
status:
  lastVersion: 1
```

When starting this pipeline build, the normal build view is displayed, and the pipeline build view is *NOT* displayed for either nationalparks or nationalparks-live

```
oc get dc -n explore-00
NAME                 REVISION   DESIRED   CURRENT   TRIGGERED BY
mongodb              1          1         1         config,image(mongodb:3.2)
mongodb-live         1          1         1         config,image(mongodb:3.2)
nationalparks        1          1         1         config,image(nationalparks:latest)
nationalparks-live   2          1         1         config,image(nationalparks:live)
parksmap             1          1         1         config,image(parksmap:0.5)
```

You can see that both DCs exist in the "explore-00"

If I move this pipeline build config into the explore-00 project and set the namespace to "" then it will display properly. However, in a different project, it does not display properly.

Is there some kind of permission or additional annotation required?

**Comment by spadgett** [comment]
@thoraxe We key off of `spec.strategy.type -> JenkinsPipeline`, so there's no special annotation or permission. On what page did it display as a normal build (and how did you navigate there)?

Note that when the pipeline completes, we collapse it on the overview.

**Comment by thoraxe** [comment]
If this pipeline build is defined in the same project (explore-00) and is running, you will see the pipeline view:

![pipeline-overview-page](https://cloud.githubusercontent.com/assets/94413/20538499/887e06fe-b0bf-11e6-817a-5ad3d36e9111.png)

In this particular issue, the pipeline build is defined in a _different_ project (cicd-xx) and its annotations refer to the explore-00 namespace:

```YAML
annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "nationalparks", "namespace": "explore-00", "kind": "DeploymentConfig"},{"name": "nationalparks-live", "namespace": "explore-00", "kind": "DeploymentConfig"}]'
```

Yet, in the explore-00 overview, when the pipeline build is running, it only appears as a standard non-pipeline build, and is only associated with nationalparks, and not both nationalparks and nationalparks-live

**Comment by spadgett** [comment]
Ah, I see. Currently the web console only shows you resources from one namespace at a time. We don't have a way to efficiently watch objects across namespaces, and there are limits in IE on the number of websockets we can have open.

We're looking at adding first-class support for environments, which would let us to support pipelines like this.

https://trello.com/c/Mvuy5Afi

**Comment by thoraxe** [comment]
ACK. Do you want me to close or leave open?

**Comment by spadgett** [comment]
Probably close. If there's something you'd like that's not captured in the card I linked, let us know. Either way the change would be big enough to track in Trello.
