### ISSUE TITLE
Intermittent result in web automation when adding role to user who already has the role

### ISSUE THREAD

**Issue by xingxingxia** [openshift/origin-web-console#926]
@benjaminapetersen could you please help take a look?
Steps to reproduce:
1. On membership page, add role 'view' to user bob.
2. Then add role 'view' to bob again.

In **web automation**, the result of step 2 is intermittent. Sometimes, it prompts expected message: The role "view" has already been granted to "bob"
But sometimes, it prompts unexpected message: The role "view" was granted to "bob"

The issue is first discovered by @maybelinot  when automating it. See dynamic pictures [here](https://github.com/openshift/cucushift/pull/4256#issuecomment-262937708) (internal visible)
Maybe there is some problem in the web page?

PS: The issue seems never seen in manual web operations, though.

**Comment by benjaminapetersen** [comment]
@xingxingxia I scanned your cucumber suite but could not immediately tell how the tests wait for a previous action to complete. Once "view" is successfully added to "bob", it will be removed as an option.  The forms are disabled whenever an "add" is clicked, and reenabled with a server response.  

Are these actions happening fast enough to perhaps be in parallel?

**Comment by maybelinot** [comment]
@benjaminapetersen these actions happening in series with refreshing of the membership page after first action.
You can look on `.gif` animations at the end of https://github.com/openshift/cucushift/pull/4256

**Comment by xingxingxia** [comment]
Both above 2 comments sound reasonable. So I guess the cause is:
After the first 'Add', web gets server response, thus shows 'The role "view" was granted to "bob"' and enables the 'Add' form. But in fact the rolebinding update may have not yet take real effect on the server side [*1]. Because automation action is fast, the second 'Add' request may randomly come just at that point, which causes the two requests seem parallel.

[*1] Such behavior may relates to the async design of openshift. When server gets request, it begins to process it and returns to client/web information such as the object is created, the object is updated, or whatever ..., but the processing may be still in progress and not really complete.

Just guess :)

**Comment by benjaminapetersen** [comment]
I'm looking into delaying the form reset anyway, I think we can resolve this.
