### ISSUE TITLE
Add to Project from Pipelines view needs a warning that not everything is a pipeline

### ISSUE THREAD

**Issue by danmcp** [openshift/origin-web-console#932]
![image](https://cloud.githubusercontent.com/assets/492994/20680741/4ccecaae-b56e-11e6-89b5-8b38484d6995.png)

Ideally it would only show me the stuff in Add to Project which would create a pipeline.  Assuming that's not feasible, at a minimum it should warn me on the pipelines page that not everything in Add to Project is a pipeline.  Perhaps something like:

No pipelines have been added to project ${project}.  You can add pipelines by selecting templates or importing json/yaml which contain a build config of type 'JenkinsPipeline'.

And maybe pointing them to an example like:

https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/samplepipeline.json

**Comment by jwforres** [comment]
This issue is for a short term fix until we can do something better relative to https://trello.com/c/JCZS9NFW

cc @spadgett

**Comment by spadgett** [comment]
Wonder if we shouldn't have a deploy sample button that takes you directly to the sample pipeline template (when installed).

**Comment by jwforres** [comment]
@spadgett the "when installed" part is the gotcha, we have no guarantee there is a sample there for us to point to

**Comment by spadgett** [comment]
@jwforres yeah we'd have to list templates to see and maybe have a constant saying what pipeline sample to use
