### ISSUE TITLE
Resolve incompatibility issue between Selenium Webdriver and Firefox 48+

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#945]
See https://github.com/SeleniumHQ/selenium/issues/2559 for details.  

IMPORTANT:  The merge queue will break shortly after Firefox 52.0 ESR is released on 2017-03-06 as RHEL ships with Firefox ESR (current version included in RHEL is Firefox 45.x ESR).

Workaround:  use Firefox 45 ESR or 47 or earlier.

cc: @jwforres, @benjaminapetersen

**Comment by jwforres** [comment]
The open issue they are tracking is https://github.com/SeleniumHQ/selenium/issues/2942

But it does not sound like they have any plans to fix the WebDriver support.  We need to look into protractor using GeckoDriver instead. https://github.com/angular/protractor/issues/3556

**Comment by benjaminapetersen** [comment]
Looks like we can swap for the `marionette` driver by updating `protractor.conf.js` to include this:
```javascript
capabilities: {
  marionette: true
}
```
No idea if it will fix but might be worth a shot given the simplicity.

**Comment by benjaminapetersen** [comment]
Hmm. is Marionette only for Firefox though?  [Looks like it](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette).  Dunno how we feel about that.

**Comment by jwforres** [comment]
@stevekuznetsov this is the firefox test issue we were discussing

**Comment by benjaminapetersen** [comment]
Another reference to this:
https://github.com/angular/protractor/issues/3750, specifically [this comment](https://github.com/angular/protractor/issues/3750#issuecomment-261414310) where firefox 47 is still recommended.

**Comment by jwforres** [comment]
@MarkDeMaria we talked about this a little bit before the holidays, are you interested in tackling this?

**Comment by MarkDeMaria** [comment]
@jwforres Certainly!

**Comment by jwforres** [comment]
Reducing the severity on this since we have found the problem only affects Macs, so it won't affect our merge queue

**Comment by spadgett** [comment]
There's another problem with Firefox 53+ that will likely break the merge queue down the line. geckodriver 1.3.0 does not correctly support `sendKeys` with current Firefox versions. We'll need to update geckodriver to 1.6.0+ or avoid `sendKeys` in our tests to work around.

Updating geckodriver is not easy since it requires new selenium and protractor versions, which breaks our tests.

@jeff-phillips-18 This is why the tests aren't running for you.

**Comment by spadgett** [comment]
@benjaminapetersen FYI, I have some changes locally that make most of the tests run on a Mac.

**Comment by spadgett** [comment]
It looks like we have until March 2018 until the next ESR, which will be based on Firefox 59.

**Comment by spadgett** [comment]
The Firefox 53 issue might only be a problem with the Marionette driver.

**Comment by rhamilto** [comment]
Closing as we have other issues with integration tests that are being addressed in #2083
