### ISSUE TITLE
Indeterminate progress bar circle a little too small for some duration values

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#95]
Numbers like 30m touch the edges of the circle:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/16268849/fa68ba8c-385d-11e6-8525-212e060e768c.png)

/cc @sg00dwin

**Comment by liggitt** [comment]
making it a div with border-radius, fixed height, and min-width could make it a circle in most cases, but allow it to grow horizontally when needed
