### ISSUE TITLE
Environment vars keep saving too often in background, causing any changes started to be lost

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin-web-console#982]
**OS**
Fedora 24

**Browser**
Google Chrome Version 52.0.2743.116 (64-bit)

**Web Console Page**
project/default/browse/dc/idling-echo?tab=environment

**Issue**
This message appears a bit too often (and when I least expect it) while editing environment variables for a deploymentconfig or a buildconfig.
![error1](https://cloud.githubusercontent.com/assets/3902875/20852797/d1fd32de-b8b5-11e6-9a03-91adca1e424a.png)

I am forced to click on the message's `Reload environment variables` link every time. If I choose to keep adding my changes and ignore this message, when I finally attempt to save my changes, I receive this message:

![error2](https://cloud.githubusercontent.com/assets/3902875/20852802/d600754e-b8b5-11e6-9402-c8020da5826a.png)

I have found no consistent time interval between "background updates". Sometimes I receive the "background update" warning a few seconds after exiting the last one.

Since I am forced to `Reload environment variables` (due to the reason specified above) every time I receive this warning, it sometimes becomes an issue when updating multiple environment variables.

@openshift/ui-review

**Comment by spadgett** [comment]
Yeah, this is a known issue that typically happens when a build or deployment is running because of status updates. Related to #621 and #676

We have done some investigation of using PATCH to avoid the conflicts on save.

**Comment by jwforres** [comment]
its not us saving the env vars, we don't do that until you hit Save, its other updates to the status of the object happening in the background.  closing since we already have #621 tracking the issue

**Comment by spadgett** [comment]
This will be fixed by #1171.
